### ISSUE TITLE
Error : Cannot read property 'outerHTML' of null

### ISSUE THREAD

**Issue by vjrngn** [MatthewHerbst/react-to-print#1]
Hey gregnb,

I like the API your component offers but there seems to be a bug. Here's the codesandbox link : https://codesandbox.io/s/23o6n6n1xp

**Comment by gregnb** [comment]
Hey @vjrngn, Thanks for the feedback. It appears you have just a slight mistake in your code. Change 

```
   <div rel={el => this.componentRef = el}>
```
to
```
    <div ref={el => this.componentRef = el}>
```
