### ISSUE TITLE
Background color is not printed on Firefox

### ISSUE THREAD

**Issue by telaoumatenyanis** [MatthewHerbst/react-to-print#100]
# Bug Description

Background colors added to components are not printed on firefox.

# Environment
**package.json:**

```
  "dependencies": {
    "prop-types": "15.6.0",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "emotion": "^10.0.7",
    "react-to-print": "^2.0.0-alpha-7"
  }
```

Firefox **65.0.1**
Chrome **72.0.3626.109**

# Reproduction steps
**Tested styling methods :**

- emotion
```
        <div
          className={css`
            background-color: red;
            color: blue;
          `}
        >
          I have a red background and a blue text !
        </div>
```

- Inline css

```
        <div style={{ backgroundColor: "blue", color: "red" }}>
          I have a blue background and a red text !
        </div>
```

**HTML result:**
<img width="441" alt="image" src="https://user-images.githubusercontent.com/29358668/53244848-4fa50380-36ac-11e9-95cf-48e4172df597.png">

**Printed result (Firefox 65.0.1):**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/29358668/53244877-664b5a80-36ac-11e9-84fc-1a4a08a40bce.png">

**Printed result (Chrome 72.0.3626.109):**
<img width="562" alt="image" src="https://user-images.githubusercontent.com/29358668/53244969-a8749c00-36ac-11e9-92c0-8827a2183087.png">

# Snippet

[CodeSandbox](https://codesandbox.io/s/mzy09xqn6j)

**Comment by MatthewHerbst** [comment]
Hi @telaoumatenyanis I'm on Chrome 72 and cannot replicate this. Are you sure your print settings are correct? You may need to select the "Background graphics" option in the "More settings" option of the Chrome print dialog.

**Comment by telaoumatenyanis** [comment]
Hi @MatthewHerbst. 

After further verification, Firefox print dialog didn't have the background color setting enabled by default. Didn't even know it was optional.

Thanks a lot, you can close this.
