### ISSUE TITLE
Mapbox does not appear in print preview or in pdf

### ISSUE THREAD

**Issue by aviv-dw** [MatthewHerbst/react-to-print#102]
I am trying to use react-to-print to save a report I am creating that includes Mapbox and 2 charts from "Recharts".
The recharts appear in the preview and in the pdf if I save it as pdf but the Mapbox which is webGL does not appear. 
Could you please fix this?

**Comment by MatthewHerbst** [comment]
Hi @aviv-dw Could you please link to a code sandbox that has an MVP replica of this issue? I've never used any of the things you're talking about before and so have no clue where to even begin looking.

**Comment by aviv-dw** [comment]
Here is an example for what I was talking about with trying to print a Mapbox:
https://codesandbox.io/s/q7zzlo0xp6

Thank you

**Comment by MatthewHerbst** [comment]
Thanks! I'll take a closer look after work today

**Comment by aviklai** [comment]
@aviv-dw Hi,

Add `preserveDrawingBuffer: true` to your ReactMapboxGl initialization.
This may impact performance a bit, but will allow to print the canvas.

Here is a working example:
https://codesandbox.io/s/509w9o843p

@MatthewHerbst  FYI

**Comment by MatthewHerbst** [comment]
Thanks @aviklai! I had to shelve this one since I wasn't able to figure anything out from out end. Always nice to learn new tricks!
