### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by vlindos** [MatthewHerbst/react-to-print#103]
Hello,
I am using:

-     "prop-types": "^15.7.2",
-     "react": "^16.8.0",
-     "react-dom": "^16.8.0",
-     "react-router": "^4.3.1",
-     "react-router-dom": "^4.3.1",
-     "react-to-print": "^2.0.0-alpha.7"

Having the following component:
```
import { Alert, Button, Divider } from "antd";
import * as h from "history";
import React = require("react");
import { Link } from "react-router-dom";
import ReactToPrint from "react-to-print";
import { LoggedInProvider } from "../../../services/LoggedInProvider";
import { WebSocketClient } from "../../../services/WebSocketClient";
import { ComponentState } from "../../models/ComponentState";
import FollowUpToPrint from "./FollowUpToPrint";

export class Content extends React.Component
    <{
        history: h.History,
        webSocketClient: WebSocketClient,
        loggedIn: LoggedInProvider,
        location: h.Location,
        match: any,
    },
    {data: any}> {
    public componentRef: any;
    constructor(props: any) {
        super (props);

        this.state = {data: {test: 1}};
    }


    public render() {
        return (
<>
    <DataComponentToPrint
        ref={(el: any) => (this.componentRef = el)}
        data={this.state.data}
        {... this.props} /> <br/>
    <Link to={`/data/1/edit`}>Edit</Link>
    <Divider type="vertical" />
    <Link to={`/data/1/delete`}>Delete</Link>
    <Divider type="vertical" />
    <ReactToPrint trigger={() => <Button>Print</Button>} content={() => this.componentRef} />
</>
        );
    }
}
```

And got this in the browser console:

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

The problem disappears if I remove **ReactToPrint** from the component.

Any help will be appreciated :)

**Comment by MatthewHerbst** [comment]
I don't see you importing `DataComponentToPrint` anywhere

**Comment by MatthewHerbst** [comment]
@vlindos were you able to solve your issue here?

**Comment by annguyenwasd** [comment]
@vlindos Button should be a react class based component, or you can replace <Button /> by native html <button>...</button>

**Comment by duyhau206** [comment]
I have a same problem with react-to-print version 2.1.0.
I'm using 
"prop-types": "^15.5.10"
"react": "^16.8.3",
"react-dom": "^16.2.0",
"react-to-print": "^2.1.0

i'm using native html
"<ReactToPrint trigger={() => <button>Print</button>} content={() => this.componentRef} />
<PrintRetailPayment ref={el => (this.componentRef = el)} />"

I have console: "Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object."

Thank everyone for help

**Comment by karpovich-philip** [comment]
> I have a same problem with react-to-print version 2.1.0.
> I'm using
> "prop-types": "^15.5.10"
> "react": "^16.8.3",
> "react-dom": "^16.2.0",
> "react-to-print": "^2.1.0
> 
> i'm using native html
> "<ReactToPrint trigger={() => Print} content={() => this.componentRef} />
> <PrintRetailPayment ref={el => (this.componentRef = el)} />"
> 
> I have console: "Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object."
> 
> Thank everyone for help

Change version to previous one. To 2.0.0-alpha.7. It fix your problem

**Comment by duyhau206** [comment]
Thank for help and best wish for you
