### ISSUE TITLE
2.0.0-alpha7 dropped index.d.ts

### ISSUE THREAD

**Issue by wakemaster39** [MatthewHerbst/react-to-print#104]
alpha-6 had a spelling error which I was happy to see is fixed, but the alpha 7 package no longer includes the index.d.ts file.

**Comment by MatthewHerbst** [comment]
Hello. I just did a clean install and I see the file included:

```sh
mkdir tmp
cd tmp
npm init
npm install --save react-to-print@latest
ls node_modules/react-to-print/lib
# index.d.ts	index.js	index.js.map
```

**Comment by wakemaster39** [comment]
yes it seems to work on a clean, I tried upgrading and downgrading a couple times and it kept getting deleted. I'll close this out.
