### ISSUE TITLE
@media print-specific styles are not being taken into effect

### ISSUE THREAD

**Issue by filiphazardous** [MatthewHerbst/react-to-print#106]
This happens when I have a style that is imported in my project with webpack, which also contains 
`@media print {
    .my-class: { ... }
}`

In my original code, the style is inlined like so:
`<style id="style-id-1" media=all>
@media print {
    .my-class: { ... }
}
</style>`

In the ReactToPrint iframe, the style is inlined like this:
`<style id="react-to-print-1">
@media print {
    .my-class: { ... }
}
</style>`

The suggested fix would seem to be to add `media=all` to the style-tags?

**Comment by filiphazardous** [comment]
Closing, it was a bug in my code... 😊

**Comment by MatthewHerbst** [comment]
@filiphazardous thanks for updating. I was trying to think through it and wasn't sure where to start. Please let us know if you run into other issues with the library!
