### ISSUE TITLE
Print: Total: 2 sheets of paper ?

### ISSUE THREAD

**Issue by zhilianbi520** [MatthewHerbst/react-to-print#107]
I've met the question as you too.The printed page always displays 2 pages, even though there is only 1 page。my website Only 580px high

Here's what I need to print。

`````
<div class="Prescription" style="width:100%;padding-left:20px;margin-top: 30px;font-size: 18px">
  <h2 style="height: 45px;vertical-align: bottom;text-align: center;line-height: 45px;position: relative;">
    <img width="184" height="37" src="" style="position:absolute;left: 0;top:5px;"/>xxx</h2>
  <div style="padding-right:50px;margin:20px 0 10px 0;">
    <table cellspacing="0" cellpadding="0" style="width: 100%">
      <tr>
        <td style="width:20%">xx&nbsp;&nbsp;xx</td>
        <td style="width:20%">xx&nbsp;&nbsp;xx</td>
        <td style="width:15%">xx&nbsp;&nbsp;xx</td>
        <td style="width:20%">xx&nbsp;&nbsp;xx</td>
        <td>xxxxx&nbsp;xxxxxxxxxxx</td>
      </tr>
      <tr>
        <td style="width:20%">Name</td>
        <td style="width:10%">Sex</td>
        <td style="width:10%">Age</td>
        <td style="width:20%">Natinonality</td>
        <td>Case Nunber</td>
      </tr>
    </table>
  </div>
  <div style="position: relative;padding-right:50px">
    <table cellpadding="0" cellspacing="0" style="height:580px;border:2px solid #666;font-size:18px;width:100%;table-layout: fixed;overflow: hidden">
      <tr style="height:578px">
        <td style="border-right: 2px solid #666;width:20%;vertical-align: top;padding:10px 0 0 10px;">
          <span>xxxxxx：</span>
          <div>Case  description &  Diagnosis</div>
          <span>xxxxx<br/></span>
          <span>xxxxx<br/></span>
        </td>
        <td style="vertical-align: top;padding:10px 0 0 10px;">
          <p>℞：</p>
          <table cellpadding="0" cellspacing="0" style="width:100%;padding: 0 10px 0 5px;text-align: center;">
            <tr>
              <th style="width: 40%;overflow-x: hidden;">xxxxx</th>
              <th>xxxxx</th>
              <th>xxxxx</th>
              <th>xxxxx</th>
              <th>xxxxx</th>
              <th>xxxxx</th>
            </tr>
            <tr>
              <td style="width: 40%;overflow-x: hidden;">xxxxx</td>
              <td>xxxxx</td>
              <td>xxxxx</td>
              <td>xxxxx</td>
              <td>xxxxx</td>
              <td>xxxxx</td>
            </tr>
            <tr>
              <td style="width: 40%;overflow-x: hidden;">xxxxx</td>
              <td>xxxxx</td>
              <td>1ml</td>
              <td>-&nbsp;</td>
              <td>-&nbsp;</td>
              <td>4ml</td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    <p style="right: 70px;position: absolute;bottom: 5px;">xxxxx:&nbsp;xxxxx<br/>Sig.<br/>xxxxx&nbsp;xxxxx&nbsp;xxxxx&nbsp;xxxxx<br/>Date</p>
  </div>
  <div style="padding-right: 50px;margin-top:5px;">
    <table cellpadding="0" cellspacing="0" style="width:100%;margin-right: 50px;font-size:
        14px;">
      <tr style="height: 30px">
        <td style="width: 38%" >xxxxx</td>
        <td style="width: 38%">xxxxx</td>
        <td style="width: 24%">xxxxx</td>
      </tr>
      <tr>
        <td>xxxxx</td>
        <td>xxxxx</td>
        <td>xxxxx</td>
      </tr>
    </table>
  </div>
</div>

**Comment by ibanjb** [comment]
I have the same issue, 2 pages are printed always. Any solution? Any workaround?
Thx!

Using v.2.0.0-alpha.7, the v.2.1.0 crashes (issue https://github.com/gregnb/react-to-print/issues/115 )

**Comment by MatthewHerbst** [comment]
Hello. Can you please create a working code example so I can see the issue? Thanks

**Comment by zhilianbi520** [comment]
https://codesandbox.io/s/01vmr100v0

**Comment by ibanjb** [comment]
> Hello. Can you please create a working code example so I can see the issue? Thanks

I uploaded a project, using pro.ant.design scaffolder (the same that I'm using in my project) into my repo with an example about this problem.

You can find it in:
https://github.com/ibanjb/ReactToPrintIssueTest

Take a look at the readme.MD to know how to test it, but its pretty simple  :)  

Basically, the two files that you need to take a look are:

- src/pages/Dashboard/Analysis.js -> has the object ReactToPrint
- src/components/PrintTest/index.js -> renders the page to be printed

Another bug that I found is about the radio and check buttons. In Google Chrome are printed good but in Firefox doesn't. I don't know if will be better to create another issue related with that or not.. what do you think?

![image](https://user-images.githubusercontent.com/7020733/55803549-d25a1480-5ada-11e9-919b-036da44f97ee.png)


Thanks!

**Comment by MatthewHerbst** [comment]
@ibanjb #66 is being used to track the known issues with the checkboxes. If you have any ideas there, please let me know.

@zhilianbi520 playing with the codesandbox, it seems the issue is `marginTop: "30px",` that you have. Removing that causes the page to properly print in a single instance. The strange part is that if I remove the content of that `div` but keep the `marginTop: "30px",` it still prints two pages of all white space basically. Clearly there is some calculation that is having problems. My best recommendation for right now is to use a class to set the margin, and then use a print media query to not include the margin while printing. I'll keep looking into this issue when I get a chance, thanks.

**Comment by zhilianbi520** [comment]
> @ibanjb #66 is being used to track the known issues with the checkboxes. If you have any ideas there, please let me know.
> 
> @zhilianbi520 playing with the codesandbox, it seems the issue is `marginTop: "30px",` that you have. Removing that causes the page to properly print in a single instance. The strange part is that if I remove the content of that `div` but keep the `marginTop: "30px",` it still prints two pages of all white space basically. Clearly there is some calculation that is having problems. My best recommendation for right now is to use a class to set the margin, and then use a print media query to not include the margin while printing. I'll keep looking into this issue when I get a chance, thanks.

ok，thanks~!

**Comment by ibanjb** [comment]
> > @ibanjb #66 is being used to track the known issues with the checkboxes. If you have any ideas there, please let me know.
> > @zhilianbi520 playing with the codesandbox, it seems the issue is `marginTop: "30px",` that you have. Removing that causes the page to properly print in a single instance. The strange part is that if I remove the content of that `div` but keep the `marginTop: "30px",` it still prints two pages of all white space basically. Clearly there is some calculation that is having problems. My best recommendation for right now is to use a class to set the margin, and then use a print media query to not include the margin while printing. I'll keep looking into this issue when I get a chance, thanks.
> 
> ok，thanks~!

About the 2 pages error, the problem was solved using your recommendations, remove the unnecesary margins and works! Thx!.

About the other problem, the checkboxes and radiobuttons, I opened an issue into ant-design github page and the response was super-duper chinese: "This is a bug of the browser that you are using, we will not fix. Issue is closed". So, meanwhile this problem exists, I will use a workaround to replace those object by images or apply a custom css to those elements, will try.

Ant-design issue link: https://github.com/ant-design/ant-design/issues/15980 

Thanks again!

**Comment by Movinda** [comment]
> @ibanjb #66 is being used to track the known issues with the checkboxes. If you have any ideas there, please let me know.
> 
> @zhilianbi520 playing with the codesandbox, it seems the issue is `marginTop: "30px",` that you have. Removing that causes the page to properly print in a single instance. The strange part is that if I remove the content of that `div` but keep the `marginTop: "30px",` it still prints two pages of all white space basically. Clearly there is some calculation that is having problems. My best recommendation for right now is to use a class to set the margin, and then use a print media query to not include the margin while printing. I'll keep looking into this issue when I get a chance, thanks.

it worked for me also, i removed unnecessary margins(top and bottom). how can i insert top and bottom margins properly if i want to insert?

**Comment by william-deckard** [comment]
A little late but this may have been caused by having Overflow: visible somewhere and as it was pointed out, margins were probably extending..
