### ISSUE TITLE
360 Browser 

### ISSUE THREAD

**Issue by smallWanziOf** [MatthewHerbst/react-to-print#113]
360 Browser error tip --- >  Uncaught TypeError: Invalid attempt to spread non-iterable instance

**Comment by MatthewHerbst** [comment]
Hello @smallWanziOf Can you please give more details? What browser are you running? What version of that browser? What version of `react-to-print`? When did this error happen? What code are you running to make it happen? Why do you think it is being caused by this library? Thanks.

**Comment by smallWanziOf** [comment]
Thanks for your answer ！i'm Chinese . My English not good . I'm sorry.
360 broswer (360浏览器) version is 8.1.1.404 maybe only in Chian . now my issues has been resolve . thank you !
react-to-print version is ^2.0.0-alpha.7
In 360 broswer if result is NodeList use [...NodeList ]  The broswer console a error tip 'Uncaught TypeError: Invalid attempt to spread non-iterable instance' now i use Array.prototype.slice.call(NodeList )
OK ! 360 broswer can run , chrome, IE, Firfox also. 

Change code：
const canvasEls = domDoc.querySelectorAll('canvas');
const tempCanvasEls = Array.prototype.slice.call(canvasEls);
tempCanvasEls.forEach((node, index) => {
     node.getContext('2d').drawImage(srcCanvasEls[index], 0, 0);
});

**Comment by MatthewHerbst** [comment]
Thank you for the extra details. I think this is the same issue that we are having with IE 11 right now in #105 

TIL for anyone who didn't know what 360 Browser is: https://en.wikipedia.org/wiki/360_Secure_Browser
