### ISSUE TITLE
Print page with partial condition

### ISSUE THREAD

**Issue by panda6412** [MatthewHerbst/react-to-print#117]
I assume press the button will trigger onConfirmButtonClick event, but in these method will call an API, if these API return errorCode, then don't need to print.
Is there any possobile determined way to solve the demand ?

```js
<ReactToPrint
              trigger={() => (
                <Button
                  basic
                  color="orange"
                  disabled={!hasContainerId}
                  onClick={() => this.onConfirmButtonClick()}
                >
                  <Icon name="checkmark" />
                  Confirm
                </Button>
              )}
              content={() => this.componentRef}
            />

onConfirmButtoClick = async () => {
    const { containerIdInput } = this.state;
    const { station, setPickStatus } = this.props;

    let result = await DragoniteWebAPI.binding(station, containerIdInput);

    const { errorCode, errorMessage } = result;
    console.log(errorCode, errorMessage);


    if (errorCode === undefined) {
      this.setState({ open: true });
      this.initState();
    } else {
      this.setState({ needPrint: false, errorMessage });
    }
  };

**Comment by MatthewHerbst** [comment]
Don't have your print button be the same button the make a network call? `onClick` does not know that it needs to wait for a promise to finish. Maybe try using `onBeforePrint`

**Comment by panda6412** [comment]
Well, let me change the way to say,
when I press the button, it will show a print preview page immediately, but I want to control whether print or not according to my return API.

Even I put `onConfirmButtoClick` function to `onBeforePrint` trigger, but how could I prevent not showing the print preview.

Thanks for assistance .

**Comment by MatthewHerbst** [comment]
You can't do that currently. If you click print, we are going to try and print. It's up to you to show a print button or not. In #88 I'm (very, very slowly since I've been super busy at work) working to extract the API from the component, meaning you would be able to manually issue the print call. However, I have no timeline for when that will get finished.

**Comment by panda6412** [comment]
Ok, I'll make the validation ensure the user cannot click the button.
Thanks for the response, wish you best!
