### ISSUE TITLE
Image not getting displayed on Print preview (Mac)

### ISSUE THREAD

**Issue by SaravananAnbu** [MatthewHerbst/react-to-print#118]
Once I click print to print a file from web, then the print preview dialog box opens, but images on my file is missing in the print file, hence after exporting as pdf, images are missing from the print file. Also every time I click print, the results vary as some times it picks up one or two images or it picksup nothing or it picksup everything.

**Comment by MatthewHerbst** [comment]
Do you have the "Background graphics" option turned on in your print dialog?

**Comment by SaravananAnbu** [comment]
Yes @MatthewHerbst

**Comment by MatthewHerbst** [comment]
Can you please make a codesandbox or something replicating the issue?

**Comment by SaravananAnbu** [comment]
`import React, {Fragment} from 'react';
import ReactToPrint from 'react-to-print';
import _ from 'lodash';
import Config from '../../config';
import history from '../../history';

const longTextArray = [ "Custom Notes", "others" ]

class PrintSinglePage extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            Name: '',
            Description: '',
            Notes: '',
            Quality_Notes: '',
            styleData:[],
            detailCards: [],
            styleColors: [],
            Original_Samp_Size: '',
            sizeEquivalenceCountry:'',
            productionSampCountry: '',
            Size_equivalence: [],
            Production_samp_size: [],
            loading: true,
            styleData: {},
            qualityLen: 0,
            notesLen: 0,
            count: 0
        }
    }
    componentDidUpdate(prevProps) {
        const styleData = this.props.styleData;
        if (this.props.styleData !== prevProps.styleData) {
            if (parseInt(this.props.styleId) === parseInt(this.props.styleData.Id)) {
                const notesLen = styleData.Notes.split(/\r\n|\r|\n/)
                const qualityLen = styleData.Quality_Notes.split(/\r\n|\r|\n/)
                this.setState({
                    Name: styleData.Name,
                    Description: styleData.Description,
                    Notes: styleData.Notes,
                    Quality_Notes: styleData.Quality_Notes,
                    Original_Samp_Size: styleData.Original_Samp_Size,
                    Production_samp_size: styleData.Production_samp_size,
                    Product_size: styleData.Product_size,
                    Size_equivalence: styleData.Size_equivalence,
                    sizeEquivalenceCountry: styleData.sizeEquivalenceCountry,
                    productionSampCountry: styleData.productionSampCountry,
                    productSizeCountry: styleData.productSizeCountry,
                    Size_equivalence_sizeId: styleData.Size_equivalence_sizeId,
                    Production_samp_sizeId: styleData.Production_samp_sizeId,
                    Product_sizeId: styleData.Product_sizeId,
                    Attributes: styleData.Attributes,
                    styleData: styleData,
                    src: Config.imagesHomeUrl + 'Styles/' + styleData.imagePath,
                    notesLen: notesLen.length,
                    qualityLen: qualityLen.length
                })
            }
        }
      
        if (this.props.detailCards !== prevProps.detailCards) {
            if(this.props.printOpt) {
                if(parseInt(this.props.styleId) === parseInt(this.props.detailCards.filter(detail => detail.Style_Id === this.props.styleId).map(detail => { return JSON.stringify(detail.Style_Id) }))) {
                    this.setState({ detailCards: this.props.detailCards })
                }
            } else {
                this.setState({ detailCards: this.props.detailCards })
            }
        }
        
        if (this.props.styleColors !== prevProps.styleColors) {
            if(this.props.printOpt) {
                if(parseInt(this.props.styleId) === parseInt(this.props.styleColors.filter(clr => clr.Style_Id === this.props.styleId).map(clr => { return JSON.stringify(clr.Style_Id) }))) {
                    this.setState({ styleColors: this.props.styleColors })
                }
            } else {
                this.setState({ styleColors: this.props.styleColors })
            }
            
        }
    }
    tick() {
        this.setState(state => ({
          count: state.count + 1
        }));
    }
    componentDidMount() {
        setTimeout(() => this.setState({ loading: false }), 1000 * 5); 
        this.interval = setInterval(() => this.tick(), 24);
    }
    componentWillMount() {
        if (this.props.printOpt) {
            const styleId = this.props.styleId;
            this.props.fetchStyleData(styleId);
            this.props.fetchDetailData(styleId);
            this.props.getColorsForStyle(styleId);
        }
    }
    formatDate(date) {
        var d = new Date(date),
            month = '' + (d.getMonth() + 1),
            day = '' + d.getDate(),
            year = d.getFullYear();

        if (month.length < 2) month = '0' + month;
        if (day.length < 2) day = '0' + day;

        return [day, month, year].join('-');
    }
    render() {
        const printDate = this.formatDate(new Date());
        const { loading } = this.state;
        if(loading) {
            return <div>
                <h5 className="text-center m-3">Please wait while image formatting is completed</h5>
                <div className="progress">
                    <div className="progress-bar progress-bar-striped bg-success" role="progressbar" style={{ width: `${this.state.count}%` }} aria-valuenow={this.state.count} aria-valuemin={0} aria-valuemax={100} />
                </div>
            </div>
        }
        const { styleData } = this.state;
        const attributeData = styleData.Attributes;
        const AttrData = {};
        if(attributeData) {
            Object.keys(attributeData).forEach((key) => {
                AttrData[key.trim()] = attributeData[key];
            });
        }        
        var attr1 = Object.entries(AttrData).filter(key => !longTextArray.includes(key[0])).map((key, index) => 
            index <= 14 &&
            <div key={index} className="" style={{display: "grid", gridTemplateColumns: "80% auto" }}>
                <div style={{ gridColumnStart: 1}}>
                    <small style={{ fontSize: 13 }}>{key[0]} : </small>
                </div>
                <div style={{  gridColumnStart: 2,  borderBottom: '1px solid #ccc'}}>
                    <small
                        style={{ fontSize: 14}}>
                        {key[1]}
                    </small>
                </div>
            </div>
        )
        var attr2 = Object.entries(AttrData).map((key, index) => 
            index > 14 &&
            <div key={index} style={{display: "grid", gridTemplateColumns: "80% auto" }}>
                <div style={{ gridColumnStart: 1}}>
                    <small style={{ fontSize: 13 }}>{key[0]} : </small>
                </div>
                <div style={{  gridColumnStart: 2,  borderBottom: '1px solid #ccc'}}>
                    <small
                        style={{ fontSize: 14}}>
                        {key[1]}
                    </small>
                </div>
            </div>
        )
        var customNotes = Object.entries(AttrData).filter(key => longTextArray.includes(key[0])).map((key, index) => 
            <div key={index} style={{display: "grid", marginLeft: styleData.categoryType === "TOP" || styleData.categoryType === "BOTTOM" ? 23 : 0, gridTemplateColumns: "25% auto" }}>
                <div style={{ gridColumnStart: 1}}>
                    <small style={{ fontSize: 13 }}>{key[0]} : </small>
                </div>
                <div style={{  gridColumnStart: 2,  borderBottom: '1px solid #ccc'}}>
                    <small
                        style={{ fontSize: 15}}>
                        {key[1].substr(0, 50)}
                    </small>
                </div>
            </div>
        )
        var customnotes = Object.entries(AttrData).filter(key => key[0] === 'custom notes').map((key, index) => 
            <div key={index} className=" row justify-content-center">
                <div className="col-4">
                    <small style={{ fontSize: 14 }}>{key[0]} : </small>
                </div>
                <div className="col-7" style={{ borderBottom: '1px solid #ccc'}}>
                    <small
                        style={{ fontSize: 15}}>
                        {key[1]}
                    </small>
                </div>
            </div>
        )
        const detailCard =(
            <div className="col-6  mt-2">
                <div className="card">
                    <div className="card-body">
                        <div className="text-center" style={{backgroundColor: "#cccccc2", height: 205, padding: '80px 20px', color: 'transparent' }}>
                            No records Available
                        </div>
                    </div>
                    
                </div>
            </div>
        )
        const imgCard =(
            <div className="card">
                <div className="card-body text-center">
                    <div style={{backgroundColor: "#cccccc2", height: 173, padding: 60, color: 'transparent' }}>
                        No Image Available
                    </div>
                </div>
            </div>
        )
        const clrCard = (
            <div className="col-4">
                <div className="card">
                    <div className="card-body text-center">
                        <div style={{backgroundColor: "#cccccc2", height: 150, padding: 60, color: 'transparent' }}>
                            No Color Available
                        </div>
                    </div>
                </div>
            </div>
        )
        const colorCard = (
            <div className="col-12">
                <div className="card mb-2">
                    <div className="card-body text-center">
                        <div className="card-text" style={{color: 'transparent'}}>
                            No color Available...
                        </div>
                        <textarea style={{ height: 150, width: 150 }}>

                        </textarea>
                    </div>
                </div>
            </div>
        )
        return (
            <div className="container-fluid" style={{position: 'relative'}}>
                <div className="row text-center text-white p-1 pt-2 mb-2" style={{ backgroundColor: '#000', fontSize: 16}}>
                    <div className="col-4">
                        <h6 style={{ textTransform: "uppercase"}}>Brand: {styleData.brandName}</h6>
                    </div>
                    <div  className="col-4">
                        <h6 style={{ fontWeight: 600}}> TECHNICAL DETAILS </h6>
                    </div>
                    <div  className="col-4">
                        <h6 style={{ textTransform: "uppercase"}}> Style Reference: {styleData.Name}</h6>
                    </div>
                </div>
            <div  className="row text-center">
                <div className="col-3">
                    <h6 className="mb-1">DATE</h6>
                    <p className="mb-1">{printDate}</p>
                </div>
                <div className="col-3">
                    <h6 className="mb-1">DESIGNER</h6>
                    <p className="mb-1">{styleData.designerName}</p>
                </div>
                <div className="col-3">
                    <h6 className="mb-1"> BUYER </h6>
                    <p className="mb-1">{this.props.buyer}</p>
                </div>
                <div className="col-3">
                    <h6 className="mb-1"> COLLECTION</h6>
                    <p className="mb-1" style={{ textTransform: "uppercase" }}>{styleData.collectionName}</p>
                </div>
            </div>
            <div className="row mb-2" style={{  border: '1px solid #555', margin:0}}>
                <div className="col-6 text-left pl-3 pr-3" style={{borderRadius: 5}}>
                    <div className="row">
                        <div className="col-12 mt-3 p-0">
                            <div className="jumbotron ml-3 mr-3" style={{backgroundColor: '#cccccc12', marginBottom: 10, padding: 12}}>
                                <h6>{styleData.categoryType} : {styleData.categoryName}</h6>
                                {styleData.categoryType === "DRESS" ? 
                                    <div className="row">
                                        <div className="col-6">
                                            {attr1}
                                        </div>
                                        <div className="col-6">
                                            {attr2}
                                        </div> 
                                        <div className="col-12">
                                            {customNotes}
                                        </div>
                                    </div>
                                 :
                                    _.map( AttrData, (value, key) => (
                                        !longTextArray.includes(key) &&
                                        <div key={key} className="row justify-content-center">
                                            <div className="col-7" style={{ gridColumnStart: 1}}>
                                                <small style={{ fontSize: 14 }}>{key} : </small>
                                            </div>
                                            <div className="col-4" style={{ borderBottom: '1px solid #ccc'}}>
                                                <small style={{ fontSize: 14}}>
                                                {(value.toString() === " ") ? "" : value.toString()}
                                                </small>
                                            </div>
                                        </div>
                                    )) 
                                } 
                                { styleData.categoryType === "TOP" && customNotes }
                                { styleData.categoryType === "BOTTOM" && customNotes }
                                
                        </div>
                        </div>
                        <div className="col-12 m-1 mt-0">
                            <div className="row">
                                <div className="col">
                                    <p className="mb-1"> Orginal Sample Size </p>
                                    <button className="btn btn-light btn-sm">{styleData.Original_Samp_Size}</button>
                                </div>
                                <div className="col">
                                    <p className="mb-1"> Size Equivalence</p>
                                    <button className="btn btn-light btn-sm" style={{marginRight: '10px'}}>{styleData.sizeEquivalenceCountry}</button>
                                    {this.state.Size_equivalence.map((size, i) => 
                                        <button className="btn btn-light btn-sm" key={i}>{size}</button>
                                    )}
                                </div>
                            </div>
                        </div>
                        <div className="col-12 m-1">
                            <p className="mb-1"> Production in SampleSize</p>
                            <button className="btn btn-light btn-sm" style={{marginRight: '10px'}}>{styleData.productionSampCountry}</button>
                            {this.state.Production_samp_size.map((size, i) => 
                                <button className="btn btn-light btn-sm" key={i} style={{marginRight: '10px'}}>{size}</button>
                            )}
                        </div>
                        <div className="col-12 m-0">
                            <p className="mb-1"> Designer Observations</p>
                            <textarea style={{ minHeight: styleData.categoryType === "BOTTOM" ? 80 : 100, width: '100%', overflow: 'hidden', resize: 'none', fontSize: this.state.notesLen >= 5 ? 10 : 12 }} readOnly={true}
                                value={styleData.Notes !== '' ? styleData.Notes : 'No records Available'}
                            />
                        </div>
                        <div className="col-12 m-0">
                            <p className="mb-1"> Quality Observations</p>
                            <textarea style={{ minHeight: styleData.categoryType === "BOTTOM" ? 80 : 100, width: '100%', overflow: 'hidden', resize: 'none', fontSize: this.state.qualityLen >= 5 ? 10 : 12  }} readOnly={true}
                                value={styleData.Quality_Notes !== '' ? styleData.Quality_Notes : 'No records Available'}
                            />
                        </div>
                    </div>
                </div>
                <div className="col-6">
                    <div className="row">
                        <div className="col-12">
                            <div className="card mt-3">
                                <div className="card-body text-center" style={{position:'relative', margin: 10, padding:10, height:245}}>
                                {  styleData.imagePath === "null" || styleData.imagePath === null ? imgCard :
                                    <img src={Config.imagesHomeUrl + 'Styles/' + styleData.imagePath} style={{ maxHeight: '100%', maxWidth: '100%', height: 'auto', position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, margin: 'auto', verticalAlign: 'middle' }} />
                                 }
                                </div>
                            </div>
                        </div>
                        <div className="col-12">
                            <div className="row p-3">
                                {this.state.detailCards.map((card, i) => 
                                    i <= 3 &&
                                    <div className="col-6 mt-2" key={i}>
                                        <div className="card" style={{ height: 247 }}>
                                            <div className="card-body text-center" style={{position: 'relative', height: 160 }}>
                                                <img src={"https://s3.us-east-2.amazonaws.com/prodesiignzprod" + card.Img_Path} style={{ maxHeight: '100%', maxWidth: '100%', height: 'auto', position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, margin: 'auto', verticalAlign: 'middle'}}/>
                                            </div>
                                            <div className="card-footer text-left">
                                                <p className="m-0" style={{ fontSize: 14}}><b>{card.Name.substr(0, 35)}</b></p>
                                                <p className="m-0" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'normal', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', fontSize: 13}}>{card.Description}</p>
                                            </div>
                                        </div>
                                    </div>
                                )}
                                {
                                    this.state.detailCards.length === 0 && <Fragment>{detailCard}{detailCard}{detailCard}{detailCard}</Fragment>
                                }
                                {
                                    this.state.detailCards.length === 1 && <Fragment>{detailCard}{detailCard}{detailCard}</Fragment>
                                }
                                {
                                    this.state.detailCards.length === 2 && <Fragment>{detailCard}{detailCard}</Fragment>
                                }
                                {
                                    this.state.detailCards.length === 3 && <Fragment>{detailCard}</Fragment>
                                }
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div className="col-12" style={{ backgroundColor: '#cccccc54', padding: '10px 20px' , height: 350}}>
                    <div className="row">
                    {_.map(this.state.styleColors, (color, i) => (
                        i <= 2 &&
                            <div key={i} className="col-4 p-2 text-center">
                                <div className="text-center m-1">
                                    <button className="btn btn-secondary btn-sm" style={{ fontSize:12, backgroundColor:'#000'}}>COLOR WAY {i+1}</button>
                                </div>
                                <div className="text-center m-1">
                                    <small className="m-0">{color.Title}</small>
                                </div>
                                <div className="form-group stext-center m-2">
                                    <input className="form-control form-control-sm text-center" defaultValue={color.Name} style={{ width:120, marginLeft: '30%'}}/>
                                </div>
                                <div  className="row justify-content-center text-center" style={{ fontSize:14 }}>
                                    <div className="col-4">
                                        <p className="m-0"> COLOR </p>
                                        <button style={{backgroundColor: color.CMYK, width: 70, height: 70, color: 'transparent'}}>t</button>
                                        <p className="m-0">{color.CMYK}</p>
                                    </div>
                                    <div className="col-4">
                                        <p className="m-0"> PANTONE </p>
                                        <button style={{backgroundColor: color.CMYK, width: 70, height: 70, color: 'transparent'}}>t</button>
                                        <p className="m-0">{color.Pantone}</p>
                                    </div>
                                </div>
                                <div className="text-center">
                                    <textarea  className="form-control p-3" style={{ width: "62%", margin: 'auto', height: 100 , resize: 'none'}}>

                                    </textarea>
                                </div>
                            </div>
                        )
                    )}
                    {
                        this.state.styleColors.length === 0 && colorCard
                    }
                    {
                        this.state.styleColors.length === 1 && <Fragment>{clrCard}{clrCard}</Fragment>
                    }
                    {
                        this.state.styleColors.length === 2 && <Fragment>{clrCard}</Fragment>
                    }
                    </div>
                </div>
            </div>
        </div>
        )
    }
}

class PrintEachPage extends React.Component {
    render() {
        const EachStyle = [];
        const stylesId = this.props.stylesId;
        for (var i = 0; i < stylesId.length; i++) {
            EachStyle.push(
                <PrintSinglePage 
                    key={i}
                    styleId={stylesId[i]} 
                    fetchStyleData={this.props.fetchStyleData}
                    fetchDetailData={this.props.fetchDetailData}
                    getColorsForStyle={this.props.getColorsForStyle}
                    styleData={this.props.styleData}
                    detailCards={this.props.detailCards}
                    styleColors={ this.props.styleColors}
                    printOpt={this.props.printOpt}
                    buyer={this.props.buyer}
                />);
        }
        return (
            <div>
                {EachStyle}
            </div>
        )
    }
}

class PrintOption1 extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            buyer: '',
            stylesId: [],
            styleId: 0,
            loading: true
        } 
    }
    componentWillMount() {
        if (this.props.match.path === "/styles/:styleId/details/print1" ) {
            const styleId = this.props.match.params.styleId
            this.props.fetchStyleData(styleId);
            this.props.fetchDetailData(styleId);
            this.props.getColorsForStyle(styleId);
            this.setState({ styleId : this.props.match.params.styleId})
        } else {
            this.setState({ stylesId: this.props.location.state.StylesId })
        }
    }
    componentDidMount() {
        document.getElementById("search_icon").style.display = "none"; 
        document.querySelector("meta[name]").content = "";
        const printStylecss = '@page { size: potrait; size: 215.9mm 279.4mm } img { -webkit-print-color-adjust: exact; color-adjust: exact } ',
        head = document.head || document.getElementsByTagName('head')[0],
        style = document.createElement('style'),
        title = document.getElementsByTagName('title');

        style.type = 'text/css';
        style.media = 'print';
        title[0].innerHTML = this.props.styleData.Name === undefined ? 'Collection' : this.props.styleData.Name
        if (style.styleSheet){
            style.styleSheet.cssText = printStylecss;
        } else {
            style.appendChild(document.createTextNode(printStylecss));
        }

        head.appendChild(style);
        this.setState({ buyer: this.props.location.state.buyer })

        setTimeout(() => this.setState({ loading: false }), 1000 * 5); 
    }
    
    render() {
        return (
            <div className="container-fluid mt-4 pt-5">
                <div className="row" style={{ height: '100vh', overflowY: 'scroll'}}>
                    <div className="col-lg-12">
                        <div className="card m-3">
                            <div className="card-body">
                                <div className="row">
                                    <div className="col-md-12 p-4">
                                        <div className="row justify-content-center">
                                            <div className="col-md-12">
                                                <div>
                                                    { !this.state.loading && <div className="text-left">
                                                        <button className="btn btn-secondary float-left" onClick={history.goBack}>Back</button>
                                                    </div>}
                                                    <div className="text-right">
                                                        <ReactToPrint
                                                            copystyles={true}
                                                            trigger={() =>  <button className="btn btn-secondary mb-3" disabled={this.state.loading}>Print this out!</button>}
                                                            content={() => this.componentRef}
                                                            onBeforePrint={() => {
                                                                
                                                            }}
                                                            onAfterPrint={() => {
                                                                console.log("after print!");
                                                            }}
                                                        />
                                                    </div>
                                                    {this.props.match.path === "/styles/:styleId/details/print1" ?
                                                        <PrintSinglePage ref={el => (this.componentRef = el)} 
                                                            styleData={this.props.styleData}
                                                            detailCards={this.props.detailCards}
                                                            styleColors={ this.props.styleColors}
                                                            buyer={this.state.buyer}
                                                            styleId={this.state.styleId}
                                                        /> : 
                                                        <PrintEachPage ref={el => (this.componentRef = el)} 
                                                            stylesId={this.state.stylesId}
                                                            buyer={this.state.buyer}
                                                            fetchStyleData={this.props.fetchStyleData}
                                                            fetchDetailData={this.props.fetchDetailData}
                                                            getColorsForStyle={this.props.getColorsForStyle}
                                                            styleData={this.props.styleData}
                                                            detailCards={this.props.detailCards}
                                                            styleColors={ this.props.styleColors}
                                                            printOpt={true}
                                                        />
                                                    }
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

export default PrintOption1;`

**Comment by SaravananAnbu** [comment]
Did you have gitlab, i will give access...

> Can you please make a codesandbox or something replicating the issue?

**Comment by ArunJeyR** [comment]
This issue is real urgent and we can provide access to our gitlab if you have an account.. The main issue is the images are missing when we tried printing on Mac but works fine on windows. Sandbox wont work.. This requires an immediate fix..

**Comment by MatthewHerbst** [comment]
@ArunJeyR why will Sandbox not work? I do not have a gitlab account.

**Comment by ArunJeyR** [comment]
Because I need to upload the entire code to Sandbox thats why.. if you want it, probably i can give you my gitlab access will that work? PS: We are pulling images from S3 bucket.

**Comment by ArunJeyR** [comment]
or if you got a skype account please drop by, and I can share my screen or video if needed.

**Comment by MatthewHerbst** [comment]
@ArunJeyR you don't need to upload all of the code. You only need to make a minimum viable example of the bug. While I appreciate the offer, I do not want access to your credentials - that is a security/privacy risk for both of us.

**Comment by ELTEGANI** [comment]
did you find any solution i have the same problem @MatthewHerbst

**Comment by ELTEGANI** [comment]
it's working but stopped suddenly with no errors in log ....this is my code @MatthewHerbst 
 ```
<div ref={el => (this.componentRef = el)}>
         <Header as='h1' textAlign='center'>{this.state.formdata.name}</Header>
         <Image 
          size='large'
           centered  
           src='myqrcodelink'
            rounded/>  
        </div>

          <Form.Group widths={1}> 
         <ReactToPrint
          trigger={() => <Button type='submit' color='pink' fluid >Print  QRCODE</Button>}
          content={() => this.componentRef}
         />

```

**Comment by MatthewHerbst** [comment]
@Tiganimohammad please make a _working_ code example. I can do nothing with the above. I don't even know what your `Image` component does.

**Comment by ArunJeyR** [comment]
@MatthewHerbst Honestly, It would be really helpful, if you can spare couple of minues on skype video call.. while I share the video.. atleast.. or if its still not ok. then I will have to paste my entire code here.. or copy paste the entire code on sandbox. Thats what i am worried about.

**Comment by MatthewHerbst** [comment]
@ArunJeyR I think you misunderstand me. I understand the problem you are having. However, I cannot attempt to investigate or fix it without a working code example. Again, you do **NOT** need to create a sandbox of your entire code. All you need to do is create a minimum viable reproduction of the bug, which sounds like it is just in a tiny, tiny section of your overall codebase.

**Comment by kildem** [comment]
I have tried this code on Mac:
```
import React, { useRef } from 'react'
import ReactToPrint from 'react-to-print'

class ComponentToPrint extends React.Component {
  render() {
    return (
      <table>
        <thead>
        <tr>
        <th>column 1</th>
        <th>column 2</th>
        <th>column 3</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>data 1</td>
          <td>data 2</td>
          <td>data 3</td>
        </tr>
        <tr>
          <td>data 1</td>
          <td>data 2</td>
          <td>data 3</td>
        </tr>
        <tr>
          <td>data 1</td>
          <td>data 2</td>
          <td>data 3</td>
        </tr>
        </tbody>
      </table>
    );
  }
}

const PrintEsample = () => {
  const componentRef = useRef();
  return (
    <div>
      <ReactToPrint
        trigger={() => <button>Print this out!</button>}
        content={() => componentRef.current}
      />
      <ComponentToPrint ref={componentRef} />
    </div>
  );
};
```
this is the page:
<img width="290" alt="Schermata 2019-04-29 alle 11 51 49" src="https://user-images.githubusercontent.com/1815732/56888814-3d14c500-6a75-11e9-9269-bec8a7f13b09.png">

When I click `Print this out!` button the preview is blank:
<img width="996" alt="Schermata 2019-04-29 alle 11 52 01" src="https://user-images.githubusercontent.com/1815732/56888867-5e75b100-6a75-11e9-8e07-b682f035e4f1.png">

**Comment by ELTEGANI** [comment]
@MatthewHerbst  sorry for not provide you with working code ...my problem is the same of the guy posted above would you please help us I used it in the production and it suddenly stopped and worked again I mean some time preview is blank and sometimes not

**Comment by MatthewHerbst** [comment]
@kildem / @Tiganimohammad are there any console errors when you get the blank screen?

**Comment by ELTEGANI** [comment]
@MatthewHerbst I have no errors in the console

**Comment by MatthewHerbst** [comment]
@Tiganimohammad it works for me using this codesandbox with the code above (seems to be the main example but using `useRef` as the only difference: https://codesandbox.io/s/3qyl47rznq?fontsize=14

I cannot replicate this issue, and no one has been able to give me an error message. Can someone please get me either an error message or a working code example that can reproduce the issue? Thank you.

**Comment by kildem** [comment]
@MatthewHerbst I don't understand why in version 2.0.0-beta-4 it works, but on version 2.2.1 it doesn't.
In codesanbox I see it works 🤔

**Comment by kildem** [comment]
I have upgrade the packages react-... and Webpack-.... and it works now :tada:

**Comment by kildem** [comment]
using version 2.1.1 it works only if I remove 
@font-face ( url("...woff2") format("woff2"), url("... truetype") format("truetype”), url("... woff")  format("woff")) from my application. :disappointed:
if I use  react-to-print@2.0.0-beta-4 everything works

**Comment by MatthewHerbst** [comment]
@kildem can you make a working codesandbox with that css breaking `react-to-print` so that I can play around with it please?

**Comment by kildem** [comment]
@MatthewHerbst I have created a public Github repository that replicate this issue, you can clone it and play around with it:
https://github.com/kildem/test-react-to-print

**Comment by MatthewHerbst** [comment]
Hello. Version 2.1.2 was just published with a fix from @aviklai that aims to address this issue. Please let me know if you see any continued problems.

**Comment by kildem** [comment]
It works now :smiley:

**Comment by MatthewHerbst** [comment]
Haven't seen anyone else complain about this. Going to close as fixed. Thank you everyone for your reports and patience, and thank you @aviklai for the fix!
