### ISSUE TITLE
Only first page is printing on Firefox web browser 

### ISSUE THREAD

**Issue by Erandakuruneru** [MatthewHerbst/react-to-print#12]
An only first page is printing on Firefox web browser. Did not print the second page.
if we set the copyStyles as false.then only print all the pages, but that time paging styles disappeared.

**Comment by gregnb** [comment]
Thank you for reporting the issue. Would you be able to share your repo so I could download and look at this issue myself? Is it available on Github?

**Comment by Erandakuruneru** [comment]
Sorry, it's not available on Github, I have modified the code,
in my print.css file added following code line.
div {
    overflow: visible !important;
  }
After that, I was able to print two pages, but this time I got the empty page as the first page and two, three pages had all the data.

**Comment by gregnb** [comment]
Yeah it will be hard for me to see what is going on for you exactly.  If you can provide some sort of stripped down simple version online I would be more than happy to look into the issue for you

**Comment by gregnb** [comment]
I've started to use this package to support another one I've created and if you visit: 

https://wy2rl1nyzl.codesandbox.io/

and click on the print icon in the upper right hand toolbar you shouldn't experience any issues. In the popped up window this is extracting dynamic styles generated from material-ui

<img width="1427" alt="screen shot 2018-04-10 at 6 01 03 pm" src="https://user-images.githubusercontent.com/19170080/38585793-32db4254-3ce9-11e8-8846-b1a7b6ba3f4c.png">

**Comment by Erandakuruneru** [comment]
that's something related to my styling if I remove styles it will work fine. there is no issue with the print package.
Thanks for your comments and supports.

**Comment by kwayebopp** [comment]
@Erandakuruneru what did you change to solve your problem? I believe I am experiencing the same bug. 

I have a long div (specifically as QuillJS text editor), and I want to print the content. Only the first page gets stuff printed onto it, and the text runs off the bottom of the first page instead starting the next page.

**Comment by Erandakuruneru** [comment]
Actually that was css styling issue, Our UI developer changed the styling,then it works fine.

**Comment by kwayebopp** [comment]
Can you say exactly what the fix was, or post some sample code for the fix?
