### ISSUE TITLE
Cannot run the app after using the library

### ISSUE THREAD

**Issue by kithma** [MatthewHerbst/react-to-print#121]
After using react-to-print I got following error

index.js:2178 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

and now I cannot run the app

Any idea why this happen?

**Comment by MatthewHerbst** [comment]
Hello. How are you using it? How are you importing it? What version of the app are you using?

**Comment by kithma** [comment]
React version - 16.4.2
react-to-print - 2.0.0-alpha.7

This is how I'm importing it and basically using it

import ReactToPrint from "react-to-print";

```export default class CalendarStartPage extends Component {
    render(){
        return ( <div>
                       	{this.renderPrintButton()}
                       <Calendar onViewChange={view => this.setState({ view })} ref={el => 
                      (this.componentRef = el)} />)
                    </div>
    }
    	renderPrintButton() {
		return (
			<ReactToPrint
				trigger={() => (
					<div className="print-button">
						<i className="icon icon--basket" />
						<span className="ml-1">Print me</span>
					</div>
				)}
				content={() => this.componentRef}
			/>
		);
	}
}```

**Comment by MatthewHerbst** [comment]
@kithma please try using the latest version, 2.1.1

**Comment by kithma** [comment]
Thanks @MatthewHerbst now it's working :D
