### ISSUE TITLE
Default Filename in save as PDF

### ISSUE THREAD

**Issue by abdurrehman1998** [MatthewHerbst/react-to-print#122]
I am trying to give default filename for the save as pdf option in react-to-print.

**Comment by MatthewHerbst** [comment]
Pull requests are welcome to add support for this :)

**Comment by gregnb** [comment]
I would probably say no to this feature only because we would need to bring in jsPDF which doesn't really generate quality PDF's on top of the cost of importing that library.

Thoughts @MatthewHerbst ?

**Comment by MatthewHerbst** [comment]
Oh, my understand of the issue was to just be able to set a default file name in the print preview, irregardless of what is being printed. @abdurrehman1998 can you expand on what functionally you are looking for please?

**Comment by gregnb** [comment]
You're right I misread that. I tried digging around and seems like this would work in Chrome:

https://stackoverflow.com/questions/26905908/chrome-save-to-pdf-custom-filename

but I don't see much about other browsers

**Comment by abdurrehman1998** [comment]
I resolved that by adding <title>Filename</title> tag at the top of my component that is to be print.Thanks all.

**Comment by qron** [comment]
> I resolved that by adding <title>Filename</title> tag at the top of my component that is to be print.Thanks all.

Sadly, I am not able to make it work with Chrome (Version 77.0.3865.90 (Official Build) beta (64-bit) on OSX Mojave 10.14.6 but I am not sure if it depends of chrome version). But it seems to work perfectly with firefox.

Edit: Okay, I think I've figured it out: I believe Chrome takes the highest title tag to define the title of the print export, at the contrary of Firefox, which takes the lowest.

**Comment by MatthewHerbst** [comment]
Thanks for the insight @qron!

**Comment by soccermom123** [comment]
I used ' document.title="the-name-of-the-pdf-file"; ' to set title of the page,and turns out it worked(edge firefox and chrome).

**Comment by HlalaElseadawy** [comment]
> I used ' document.title="the-name-of-the-pdf-file"; '

how can i use it in oracle apex print page

**Comment by MatthewHerbst** [comment]
> how can i use it in oracle apex print page

Hi @HlalaElseadawy please open a new issue if you are having trouble, thank you
