### ISSUE TITLE
how do you make a print directly? without click the button first ?

### ISSUE THREAD

**Issue by putrairawan992** [MatthewHerbst/react-to-print#126]

**Comment by MatthewHerbst** [comment]
There's no way to print via API right now. The work is planned but there is no estimation for when it will be completed. If you'd like to make a PR supporting this I'd be happy to get it included!

**Comment by putrairawan992** [comment]
this my code

[
![Screen Shot 2019-05-14 at 11 29 22](https://user-images.githubusercontent.com/31697177/57671310-73d60800-763d-11e9-9c6d-7805ddf10936.png)
](url)

**Comment by MatthewHerbst** [comment]
@putrairawan992 what you are asking for is not currently possible.
