### ISSUE TITLE
How to print child component without render it on parent component

### ISSUE THREAD

**Issue by jogoool** [MatthewHerbst/react-to-print#127]
My parent component is a table and it has many other components with a print button that generate report to print, the child component <ReportTemplate /> is a template of report. when I try to reference it` <ReportTemplate ref={el => (this.componentRef = el)}/>` it is rendered in Parent component. How can I pass the child component to `<ReactToPrint/>` without rendering it on parent component.

example 

```
import ReportTemplate from './ReportTemplate';

class Report extends Component {
...

render() {
     return(
        <div>... </div> . <----- other child components
        <div>
            <ReactToPrint
                  trigger={() => <a href="#">Print this out!</a>}
                  content={() => this.componentRef}
            />
            <ReportTemplate ref={el => (this.componentRef = el)} /> . <--- ReportTemplate is rendering in parent component.
      </div>
    );
}
}

export default Report;
```

**Comment by lxx7061** [comment]
```js
<ReportTemplate ref={el => (this.componentRef = el)} /> 
```
 to => 
```js
<div style={{display:none}}>
     <ReportTemplate ref={el => (this.componentRef = el)} /> 
</div>
```

**Comment by fershibli** [comment]
> ```js
> <ReportTemplate ref={el => (this.componentRef = el)} /> 
> ```
> 
> to =>
> 
> ```js
> <div style={{display:none}}>
>      <ReportTemplate ref={el => (this.componentRef = el)} /> 
> </div>
> ```

I've tried your solution, but got an error instead:
`'none' is not defined  no-undef`

here's my code:
```
<div>
  <ReactToPrint
    trigger={() => <Button >{t("Print Token")}</Button>}
    content={() => this.componentToPrint}
  />
  <div style={{display:none}}>
    <ResultAccessToken ref={el => (this.componentToPrint = el)} />
  </div>
</div>
```

**Comment by MatthewHerbst** [comment]
@FernandoLuizNemeChibli the `style` prop does not understand CSS, so values need to be strings:

`style={{display:none}}` -> `style={{ display: 'none' }}`

**Comment by fershibli** [comment]
@MatthewHerbst oh! now worked perfectly! thanks! (:
Thank you too, @lxx7061!

**Comment by phongle2512** [comment]
Actually, when I have more than 200 tables to print (each table per page), the `<ReportTemplate ref={el => (this.componentRef = el)} />` make the parent component render too slow :( although I wrap a div to hide it `<div style={{display:"none"}}></div>`

Anyone suggest any solution ? I tried to use `onBeforePrint` to inject html then do the print, but it returns empty page, if I tried again then I can see the data =.=

**Comment by devuxer** [comment]
Can I suggest adding this to the FAQ in the README?

**Comment by MatthewHerbst** [comment]
@devuxer Sure! Mind making a PR for it?

**Comment by devuxer** [comment]
@MatthewHerbst , Done!
