### ISSUE TITLE
Why are there css that don't appear when printed?

### ISSUE THREAD

**Issue by putrairawan992** [MatthewHerbst/react-to-print#128]
this display in the browser :
![Screen Shot 2019-05-15 at 22 21 58](https://user-images.githubusercontent.com/31697177/57787621-eccd8080-775f-11e9-9ec3-ec39ed102362.png)

this print view :
![Screen Shot 2019-05-15 at 22 23 04](https://user-images.githubusercontent.com/31697177/57787697-171f3e00-7760-11e9-9b01-f16595e8d949.png)

this code:
![Screen Shot 2019-05-15 at 22 24 28](https://user-images.githubusercontent.com/31697177/57787834-46ce4600-7760-11e9-837a-7d17a0696d65.png)
![Screen Shot 2019-05-15 at 22 24 36](https://user-images.githubusercontent.com/31697177/57787839-4a61cd00-7760-11e9-8967-4b9ae9ee7498.png)

and SASS
![Screen Shot 2019-05-15 at 22 24 46](https://user-images.githubusercontent.com/31697177/57787848-4fbf1780-7760-11e9-9ac6-68293394730f.png)

help me thanks

**Comment by putrairawan992** [comment]
@MatthewHerbst

**Comment by MatthewHerbst** [comment]
Can you please ensure that you have the background graphics options turned on when you are in the print preview?
<img width="994" alt="Screen Shot 2019-05-15 at 2 28 00 PM" src="https://user-images.githubusercontent.com/1287375/57810855-aa834f80-771d-11e9-8232-8c025515a94b.png">

**Comment by ronmaple** [comment]
I have the same problem on Chrome -- with background graphics turned on

**Comment by MatthewHerbst** [comment]
What version of the library are you using @ronmaple ?

**Comment by ronmaple** [comment]
2.1.2

**Comment by MatthewHerbst** [comment]
@ronmaple any chance you could make a codesandbox please replicating the issue?

**Comment by ronmaple** [comment]
https://codesandbox.io/embed/compassionate-dew-txilb

I'm trying to center the QRCode component, and the p tag

**Comment by MatthewHerbst** [comment]
Thanks @ronmaple! I'll try and take a look tonight but may not be able to get to it until this weekend

**Comment by putrairawan992** [comment]
@MatthewHerbst  hello helpme please

**Comment by MatthewHerbst** [comment]
@putrairawan992 can you please make a condesandbox with your code so I can see it live?

**Comment by MatthewHerbst** [comment]
@ronmaple your issue is that your `text-align: center` is on the `App` class but that class is on the parent of the component being printed, not on the component itself.

**Comment by putrairawan992** [comment]
https://codesandbox.io/embed/reverent-bas-whpw7 @MatthewHerbst

**Comment by ronmaple** [comment]
@MatthewHerbst Oh! I see, that fixes it. I didn't realise that the print view might have been different from the web view, in terms of how (I'm assuming) the library uses the component to render the view. Thanks!

**Comment by putrairawan992** [comment]
why can't the background color and image appear

**Comment by MatthewHerbst** [comment]
@putrairawan992 I don't see a difference between the codesandbox render and the print output. I'm on Chrome 74. What browser are you using?

<img width="1189" alt="Screen Shot 2019-05-15 at 4 43 48 PM" src="https://user-images.githubusercontent.com/1287375/57816594-bdebe600-7730-11e9-8ad2-495d1e8f3b3f.png">
<img width="683" alt="Screen Shot 2019-05-15 at 4 44 03 PM" src="https://user-images.githubusercontent.com/1287375/57816595-bdebe600-7730-11e9-8060-b6f1be0f729c.png">

**Comment by putrairawan992** [comment]
![Screen Shot 2019-05-16 at 08 28 50](https://user-images.githubusercontent.com/31697177/57819930-bcfc9800-77b4-11e9-8360-b84032180681.png)
Os Macbook

**Comment by MatthewHerbst** [comment]
@putrairawan992 is there something in the screen shots I shared that is not being displayed?

**Comment by putrairawan992** [comment]
i dont show background 
![Screen Shot 2019-05-16 at 08 28 50](https://user-images.githubusercontent.com/31697177/57820057-50ce6400-77b5-11e9-987f-939a33d0cffc.png)

**Comment by putrairawan992** [comment]
![Screen Shot 2019-05-16 at 08 32 46](https://user-images.githubusercontent.com/31697177/57820157-c6d2cb00-77b5-11e9-83b5-bd9b23a60709.png)

**Comment by MatthewHerbst** [comment]
@putrairawan992 can you show me the options under "More settings"? On mine I can replicate what you see by turning "Background graphics" off. You need to turn that on.

**Comment by putrairawan992** [comment]
solved brother thanks
