### ISSUE TITLE
How do I configure to print for a ticket printer?

### ISSUE THREAD

**Issue by fershibli** [MatthewHerbst/react-to-print#130]
I need to print in a thermal paper printer, those that prints tokens, tickets, etc. 
What argument do I pass in pageStyle parameter to print in that size? Is there a list of page styles or a way of configuring a new page style?
How do I test this without a printing?

**Comment by MatthewHerbst** [comment]
This sounds like a question better suited for StackOverflow.

**Comment by fershibli** [comment]
For people who got at this page and is looking for my question at StackOverflow, here is the link: https://stackoverflow.com/questions/56265202/how-do-i-configure-to-print-for-a-thermal-paper-printer-with-react-to-print

**Comment by MatthewHerbst** [comment]
Hi @FernandoLuizNemeChibli were you ever able to figure this out? I'm going to close the issue would would love to know the solution so that if others have the same problem they can find this question

**Comment by luissantiagodev** [comment]
I just came up with this problem, is there a solution to this?

**Comment by MatthewHerbst** [comment]
@luissantiagodev you'll likely have to do some type of media query or use printer specific driver settings on your computer, this library has no knowledge of what type of printer you use to print.
