### ISSUE TITLE
Error: Function components cannot be given refs. Attempts to access this ref will fail

### ISSUE THREAD

**Issue by ibanjb** [MatthewHerbst/react-to-print#131]
Hi there!

I'm using this module in our application and, when the component that has the logic to print is displayed, appears in the browser's console an error message: "Function components cannot be given refs. Attempts to access this ref will fail".  

The code that I'm using is this:

```
class CaseTasks extends PureComponent {


<ReactToPrint
   trigger={() => <Icon className={styles.onHover} type="printer" />}
   content={() => this.componentRef}
/>
<div style={{ display: 'none' }}>
   <PatientGynPrintForm
     patient={patient}
     patientCase={patientCase}
     ref={el => (this.componentRef = el)}
   />
</div>

```

And the module 'PatientGynPrintForm' is a React.PureComponent class too so I don't know how to solve this problem. I was taking a look at the issue #96 but is not the same case.

Any tips will be appreciated.

Thanks!

**Comment by MatthewHerbst** [comment]
Hi there. Can you please most more complete code, or ideally make a codesandbox or similar where I can see the problem live?

**Comment by jpnut** [comment]
Is the `Icon` component a functional component? The react element used for the trigger is [cloned and a ref injected](https://github.com/gregnb/react-to-print/blob/master/src/index.tsx#L193), so it must also not be a functional component.

If that's the case, you could:
 - wrap the `Icon` with another element or non-functional component
 - change `Icon` to a non-functional component
 - [forward the ref](https://reactjs.org/docs/forwarding-refs.html) on the `Icon` component

**Comment by MatthewHerbst** [comment]
Hey @ibanjb were you able to solve your issue here?
