### ISSUE TITLE
Can't use setState() in onAfterPrint callback function if I click exit window button

### ISSUE THREAD

**Issue by hyunpill3** [MatthewHerbst/react-to-print#132]
I have this element

```
<ReactToPrint
                  trigger={() => (
                 <IconButton
                   aria-label={intl.formatMessage(message.tableToolbarPrint)}
                   classes={{ root: classes.icon }}
                   style={{
                     color: printState ? '#FFF' : '#757575',
                     background: printState ? '#FBCF21' : 'none',
                   }}
                 >
              <PrintIcon data-igls-test="mui-data-table-toolbar-print" />
              /IconButton>
         )}
        content={() => this.props.tableRef()}
       onBeforePrint={() => { this.setState({ printState: true}) }}
      onAfterPrint={() => { this.setState({ printState: false }) }}
      closeAfterPrint
/>
```

onBeforePrint and onAfterPrint work fine. However, if I close the print window using exit button (not cancel button), then the site crashes and I am getting this error.

> Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by MatthewHerbst** [comment]
Hello. Can you please make a working code example (such as with codesandbox.io) to show the problem? I am unable to replicate it with the base example.

**Comment by hyunpill3** [comment]
@MatthewHerbst 
Sorry I solved the issue. I was using old version of react-to-print. Newer version works.
Closing the issue
