### ISSUE TITLE
Make Code Sandbox example for Functional Components with hooks in strict TypeScript

### ISSUE THREAD

**Issue by nhooey** [MatthewHerbst/react-to-print#135]
I'm getting a `cross-origin error` when copy-pasting the [Calling from functional components with hooks](https://github.com/gregnb/react-to-print#calling-from-functional-components-with-hooks) example over the `example/index.js` file found in the [Code Sandbox Example](https://codesandbox.io/s/kmmw7l39y7), in this [forked Code Sandbox Example](https://codesandbox.io/s/reacttoprint-oep7f).

I'm trying to do this because in my private repository, TypeScript is complaining that the function supplied to `<ReactToPrint>`'s `content` parameter could have an `undefined` value for the `componentRef` variable.

It seems that the Functional Components example doesn't work with strict TypeScript.

Adding a new Code Sandbox example would help.

**Comment by MatthewHerbst** [comment]
Yeah, we have a few issues with the Code Sandbox example, the primary one being that it uses an outdated version of the app. Agreed that we should make additional ones. If we don't see an update in https://github.com/gregnb/react-to-print/issues/133 soon I'll create new sandboxes on my account, but was hoping @gregnb would keep them updated on his.
