### ISSUE TITLE
Unable to print child components

### ISSUE THREAD

**Issue by muriukim** [MatthewHerbst/react-to-print#14]
```html
<div style={{ textAlign: "left" }}>
       <p style={{ textTransform: "uppercase" }}>Name: {patient.get('firstName') + " " + 
         patient.get('middleName') + patient.get('lastName')}</p>
        <p>ID: {patient.get('id')}</p>
        <p>Time:{(new Date(parseInt(queueItem.get('time')))).toLocaleDateString()}</p>
        <p>Ticket 2453:</p>
         <p>There are patient(s) ahead of you</p>
         <QRCode size={100} value={434} />
         <Footer />
</div>
```

The components QRCode and Footer doesnt appear in the print.

**Comment by gregnb** [comment]
If you look at this example here: https://codesandbox.io/s/x3jx2kpq6w

There is no issue with child components

**Comment by muriukim** [comment]
What could be the issue with my child components. Ofnotes is the the QRCode component actually renders a canvas

**Comment by muriukim** [comment]
In the sandbox, the QRCode doesnt print. Seems your library cant canvas. I think you should add that as a feature

**Comment by muriukim** [comment]
But just noticed that the QRCode library allows you to render as svg using the renderAs prop. Thanks for the help and nice library.
