### ISSUE TITLE
BuiltIn Flag to exclude the "Trigger" from Print

### ISSUE THREAD

**Issue by LeopoldLerch** [MatthewHerbst/react-to-print#141]
Like the title said

It would be nice to have a flag for excluding the trigger from the print. Of course we can add the corresponding "media"-styles by ourself, but it would be a nice idea to have that built in.

**Comment by MatthewHerbst** [comment]
Hi @LeopoldLerch can you please post an example of what you want? The trigger is not included in the print, as can be seen from the codesandbox example on the README.

**Comment by LeopoldLerch** [comment]
No, in the example it is not included because it is printing a component in
which the reacttoprint component is not included. My case is about printing
a component where the reacttoprint- component ( and therefore the trigger)
IS included in the component-stack.

Matthew Herbst <notifications@github.com> schrieb am Fr., 28. Juni 2019,
19:56:

**Comment by MatthewHerbst** [comment]
`react-to-print` has no knowledge of what is in the component-stack to print, it only ones what the ref of the root level node of the stack is. You will need to remove `ReactToPrint` from the component stack.

You can do that either by re-arranging your code a bit, or, by using CSS to hide (`display: none`) the trigger component when being printed.

**Comment by LeopoldLerch** [comment]
I am speaking about such a constellation, to be clear:

```jsx
const componentRef = useRef();

return (
  <div className={css(styles.formsContainer)} ref={componentRef} >
    <h2 className={styles.formsTitle}>
      {Strings.PressespiegelHeaderText}
      {!printMode &&
        <ReactToPrint
          trigger={() => <a href="#">Print this out!</a>}
          content={() => componentRef.current}
          onBeforePrint={() => setPrintMode(true)}
          onAfterPrint={() => setPrintMode(false)}
        />
      }
</h2>
</div>
```

So, it is about printing an parent-component of the ReactToPrint-Component. In this case the trigger is included. In the example it is a "neighbouring" component which should be printed, therefore of course the trigger is not included in the output.

**Comment by LeopoldLerch** [comment]
I know that it doesn´t know about the stack. That´s why I asked for an flag/property which results in in wrapping the trigger in a html element with a "@media:print {display:none}" or something like that. (Well, as I think about it, this could also be the default I guess). That way i can leave it inside the component (which makes it easier for positioning purposes) and it won´t be printed at all (and the function is already built in and does not need to be readded by every user who needs that case).

Just a proposal.

**Comment by MatthewHerbst** [comment]
Why not just wrap it in the media query yourself? I think we should be very wary of API bloat or DOM changes, even for little things.

**Comment by MatthewHerbst** [comment]
I'm going to close this since I think there are available solutions for doing this without library changes. If you know of a way the library could do this that is far superior to what can happen is user-land I would be open to considering it
