### ISSUE TITLE
Issues printing on chrome

### ISSUE THREAD

**Issue by taylorgannon** [MatthewHerbst/react-to-print#142]
I'm having issues printing on Chrome from my project.  It's working sometimes, but I can't find a pattern to indicate why it's sometimes working and sometimes not working.  Whenever I press the print button I see the `<iframe>` in the "Elements" of Chrome dev tools, but the print dialog never shows up.  Any idea what could be happening?

Print Component
```jsx
export class Print extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    const { label, withConfiguration } = this.props;
    return (
      <div>
        <ReactToPrint
          pageStyle={
            '@page { margin: 0.5in; } @media print { body { -webkit-print-color-adjust: exact; } }'
          }
          trigger={ () => (
            <a href='#'>
              <Button
                label={ label }
                icon='print'
                color='secondary'
                onClick={ () => {} }
              />
            </a>
          ) }
          content={ () => this.componentRef }
        />
        <div style={{ display: 'none' }}>
          <ComponentToPrint
            { ...this.props }
            ref={ el => (this.componentRef = el) }
            withConfiguration={ withConfiguration }
          />
        </div>
      </div>
    );
  }
}
```

Component to Print
```jsx
export class ComponentToPrint extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    const { office, withConfiguration, officeColor } = this.props;
    return (
      <Row style={ sty.wrapper }>
        ...
      </Row>
    );
  }
}
```

**Comment by MatthewHerbst** [comment]
Hi there. That does sound pretty strange. Can you please let me know what version of Chrome you are on? Also, what stylesheets are loaded on the page?

On a side note, you don't need to have the `<a>` tag around your button for it to work, and I'm pretty sure a `button` tag should not be within an `a` tag.

**Comment by taylorgannon** [comment]
@MatthewHerbst It was an issue with the configuration of the project 👍 Back to normal now.
