### ISSUE TITLE
Footer /tfoot at the bottom of the 2nd page

### ISSUE THREAD

**Issue by navjeetsingh** [MatthewHerbst/react-to-print#143]
Hey, 
First, thank you very much for the awesome library. I am having minor issues, I have wrapped the content in a HTML table tag and on single page by giving `tfoot` with the css property of `vertical-align: bottom` the main table wrapper of 90vh and table tag a height of 100% puts the `tfoot` at the bottom which is perfect now the problem is if the content/`tbody` goes to 2nd page the 2nd page `tfoot` does not sit at the bottom of the 2nd page. any idea how can I fix this issue on the 2nd page?
Is there a way to determine on which page we are? so we can set the footer always as a bottom?

Thank you very much.

**Comment by MatthewHerbst** [comment]
Hello, thanks for asking. Can you please make a codesanbox showing the issue?

**Comment by navjeetsingh** [comment]
Hello Matthew,

Thank you very much for the prompt reply, please find the link for the codesandbox below:

[printpdf codesandox](https://codesandbox.io/s/sad-silence-79wrc?eslint=1&expanddevtools=1&fontsize=14&initialpath=%2Fsrc&moduleview=1)

Regards,

**Comment by MatthewHerbst** [comment]
Hi @navjeetsingh sorry for the delayed response. I'm looking at the example you posted and I feel that I don't fully understand what the problem is. Can you explain visually what you are expecting versus what is happening? Thanks

**Comment by navjeetsingh** [comment]
Hi @MatthewHerbst, thank you for the reply, the problem I am facing is if the pdf is more than one page long the footer from 2nd page onwards does not sit at the bottom, attaching how the footer sits on the first page the footer sits at the bottom no matter how short the content is. But the moment we are on the 2nd page or the 3rd page the footer does not stick at the bottom anymore. Attaching how the footer sits on the 2nd page is displayed. I am using HTML table syntax and for the footer, my content is in `<tfoot>` as I have tried to show on code sandbox. Hope I am able to express my concern clearer this time :)
Thank you once again 
![footer-1st-page](https://user-images.githubusercontent.com/4686409/61600916-5d5fb480-ac5d-11e9-8706-403604f236fb.png)
![footer-2nd-page](https://user-images.githubusercontent.com/4686409/61600924-62bcff00-ac5d-11e9-97c5-6d5a04509d72.png)

**Comment by MatthewHerbst** [comment]
Hi @navjeetsingh I have been looking at this and I don't see anything related specifically to this library that might be causing the issue. Do you have a reason to think the issue is caused by `react-to-print`? I'm not an expert on HTML table css so not sure what might be going on there. Have you been able to find a solution to this?

**Comment by MatthewHerbst** [comment]
Hi @navjeetsingh were you able to resolve this?

**Comment by navjeetsingh** [comment]
Hello,

Unfortunately, the problem still persists :( Is there a patch to fix this issue?

Thank you very much for getting back

**Comment by ruralist-siyi** [comment]
I met the same problem，Do you have a solution？

**Comment by navjeetsingh** [comment]
Unfortunately no :( we are now thinking of having the pdf generated by the backend and we just use the pdf url from there.

A nice plugin tho just some minor issues need addressing.
