### ISSUE TITLE
How can I print to a specific printer ?

### ISSUE THREAD

**Issue by sonnthai97** [MatthewHerbst/react-to-print#144]
I have a list of printers as shown below. How do I choose a printer on that list ?

![ListPrinter](https://user-images.githubusercontent.com/48054554/61195252-0142e080-a6f1-11e9-9e2c-ff61f9d8f425.PNG)

**Comment by MatthewHerbst** [comment]
You click one and select it? This question has nothing to do with this library. Please ask it on StackOverflow or some other general question site, thank you.

**Comment by sonnthai97** [comment]
No. I want to select one specific printer with each button. Ex: When I click button A then BIXILON SLP-T403 printer automatically selected in preview pop-up.

// This button will select one specific printer.
 <ReactToPrint
                  copyStyles
                  trigger={() => (
                    <button>This button will select BIXILON SPL-T403 Printer<button>
                  )}
                  content={() => this.orderReceiptCard}
/>

**Comment by MatthewHerbst** [comment]
I don't think there is any way for us to do that. All we do is open the print window. After that the browser handles everything.

If you know of a widely supported API that lets us pre-select options in the print window when we open it, please let me know and I'd be more than happy to implement it.

**Comment by laclance** [comment]
Anyone know of a solution yet?

**Comment by MatthewHerbst** [comment]
> Anyone know of a solution yet?

Unfortunately this is simply not possible with JavaScript today 😢  there is no Print API that browsers implement, though I'm working on such a proposal! Unfortunately that will probably take years since such things go through many layers of standards committees before ever being implemented by the browsers

**Comment by laclance** [comment]
Yeah well we are using nextjs so hopefully can use https://github.com/Klemen1337/node-thermal-printer.

**Comment by MatthewHerbst** [comment]
Nextjs is still JavaScript. What you are looking for is something _the browsers_ do not support. There is no JavaScript you can write, or package you can use, to make the browsers support it. There are many interesting packages, including the one you linked, that can be used when Node.js is being used, but your website doesn't run Node.js on the client, only on the server, and your servers can't tell a client's browser which printer to select.

On the topic of Node.js printing, there was a very fun read the other week about a dev making a printer driver in JS: https://kubesail.com/blog/2022-02-01-printer-driver-in-javascript

**Comment by laclance** [comment]
Thanks for your reply, yeah but the package doesn't print through the browser, it prints directly to the printer but I guess would have to set up the printer so it's available and secure it. Otherwise nextjs has a Custom Server capability which runs locally.

**Comment by laclance** [comment]
but looking at that blog post and the comments maybe it is possible to do it client side

**Comment by MatthewHerbst** [comment]
> the package doesn't print through the browser, it prints directly to the printer

In that case I don't think `react-to-print` will work for you at all, since we access the `window` object and assume the library is being run in the browser. The library will likely not work natively in a pure Node.js environment
