### ISSUE TITLE
Version 2.2.0 does not open print window

### ISSUE THREAD

**Issue by hilo2120** [MatthewHerbst/react-to-print#148]
I tried to use the latest version (2.2.0 at the time), but print window does not open, I forked official codesandbox example using latest version and it doesnt work either.
https://codesandbox.io/s/react-to-print-in5sj
version 2.1.2 works as expected.

My Repositories:
react 16.8.6
react-dom 16.8.6
...

Browsers:
chrome 75.0
firefox 68.0.1

**Comment by MatthewHerbst** [comment]
Fixed in #149 and published as version 2.2.1, thanks for the report and please let us know if you encounter any other issues!
