### ISSUE TITLE
can't print image

### ISSUE THREAD

**Issue by zhayes** [MatthewHerbst/react-to-print#15]
![image](https://user-images.githubusercontent.com/17758062/39976464-7da83ed0-5766-11e8-9354-7116970bb392.png)

![image](https://user-images.githubusercontent.com/17758062/39976390-13432668-5766-11e8-887e-95744c5db10c.png)

![image](https://user-images.githubusercontent.com/17758062/39976413-32e23d74-5766-11e8-948e-812fb90fc78f.png)

**Comment by vademyanchik** [comment]
The same problem

**Comment by gregnb** [comment]
What path is provided for the image? is it absolute? Or relative?

My guess is that it is a relative path and I need to fix the package to handle relative paths for images. That was a recent bug in the stylesheets that I should address here regardless

**Comment by zhayes** [comment]
absolute path @gregnb

**Comment by mezzab** [comment]
same problem

**Comment by rafael-cineis** [comment]
Any update? I'm having the same issue when trying to print an image using Edge. Using Chrome, Firefox and IE it works fine. Pressing CTRL+P works fine in Edge.

**Comment by gregnb** [comment]
I just published 1.0.18 and I've added a debug mode. To turn it on add the debug={true} prop like so:

```
       <ReactToPrint
          trigger={() => <a href="#">Print this out!</a>}
          content={() => this.componentRef}
          debug={true}
        />
```

What this will do is when you click to print it'll open the print window but it will NOT print and it will NOT close.  What I would like is if anyone experiencing issues could open up console and then look for any issues? Also, if they could paste the contents HTML elements like so below:

<img width="1421" alt="screen shot 2018-06-05 at 8 08 28 pm" src="https://user-images.githubusercontent.com/19170080/41008991-426e01c2-68fc-11e8-9559-765e40678942.png">

**Comment by ssxv** [comment]
I have an `<img src="url" />`
url is an Amazon S3 url.
When triggered, and the Print dialog opens, 
I see the network tab, it doesn't request for this image, first time.
then I close the dialog.
And open again 
this time it fetches the url.

**Comment by ssxv** [comment]
my observations are, on trigger, it does not fetch the image first time.
on second trigger it fetches the image as 'octet-stream' and renders it in print dialog.
on further triggers, the image is not fetched, but is seen in the print dialog.

Hope this helps @gregnb

**Comment by gregnb** [comment]
I would encourage anyone having issues to try the new beta version which is going to rely on an iframe to solve the cross origin issues some people are experiencing.

```
npm install react-to-print@2.0.0-beta-1
```

and let me know the feedback if this solves issues

**Comment by zhayes** [comment]
i have used [https://www.npmjs.com/package/rc-print](url)

**Comment by brettkoz** [comment]
Any update here? I'm having the same issue.

**Comment by saraems** [comment]
Hello,  It's still not working. I have that issue. <ComponentToPrint/> contains the img with src or the div with a background but it's not on the print. What is more it does not trigger print-system dialog while <ComponentToPrint/> contains an image.

**Comment by MatthewHerbst** [comment]
hello @saraems can you please possibly make a codesandbox showing the problem?

**Comment by TheRogue76** [comment]
> What path is provided for the image? is it absolute? Or relative?
> 
> My guess is that it is a relative path and I need to fix the package to handle relative paths for images. That was a recent bug in the stylesheets that I should address here regardless

Hi there. I'm using Electron and React for my project and while i can show the image in the app using import or require, the second i try to print it it vanishes. It's using a relative path for the image src. Calling the absolute path (ex: http://localhost:3000/static/media/logo1.0550988b.png) will work in development and show the image in both the app and the printed file, But this can not be done in production (the webpage files are not available). Any ideas?

**Comment by Islombek-FD** [comment]
Hello everyone, I want to print a react-component using the react-to-print box, but the image is blurry. How can I run this? Thanks beforehand.
![image](https://github.com/gregnb/react-to-print/assets/89459802/986af053-02f5-425c-a184-120712af3e0f)

**Comment by kumaresan17** [comment]
@TheRogue76 Try background image as base64. Because the app doesn't know whether the image path will be absolute or relative path. for the first time loading it get confused. after it working fine. I tried it's working fine.
