### ISSUE TITLE
undefine closeAfterPrint in property

### ISSUE THREAD

**Issue by ywCn1998** [MatthewHerbst/react-to-print#151]
Hi
I use version 2.2.1
and It doesn't have closeAfterPrint property to use

**Comment by MatthewHerbst** [comment]
Thanks for the report! I'm not sure when or why this was removed from the code but not the documentation, or if it was meant to stay in the code and was removed by mistake. I'll be able to take a closer look at this next week.

**Comment by MatthewHerbst** [comment]
This has been corrected by the introduction of a new prop `removeAfterPrint` which replaces the old `closeAfterPrint`. This is now available in version 2.3.0, just published. Thanks for finding this issue!
