### ISSUE TITLE
some inline styles cannot be printed

### ISSUE THREAD

**Issue by henrycheung19** [MatthewHerbst/react-to-print#162]
Hello,

In Sandbox,
https://codesandbox.io/s/react-to-print-up15g
all inline styles works fine.

when I add some inline styles to the html to my project, e.g. colors, margin, alignment, only alignment and margin is reflected in the print preview window. For colors, they are not effective.

my package versions
"react": "^16.9.0",
"react-dom": "^16.8.4",

Thanks a lot

**Comment by MatthewHerbst** [comment]
Hello. Can you please show us the code you are using in your project, and be more specific about which styles aren't working?

**Comment by henrycheung19** [comment]
I tried to copy and paste some codes here but I observe the format is broken. So I attached the code with some screenshots:-

[code.js.zip](https://github.com/gregnb/react-to-print/files/3528590/code.js.zip)

![image](https://user-images.githubusercontent.com/31651310/63491014-afa82580-c4e8-11e9-8621-d68eacb377ad.png)

![image](https://user-images.githubusercontent.com/31651310/63491289-673d3780-c4e9-11e9-8684-cdfb2bd43d1d.png)

browser html:
![image](https://user-images.githubusercontent.com/31651310/63490558-90f55f00-c4e7-11e9-82c1-258b2c511edd.png)

print popup:
![image](https://user-images.githubusercontent.com/31651310/63490588-a23e6b80-c4e7-11e9-9170-ea73589b0cd8.png)

**Comment by henrycheung19** [comment]
Hello,

I got the answer. Your package is working well. But the usage of react bootstrap will override the print style.

Thanks so much.

BR,

Henry

**Comment by MatthewHerbst** [comment]
Glad you figured it out, thanks for letting us know!
