### ISSUE TITLE
Issue with github repo

### ISSUE THREAD

**Issue by westbergjohanna** [MatthewHerbst/react-to-print#164]
I have a problem printing in the Edge browser. I use React 16.7.0 and react-to-print 2.1.2. It works fine for all other browsers but when I use a PC and Edge (it works on Edge for mac) I sometimes have a problem with the print command not working at all (neither the button or ctrl-p). When the print command works some information on the page is missing in the print preview. I'm trying to print a calendar and all the activities and colors are missing. Can it be some problem with react-to-print? Has anyone experienced similar problems?

Thank you!

**Comment by MatthewHerbst** [comment]
Hello. That sounds very strange indeed. Could you please post some code showing how you are using `react-to-print`? Also, could you please try upgrading to the newest version, `2.4.0`? There have a been a bunch of bug fixes (and new features) since `2.1.2`.

**Comment by westbergjohanna** [comment]
Thanks for your response! Unfortunately nothing happens when we update the library. Here is the code

```jsx
renderPrintButton() {
  return (
    <ReactToPrint
      trigger={() => (
        <div className="print-button">
	  <i className="icon icon--print" />
	  <span className="ml-1">{this.props.intl.formatMessage({ id: "PRINT_OUT" })}</span>
	</div>
      )}
      content={() => this.componentRef}
    />
  );
}
```

**Comment by MatthewHerbst** [comment]
Can you please share more about the component being printed?

I'm also concerned that you mention you also have problems with ctrl-p. This library does not impact that at all, so any problems there are likely with your OS/browser.

**Comment by kithma** [comment]
we are using the react-to-print to print the calendar view from react-big-calendar. Calendar is showing in preview when we try to print in Edge  but not any colors or calendar events.

**Comment by MatthewHerbst** [comment]
It seems to be an issue with `react-big-calendar`. I have it in one of my apps, and I just tested trying to print with `ctrl+p` (which does not go through `react-to-print`) and I have a similar issue: there are calendar events but no colors. I'll see if I can figure that out

**Comment by MatthewHerbst** [comment]
For tracking: https://github.com/intljusticemission/react-big-calendar/issues/1443

**Comment by MatthewHerbst** [comment]
I'm going to close this issue here. Let's move any further discussion to the opened issue above. Thanks!
