### ISSUE TITLE
when i cancel print, make my page all can't click

### ISSUE THREAD

**Issue by hhgogo** [MatthewHerbst/react-to-print#165]
react 16.8.6 
react-to-print 2.4.0 
electron 6.0.2
This is my print code:
```jsx
<ReactToPrint
      trigger={() => <Button className="title-btn edit-btn" type="primary">print</Button>}
      content={() => this.componentRef}
      pageStyle='vertical-align: middle;'
      removeAfterPrint={true}
      onBeforePrint={this.onBeforePrint}
      onPrintError={this.onPrintError}
      onAfterPrint={this.onAfterPrint}
/>
```
Are there any ways to listen for cancel printing？Because when you cancel printing, don't remove the iframe

**Comment by MatthewHerbst** [comment]
Hi @dream-hang I'm unable to reproduce your issue using the codesandbox example on Chrome 76. Can you please tell us what browser you are using, and share your code?

**Comment by dream-hang** [comment]
> Hi @dream-hang I'm unable to reproduce your issue using the codesandbox example on Chrome 76. Can you please tell us what browser you are using, and share your code?
Hi , I added to my question . I'm using in electron

**Comment by hhgogo** [comment]
@MatthewHerbst Hi , I added to my question . I'm using in electron

**Comment by MatthewHerbst** [comment]
Without a reproducible example I don't know how to look into the claim that the page freezes. I would imagine many people would be raising that issue if it were common.

As for removing the iframe, if you pass the `removeAfterPrint` to `ReactToPrint` the iframe will be removed.

**Comment by MatthewHerbst** [comment]
Hmm, I see you are doing that already. Are you saying that the iframe stays even when you pass `removeAfterPrint`?

**Comment by hhgogo** [comment]
@MatthewHerbst yes，but i found that is electron bug .when i use window.print() method,It makes the page unclickable.so, I don't think it's the react to print bug.Thank you for your reply！when i cancel print, Does onAfterPrint execute?

**Comment by ClaudeRobertBell** [comment]
I get the same bug and can find no way to use the options to get around it.

**Comment by MatthewHerbst** [comment]
@dream-hang sorry for the delayed response. Yes, `onAfterPrint` will fire if you hit the cancel button in the print window. To my knowledge, there is no cross-browser way to determine if the print window was closed because of a successful print or because the user canceled the print.

@ClaudeRobertBell this seems to be a bug with electron, I would recommend filing an issue with them if one does not exist already.

**Comment by MatthewHerbst** [comment]
Working Electron example with how to print using `react-to-print` is now available! https://stackoverflow.com/questions/68751490/electron-print-iframe-given-reference-to-it
