### ISSUE TITLE
"Pages per sheet" fails to load preview / print

### ISSUE THREAD

**Issue by jacobkx** [MatthewHerbst/react-to-print#166]
When printing, if you select any option other than **1** under "Pages per sheet" (found under _More Settings_), the preview will never load, and fails to print/save. Sometimes, it actually causes the page to become unresponsive. 

This can be seen even on the example for this library: https://codesandbox.io/s/rzdhd

![image](https://user-images.githubusercontent.com/53013941/65000723-7f626580-d8a1-11e9-8617-149a96f2efaa.png)

**Comment by MatthewHerbst** [comment]
Thanks, I'll dig more into this later.

**Comment by jacobkx** [comment]
Hi! Sorry, would like to update. This actually seems to be more of a mac issue, where Macs don't like the 'pages per sheet' option for web pages (or web elements), but it works just fine for PDFs. This seems to work ok on Windows. 

So, for anyone in the future, if you're trying to use this feature, convert your component into a PDF and then try using 'pages per sheet'. 😄

**Comment by MatthewHerbst** [comment]
Oh wow, I just tried it here on GitHub and the same issue. That seems like a pretty big bug for an entire OS! I wonder if there is an upstream report somewhere we could link to for people to follow

**Comment by MatthewHerbst** [comment]
Going to close this so it doesn't show as an active issue, but if you know of an upstream report I would love to see that. Thanks!
