### ISSUE TITLE
No trigger if CTRL+P clicked

### ISSUE THREAD

**Issue by putnap** [MatthewHerbst/react-to-print#17]
Hey,

I'm working with React in TS, I wrote my own type definitions, everything works as expected on normal trigger of a button, but I can't get the component to trigger when CTRL+P is pushed. 

What am I missing or is this a missing feature?

**Comment by gregnb** [comment]
Right, because as it stands today this is only triggered by a click event.  I'm not sure if this package should be setting up an event listener for CTRL+P.  Let me think about it. Maybe it could be an option turned on/off, but off by default

**Comment by putnap** [comment]
Well,
I understand why you might feel hesitant, but it defeats the purpose of this control if it can't be triggered when user selects CTRL+P or even Print icon in the toolbar of browser. Means my whole print logic goes out the window...

**Comment by gregnb** [comment]
Right, but think about this for a moment. What about people who have multiple instances of this component on a single page? When a user selects CTRL+P which instance of the component should it print? I can see that becoming a tricky situation

Maybe adding a option that is turned off by default could be a compromise

**Comment by putnap** [comment]
You are right... I believe an option is a must to make this control complete solution to printing needs. I'm pretty new to web development in general, I couldn't find a workaround for this. I tried using media matching and then calling the controls trigger, but it didn't work... Any ideas?

**Comment by thamjieying** [comment]
if you want to trigger print page, maybe you should consider [react-print](https://github.com/captray-zz/react-print) instead, or use print media
