### ISSUE TITLE
App crash on cancel button

### ISSUE THREAD

**Issue by MarioVillafaina** [MatthewHerbst/react-to-print#174]
Hi!

When I print a content, a printing window is opening. If I click in Print button, no problem exists, the document is printed correctly and the app is still working, but when I click Cancel button in the printing window, the app doesn't respond to click events.

Log:

When I click Print button:

```
[Violation] Avoid using document.write().  
[Violation] 'setTimeout' handler took 6229ms  
[Violation] Forced reflow while executing JavaScript took 80ms
```

When I click Cancel button only first "Violation" message appears but not the other two.

Before update to react 16.x.x and react-to-print 2.5.0 this problem didn't exist.

Best regards,
Mario

**Comment by MatthewHerbst** [comment]
Hi @MarioVillafaina thanks for the report. Can you please tell us more about what you are doing? Those errors don't look like browser errors to me, and I am able to click cancel on the print window from the [example](https://codesandbox.io/s/rzdhd) without issue (I'm on Chrome 77).

**Comment by MarioVillafaina** [comment]
Hi @MatthewHerbst!

Thanks for your reply.

I have did some tests and I have discovered that is a problem under Windows print dialog (I use electron)

![image](https://user-images.githubusercontent.com/8377435/67215240-7117e400-f421-11e9-9467-84a4ca0967d7.png)

If I print under Google Chrome print dialog, not problem exists.

Thank you in advance!

Regards,
Mario

**Comment by MarioVillafaina** [comment]
Hi again @MatthewHerbst!

I just read that is an Electron problem when you click on cancel button in the print dialog.

https://github.com/electron/electron/issues/20426

Sorry for the inconveniences.

Thanks!

Best regards,
Mario
