### ISSUE TITLE
Images don't show up on print popup on mobile

### ISSUE THREAD

**Issue by felri** [MatthewHerbst/react-to-print#175]
When I try to print on desktop everything works normally, but on mobile the images does not show up

```js
import Logo from "../../../resources/imgs/logo-voucher.png"

class VoucherPrint extends React.PureComponent {
  render() {
    return (
      <Voucher>
        <LogoContainer src={Logo} />
      </Voucher>
    );
  }
}
```

![Screenshot_2019-10-25-09-50-59-740_com android printspooler](https://user-images.githubusercontent.com/56592364/67572695-1de9ae00-f70d-11e9-8769-7d0c6f429513.png)
![Captura de Tela 2019-10-25 às 09 50 13](https://user-images.githubusercontent.com/56592364/67572704-217d3500-f70d-11e9-902d-bc8914674e64.png)

**Comment by MatthewHerbst** [comment]
Hello. On the Desktop at one point you likely enabled the "Background graphics" option in the "More settings" (Mais definicoes) dropdown. There is likely a similar option on your mobile device. Please make sure that it is enabled.

**Comment by MatthewHerbst** [comment]
Hello @felri, were you able to resolve this issue?

**Comment by felri** [comment]
@MatthewHerbst sorry for the delay, no I was not, I don't have access to the users print settings, i'm still trying to find a solution, a hack that worked for Android but did not for Iphone was to change the 

`<div style="display: none"><PrintComponent /></div>
`
to 

`<div style="position: absolute, left: -999px"><PrintComponent /></div>
`

**Comment by MatthewHerbst** [comment]
If you can find something that's generic and would help everyone I'm happy to try and find a way to include it, though we can't add features per-browser

**Comment by ludan1107743896** [comment]
@MatthewHerbst   My picture style was not loaded when I printed it.

**Comment by MatthewHerbst** [comment]
@ludan1107743896 sorry I never got back to you. If you are still having an issue please open a new ticket for that.

@felri if you are able to find a cross-browser solution I'm happy to look into it, but I don't think it's right for us to implement features for a single browser at a time. Going to close this for now, please re-open if you need to, or feel free to create a new issue
