### ISSUE TITLE
Print dialog is not displayed when using <img src="file.svg" />

### ISSUE THREAD

**Issue by vavdav** [MatthewHerbst/react-to-print#18]
Thanks for great tool. Just one thing that I found, when I was using 

    <img src="file.svg" />

then print dialog is not displayed. It just displays popup. I solved it for me by using direct <svg... 

Another thing is when onBeforePrint callback is called and I call setState (to hide some elements) in this callback, it is not handled. 
I had to do some hack:

Helper function

    handlePrint = () => {
      if (this.printer && this.printer.firstChild) {
        this.setState({
          isPrinting: true,
        }, () => {
          this.printer.firstChild.click();
        });
      }
    }

in Render

          <Button type="submit" onClick={this.handlePrint}>
            Print!
          </Button>
          <div
            ref={(printer) => { this.printer = printer; }}
          >
            <ReactToPrint
              onAfterPrint={this.printFinished}
              trigger={() => (<div />)}
              content={() => this.componentRef}
            />
          </div>

**Comment by gregnb** [comment]
Try: 
```
npm install react-to-print@2.0.0-alpha-1 --save
```
