### ISSUE TITLE
Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by jngbng** [MatthewHerbst/react-to-print#180]
I got an error report from some client:

```
TypeError: Cannot read property 'focus' of null
```

from following line.

https://github.com/gregnb/react-to-print/blob/6dd26543319fcc06f603b02efd10e043271f82da/src/index.tsx#L41

Browser: Chrome (Version 78.0.3904)
OS: Windows 10

I failed to reproduce the problem, but  I guess it may be null on some special case.

**Comment by MatthewHerbst** [comment]
Thanks for the report. That's pretty strange if it's actually Chrome. What do you think the best thing is to do here? Generally in apps I build I ignore such errors as being edge-case. We could put a check into this library for it, though not being able to focus means we can't do anything, so we'd essentially just have to kill the print job. In that scenario there would be no error (unless we re-threw it, but then why catch it in the first place...), and you would never know that the user wasn't able to print.

**Comment by jngbng** [comment]
@MatthewHerbst Thanks for very fast response. I agree with you and will ignore this problem.

**Comment by polaris218** [comment]
@MatthewHerbst  In the edge browser, we can't fix this issue on codebase?

I am getting issue on Edge.

`Unable to get property 'focus' of undefined or null reference`
![image](https://user-images.githubusercontent.com/44607982/74168335-e9264600-4c6c-11ea-836a-70733d23aaf1.png)

**Comment by MatthewHerbst** [comment]
@actiongeek can you tell me more about the browser you are using? What version of Edge, etc? As noted in my previous post, there's not much we can do if your browser doesn't support `contentWindow`, unless you know of workaround for when it does not exist?

**Comment by polaris218** [comment]
@MatthewHerbst  Sorry too lated.
Actually this issue is from [Sentry](https://sentry.io).
Issue is https://sentry.io/share/issue/a5d5d474b6ee4f0ba10beed823be4ddf/
It catched error from Edge Browser User. As I wrote before, it's working perfectly in Modern broswers.
So I would like to know this package supports the Edge 11 or not.

**Comment by MatthewHerbst** [comment]
Yes, we try to support IE 11, and we do support Edge. Edge and IE [both support `contentWindow`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow), so I'm extremely skeptical that the browser this error occurred on is IE11 or Edge. Are you able to reproduce it? Did you create the error, or did one of your users?

**Comment by augustofontes** [comment]
We are also facing this error. Not only on Edge, but also on Chrome.

On Edge: Unable to get property 'focus' of undefined or null reference
On Chrome: Cannot read property 'focus' of null

Always happens after user clicks print button.

**Comment by MatthewHerbst** [comment]
@augustofontes can you please share a codesandbox or something where you can reproduce this error?

**Comment by TobyLiu-max** [comment]
@MatthewHerbst   Click twice in a row, and "Uncaught TypeError: Cannot read property'focus' of null" will appear. In your examples, click continuously and appear "react_devtools_backend.js:2430 Printing failed because the `contentWindow` of the print iframe did not load. This is possibly an error with `react-to-print`. Please file an issue: https://github.com/gregnb/react-to-print/issues/"

**Comment by miguelmich** [comment]
@xxxliuzhifu the same thing is happening to me (Chrome), I get this error when I double click the component, is there a way to avoid a second click @MatthewHerbst? thank you!

**Comment by MatthewHerbst** [comment]
@miguelmich any chance you could make a code sandbox showing the issue? I think an easy fix on your end would be to disable the button while printing:

```jsx
const [printing, setPrinting] = useState(false);

return (
  <ReactToPrint
    ...
    onAfterPrint={() => setPrinting(false)}
    onBeforePrint={() => setPrinting(true)}
    trigger={() => <button disabled={printing}>Print</button>}
  />
);
```
