### ISSUE TITLE
How can I forcefully move a component to print in a different page

### ISSUE THREAD

**Issue by thidasapankaja** [MatthewHerbst/react-to-print#182]
I have integrated react-to-print with material-ui .But I'm having some trouble since some components are cutting in half. How can I move to a different page after or before a specific component ? I tried using **page-break-before** MediaQuery. But it doesn't work. Is there any turnaround for this ?

**Comment by MatthewHerbst** [comment]
Hello. You'd have the post your code for me to see exactly what's going on, but I can't profess to being a CSS expert. This question actually has very little to do with `react-to-print` directly, so you'd probably be better asking it on StackOverflow where there are likely many more CSS experts.
