### ISSUE TITLE
Print without button

### ISSUE THREAD

**Issue by alfaex** [MatthewHerbst/react-to-print#184]
I need to trigger the printing on the 'componentdidmount'.

But the documentation says that trigger need to be a function that return an element or component.

The screen responsable to print should print when the user enter on that component, there will be no button (or element) for the user to click.

It is possible to do some hack to trigger the printing just calling a function, without return nothing?

Thanks.

**Comment by MatthewHerbst** [comment]
Unfortunately we don't export a `print` function standalone right now. We have an existing ticket to do that work but haven't gotten around to it yet (PRs are welcome!). My advise would be to create a hidden button on the page. Save a ref to the button. Inside the `componentDidMount` you can call click on the button via JS. I believe that should work.

**Comment by alfaex** [comment]
Ok.
I'll try to do that.
Thanks for the feedback.

Cheers.

**Comment by Jordy-A** [comment]
Or for functional component:

```
export default function Print(props) {
  const componentRef = useRef();
  const printRef = useRef();

  useEffect(() => {
    printRef.current.handleClick();
  }, []);

  return (
    <div>
      <ReactToPrint
        trigger={() => <React.Fragment/>}
        content={() => componentRef.current}
        ref={printRef}
      />
      <div style={{ display: "none" }}>
        <PrintCard ref={componentRef} />
      </div>
    </div>
  );
}
```
