### ISSUE TITLE
defer rendering to trigger click [question]

### ISSUE THREAD

**Issue by idanhaviv** [MatthewHerbst/react-to-print#185]
My ComponentToPrint fetches lots of data, and I wish I could defer that work to only after 
print button is clicked, but they're coupled.

my component looks like: 

```
<div>
      <div style={{ display: "none" }}>
        <ComponentToPrint ref={componentRef}/>
      </div>
      <ReactToPrint
        trigger={() => <Button>
          {label}
        </Button>}
        content={() => componentRef.current}
      />
 </div>
```

how can I defer ComponentToPrint rendering to after the print button is clicked?
@MatthewHerbst

**Comment by MatthewHerbst** [comment]
You could use the `onBeforeGetContent` method to only render in your component after the print button is clicked. Have the promise resolve when your data is loaded and the components are mounted
