### ISSUE TITLE
my content in react to print does an error but still it works with the error in it

### ISSUE THREAD

**Issue by undesputed** [MatthewHerbst/react-to-print#188]
![image](https://user-images.githubusercontent.com/33367564/70492016-f5433980-1b3d-11ea-9105-d85c620ce079.png)

**Comment by MatthewHerbst** [comment]
Maybe it has to do with the `useRef(null)` call?

**Comment by undesputed** [comment]
if i will remove the null in the useRef the ref in my previewdetails errors and it doesn't fix that part..

**Comment by MatthewHerbst** [comment]
Can you make a working code example please so we can play around with it? Thanks
