### ISSUE TITLE
No styles coming through in print window

### ISSUE THREAD

**Issue by ericwallen** [MatthewHerbst/react-to-print#189]
Hi, I can't seem to get any styles to come from my page to the print window. Am I doing something wrong?

<img width="1246" alt="Screen Shot 2019-12-16 at 9 44 37 AM" src="https://user-images.githubusercontent.com/9659936/70925800-1e097a00-1fe9-11ea-9c3f-23f4e1f2a7e1.png">
<img width="1004" alt="Screen Shot 2019-12-16 at 9 45 11 AM" src="https://user-images.githubusercontent.com/9659936/70925805-21046a80-1fe9-11ea-9780-00a60a290143.png">

```
import React from 'react'
import { connectStore } from '../App'

import ReactToPrint from 'react-to-print';
import GenerateVoyagePDF from './GenerateVoyagePDF'


class PrintVoyagePDF extends React.Component {
    render() {
      return (
        <div>
          <ReactToPrint
            trigger={() => <a href="#">Print this out!</a>}
            content={() => this.componentRef}
          />
          <GenerateVoyagePDF ref={el => (this.componentRef = el)} />
        </div>
      );
    }
  }

export default connectStore(PrintVoyagePDF)
```

**Comment by MatthewHerbst** [comment]
Try selecting the "Background graphics" option for your printer settings

**Comment by ericwallen** [comment]
I tried ticking that box before opening a ticket hoping that might have some effect on it but it, unfortunately, didn't change anything.

**Comment by MatthewHerbst** [comment]
Can you share some working code please so we can see the problem? Thanks

**Comment by ericwallen** [comment]
Hi Mathew, thanks for offering additional help. Sorry, it took so long to reply. I ended up having no print styling issues once I switched my app to React Hooks. I am going to close this as it seems I was the only person having this issue with class components.

**Comment by MatthewHerbst** [comment]
Glad you found something that works, thanks for the update

**Comment by 7xrobin** [comment]
I'm having a similar issue. Some properties related to background and images are not been displayed on the print even with the "Background graphics" option. Change the component to use Hooks doesn't solve my problems.

**Comment by MatthewHerbst** [comment]
@robindesu can you please create a codesandbox showing the problem? Thanks

**Comment by 7xrobin** [comment]
@MatthewHerbst I created the Sandbox trying to replicate my application, but the problem doesn't appear. What is different from mine is the data fetching that I add to a table imported from Ant Design lib, but this is indicated on the code:

https://codesandbox.io/s/damp-sky-ttl7f

If you have any idea what could be wrong, let me know, please.

**Comment by MatthewHerbst** [comment]
@robindesu can you please update it to show the fetching code? It could be that you are trying to print before all the data is loaded.

**Comment by 7xrobin** [comment]
@MatthewHerbst I can't add the fetch, because it's private from my company, and it is necessary to have token access. 
 But the data is showed on the print, in a table. Just the red color on the top of the page, as in the codesandbox, doesn't appear on the print of my application. 
I tried to change the styling methods, for inline and by class but didn't work.

**Comment by MatthewHerbst** [comment]
I couldn't tell you why it doesn't work without having a working example showing it not working, I'm sorry.
