### ISSUE TITLE
I can not use CSS in print page

### ISSUE THREAD

**Issue by icebravo** [MatthewHerbst/react-to-print#192]
Hi! 
I dont know if I am doing something wrong with this.
I am using TypeScript in a SharePoint context. 
myComponent to be printed has it owns css (as _name_.module.scss). If I render the component in the render of React works fine, but when I use the ref into the <ReactToPrint> myComponent losses its styles.
Someone can help me?

**Comment by icebravo** [comment]
```jsx
<ReactToPrint
  trigger={() => <p>Printer Fn </p>}
  content={() => this.testTitleRef1.current}
  copyStyles={false}
  onBeforeGetContent={()=> this.onBeforeGetContent()}
  onBeforePrint={() => this.onBeforePrint()}
  onAfterPrint={() => this.onAfterPrint()}
  onPrintError={(el, e) => this.onPrintError(el, e)}
/>

// the component to print (a functional component)
<div ref={props.refComp} className={styles["body-page"]}>
  <h1>{props.count}</h1>
  <p className={styles["text"]}>Texto</p>
</div>;
```

**Comment by MatthewHerbst** [comment]
Hello. Can you please post a working (codesandbox or equivalent) code example so we can see exactly what the problem is? Thank you

**Comment by icebravo** [comment]
Yes of course
https://codesandbox.io/s/friendly-davinci-pdpn3?fontsize=14&hidenavigation=1&theme=dark

another question. Where I can find the full documentation of the reacto-to-print

**Comment by icebravo** [comment]
UPDATE: 
I realized that the problem is the " copyStyles={true}" accessory.
My apologies.

I updated the codeSandBox for Class component and Functional component
Great module!

**Comment by icebravo** [comment]
Does not exist any problem. Set prop copyStyles = true to maintain styles from component itself
