### ISSUE TITLE
Marked checkbox not printing

### ISSUE THREAD

**Issue by BobbyErickson89** [MatthewHerbst/react-to-print#195]
I'm having an issue with the marked checkbox printing correctly.  I will have a checkbox that has a `checked` attribute dependent on a state variable.  It has an `onChange` event that toggles the checked attribute/state between `true` and `false` whenever the checkbox is clicked.  

My problem is that react-to-print will only print whatever the default `checked` attribute is.  So if I have the default `checked` state in the constructor set to `false`, then react-to-print will print my checkbox as unmarked, regardless of if I have checked the box or not.  Is anyone else experiencing this issue?

I've included a code sandbox link as an example of the problem.
[CodeSandbox Example](https://codesandbox.io/s/react-to-print-vpryg)

**Comment by MatthewHerbst** [comment]
Thanks for the report. We [previously experienced this issue](https://github.com/gregnb/react-to-print/issues/66) and it seemed at the time that updating `react` and `react-dom` fixed it, however, it appears that is not the case.

Do you have any ideas on what might be causing this? I've never been able to to pin it down to anything in this library, but happy to be proved wrong about that.

**Comment by BobbyErickson89** [comment]
Really not too sure what would be causing the problem.  I've been trying to get it figured out for the past day or so.  

I have a similar [dropdown issue](https://github.com/gregnb/react-to-print/issues/196) that I just opened.  The main similarities that I see between the two is that both have `onChange` events that don't seem to be getting registered with the `ref` that the print is using.  Have there been any issues with `onChange` in the past?

**Comment by mmazanec22** [comment]
I was having this issue with just window.print and tried this library to see if it would help but am facing the same problem with both: selected checkboxes don't appear checked the first time I attempt to print, though the second time (without a refresh in between) they do.  This is not an issue with other types of input.  Updating react and react-dom didn't help.  This is a problem in Chrome on Linux, Windows, and Mac.  It appears to not be a problem in Firefox on Linux.  I'm tempted to write it off as a browser issue but would love to hear of any workarounds.  Has anyone solved this?

Editing to note: this appears to be React specific.

**Comment by BobbyErickson89** [comment]
@mmazanec22 I actually came up with a solution but it's not using react-to-print.  Not sure if it will work for your project, but I figured I'd share

My react site actually ended up printing fine when I forced Chrome to print background graphics.  In print preview on Chrome under the Advanced options, there's a checkbox where you can choose whether or not to print the background graphics.  Checking this box seemed to render my website perfectly for printing.  However, it's not good UX if we need to alert users to check that option.  I did some digging and found that your site will automatically print background graphics with this line of css:

`* { -webkit-print-color-adjust: exact !important; }`

I believe this solution is supposed to work for both Chrome and Safari.  I believe there's a different line that can be used for Firefox as well.  However, [Mozilla doesn't recommend using this line in production](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust) as it's not a standard and can possibly change in the future.  It worked for what I needed at the moment though, so this is what I'm using.

Sorry for the long comment, but hopefully this helps!

**Comment by mmazanec22** [comment]
Thank you so much @BobbyErickson89 !  Unfortunately for me that didn't work for my case, but hopefully someone else who stumbles on this thread will have their problem solved.

**Comment by MatthewHerbst** [comment]
This is likely related to #196

**Comment by MatthewHerbst** [comment]
This should be fixed as of v`2.10.2`. Please let me know if you see otherwise. Apologies for how long it took to fix this.
