### ISSUE TITLE
Dropdown only printing first option

### ISSUE THREAD

**Issue by BobbyErickson89** [MatthewHerbst/react-to-print#196]
I am currently experiencing a problem with trying to print a dropdown on my site's page.  It appears that the `select` tag is only rendering the first `option` for print, regardless of which `option` has been chosen by the user.

My `select` element has a `value` attribute that is tied to a `state` variable.  There is also an `onChange` event on my `select` tag that triggers the state/value change whenever the user selects a new option from the dropdown.  However, printing seems to ignore whatever the chosen value is and will only print the first option in the dropdown.

I've attached a code sandbox link demonstrating this problem.
[CodeSandbox Example](https://codesandbox.io/s/react-to-print-hflc4?fontsize=14&hidenavigation=1&theme=dark)

**Comment by MattFromGer** [comment]
Maybe this issue comes from the fact that the DOM tree gets cloned and some attributes are getting lost in the process?
The built-in browser printing mode works as expected.

Same issue here: #66 which got closed mistakenly.

**Comment by MatthewHerbst** [comment]
@MattFromGer yes, all these issues are likely related. I don't know what's causing them. If you have any ideas, I'm happy to explore. #66 was closed because the same issue is now being tracked in #195

**Comment by tugayevci** [comment]
Any update ?

**Comment by alejandroyunes** [comment]
anyone came up with a solution??

**Comment by MatthewHerbst** [comment]
Apologies for the delay on fixing this. Turns out it was very similar to the previous issue with fixing checkbox values. Will push a new version shortly with the fix. Happy new years!

**Comment by MatthewHerbst** [comment]
Should be fixed in v2.12.2, along with ensuring all inputs work. Please let me know if you see any issues. Thanks!
