### ISSUE TITLE
Component compatibility

### ISSUE THREAD

**Issue by roferjack** [MatthewHerbst/react-to-print#199]
Is this component compatible with ie?

**Comment by roferjack** [comment]
How is it compatible with Internet Explorer? ie11

**Comment by MatthewHerbst** [comment]
It should be. If you see an error using it on IE11 please let us know.

**Comment by roferjack** [comment]
ok,Thank you very much for your answer！Some users' IE doesn't show print pdf，It's not clear what the problem is, it might be the problem of ie，I will verify the problem again。And I have another question, how to set the default file name instead of using the page name。Looking forward to your answer，Thank you！

**Comment by roferjack** [comment]
oh，I have solved it,document.title =`customName`，If you have other options, please tell me

**Comment by MatthewHerbst** [comment]
That sounds like a good way to do it!

If you do see a bug in IE please report it and we'll do our best to fix it. Thanks!
