### ISSUE TITLE
Triggering ReactToPrint on button click.

### ISSUE THREAD

**Issue by zainasghar200** [MatthewHerbst/react-to-print#201]
Currently, we have to add a component to the DOM to print the data which is shown below.
```
<ReactToPrint
          trigger={() => <a href="#">Print this out!</a>}
          content={() => this.componentRef}
/>
```
Is there anty way to print the reffrenced data on button click. i.e on submition button clicked. I want `trigger={() => <a href="#">Print this out!</a>}` on butoon click

**Comment by MatthewHerbst** [comment]
While this could probably be done using `onBeforeGetContent`, why not just only render your component inside `react-to-print` when you actually want to print?

```jsx
render() {
  return (
    <div>
      {this.state.submitClicked ? 
        <ReactToPrint ...>
          <someContent />
        </ReactToPrint> : 
        <someContent>
      }
    </div>
  );
}
```
