### ISSUE TITLE
There is no "more options" drop down while print previewing. 

### ISSUE THREAD

**Issue by zainasghar200** [MatthewHerbst/react-to-print#205]
I want to change page size but there is no option for that.

![image](https://user-images.githubusercontent.com/25928974/71971623-cf887d80-322c-11ea-9610-debebd9e046b.png)

**Comment by MatthewHerbst** [comment]
Hello. The options in the print preview panel are displayed by your browser. We don't have any control over them, all we do is open the print preview panel.

**Comment by tygraphics** [comment]
Your print dialog looks like you are using chrome with PDF as target. If you choose a specific printer as target you will see more options. Safari gives full range of options with PDF as target.
