### ISSUE TITLE
Print large amount of data

### ISSUE THREAD

**Issue by xStorm111** [MatthewHerbst/react-to-print#206]
Hello, i'm trying to implement react-to-print on material-table and i'm having some issues for multiple page data.
Example:
I have this scenario where i have more rows than the window can show.
![image](https://user-images.githubusercontent.com/22938156/71989514-bcc07980-3229-11ea-83aa-4bdaa0b533c8.png)

I implemented the code on material-table using gregnb/mui-datatable as an example.
But gregnb/mui-datatable print function reaches all data from tableContent and here i can only reach the tableContent that is displayed on the screen or less than that.
![image](https://user-images.githubusercontent.com/22938156/71989858-4f611880-322a-11ea-987e-1f79bea9812e.png)

## Expected Behavior

Print all data from table
![image](https://user-images.githubusercontent.com/22938156/71990618-9c91ba00-322b-11ea-9ae3-bb985251100b.png)

**Comment by MatthewHerbst** [comment]
Hello. Could you please make a codesandbox or codepen that shows the problem? Thank you. My guess is it has to do with virtual rendering.

**Comment by xStorm111** [comment]
Hello @MatthewHerbst, first of all thanks for the reply.
I created a mini project to show the problem and i imported it into a codesandbox as you asked
I will leave the link below:
https://codesandbox.io/s/tender-mirzakhani-mjng8

The code might be a bit confuse but the most important code about react-to-print is located on files utils/m-table-toolbar, utils/material-table and utils/index

**Comment by MatthewHerbst** [comment]
If I had to guess, passing the ref via props is not updating the ref correctly, but I'm not sure. I wonder if a simpler example could be made with just mui-datatable and react-to-print?

**Comment by xStorm111** [comment]
Infortunately i don't think i can make an easier example. I created a new codesandbox with both datatables imported but i left the material-table commented.
I will leave the link below:
https://codesandbox.io/s/react-print-issue-with-material-table-idxwl

**Comment by MatthewHerbst** [comment]
@xStorm111 sorry for taking so long to get back to you. Does `mui-datatable` do virtual rendering? I think this is the same issue as https://github.com/gregnb/react-to-print/issues/95

I'm taking another look at it. It should be fixable, but very difficult and will be hard to test it properly.

**Comment by xStorm111** [comment]
@MatthewHerbst Hello, you don't have to be sorry for it.
I made some progress about this, i manage to realize this bug only happens **IF** i have maxBodyHeight defined.

Makes sense that react-to-print reacts that way to a maxBodyHeight

**Comment by MatthewHerbst** [comment]
@xStorm111 interesting. I wonder if a solution would be for `react-to-print` to remove that property if it exists? That seems like it could cause other problems though since we don't know anything else about the styles.
