### ISSUE TITLE
Canvas not being printed

### ISSUE THREAD

**Issue by asliwinski** [MatthewHerbst/react-to-print#21]
As mentioned in https://github.com/gregnb/react-to-print/issues/14 the canvas elements are not being printed.

**Comment by gregnb** [comment]
I am trying to complete a rewrite of this library using iframes to solve cross origin issues. Along with that will be canvas fix. Bear with me and apologies for any issues in the mean time

**Comment by gregnb** [comment]
This issue has been solved with 2.0.0-alpha-1

```
npm install react-to-print@2.0.0-alpha-1 --save
```
