### ISSUE TITLE
The picture will be truncated

### ISSUE THREAD

**Issue by ZhangAixue** [MatthewHerbst/react-to-print#210]
When the picture is between two pages
![image](https://user-images.githubusercontent.com/24401016/72241756-a0a24b00-3622-11ea-8905-cd934cee4de7.png)

**Comment by nhan-huynhvan** [comment]
This issue relating to styles, please try styles for image follow: 
```
img {
    page-break-before: auto; /* 'always,' 'avoid,' 'left,' 'inherit,' or 'right' */
    page-break-after: auto; /* 'always,' 'avoid,' 'left,' 'inherit,' or 'right' */
    page-break-inside: avoid; /* or 'auto' */
}
```
Please confirm result after apply that styles :) 
Thank!
