### ISSUE TITLE
Call backend API to retrieve updated data before print

### ISSUE THREAD

**Issue by chesterheng** [MatthewHerbst/react-to-print#212]
Hi,

Is it possible for me to make a backend api call after i trigger the button to print?

I have a "create report" button.
So when user click the "create report" button, I make a backend api to get the latest content before a pdf is generated.

**Comment by MatthewHerbst** [comment]
Do you need to make the call before the print happens or after it happens?

**Comment by stefensuhat** [comment]
it happens I need the same feature.

It will load the data from API and call the print method.

**Comment by MatthewHerbst** [comment]
If you make the call in `onBeforeGetContent` you can modify the content of the page before the print happens. Just return a Promise to the function to let it know when you are done.
