### ISSUE TITLE
Type 'null' is not assignable to type 'ReactInstance'.

### ISSUE THREAD

**Issue by invious** [MatthewHerbst/react-to-print#214]
getting this complaint from typescript following the hooks docs on the README

`TS2769: No overload matches this call.   Overload 1 of 2, '(props: Readonly<IReactToPrintProps>): ReactToPrint', gave the following error.     Type 'null' is not assignable to type 'ReactInstance'.   Overload 2 of 2, '(props: IReactToPrintProps, context?: any): ReactToPrint', gave the following error.     Type 'null' is not assignable to type 'ReactInstance'.`

```
const QuestionSet: FunctionComponent<IQuestionSetProps> = ({ ibns }) => {

    const componentRef = useRef(null);

    return (<>
            <ReactToPrint
                trigger={() => <button>Print this out!</button>}
                content={() => componentRef.current}
            />
            {ibns.map((ibn) =>
                <Question key={ibn} ibn={ibn}/>
            )}
            </>
            )


};
```

**Comment by MatthewHerbst** [comment]
Thanks for reporting. I'm currently traveling, but will look into this when I get back in a few days. If you are able to find a fix, I would be happy to review a PR.

**Comment by MatthewHerbst** [comment]
Hi, sorry for not getting back to you on this. Are you still having this issue?

**Comment by MatthewHerbst** [comment]
Reading [this blog post](https://medium.com/@martin_hotell/react-refs-with-typescript-a32d56c4d315), can you try doing `const componentRef<FunctionComponent> = useRef(null);` and let me know if that helps? They also recommend that same approach in `DefinitelyTyped`: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35572#issuecomment-498242139

**Comment by MatthewHerbst** [comment]
Though I remind you that officially we do _not_ support functional components right now, so I also don't know how `FunctionComponent` plays into what might be going on here.

**Comment by MatthewHerbst** [comment]
I was able to get a working version using `React.Component` when doing `const componentRef<Component> = useRef(null);` However, `FunctionalComponent` through type errors. It might be possible to resolve them but I don't have the time to look at that tonight.

**Comment by MatthewHerbst** [comment]
Going to close this for now. Let me know if the issue still exists and we can work to fix it. We are now supporting functional components with the new hook we have!
