### ISSUE TITLE
Can you add a repeating header?

### ISSUE THREAD

**Issue by invious** [MatthewHerbst/react-to-print#216]
Would it be possible to make a header on every page?

**Comment by MatthewHerbst** [comment]
Hello. What do you mean by the header?

**Comment by invious** [comment]
For my use case I am printing out multiple questions. Each question may span a couple of pages. A header at the top of the page with the question number that page belongs to for example

**Comment by MatthewHerbst** [comment]
You would have to include that yourself on the page. The library is fairly simple, in that it tries to print exactly what is in the content component. You should be able to use React + css to get the desired effect you want.
