### ISSUE TITLE
Suppress Error Messages?

### ISSUE THREAD

**Issue by invious** [MatthewHerbst/react-to-print#217]
I am loading a lot of HTML, and many links are invalid. Can I suppress this error?

`"react-to-print" was unable to load a link. It may be invalid.`

**Comment by MatthewHerbst** [comment]
Hmm. Right now there is no ability to do that, but it would be a pretty trivial PR to add a `suppresErrors` prop to do what you want. I'm out of town right now, but if you can make the PR I can review it and merge it when I return in a few days.

**Comment by invious** [comment]
https://github.com/gregnb/react-to-print/pull/220

**Comment by MatthewHerbst** [comment]
Published in `v2.6.0`, thank you!
