### ISSUE TITLE
ReactToPrint trigger by ref of button outside component

### ISSUE THREAD

**Issue by soundquiet** [MatthewHerbst/react-to-print#219]
hi, I want to know if it is possible to use `ref` for `trigger`. I would like to put the print button in the parent component.

I tried `trigger={()=>this.printRef}` but it did not work.

Did I make some misunderstandings? thanks a lot.

**Comment by MatthewHerbst** [comment]
Hello. This is not currently possible, however, it could probably be made possible with a relatively simple PR. I'm currently traveling so can't make one myself. I'd be happy to review one of you can make it.

**Comment by MatthewHerbst** [comment]
This is available in `2.8.0-beta.1` and will be available in `2.8.0` later tonight. Thanks fo the ideas!
