### ISSUE TITLE
Print two or more components

### ISSUE THREAD

**Issue by rayfcrols** [MatthewHerbst/react-to-print#225]
Display the component only once and print the same component two or more times. How to proceed?

More specifically I have an html form component, which must be printed 2 copies on a single page.

Example: [https://codesandbox.io/s/react-to-print-5yirl](https://codesandbox.io/s/react-to-print-5yirl)

**Comment by MatthewHerbst** [comment]
It will print whatever is on the page within the `content` ref. If you need to duplicate something on the page you need to do that before printing happens, such as by using the `onBeforeGetContent` prop to modify content before print, and then using `onAfterPrint` to cleanup that modification once printing is completed.

**Comment by rayfcrols** [comment]
> It will print whatever is on the page within the `content` ref. If you need to duplicate something on the page you need to do that before printing happens, such as by using the `onBeforeGetContent` prop to modify content before print, and then using `onAfterPrint` to cleanup that modification once printing is completed.


Thanks, Matthew. Do you have an example?

**Comment by MatthewHerbst** [comment]
The example code in the repo shows how to use it: https://github.com/gregnb/react-to-print/blob/master/example/index.tsx please let me know if you encounter any issues

**Comment by invious** [comment]
```
import React, { FunctionComponent, ReactInstance, useRef } from 'react';
import ReactToPrint from 'react-to-print';
import './styles.scss';

export interface IPrintPDFProps {
    trigger: React.ReactElement;
    children: React.ReactElement;
    showDOM?: boolean;
    onBeforeGetContent: () => void | Promise<any>;
}

/**
 * This component prints the rendered children in the browser print dialog.
 * It takes a ReactElement as a trigger element, e.g. a button
 *
 * @param trigger
 * @param showDOM
 * @param children
 * @param onBeforeGetContent
 * @constructor
 */
const PrintPDF: FunctionComponent<IPrintPDFProps> = ({ trigger, showDOM = false, children, onBeforeGetContent }) => {
    const componentRef = useRef(null);

    const contentFunction = () => (componentRef.current as unknown) as ReactInstance;
    const triggerFunction = () => trigger;
    return (
        <>
            {/* @see https://github.com/gregnb/react-to-print */}
            <ReactToPrint
                trigger={triggerFunction}
                content={contentFunction}
                onBeforeGetContent={onBeforeGetContent}
                suppressErrors={true}
            />
            <div className={`${!showDOM && 'display-none'}`}>
                <div ref={componentRef}>{children}</div>
            </div>
        </>
    );
};

export default PrintPDF;
```

```
 <PrintPDF
            // callback that takes a promise to do any DOM changes before print
            onBeforeGetContent={populate}
            trigger={<SecondaryButton>{EXPORT.BUTTON}</SecondaryButton>}
        >
            <>
                {exportedQuestions.questionsWithDrupalContent.map((question, index) => (
                    <Question showExplanations={showExplanations} key={index} questionWithDrupalContent={question} />
                ))}
            </>
        </PrintPDF>
```

**Comment by cyruzin** [comment]
> const triggerFunction = () => trigger;

Thanks bro, that worked for my case.
