### ISSUE TITLE
Content disappears after saving

### ISSUE THREAD

**Issue by invious** [MatthewHerbst/react-to-print#229]
I don't know if this is an issue with React to Print or my specific implementation, but content shows up fine in the print preview window and then when you actually go to save it, it. disappears. And not all of it, just a certain part

![image](https://user-images.githubusercontent.com/1996089/76329007-6243a800-62c2-11ea-938f-276af27092e8.png)

![image](https://user-images.githubusercontent.com/1996089/76329017-64a60200-62c2-11ea-9894-1e255c61a136.png)

**Comment by MatthewHerbst** [comment]
Hello. This sounds like an issue on your machine/browsers, not a library issue. However, I'm happy to take a deeper look if you are able to provide a working codesandbox or similar for me to play with the issue you are seeing. Thanks
