### ISSUE TITLE
External Image links are broken

### ISSUE THREAD

**Issue by theghostyced** [MatthewHerbst/react-to-print#232]
## Description
- I have an image tag that fetches its image from `Google Storage` but the image is broken. 

<img width="635" alt="Screenshot 2020-03-18 at 15 39 52" src="https://user-images.githubusercontent.com/28215750/76972480-ee8f4400-692e-11ea-94b9-76d2901bad11.png">

Any ideas how to go about this?

**Comment by MatthewHerbst** [comment]
Hello. Is it broken in general, or just when using `react-to-print`? Can you please share a codesandbox example if possible? Thanks

**Comment by theghostyced** [comment]
When using `react-to-print` the external image from GCP storage links dont show up it instead shows just a broken image link.. Will try to reproduce in a codesandbox

**Comment by MatthewHerbst** [comment]
Yeah, if you could make a working codesandbox that would be fantastic, thank you

**Comment by theghostyced** [comment]
Hey @MatthewHerbst I couldnt replicate it on CodeSandbox so i screen recorded it instead, apologies for the screen size

![dad](http://g.recordit.co/TlghI5Dc4K.gif)

Here is the image link that was generated `https://storage.googleapis.com/elliot-images-us/production/842/lookandfeel/SLxB_FullLogo-02.png`

Screen record link for the video - https://recordit.co/TlghI5Dc4K

**Comment by MatthewHerbst** [comment]
I don't see you opening the print window in that video? I really can't do much to investigate without a reproducible example unfortunately.

**Comment by p8ul** [comment]
The issue happens when you don't give DOM enough time to load the image once it has the src set. [stackoverflow](https://stackoverflow.com/a/38247699/9298143)

A quick hack is to download the image blob then convert it to image URL, in advance. Then use it on the print content.

```
      fetch(
        'image-url')
      )
        .then(function(response) {
          return response.blob();
        })
        .then(function(blob) {
          var urlCreator = window.URL;
          var imageUrl = urlCreator.createObjectURL(blob);
          setImageLogo(imageUrl);
        });
    }
  ```

**Comment by theghostyced** [comment]
Thanks a lot @p8ul that solved it.. Thanks also @MatthewHerbst  for the time

**Comment by MatthewHerbst** [comment]
Glad that got figured out, thank you
