### ISSUE TITLE
IE11 supported?

### ISSUE THREAD

**Issue by k-eb** [MatthewHerbst/react-to-print#233]
Hi, I am considering using this package for a project, but I need to support IE11. Does this package support IE11?

Wasn’t sure about this because the repo subtitle excludes IE: **„Print React components in the browser. Supports Chrome, Safari, Firefox and EDGE“**.

But scanning through the repo I see IE issues being addressed.

Thanks for any clarification.

**Comment by MatthewHerbst** [comment]
Hello, thanks for your interest! We do our very best to maintain support for IE11. As far as I know the package works for IE11, and if you find any bugs we will do our best to support them!
