### ISSUE TITLE
Set zoom default when print preview.

### ISSUE THREAD

**Issue by manhlt1990** [MatthewHerbst/react-to-print#234]
When print preview, I want set zoom in default 200%. How can i do that?
![Untitled](https://user-images.githubusercontent.com/18260709/77984655-63ee1200-733c-11ea-918f-bfa6421247f3.png)

**Comment by MatthewHerbst** [comment]
Hello. Unfortunately the zoom level is set by your browser, and it something that we have no control over. Once the print menu opens we have no control. The only thing we control is when the print window opens and what content it has.
