### ISSUE TITLE
How do I use this library and print window opens in new tab?

### ISSUE THREAD

**Issue by puneethbs** [MatthewHerbst/react-to-print#235]

**Comment by MatthewHerbst** [comment]
Hello. The print window will do whatever your browser decides, we have no control over it. All we can do is open the print widow.

**Comment by puneethbs** [comment]
```
return (
      <div>
        <ReactToPrint
          trigger={() => (
            <a href="#" target="_blank">
              Print this out!
            </a>
          )}
          content={() => this.componentRef}
        />
        <ComponentToPrint ref={el => (this.componentRef = el)} />
      </div>
    );
```

I have this code, some link opens in a new tab, but the print window opens in the same tab, where we click.

https://codesandbox.io/s/react-to-print-xjr7i

**Comment by MatthewHerbst** [comment]
Why would you expect it to open on the page the link goes to?

**Comment by MatthewHerbst** [comment]
Happy to help you with ideas to solve your problem, but what you are trying to do is actually unrelated to this library

**Comment by dkumar431** [comment]
@MatthewHerbst ,
I am having the exact same issue, I want to open the print window in a new tab.
Is there any option available in react-to-print library? Basically I want that when someone clicks on the print button it should open a new tab with print option.

**Comment by MatthewHerbst** [comment]
@dkumar431 This is not a thing that `react-to-print` (or any other library) can solve for you. If you want to open a new tab with the content, then you need to design a page/js that will render that content into that page when it is opened, the same way your pages work now. `react-to-print` can live in that code and print it from that page, but it's not possible for us to open a new tab for you and drop random code into it. That would be a massive security problem if browsers allowed that.

**Comment by dkumar431** [comment]
Thanks, @MatthewHerbst for your quick response. Basically, as this print dialog blocking the UI thread like a default js alert box, I had a requirement to open in a new window. I got your point now.

**Comment by sangeetasingh17** [comment]
@dkumar431 how did you resolve your issue? or did you change your requirements?
