### ISSUE TITLE
Italic corrupts printed page.

### ISSUE THREAD

**Issue by dance-dance-banana-frenzy** [MatthewHerbst/react-to-print#238]
In google chrome mac os, the following cases cause a corruption problem printing italic text.

This works
```javascript
return <div ref={el => (this.componentRef = el)}>Good</div>
```

This fails
```javascript
return <i ref={el => (this.componentRef = el)}>Bad</i>
```

This fails
```javascript
return <em ref={el => (this.componentRef = el)}>Bad</em>
```

This fails
```javascript
return <div ref={el => (this.componentRef = el)} style={{fontStyle: 'italic'}}>Bad</div>
```

This fails
```css
.foo {
  font-style: italic;
}
```
```javascript
return <div ref={el => (this.componentRef = el)} className="foo">Bad</div>
```

Example of failure
<img width="999" alt="Screen Shot 2020-04-08 at 3 15 58 PM" src="https://user-images.githubusercontent.com/47341218/78824217-009f5800-79ac-11ea-897f-ebacb9503e5a.png">

**Comment by MatthewHerbst** [comment]
Hi, thanks for the issue. Can you confirm to me that this happens only when printing via `react-to-print`, and not also when simply hitting `cmd+p` on the page?

**Comment by dance-dance-banana-frenzy** [comment]
Yes. I found it was with hitting `cmd+p`. However, I was able to knock it down to the font being used. It has a problem with one of these.
`font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Open Sans,Helvetica Neue,Icons16,sans-serif;`

**Comment by MatthewHerbst** [comment]
Yeah, sounds like a Chrome issue. If you find a Chromium bug for this please feel free to link it back here so we can track it. Thanks!
