### ISSUE TITLE
print orientation 

### ISSUE THREAD

**Issue by manfye** [MatthewHerbst/react-to-print#240]
How do I set for portrait or landscape mode in default?

**Comment by MatthewHerbst** [comment]
I don't believe there is a way to do that. The settings in the print preview dialog are determined by your browser, and there is no standard way that I know of to set them across all browsers. If you know of such a mechanism please let me know!

**Comment by xgj1988** [comment]
@manfye  Did you resolve this problem?

**Comment by bashleigh** [comment]
I found a way to force the orientation. Inside my refed component I added this block

```
<style type="text/css" media="print">{"\
   @page {\ size: landscape;\ }\
"}</style>
```

**Comment by MatthewHerbst** [comment]
Thanks for posting that @bashleigh!

**Comment by bashleigh** [comment]
No problem!

**Comment by ronyfhebrian** [comment]
@bashleigh's answer is worked on me rather than importing "index.css" in my refed component. Don't know why

**Comment by tvjigar** [comment]
is that wroking

> I found a way to force the orientation. Inside my refed component I added this block
> 
> ```
> <style type="text/css" media="print">{"\
>    @page {\ size: landscape;\ }\
> "}</style>
> ```

**Comment by fastDev01** [comment]
Dosen't work on Safari

**Comment by jeff-r-skillrev** [comment]
> Dosen't work on Safari

Correct, and for anyone else wondering, CanIUse gives you a pretty good idea of which browsers will and will not support this. That means both you and the library maintainer are left w/o workarounds for some browsers.

https://caniuse.com/css-paged-media

**Comment by vandan501** [comment]
> > Dosen't work on Safari
> 
> Correct, and for anyone else wondering, CanIUse gives you a pretty good idea of which browsers will and will not support this. That means both you and the library maintainer are left w/o workarounds for some browsers.
> 
> https://caniuse.com/css-paged-media

How can i do default selected Orientation Landscape in safari browser only?
I dont want to show portrait mode is their any ways??

**Comment by JustinLuuu** [comment]
@bashleigh Thank you, that really works 🙌

**Comment by osamajavaid** [comment]
@fastDev01  @vandan501 did you found the solution for safari? Or did you switched the library?
react-to-print is very light package but it has some serious limitations for safari (mac and ios)

**Comment by MatthewHerbst** [comment]
@osamajavaid PRs to `react-to-print` to make it better are always welcome 😅
