### ISSUE TITLE
react-to-print can't resolve react-dom on nextjs project?

### ISSUE THREAD

**Issue by saidybarry** [MatthewHerbst/react-to-print#242]
I have tried installing react-dom, but no avail.

**Comment by MatthewHerbst** [comment]
Hello. Can you please let me know what version of `react-to-print` you are using? Also, a working codesandbox showing the problem would be greatly appreciated.

**Comment by saidybarry** [comment]
Hi, I was using the "2.7.0 beta", but I resolved my issue by downgrading to
"2.7.0"
*Saidy Barry,*
*Lead Backend Engineer* | *2581571,*

*7-8 Madiba Mall, *
*Brufut Gardens,*
*Brufut,*

*The Gambia*

*www.assutech.gm <http://www.assutech.gm/>*

**Comment by MatthewHerbst** [comment]
Hi @saidybarry moving from `2.7.0-beta.1` to `2.7.0` is an upgrade, not a downgrade :) Glad you resolved the issue

**Comment by saidybarry** [comment]
Lol Indeed my bad.
*Saidy Barry,*
*Lead Backend Engineer* | *2581571,*

*7-8 Madiba Mall, *
*Brufut Gardens,*
*Brufut,*

*The Gambia*

*www.assutech.gm <http://www.assutech.gm/>*
