### ISSUE TITLE
default title when print to pdf.

### ISSUE THREAD

**Issue by zb2oby** [MatthewHerbst/react-to-print#243]
Hello,

Actually when i try to print to pdf, it takes page's title defined in the head tag.

Is there any existing props to customize page title for print to pdf ? Anyway, it could be a great feature.

Thanks

EDIT : i've seen there was another issue about this. #122 . But there was not real solution, just workarounds. My problem is i'm using Helmet to update document title dynamically. And i don't want to change it in browser tab when printing. for my pdf, I just need to set a different filename from document title.

EDIT2 : i've found a workaround. basically i change document.title beforePrint and reset with previous saved title afterPrint.
 But it is not very clean because browser tab title really change before and after. Also, it brings some complexity for this simple feature.

Example to Change document title before and after : 
```
<ReactToPrint
            trigger={...}
            content={() => printable.current}
             onBeforePrint={() => document.title = "Print page title"}
             onAfterPrint={() => document.title = originalTitle}
/>
```

Complexity to save original title with useState and useEffect:
```
const [originalTitle, setOriginalTitle] = useState('');

useEffect(() => {
  
       setOriginalTitle(printable.current.ownerDocument.title) 
       //here not just document.title because  document.title take the value of <title> tag.
       //But with Helmet real title could be different
       //So we want the real Helmet updated title and this one is in printable.current.ownerDocument
       
}, [printable]);
```

**Comment by MatthewHerbst** [comment]
I've been thinking for a while we should probably expose a prop to easily do this. Are you interested in making a PR for it? The prop could just be called `title`. It should probably accept a string or a function (no args) that returns a string.
