### ISSUE TITLE
Child prop

### ISSUE THREAD

**Issue by davidjbradshaw** [MatthewHerbst/react-to-print#246]
Just wondering why the content to print is not the child of the ` < ReactToPrint>` component. It would make the syntax a lot simpler

    <ReactToPrint trigger={() => <button>Print this out!</button>} />
      <ComponentToPrint />
    </ReactToPrint >

Instead of

    <div>
      <ReactToPrint
        trigger={() => <button>Print this out!</button>}
        content={() => componentRef.current}
      />
      <ComponentToPrint ref={componentRef} />
    </div>

**Comment by MatthewHerbst** [comment]
I couldn't say, it's been this way since before I got involved with the library. We could certainly talk about support using children instead of having to pass `content`.
