### ISSUE TITLE
Table header cannot wrap?

### ISSUE THREAD

**Issue by laolaolulu** [MatthewHerbst/react-to-print#247]
![TIM截图20200510203342](https://user-images.githubusercontent.com/33310261/81499375-bc320f80-92fd-11ea-9610-1ed1eef0566d.png)
![TIM截图20200510203412](https://user-images.githubusercontent.com/33310261/81499391-dbc93800-92fd-11ea-8ccd-808cb6ab5dfa.png)

**Comment by MatthewHerbst** [comment]
Hello. Thank you for reporting the problem. Can you please make a working demo (codesandbox for example) that shows the problem so I can debug? Thank you
