### ISSUE TITLE
Breaking table layout on Component

### ISSUE THREAD

**Issue by kevfay** [MatthewHerbst/react-to-print#252]
I have a component that I am calling with ReactToPrint that has a table layout to contain the header and footer on each page. Does ReactToPrint add a wrapper or other code that could be breaking my page? When I print the page with the component it works perfectly, but using ReactToPrint it pushes my header to the bottom of the page. I essentially want ReactToPrint my component with nothing extra.

`<ReactToPrint
              trigger={() => (
                <span>
                  <IconLink iconName="print" href="#">
                    Print
                  </IconLink>
                </span>
              )}
              content={() => componentRef.current}
            />`
``
The start of my component to be printed: 
`return (
      <table className="report-container">
        <thead className="report-header">
          <tr>
            <th className="report-header-cell">
              <div className="header-info">
                <LogoHeader />
              </div>
            </th>
          </tr>
          </thead>`

Thanks!

**Comment by MatthewHerbst** [comment]
Hello. We default the `pageStyle` prop to: `"@page { size: auto;  margin: 0mm; } @media print { body { -webkit-print-color-adjust: exact; } }"` This could potentially be impacting you. You could try overriding it by passing an empty string, though I'm not sure why that would be causing the issue you have. Could you make a codesandbox or similar so your issue can be reproduced? Thanks

**Comment by kevfay** [comment]
Wasn't an issue with React To Print.
