### ISSUE TITLE
Provide practical examples using pageStyle property

### ISSUE THREAD

**Issue by raedbenz** [MatthewHerbst/react-to-print#259]
there is a lack of examples of using pageStyle e.g. how to fit component into A4 page, etc...
Please provide better description and examples !

**Comment by MatthewHerbst** [comment]
You are welcome to submit a PR 😄

**Comment by MatthewHerbst** [comment]
A small example of this will be added in the next release. Happy new year

**Comment by neverbe10** [comment]
I can't  locate the document
