### ISSUE TITLE
Getting a Blank Page along with the component to be printed 

### ISSUE THREAD

**Issue by shyam2794** [MatthewHerbst/react-to-print#26]
Hi , 

I am trying to print the bill . And am facing some issues in handling it . I am able to get the bill component to be printed but am getting another blank page . 

![screenshot from 2018-06-24 17-13-19](https://user-images.githubusercontent.com/30238125/41818808-7c9e5870-77d3-11e8-837d-a4cf73c248f3.png)

By Default it takes two pages . Am not sure how to resolve this .

**Comment by gregnb** [comment]
Hi @shyam2794 sorry for the delay. Try the new beta version which is going to rely on an iframe to solve the cross origin issues some people are experiencing.

```
npm install react-to-print@2.0.0-beta-3
```

and let me know the feedback if this solves issues

**Comment by gregnb** [comment]
There has been a rewrite pivoting away from popup windows. 

```
npm install react-to-print@2.0.0-alpha-1 --save
```

**Comment by dsdavis4** [comment]
I am facing the same issue with firefox, and neither of those versions fix the issue. Also tried using pageStyle to set the overflow property with no success. Works great on chrome

**Comment by LucasBSC** [comment]
Hello, is this problem already solved somehow? Having same issue here

**Comment by MatthewHerbst** [comment]
Hi @LucasBSC can you please create a new issue with more details if you are experiencing a problem? Thank you

**Comment by zainpros** [comment]
I am using the latest version and no working for me; is there and other proposed solution please

**Comment by MatthewHerbst** [comment]
@zainpros if you are having problems please create a new issue and describe your problem, as well as share the code you are using please, thank you.

**Comment by srj-github** [comment]
If anyone lands here, perhaps this will help:

```css
@media print {
  html, body {
    height: 100vh;
    margin: 0 !important;
    padding: 0 !important;
    overflow: hidden;
  }
}
```

**Comment by JavierVescio** [comment]
The solution from @srj-github almost solved my problem (thank you btw). I had to make a little change.
Instead of 
`height: 100vh;`
I had to write
`height: auto;`

In my case, I had a list which orginally had several rows but I wanted to print only the ones that were checked. If you write 100vh, the print won't take more than one page (it seems that it always prints one page), even when sometimes you actually need two or more pages to show all the rows. But if you write the value auto for the prop height, then it will automatically calculate the correct quantity of pages you need.

**Comment by ashabhussan** [comment]
> If anyone lands here, perhaps this will help:
> 
> ```css
> @media print {
>   html, body {
>     height: 100vh;
>     margin: 0 !important;
>     padding: 0 !important;
>     overflow: hidden;
>   }
> }
> ```

Thanks, @srj-github, It has worked for me.

**Comment by tomershlasky** [comment]
For whoever needs dynamic content that can be more than 1 page, and @JavierVescio's solution didn’t work for him. I managed to remove the extra page with this-
```css
@media print {
  html, body {
    height: initial !important;
    overflow: initial !important;
  }
}
```

**Comment by mateusdegobi** [comment]
@srj-github 
> ```css
>     height: 100vh;
>     margin: 0 !important;
>     padding: 0 !important;
>     overflow: hidden;
> ```

It works for me!!
Thanks, friend.

**Comment by abhijitkumarIN** [comment]
ya it is working only for one page but let suppose it page can be 100 page or some time it can be 1 page 
but when it is only one page still it is showing two page so on basis of page count we would be inject css ?

**Comment by yasinbhojani** [comment]
Thanks, this works @srj-github

**Comment by darkengine** [comment]
> @srj-github
> 
> > ```css
> >     height: 100vh;
> >     margin: 0 !important;
> >     padding: 0 !important;
> >     overflow: hidden;
> > ```
> 
> It works for me!! Thanks, friend.

This works for me. It handles one page and multiple pages correctly. @srj-github 's solution will cut it to a dead one page.

**Comment by Preetam7064** [comment]
> ```css
>  height: 100vh;
>     margin: 0 !important;
>     padding: 0 !important;
>     overflow: hidden;
> ```

Not working

**Comment by GourabPaul007** [comment]
It does not work in my case, The styles on 2nd page onwards gets weird.

This is what its supposed to print
![image](https://github.com/user-attachments/assets/55338d1f-1dfe-429e-a43f-2a9a8b9d464b)

But in the print window, it shows
![image](https://github.com/user-attachments/assets/d4de2fe5-48a4-4f11-9b77-241c11e93f93)

I have tried all solutions in this thread. Is there any reason why it is behaving like this?

**Comment by MatthewHerbst** [comment]
> I have tried all solutions in this thread. Is there any reason why it is behaving like this?

Please share your code, ideally in a working Codesandbox or similar. Can't debug from pictures.

**Comment by GourabPaul007** [comment]
Here is a codesandbox https://codesandbox.io/p/sandbox/quiet-pine-8behs
I think the problem lies with absolute positioning of the smaller blocks/components. referring to this 
![image](https://github.com/user-attachments/assets/2d501c65-6652-48ea-9d59-91e8efbde2bf)
This project requires absolute positioning. Help me know if there is any other way to fix this problem.

**Comment by MatthewHerbst** [comment]
> Here is a codesandbox https://codesandbox.io/p/sandbox/quiet-pine-8behs 

For me this prints without issue, though it's hard to tell because the formatting is hard to understand
