### ISSUE TITLE
Lazy load content for a search results page?

### ISSUE THREAD

**Issue by alxmrtn** [MatthewHerbst/react-to-print#262]
I'm currently working on building a search results page that has the option to print directly from the search results page. Our current implementation loads the content for all of the search results as hidden components for printing. Is there a way to only load the content to print once the trigger has been clicked?

**Comment by MatthewHerbst** [comment]
Yes! Using the `onBeforeGetContent` prop you can initiate a Promise and do whatever you need to do to the page. `react-to-print` will not gather the contents of the page until the Promise resolves:

```js
onBeforeGetContent={() => new Promise((resolve, reject) => {
  return LoadDataPromise
    .then((data) => {
      modifyPageWithNewData();
      resolve();
    })
    .catch(reject);
})}
```

Could also use `async`/`await`:

```js
onBeforeGetContent={async () => {
  await LoadDataPromise();
  modifyPageWithNewData();
}}
```
