### ISSUE TITLE
Some styles not appearing on print

### ISSUE THREAD

**Issue by murilinhoPs** [MatthewHerbst/react-to-print#263]
When I click print on my printing button it print everything I want, but it breaks the styles from children that have the display flex on my css (display:flex).

The code:
```jsx 
  return (
    <>
    <button className="PrintButton" onClick={handlePrint}>Imprimir</button>
      <div className="container" ref={printableRef}>
        <TodoDaily day="Segunda" />
        <TodoDaily day="Terça" />
        <TodoDaily day="Quarta" />
        <TodoDaily day="Quinta" />
        <TodoDaily day="Sexta" />
        <TodoDaily day="Sábado" />
        <TodoDaily day="Domingo" />
      </div>
    </>
  );
````

The flex property works inside the <div className="container"> but it breaks the flex style that is inside the TodoDaily component and is children. 

This is how it should looks:
![Captura de tela de 2020-06-17 12-06-19](https://user-images.githubusercontent.com/36513735/84915798-a4377380-b093-11ea-9aba-e064ad00a9d7.png)

This is how it prints:
![issue](https://user-images.githubusercontent.com/36513735/84915866-bb766100-b093-11ea-84e7-bb195699661c.png)

Can someone help me?

**Comment by MatthewHerbst** [comment]
Hello. Could you by chance make a codesandbox that replicates your issue? It's hard to diagnose any problems without having all of the working code

**Comment by murilinhoPs** [comment]
Okay, I'll create a codesandbox and send it to you, thanks!

**Comment by murilinhoPs** [comment]
The link to sandbox:

https://codesandbox.io/s/github/murilinhoPs/MVP-Rotina-IL/tree/master/?fontsize=14&hidenavigation=1&theme=dark

https://codesandbox.io/s/github/murilinhoPs/MVP-Rotina-IL?file=/src/index.js

**Comment by MatthewHerbst** [comment]
Thanks, I'll take a look when I get some free time

**Comment by Israel-oduguwa** [comment]
Then same thing is happening to me it breaks the display flex

**Comment by jlongguo** [comment]
me too

**Comment by kevinswartz** [comment]
me too!

**Comment by MatthewHerbst** [comment]
Trying to re-visit this, could someone please provide me with a working codesandbox showing the issue? The above ones no longer seem to work. Also, to be clear: the print is based on the size of a piece of paper (a size you can change in CSS). If you are trying to print a page that is wider or taller than the page size of the paper there is no possible way it is ever going to look right for you. You would need styles similar to handling mobile devices, though possibly within an `@media print` query
