### ISSUE TITLE
Multiple page print - default top and bottom margin.

### ISSUE THREAD

**Issue by shashankrepo** [MatthewHerbst/react-to-print#264]
When printing the component, I see there is no default margin. For the left and right margin, I have given some padding in the root component, but when the component is taking more than one page, it is continued and there is no top and bottom margin in pdf.

**Comment by shashankrepo** [comment]
pageStyle:
      '@page { size: auto;  margin: 10mm; } @media print { body { -webkit-print-color-adjust: exact; } }'

**Comment by MatthewHerbst** [comment]
Glad you got this figured out!
