### ISSUE TITLE
Preview Load Empty and print empty

### ISSUE THREAD

**Issue by HoaiHuynh** [MatthewHerbst/react-to-print#276]
I have an issue with my project, i have installed lib and run demo, but its empty. Any one have same issue? And how to fix that. Thank

**Comment by MatthewHerbst** [comment]
Hello. Can you please walk us through the steps that you did? Also, what version of Node are you using?

**Comment by DubstepKnight** [comment]
Hello, I have a similar problem. I am trying to print a component inside a modal overlay, (ant-design modal component). But it does not show anything in print preview. 
![image](https://user-images.githubusercontent.com/19612144/105337002-970ed400-5be2-11eb-9408-74014143d789.png)

I also see a warning from the library: 
![image](https://user-images.githubusercontent.com/19612144/105337082-a8f07700-5be2-11eb-884b-74a4e254a7f9.png)

The versions:
- Node is 15.4.0
- React 16.13.0
- antd 4.5.4

**Comment by MatthewHerbst** [comment]
@DubstepKnight any chance you can make a working codesandbox showing the problem? It's all but impossible to debug otherwise

**Comment by DubstepKnight** [comment]
@MatthewHerbst yes, I will try, wait for a while

**Comment by DubstepKnight** [comment]
@MatthewHerbst Unfortunately,  I could not replicate it on CodeSandbox. I decided to use **react-pdf** library for now. Because it seems to satisfy the current requirements. Thanks for the quick response.
