### ISSUE TITLE
Print layout issue on overlay in Internet Explorer 11

### ISSUE THREAD

**Issue by shrikartare** [MatthewHerbst/react-to-print#277]
We are trying to print a component which is on overlay(modal) content body . 
In print layout elements behind  the model and apart from  print component which we gave reference are displayed in Print layout.
We have to manually remove elements from body or apply media print queries with display none.

**This issue occurs only on Internet Explorer 11.**

**Comment by MatthewHerbst** [comment]
Hello. Could you please share screenshots of the problem, and ideally a codesandbox with working code that replicates it? Thank you

**Comment by shrikartare** [comment]
Hello , we are working in secured environment so not able to share code.
But when we use this command 
```js
document.getElementById("printWindow").contentWindow.document.execCommand('print', false, null);
```
in internet explorer on the iframe created by `react-to-print`  package, print works correctly.

React to Print works correctly on IE on body element, issue is there on modal(overlay).

**Comment by MatthewHerbst** [comment]
Hi. Could you share just some basic HTML that replicates the problem? I'm having a hard time understanding your use case

**Comment by shrikartare** [comment]
Hi,
i have added sandbox code. Please find the link below.

Steps to produce the issue
1. Go to sandbox url  (**https://codesandbox.io/s/competent-tree-rtj4c**).
2. Click open modal button.
3. Modal will open and click on print button.Print button will print the contents of the div  with text "**Print Content**"  inside the modal.
4. Check print preview layout in Internet Explorer 11.

Results: 

**1) Internet explorer 11: Entire Page is displayed in print preview.Html  outside the ref  div are also displayed. --Not as per  expected results.**

 2) Other Browser: Contents of  print div whose reference is passed is displayed. --As per expected result

**Note:-** On adding this code in onBeforePrint function print preview in correctly displayed for IE 11.This is a temporary solution we  have added.

```jsx
<ReactToPrint
  content={} 
  trigger={}
  onBeforePrint = () => {
    if (browserName="IE11") {
      document.getElementById("printWindow").contentWindow.document.execCommand('print', false, null);
      return Promise.reject();
    }
  }
/>
```

**Comment by iampriyaank** [comment]
Hi @MatthewHerbst ,

I am also facing similar issue. Are you planning for a fix to this issue? Any tentative deadline?

**Comment by MatthewHerbst** [comment]
Hi. I have been having a hard time trying to test this because codesandbox does not work on IE11 apparently :( I'm trying to make it work with stackblitz.com but haven't gotten it setup yet

**Comment by shrikartare** [comment]
Hi  ,
If we are having problems on sandbox, and stackblitz,
Can we try to replicate the  code on local machine?

**Comment by MatthewHerbst** [comment]
I don't use Windows so local machine won't work for me unfortunately. I will try again this weekend

**Comment by MatthewHerbst** [comment]
Going to close this out as a won't-fix. If someone knows how to fix this I will happily accept a PR, but I don't have time to spend on IE11 support
