### ISSUE TITLE
Custom fonts not copying correctly

### ISSUE THREAD

**Issue by rajat-barman-js** [MatthewHerbst/react-to-print#281]
While Printing a component.
Most of the texts in original page vanishes in chrome somehow. but doing the same thing in safari or firefox doesn't produce such behaviour

behaviour in chrome
As you can see the labels texts in the original page at the back is is spomehow vanished
<img width="1272" alt="Screenshot 2020-08-29 at 11 32 30 PM" src="https://user-images.githubusercontent.com/39688364/91643395-805bbb00-ea50-11ea-89a9-d07594abb0a8.png">

but in the firefox its behaviour is correct
<img width="1272" alt="Screenshot 2020-08-29 at 11 34 03 PM" src="https://user-images.githubusercontent.com/39688364/91643401-8356ab80-ea50-11ea-92c7-e019d4bb47b7.png">

P.S.- we are using custom font in the website

**Comment by MatthewHerbst** [comment]
Hi. That is very strange indeed! Would you mind sharing a working codesandbox or similar that replicates the problem? would love to dig deeper into this

**Comment by MatthewHerbst** [comment]
Also, have to ask: did you verify that this only happens when printing with `react-to-print`, or does it also happen when just printing normally with `ctrl/cmd + p`?

**Comment by rajat-barman-js** [comment]
> Also, have to ask: did you verify that this only happens when printing with `react-to-print`, or does it also happen when just printing normally with `ctrl/cmd + p`?

Tried with cmd +p
 it works fine

**Comment by rajat-barman-js** [comment]
> Hi. That is very strange indeed! Would you mind sharing a working codesandbox or similar that replicates the problem? would love to dig deeper into this

We are using Gustanlp-Book in the system which might be creating problem.
Is there some existing bug related to font??

**Comment by MatthewHerbst** [comment]
If you use a normal font does it work? It's possible we don't copy over fonts properly

**Comment by rajat-barman-js** [comment]
> If you use a normal font does it work? It's possible we don't copy over fonts properly

it works with normal font, but doesn't work with our custom font

**Comment by MatthewHerbst** [comment]
Interesting. I'll look into it. Must be a special thing we need to do to copy custom fonts over. Thanks for helping narrowing it down

**Comment by MatthewHerbst** [comment]
Can you show me please how you include your custom fonts on the page?

**Comment by rajat-barman-js** [comment]
> Can you show me please how you include your custom fonts on the page?

```css
@font-face {
  font-family: 'test';
  src: local('test'), url(./fonts/Gustanlp-Book.otf) format('opentype');
}

body {
  margin: 0;
  padding: 0;
  font-family: test;
}
```

**Comment by MatthewHerbst** [comment]
So, the issue is that we are not waiting for the fonts to load before opening the print preview window, because we don't know that there even are fonts that are loading. We currently listen for HTML and CSS loads to finish, but font loads happen in their own world. I think I can offer a new prop that would fix this using the new [CSS Font Loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API) (only for new browsers, won't work in IE11). Will try and make a PR showing it tomorrow. It would be something like:

```jsx
<ReactToPrint
  ...
  fonts=[{ name: 'Font', url: 'urlToDownloadFront', local: 'localFontFileIfAny' }]
/>
```
Then I would do something like [this example](https://googlechrome.github.io/samples/font-face-set/) to wait for them to load before printing

**Comment by rajat-barman-js** [comment]
> So, the issue is that we are not waiting for the fonts to load before opening the print preview window, because we don't know that there even are fonts that are loading. We currently listen for HTML and CSS loads to finish, but font loads happen in their own world. I think I can offer a new prop that would fix this using the new [CSS Font Loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API) (only for new browsers, won't work in IE11). Will try and make a PR showing it tomorrow. It would be something like:
> 
> ```js-jsx
> <ReactToPrint
>   ...
>   fonts=[{ name: 'Font', url: 'urlToDownloadFront', local: 'localFontFileIfAny' }]
> />
> ```
> 
> Then I would do something like [this example](https://googlechrome.github.io/samples/font-face-set/) to wait for them to load before printing

That would be great.

Thanks

**Comment by MatthewHerbst** [comment]
Hey, checkout #285 and let me know if that works for you. If you could test it by trying to run it locally with the fonts you have that would be fantastic too

**Comment by MatthewHerbst** [comment]
Hi @iamthespecial1 did you have a chance to look at that PR? I'm excited to get it merged but I'd like to make sure it actually solves your problem first

**Comment by JetsterDajet** [comment]
@MatthewHerbst I am having a similar issue, going to try your `fonts` branch and let you know how it goes. Thanks for helping out w/ this, overall package works really well.

**Comment by MatthewHerbst** [comment]
Published as v`2.11.0` 🎉

**Comment by hahouari** [comment]
> > Can you show me please how you include your custom fonts on the page?
> 
> ```css
> @font-face {
>   font-family: 'test';
>   src: local('test'), url(./fonts/Gustanlp-Book.otf) format('opentype');
> }
> 
> body {
>   margin: 0;
>   padding: 0;
>   font-family: test;
> }
> ```

I faced the exact same problem and trying to solve it for two days, as @MatthewHerbst said the fonts are not loaded when the print dialog is opened, adding `font-display: swap` to `@font-face` clause allows the browser to wait a little for the font to load as mentioned in [Mozilla MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display), keep in mind [browser support](https://caniuse.com/?search=font-display), so your css code would be:

```css
@font-face {
  font-family: 'test';
  font-display: swap; // << add this
  src: local('test'), url(./fonts/Gustanlp-Book.otf) format('opentype');
}
```

**Comment by AndreOdon** [comment]
I found the problem, as I am using a custom font, it was not being loaded the first time I opened the print modal.
Here is the solution: https://github.com/gregnb/react-to-print/issues/281#issuecomment-1098039528

**Comment by youneszahzouh** [comment]
> ```css
>   font-display: swap; // << add this
> ```

adding this worked for me .. thanks
