### ISSUE TITLE
Styling not added to print when the page is in iframe

### ISSUE THREAD

**Issue by rajat-barman-js** [MatthewHerbst/react-to-print#283]
My page is in iframe, when i am printing the component in the inframe,it shows the following
react-to-print" was unable to load a linked node. It may be invalid. "react-to-print" will continue attempting to print the page. The linked node that errored was: <link href=​"./​static/​css/​main.b482d9d9.chunk.css" rel=​"stylesheet">​

**Comment by MatthewHerbst** [comment]
Not sure what I can really tell you without more information. Are you sure the link is valid and that the file has no errors in it? We attach directly to the DOM `onerror` event, so if you are getting this message there is almost certainly a problem that is unlikely to be related to `react-to-print`. Can you make a codesandbox with a working demo?

**Comment by MatthewHerbst** [comment]
Hello. Are you able to provide more information by chance? I would love to see you able to resolve this issue
