### ISSUE TITLE
Not triggering print at all (content or onBeforeGetContent neither is called)

### ISSUE THREAD

**Issue by ziaulrehman40** [MatthewHerbst/react-to-print#284]
`content` or `onBeforeGetContent` is not being triggered at all.
We recently did some changes in which we added some new pages with lot of new JS plugins. Something from there is messing this up. Because it was working all fine before that commit got in, we tried on commits before that merge and it still works.

I know this is some dependency issue but **I am opening the issue just to get some help debugging the exact problem.** And perhaps when i figure the issue out, it might be some incompatible library/transpiler versions which I will comment here so people can be warned.

We tried upgrading to latest version of react-to-print. We are using `react 16.2`
And code looks something like:

```
    ...
    const reactToPrintContent = _ => this.componentRef
    const printTicketRef = el => this.componentRef = el

    const reactToPrintOnTrigger = _ => (
      <Tooltip title='Print Expense'>
        <FontAwesome className='print-expense-text' name='print' />
      </Tooltip>
    )
...
    return (
      ...
          <ReactToPrint trigger={reactToPrintOnTrigger} content={reactToPrintContent} />
            <br/>
            <br/>
            <PrintComp ref={printTicketRef} data={data} />
          </div>
```

**Comment by MatthewHerbst** [comment]
Hello. I don't see `onBeforeGetContent` getting called anywhere. Your use of `content` seems correct. Do you see any errors in the console? Also, what packages did you upgrade? `react-to-print` doesn't use any packages except `prop-types`, so I can't imagine how upgrading another package could change printing behavior

**Comment by ziaulrehman40** [comment]
Ok, sorry for the bother, it turns out we are using some deprecated versions of material-ui and the tooltip is coming from that, packages changes included something around material UI.
We wrapped the trigger(tooltip) in a div and everything stated working again.
