### ISSUE TITLE
Img cannot be displayed

### ISSUE THREAD

**Issue by wx9999** [MatthewHerbst/react-to-print#288]
Is there any solution

<img src="./images/offline-line-1.png" alt="" />

**Comment by wx9999** [comment]
You don't show pictures when you print them

**Comment by MatthewHerbst** [comment]
Hello. We certainly do include images in the page. What browser are you using? On Chrome and some others you need to manually enabled background graphics in the print preview window (doing so once should save the setting for all future prints)
![Screen Shot 2020-09-15 at 11 15 09 PM](https://user-images.githubusercontent.com/1287375/93299151-730d3300-f7a9-11ea-828d-a23b2336fb54.png)
