### ISSUE TITLE
Pattern，Content is not paginated

### ISSUE THREAD

**Issue by wx9999** [MatthewHerbst/react-to-print#289]
How can I avoid automatic paging，
Do not paginate content when it is too long

**Comment by MatthewHerbst** [comment]
Not sure I understand. Can you show an example please? My guess is you need to modify the CSS styles for `@media print`

**Comment by wx9999** [comment]
I probably don't need to paginate when I print. How do I do that。

![image](https://user-images.githubusercontent.com/42061047/93411047-dcd22d80-f8cc-11ea-968d-c4ef04d2ab87.png)


In the case of an image, make its content non-pageable

**Comment by MatthewHerbst** [comment]
If it's paginating it's because your content doesn't fit on one page... you need to make your content fit on one page. If you shared a working codesandbox that would be helpful
