### ISSUE TITLE
Is it possible to print onClick without print dialog popup?

### ISSUE THREAD

**Issue by delton1994** [MatthewHerbst/react-to-print#294]
Client only uses one type of printer and a set of custom margins for project.  DYMO Label v.8. The sample framework is dated and a pain. I love using this package because its streamlined and simple. Is it possible to capture the component before the print dialog displays and send in to a printer? Or since the printer is known, can I suppress the print window while printing the persisted data?

**Comment by MatthewHerbst** [comment]
Hi, and thanks for using the package 😄 

We use the [`Window.print`](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) method to print. What happens after we call that is decided by the browser, and unfortunately we don't have any control over what the browser decides to do. There is no way to have the browser silently print using native APIs. There are per-browser workarounds such as [plugins and extensions](https://stackoverflow.com/questions/27633386/how-to-skip-browser-default-print-preview-and-print-content-directly-to-printer), or using [Google Cloud Print](https://stackoverflow.com/questions/19656372/select-a-printer-and-silently-print), but nothing that's shared across all browsers.

The ideal solution is for there to be a new HTML Print API, but I haven't heard of anything like that being worked on unfortunately. Maybe I'll try and see if that's something that's even possible to get the ball rolling on, though proposals like that can take years to reach fruition.
