### ISSUE TITLE
For "react-to-print" to work only Class based components can be printed.

### ISSUE THREAD

**Issue by xStorm111** [MatthewHerbst/react-to-print#304]
Hello, 
I'm trying to print a component (in this case, a **Grid from Material-UI**) that **i don't want** show on the screen first. 
I was trying to use **Hidden** component as a parent of Grid but aparently i can't fill componentRef from Grid ref if the grid is inside **Hidden**

![image](https://user-images.githubusercontent.com/22938156/96887629-ac0d8700-147c-11eb-9ed2-727edb1b567f.png)

ReactToPrint Component :
![image](https://user-images.githubusercontent.com/22938156/96887732-c6476500-147c-11eb-86b9-4a5e4a947205.png)

Is there anyway solution for this or a easier way?

**Comment by xStorm111** [comment]
🤦 i swapped Hidden to div hidden and it worked

**Comment by MatthewHerbst** [comment]
Glad you got it working!
