### ISSUE TITLE
When using the antd form, there is no way to display the fields that need to be displayed in the render method

### ISSUE THREAD

**Issue by A9074o** [MatthewHerbst/react-to-print#307]
When using the antd form, there is no way to display the fields that need to be displayed in the render method

The problem is as shown below;
![image](https://user-images.githubusercontent.com/45235142/97562249-4bea8800-1a1c-11eb-92e4-08ded6e6f798.png)

![image](https://user-images.githubusercontent.com/45235142/97562538-be5b6800-1a1c-11eb-99d7-be931e065a9c.png)

![image](https://user-images.githubusercontent.com/45235142/97562474-a4ba2080-1a1c-11eb-9681-845413b24438.png)

version number:
![image](https://user-images.githubusercontent.com/45235142/97562595-d4692880-1a1c-11eb-93c2-8956000a49bc.png)

The problem is urgent, waiting to go online

**Comment by Asence** [comment]
@devuxer

**Comment by MatthewHerbst** [comment]
Hello,

To clarify, you want to print only the fields you have put in red?

**Comment by A9074o** [comment]
你好，
我的render里面写了两个字段, 但是打印的时候只打印出了我表格dataindex绑定的字段，另外一个字段没有展示出来 @MatthewHerbst 

> (from Google translate)
> Hello there,
There are two fields in my render, but only the fields bound to my dataindex are printed when printing, and the other field is not displayed.

**Comment by MatthewHerbst** [comment]
Sorry for not replying sooner. Can you make an example I can use to debug please? You can use a website such as [codesandbox](https://codesandbox.io/s/rzdhd)
