### ISSUE TITLE
How to print as the page open?

### ISSUE THREAD

**Issue by marta312** [MatthewHerbst/react-to-print#31]
Hallo,
Than you for sharing, I found the lib really usefull!

I would like to let the printing process start as the page open, but I do not know how to set the trigger function.
Do you think is there a way to manage this?

Thank you
Marta

**Comment by gregnb** [comment]
Hi @marta312, I am going to say that is probably out of scope for this package. This package is meant to be a action based and not on a page load. There might be some other solutions out there that will work better for you
