### ISSUE TITLE
how to make small size for pdf result

### ISSUE THREAD

**Issue by andreenov** [MatthewHerbst/react-to-print#310]
hi

is it possible to make a size for pdf result smaller? or is it possible to compress the file size before downloading its file

thank you

**Comment by MatthewHerbst** [comment]
Hello. The PDF generation is determined by your browser based off of what is being printed. I don't know if there is a way to use CSS to change styles only in PDFs, but you can use `@media print { ... }` to control styles during printing. The actual size of the file is based on what's being printed, so I would suggest making any images or such that you have smaller. If you post a working code example I'm happy to try and help diagnose any issues.

**Comment by andreenov** [comment]
Hi @MatthewHerbst thank you for responding to my question.
there are more than 900 lines of code but here's some of my code. I'm using CSS style inside my component. Should I put the CSS code outside the component? like styled component

```js
<Card>
                  <Card.Grid style={{ width: '15%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>Blood Pressure</Card.Grid>
                  <Card.Grid style={{ width: '10%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>Pulse</Card.Grid>
                  <Card.Grid style={{ width: '13%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>Temperature</Card.Grid>
                  <Card.Grid style={{ width: '13%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>Pain Scale</Card.Grid>
                  <Card.Grid style={{ width: '13%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>Respiration</Card.Grid>
                  <Card.Grid style={{ width: '9%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>GCS</Card.Grid>
                  <Card.Grid style={{ width: '9%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>E</Card.Grid>
                  <Card.Grid style={{ width: '9%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>M</Card.Grid>
                  <Card.Grid style={{ width: '9%', textAlign: 'center', background: palette.grayscale[10], padding: '5px' }}>V</Card.Grid>
</Card>

```

thank you

**Comment by MatthewHerbst** [comment]
Doesn't really matter where the styles are so long as you have the right styles for what you need. In terms of the PDF size I really can't help there without a full working code example

**Comment by andreenov** [comment]
here's the full code, I put on codesanbox [https://codesandbox.io/s/condescending-morning-s96o9?file=/src/medResPrint.js](https://codesandbox.io/s/condescending-morning-s96o9?file=/src/medResPrint.js)

**Comment by MatthewHerbst** [comment]
I don't see any reason why that should produce a large file size. How big is the file you are seeing?

**Comment by andreenov** [comment]
it depends on the data from the database, could be more than 5MB,

**Comment by MatthewHerbst** [comment]
That doesn't strike me as too big if you are actually printing out that much from the server. What would you expect it to be?

**Comment by andreenov** [comment]
it is possible for our app to generate pdf more than 45 pages and it counts for 14MB file size, it is because the user has to upload to 3rd party system and the system will reject the file more than 5MB

**Comment by MatthewHerbst** [comment]
What would you like this library to do to help solve that? We don't modify any content inside the print window

**Comment by andreenov** [comment]
is it possible to compress the file size just before the data is converting into pdf? or is any way to make the file size smaller?

**Comment by MatthewHerbst** [comment]
We don't control that, it's all happening in the user's browser. All we do is open the print window. If the user selects to send that to a printer or to print as a PDF we don't have control over. Once the Print Preview dialog opens we lose all control unfortunately, there is no API for controlling that yet 😢  It would solve so many feature requests with this lib if there was.

If there is any data compression going to happen it would have to happen on your end before you try and print the file to a PDF. If you have 14MB of text to display though I don't know how you could possibly compress that to 5MB and still display it. Might be a good question for StackOverflow

**Comment by andreenov** [comment]
it's all right @MatthewHerbst thank you for your kind response, i really appreciate that

have a good day

**Comment by MatthewHerbst** [comment]
Best of luck! And thanks for using the library
