### ISSUE TITLE
useRef in example can be Typesafe - solves your TODO

### ISSUE THREAD

**Issue by nealeu** [MatthewHerbst/react-to-print#311]
This line: 
https://github.com/gregnb/react-to-print/blob/d6349a0c27e85887eddfe8b0f0e2832600b48869/example/FunctionalComponentWithHook/index.tsx#L9-L10

Can be:
```const onBeforeGetContentResolve = useRef<(() => void) | null>(null);```

**Comment by MatthewHerbst** [comment]
🥂 Thank you! Would you like to may the PR for that?

**Comment by MatthewHerbst** [comment]
Done in #320, thanks again!
