### ISSUE TITLE
Electron Silent Print Bug

### ISSUE THREAD

**Issue by ckrgithub** [MatthewHerbst/react-to-print#313]
![image](https://user-images.githubusercontent.com/18225851/98788018-340efd00-243b-11eb-8655-202b065a4897.png)

**Comment by MatthewHerbst** [comment]
Hello. Can you please give more details? I don't understand how the screen shot has anything to do with this library

**Comment by ckrgithub** [comment]
I find [the project](https://github.com/Ririshi/react-to-print/blob/print-replacer-example/example/ElectronPrint/electron/electron.js) based on #270 

**This method does not have a callback causing the specified print device to not take effect**
```js
  ipcMain.on('silent-print', (event) => {
    // Print the window silently
    const options = { 
      landscape: true,
      deviceName: 'EPSON LQ-630KII ESC/P2',
      silent: true
    }
    event.sender.print(options, (success, failureReason) => {
      // Signal that the print is finished
      event.reply('silent-print-result', success ? 'success' : failureReason);
    });
  });
```

**Comment by fralfarom** [comment]
Hi @ckrgithub could you print a react component from electronjs with this library? I'm trying to do this but I can't ...

**Comment by MatthewHerbst** [comment]
Hello. I'm still waiting for a code sample to see how this is used with `react-to-print`, right now I only see Electron code

**Comment by MatthewHerbst** [comment]
Working Electron example with how to print using `react-to-print` is now available! https://stackoverflow.com/questions/68751490/electron-print-iframe-given-reference-to-it
