### ISSUE TITLE
return with pdf file

### ISSUE THREAD

**Issue by mbarlescuBVdash** [MatthewHerbst/react-to-print#314]
Hi guys, great work. Are we able to access the generated pdf file in our FE? For example, upon generation can the file be returned to the FE in any way, instead of the user having the download the pdf themselves. Thanks!

**Comment by MatthewHerbst** [comment]
Hi there. We don't actually generate a PDF, that is being done completely in the user's browser. All we do is tell the browser what to include in the Print Preview Window. What options the user selects in there, including printing to a normal printer or saving to a PDF (an option all major browsers have, but not all browsers have), is totally up to the user.

There was some attempted work a few months ago to try and get a direct-to-download PDF client into this library but it didn't go very far unfortunately. PDF libraries are fairly large and to be included here, need to be cross-browser compatible.

If you have any ideas on ways to improve our handling of a user wanting to print a PDF we are always open to suggestions
