### ISSUE TITLE
Question: How to print multiple pages

### ISSUE THREAD

**Issue by zhitomir-oreshenski-mm** [MatthewHerbst/react-to-print#317]
Hi,

it seems that somehow printing multiple pages is not possible in my case.

I've tried multiple suggested solutions here, but without any luck.

Basically I am using surveyjs and try to print the content in preview mode:

https://surveyjs.io/Examples/Library/?id=survey-displaymode&platform=Reactjs#content-result

Any suggestions what can be the case?

PS: I've double checked following example: https://codesandbox.io/s/react-to-print-forked-swrdl?file=/example/index.js:249-8288

Best regards,
Zhi

**Comment by MatthewHerbst** [comment]
Hello. Could you make a codesandbox showing your problem please? I've never used surveyjs before so seeing your actual problem will be the most useful to help debugging, thank you

**Comment by zhitomir-oreshenski-mm** [comment]
Hi Matthew Herbst,

Thank you for your prompt response. 

I've managed to fix it by passing following styles:

```css
@media print {
  html, body {
    height: initial;
    overflow: initial;
  }
}

@page {
  size: auto;
}
```

into surveyjs custom css file.

Thank you, you can close the request.

Fantastic work on this lib!

BR,
Zhi

**Comment by MatthewHerbst** [comment]
Glad you got it working!
