### ISSUE TITLE
Is Support trigger custom function after show print-dialog

### ISSUE THREAD

**Issue by MarsonShine** [MatthewHerbst/react-to-print#318]
when call `trigger` function, and show print-dialog
then i want to call custom function when print-dialog displayed
how do it?
thk

**Comment by MatthewHerbst** [comment]
Hello. You want to show the custom dialog on top of the print-dialog, or after the print-dialog has closed?

**Comment by MarsonShine** [comment]
first i description my case 
1. raise `trigger` function then show print-dialog
2. then user select 'print'(not 'cancel')
3. print succeed，then i call service to increase numbers of print for data analysis

now，`onAfterPrint` is raised whenever print and cancel。so is not my needs

expect: only print succeed

finally，sorry for my english

**Comment by MatthewHerbst** [comment]
Ah, I understand. I'm sorry, but unfortunately [it is not possible](https://github.com/gregnb/react-to-print#why-does-onafterprint-fire-even-if-the-user-cancels-printing). We listen for the [`onAfterPrint`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint) event to detect when the print-dialog has closed. That event is fired regardless of selecting "print" or "cancel"

From the documentation:

> These events are raised after the user prints, or if they abort the print dialog.

One day there might be a standard Print API, but right now we are very limited in what control we have.

**Comment by MarsonShine** [comment]
ok，i see and thank for your reply
i close issue
