### ISSUE TITLE
Using library in electronjs

### ISSUE THREAD

**Issue by fralfarom** [MatthewHerbst/react-to-print#319]
Hi, I read that to use this library I had to pass the print prop in the <ReactToPrint> component ... I have tried in some ways but I still can't print a component ... the only error I get is "For" react-to- print "to work only Class based components can be printed."
Is there an example of how to use this library in electronjs? Thanks a lot.

**Comment by MatthewHerbst** [comment]
Hello. Can you share some of the code please? It sounds like the problem you are having is that you are trying to print a functional component at the top-level when right now we only support class components at the top-level

**Comment by fralfarom** [comment]
edit: I dont know why the code change its format 😥 sorry.

Hello @MatthewHerbst  my component to print is:
```jsx
export default class ComponentToPrint extends React.Component {
  render() {
        return (
          <table>
            <thead>
              <th>column 1</th>
              <th>column 2</th>
              <th>column 3</th>
            </thead>
            <tbody>
              <tr>
                <td>data 1</td>
                <td>data 2</td>
                <td>data 3</td>
              </tr>
            </tbody>
          </table>
        );
      }
  }
```

and Im calling :
```jsx
<ReactToPrint
      trigger={()=>{
        return <a href="#">Print this out!</a>;
      }}
      print={()=>this.componentRef}
      content={() => this.componentRef}
>
      <ComponentToPrint ref={el => (this.componentRef = el)} />
</ReactToPrint>
```

I have this in a button onClick then when I clicked the button I just getting the error "For" react-to- print "to work only Class based components can be printed."
Im trying use "print" prop because Im in electron app...but to tell the truth... I don't know how to use this prop 😅😅😅

**Comment by MatthewHerbst** [comment]
Ah, yes. Take a look at #270. There is discussion and links there that might help you. Essentially though, the `print` prop gets as an argument the content to print, and must return a promise. So, it should be used like:

```jsx
<ReactToPrint
  trigger={()=>{
    return <a href="#">Print this out!</a>;
  }}
  print={(htmlContentToPrint) => {
    return new Promise((resolve, reject) => {
      // Do electron printing here, when finished call resolve(), if there is an error, call reject()
    });
  }}
  content={() => this.componentRef}
>
  <ComponentToPrint ref={el => (this.componentRef = el)} />
</ReactToPrint>
```

P.S. for formatting code on multiple lines in GitHub, use three ticks instead of one, so do

this
\```
code here
\```

instead of 
\`
code here
\` 

Let me know if you still have trouble after looking at #270

**Comment by fralfarom** [comment]
@MatthewHerbst Thank you very much for the reply! When I can Illtry this and Ill tell you.

**Comment by SoyMarco** [comment]
Hello! Did they manage to do it? I have been trying to use print but I don't know how to do it. You have a more specific example to work with the "silent print"

**Comment by MatthewHerbst** [comment]
Working Electron example with how to print using `react-to-print` is now available! https://stackoverflow.com/questions/68751490/electron-print-iframe-given-reference-to-it
