### ISSUE TITLE
documentTitle doesn't seem to work

### ISSUE THREAD

**Issue by matYang** [MatthewHerbst/react-to-print#321]
Using react-to-print v2.11.0

```
<ReactToPrint
   documentTitle='some title'
   trigger={() => (
      <Button
         primary
         size='small'
      >
         Export
      </Button>
    )}
    content={() => this.someRef}
/>
```

when choosing to save download as PDF, the default document name is still the page title, not the one specified in documentTitle prop

also using react helmet v5.2.1 to set the page title at render, not sure if it impacts anything

**Comment by MatthewHerbst** [comment]
Hello. I see it working properly when I run the examples locally (the file name changes to what is specified in `documentTitle`), however, when I run the example in codesandbox I do see the issue you are running into. I'll take a look. Any chance you could share the code you use to set the title? Thank you

**Comment by MatthewHerbst** [comment]
Ok, I have a theory about the codesandbox example: they render the page within an `iframe`, and I'm willing to bet that changing the value of `document.title` within the `iframe` only changes the value within the `iframe`, and not in the parent window. I would love to see how your code works to see if that could be related, or if I'm missing something else

**Comment by MatthewHerbst** [comment]
Ok, I can confirm that attempting to set `document.title` in an `iframe` only effects the `iframe`, not the main `document`. Interestingly, setting the `title` attribute on an `iframe` does not set its `document.title`.

For same-origin `iframe`s we can change the parent title from within the `iframe` by doing `window.parent.document.title = 'Some New Title`. The problem with this is that `react-to-print` has no way of knowing how far down you are, for example, you could be printing in an `iframe` within another `iframe`. This also won't work on cross-origin `iframe`s.

Would love to see your code. Does it use `iframe`s, or maybe there is something else happening?

**Comment by MatthewHerbst** [comment]
Related: https://stackoverflow.com/questions/42014507/how-can-i-set-the-default-filename-for-the-chrome-print-dialog-from-within-an-if

**Comment by MatthewHerbst** [comment]
A naive solution to this is to allow `documentTitle` to accept a function that would return the reference to `document.title` at the top layer, and simply leave it to the user to figure out how that should be determined/retrieved. Ex:

```jsx
const getDocumentTitle = () => {
  // User figures out what the correct reference is
  return window.parent.window.parent.window.parent.document;
};

return (
  <ReactToPrint
    documentTitle={getDocumentTitle}
    ...
  />
);
```

Another solution is for the user to manually control this using the existing callbacks:

```jsx
const handleOnBeforePrint = () => {
  // User figures out how to correctly set the title of the top-level page for printing
  setNewTopLevelPageTitle('Printing Title');
};

const handleOnAfterPrint = () => {
  // User figures out how to correctly set the title of the top-level page back to what it should be
  setNewTopLevelPageTitle('Original Title');
};

return (
  <ReactToPrint
    onBeforePrint={handleOnBeforePrint}
    onAfterPrint={handleOnAfterPrint}
    ...
  />
);
```

Neither are amazing but I'm not sure of another solution. I'll keep thinking about it. Again, would love to see your code when you get a chance please.

**Comment by matYang** [comment]
Sorry for the late response, we are not rendering the page in iframe, it's standard HTML.

The page in question is an admin download page, its title is set during a componentDidMount event in a parent element by

`document.title = `${applicationName} | Admin`;`

checking the HTML, the title is properly set in the head, and when saving the PDF, the default name is the page title

**Comment by matYang** [comment]
adding

```
onBeforePrint={() => { document.title = 'Test1'; }}
onAfterPrint={() => { document.title = 'Test2'; }}
```

successfully set the exported PDF default name to Test1, documentTitle prop still not working for me tho

**Comment by khryshan** [comment]
@MatthewHerbst Hi! I have the same issue. Tell me, please, are you find a good solution? As for your up solutions, I don't figure out how to allow `documentTitle` to accept a function.

**Comment by dongying09** [comment]
Hi, I am having a similar issue, documentTitle works for chrome, not for firefox or safari. I tried to change document.title using useEffect or onBeforePrint, the title is changed but the printer doesn't pick up the name. For firefox and Safari, the default name is still "Untitled".

**Comment by cbix** [comment]
Weird, for me (Arch Linux) `documentTitle` works in Firefox, but not in Chromium (it just uses the main window title).

**Comment by MatthewHerbst** [comment]
@cbix what version of `react-to-print` are you on? The [fix](https://github.com/gregnb/react-to-print/pull/418/commits/f50a7ba059e3383998076a43ce2092965c6e043c) published in [`v2.14.0`](https://github.com/gregnb/react-to-print/blob/master/CHANGELOG.md#2140-october-20th-2021) should have solved this 🙏

**Comment by cbix** [comment]
@MatthewHerbst I'm on v2.14.1 and even in the [Codesandbox example](https://codesandbox.io/s/rzdhd) (which uses v2.14.1 as well) `documentTitle` doesn't work:
![Screenshot from 2021-11-23 09-32-35](https://user-images.githubusercontent.com/1295945/142992359-009ef688-1b17-4a8a-b87f-5696f03047d0.png)

Update: I figured out it's because the app would run in an iframe (Storybook for my development, and in Codesandbox it also runs in an iframe) and apparently that prevents setting the main window title. When opening the component in Storybook/Codesandbox in its own window, it works 🎉 I guess that solves it for me, as I only use Storybook for some component development while the production app doesn't run in an iframe.

**Comment by MatthewHerbst** [comment]
> it's because the app would run in an iframe

Great, glad to know it will work in your prod environment. I added a note to the CodeSandbox example stating this issue. I'll also add something to the README about it. It's not something we can solve since the `iframe` blocks access to the parent element.

Are you able to set the `title` of the `iframe` in Storybook? That might allow it to pick-up the right value.

**Comment by cbix** [comment]
> Are you able to set the `title` of the `iframe` in Storybook? That might allow it to pick-up the right value.

Well it's the same behavior as in Codesandbox. The component inside the iframe sets its own title, but the PDF printing filename will still be derived from the parent window, which is not accessible from the component.

**Comment by MatthewHerbst** [comment]
True 😢 I guess if you have access to the parent you could manually change and then restore the parent document's title using `onBeforeGetContent` and `onAfterPrint` but that's certainly not ideal.

**Comment by MatthewHerbst** [comment]
Added this to the README:

> `documentTitle` will not work if `react-to-print` is running within an `iframe`. If `react-to-print` is running within an `iframe` and your script has access to the parent document, you may be able to manually set and then restore the parent document's `title` during the print. This can be done by leveraging the `onBeforeGetContent` and `onAfterPrint` props.
