### ISSUE TITLE
Page numbers

### ISSUE THREAD

**Issue by rabbittheory** [MatthewHerbst/react-to-print#322]
Hello,
Is there a way to understand or even predict how many pages the print is going to be before kicking off the job. My content height is dynamic and I need to include the page numbers inside the component before render somehow. Thank you.

**Comment by MatthewHerbst** [comment]
Hi there. There is no way to do this with JavaScript unfortunately. There may be a solution using CSS though.

See [this SO question](https://stackoverflow.com/questions/20050939/print-page-numbers-on-pages-when-printing-html) for more details. I think you should be able to do what you want. Please let me know if you run into issues with that.

**Comment by YahyaProg** [comment]
hi,
i have a problem
When I want to print, two pages are printed instead of one page
A page containing the desired content
and a blank page

**Comment by YahyaProg** [comment]
![image](https://user-images.githubusercontent.com/109727350/210340753-9ccfaa14-07df-4fcf-a1bd-0474a4ba3c60.png)
