### ISSUE TITLE
print window is not opening on Firefox.

### ISSUE THREAD

**Issue by shridharbennisur** [MatthewHerbst/react-to-print#33]
print window is not opening on Firefox.

**Comment by gregnb** [comment]
Try the new beta version which is going to rely on an iframe to solve the cross origin issues some people are experiencing.

```
npm install react-to-print@2.0.0-beta-3
```

and let me know the feedback if this solves issues

**Comment by LazarLidia** [comment]
Hello, I have the same problem on Firefox and I installed react-to-print@2.0.0-beta-3. It still doesn't work.

**Comment by gregnb** [comment]
Which version and OS?

**Comment by LazarLidia** [comment]
I tested on Linux, Ubuntu 16.04.3 LTS distribution;

**Comment by gregnb** [comment]
Which version of Firefox?

**Comment by LazarLidia** [comment]
Firefox Quantum version: 61.0.1 (64-bit), tested on Linux and on Windows also.

**Comment by gregnb** [comment]
try installing:

```
npm install react-to-print@2.0.0-beta-4
```

**Comment by LazarLidia** [comment]
I'm sorry but your suggestion didn't help me. The print file doesn't open on Mozilla. I don't have any error but it just doesn't work. (with the last version of react-to-print@2.0.0-beta-4 I tested only on Linux, I didn't try on Windows but probably will be the same behavior) Thanks for you trying.

**Comment by gregnb** [comment]
This is me testing the lastest Firefox with this link here: https://codesandbox.io/s/vj843ljyk3

I'm on a Mac. I'll give different OS a shot later. Can you let me know the results of that link for you?

![screen shot 2018-07-20 at 9 35 23 am](https://user-images.githubusercontent.com/19170080/43005256-533440e4-8c00-11e8-9123-47b72da4ba7a.jpg)

**Comment by LazarLidia** [comment]
Hey, indeed your example works. I tested on Linux / Mozilla. There are some issues, you can see them in the first screenshot, but after a few seconds the print dialog appears well. So.. I don't know why my print button doesn't work on Mozilla. I see there a react version difference but I don't think is that.. I'm using "react": "^15.5.4";

![mozillapdf1](https://user-images.githubusercontent.com/14886213/43007117-1a016262-8c40-11e8-96fb-0517a406125a.png)

![mozillapdf](https://user-images.githubusercontent.com/14886213/43007143-23de7ed2-8c40-11e8-9ac2-5507eaf8cea7.png)

**Comment by gregnb** [comment]
@LazarLidia Have you been able to figure it out? i can't trigger your error

**Comment by Okami92** [comment]
@gregnb Hello. for some reason, after build I am having this error: http://prntscr.com/kaszq7

Do you know what it could be?

**Comment by maloun96** [comment]
that's because the print button is above the trigger button.
Please add a` ref="print"` and than when user click print add  `this.refs['print'].triggerRef.click();`
```js
<Button type="primary" className={'modal-print-button'} onClick={() => this.print()}>
  <div>
    <ReactToPrint
      trigger={() => <div href="#" style={{color: '#fff', width: '100%'}}>Print</div>}
      content={() => this.componentRef}
      copyStyles={true}
      ref="print"
    />
   <div style={{display: 'none'}}>
      <PrintTemplate ref={el => (this.componentRef = el)} />
    </div>
  </div>
</Button>
```

And in this.print() method add this code 
`
if(this.refs['print'])
      this.refs['print'].triggerRef.click();
`

**Comment by jindal1982** [comment]
Still not working Print window in firefox

In 1.0.1 version, working fine https://codesandbox.io/s/6n0mo326mz

but after 2.0 version, not working https://codesandbox.io/s/kmmw7l39y7

**Comment by MatthewHerbst** [comment]
@jindal1982 this is now being tracked in https://github.com/gregnb/react-to-print/issues/93
