### ISSUE TITLE
Print without background and font color and style

### ISSUE THREAD

**Issue by Nicolerobinn** [MatthewHerbst/react-to-print#330]
Background images and font styles are not displayed when printing
![image](https://user-images.githubusercontent.com/48322373/102185036-6654c400-3eeb-11eb-914a-1def11e97e84.png)
![image](https://user-images.githubusercontent.com/48322373/102185169-9734f900-3eeb-11eb-9ca4-b08847db13fc.png)

This is how I use React -to-print in the components

![image](https://user-images.githubusercontent.com/48322373/102185523-204c3000-3eec-11eb-90c7-414d42fcc9ab.png)
background use this method
`<div style="background-image: url("xxxxxxxxxxxx");" ></div>`

**Comment by MatthewHerbst** [comment]
Most browsers do not print background images by default, and instead require the user to select "Background graphics" as an option in the print dialog. Unfortunately, it is not possible for `react-to-print` to select this setting for the user.

This is what that looks like on Chrome (see bottom right of image):

<img width="1209" alt="Screen Shot 2020-12-15 at 2 47 35 AM" src="https://user-images.githubusercontent.com/1287375/102186151-2efcfd80-3e80-11eb-9acd-7d0741fd39b8.png">

**Comment by Nicolerobinn** [comment]
> 大多数浏览器默认都不打印背景图像，而是要求用户在“打印”对话框中选择“背景图形”作为选项。不幸的是，无法为`react-to-print`用户选择此设置。
> 
> 这是在Chrome上的外观（参见图片右下角）：
> 
> <img alt="屏幕快照2020-12-15 at 2 47 35 AM" width="1209" src="https://user-images.githubusercontent.com/1287375/102186151-2efcfd80-3e80-11eb-9acd-7d0741fd39b8.png">

 I know and  the font style is not displayed, so why not

**Comment by MatthewHerbst** [comment]
Are you using a custom font? If so you need to pass the fonts into the `fonts` prop

**Comment by Nicolerobinn** [comment]
> 您使用的是自定义字体吗？如果是这样，则需要将字体传递到`fonts`道具中



> Are you using a custom font? If so you need to pass the fonts into the `fonts` prop

**Comment by Nicolerobinn** [comment]
> > Are you using a custom font? If so you need to pass the fonts into the `fonts` prop

It's not the font, it's the style of the font like color font-weight that doesn't appear when you print it

**Comment by MatthewHerbst** [comment]
Can you share your styles and how you apply them please? Ideally make a working [codesandbox](http://codesandbox.io/)
