### ISSUE TITLE
Remove or Skip the Dialog

### ISSUE THREAD

**Issue by isninja** [MatthewHerbst/react-to-print#332]
I am using the React-To-Print package on my Electron.js project.
When I click the Print button, App shows a dialog. I'd like to print without this dialog.
How can I remove this dialog?

Thanks

![image](https://user-images.githubusercontent.com/59780816/102334769-727d6780-3f65-11eb-828b-da86cf43d6b3.png)

**Comment by MatthewHerbst** [comment]
Hello. See the docs for the `print` prop which lets you specify how printing should happen. There is a partial example of how to use that here: https://github.com/Ririshi/react-to-print/blob/print-replacer-example/example/ElectronPrint/electron/electron.js

**Comment by MatthewHerbst** [comment]
Working Electron example with how to print using `react-to-print` is now available! https://stackoverflow.com/questions/68751490/electron-print-iframe-given-reference-to-it

**Comment by Prashantnale** [comment]
electron js print priview code
