### ISSUE TITLE
page-break-inside does not work as expected

### ISSUE THREAD

**Issue by ChristopherHauschild** [MatthewHerbst/react-to-print#333]
The page-break-inside rule does not work as expected in some components. Even defining the display as table or inline-block, some components continue to break its internal content between pages. The curious thing is that in a more extensive list, the same component has different behaviors, working correctly in some cases and breaking the internal content between pages in others, in addition to defining margins randomly (usually on the final pages).
As I found in other issues, the parent component and the child component are with 'position: relative'. Below is an example of the properties I used in the class.

`.no-page-break {
   display: inline-block;
   width: 100%;
   page-break-inside: avoid;
}`

I have also defined overflow: initial, in addition to having already used the -webkit-region-break-inside: avoid. Is there a possible reason for the same component to behave differently between pages?

**Comment by MatthewHerbst** [comment]
Hello. I can't say I'm a CSS expert, but if you could post a working copy of your code (such as in a codesandbox) that would be very helpful for debugging

**Comment by ChristopherHauschild** [comment]
> Hello. I can't say I'm a CSS expert, but if you could post a working copy of your code (such as in a codesandbox) that would be very helpful for debugging

**Comment by ChristopherHauschild** [comment]
> Hello. I can't say I'm a CSS expert, but if you could post a working copy of your code (such as in a codesandbox) that would be very helpful for debugging

Hello Matthew. Thank you for your attention. I created a sandbox with a sample code that is breaking in print. We used the Antd library in the layout, so the use of Row and Col. I have already tested inserting the code to not allow page breaks in both Row and Col. In the application we have a listing of this Item component. In the first pages the rule works accordingly, but in the last pages, the component breaks internally.

Link: https://codesandbox.io/s/empty-river-rgob2?file=/src/App.js

**Comment by ChristopherHauschild** [comment]
> > Hello. I can't say I'm a CSS expert, but if you could post a working copy of your code (such as in a codesandbox) that would be very helpful for debugging
> 
> Hello Matthew. Thank you for your attention. I created a sandbox with a sample code that is breaking in print. We used the Antd library in the layout, so the use of Row and Col. I have already tested inserting the code to not allow page breaks in both Row and Col. In the application we have a listing of this Item component. In the first pages the rule works accordingly, but in the last pages, the component breaks internally.
> 
> Link: https://codesandbox.io/s/empty-river-rgob2?file=/src/App.js

@MatthewHerbst

**Comment by MatthewHerbst** [comment]
Hi @ChristopherHauschild sorry for the delayed response I've been pretty heads-down at work the last few days. I'm looking at your example but I don't see a print button anywhere? I don't even see `react-to-print` in the dependencies of that codesandbox project?

**Comment by ChristopherHauschild** [comment]
> Hi @ChristopherHauschild sorry for the delayed response I've been pretty heads-down at work the last few days. I'm looking at your example but I don't see a print button anywhere? I don't even see `react-to-print` in the dependencies of that codesandbox project?


Hi @MatthewHerbst ! Okay, thanks again for your attention. I apologize for the misunderstanding, I had created just one example of one of the components used in printing and which presents the problem of breakage. I updated by inserting the library `react-to-print` in the project. I created a file with false data to simulate component looping in the document. However, I was unable to find the correct class to insert the `page-break-inside: avoid` rule without the component still breaking internally. I tried to add both the `id: item-container` element and the `className: item` element, but it does not work as expected. Eventually, in the cases where it works, on the last pages, when the looping gets bigger, the component breaks.
I write in the hope that it can shed light on this behavior. I am in doubt if it can be due to the native method window.print or be related to the Antd Design library.

**Comment by ChristopherHauschild** [comment]
Here is the link: https://codesandbox.io/s/to-print-rgob2?file=/src/example/index.js

**Comment by MatthewHerbst** [comment]
The issue is your `item-container` style. `display: flex` needs to be overwritten. 

If you add the following to your `@media print{}` query I'm able to put each item on its own page no problem:

```css
  .item {
    page-break-after: always;
  }

  #item-container {
    display: block;
  }
```

**Comment by ChristopherHauschild** [comment]
> The issue is your `item-container` style. `display: flex` needs to be overwritten.
> 
> If you add the following to your `@media print{}` query I'm able to put each item on its own page no problem:
> 
> ```css
>   .item {
>     page-break-after: always;
>   }
> 
>   #item-container {
>     display: block;
>   }
> ```


Thanks again for your attention. This worked, but it is not what I need. I apologize if I have not been clear. The problem is this: in the system, the user will be able to select the information he wants to print for each profile. One option is to select a list with relationship components, just like the example I sent. If the user selects only to print this list, everything happens accordingly, `page-break-inside: avoid` works as expected and does not allow the component to break between pages. But, if the user selects to print more information, that list of relationships ends up being on the final pages. When this happens, `page-break-inside: avoid` does not work as expected, and in addition to the component breaking between pages, it receives` margin` at random.

I believe the problem is in the browser's native `window.print ()`. It is easier to have this control when you want to print only `table` components or text and images, but with entire components being printed, in a customized way, I believe it becomes difficult for the browser to have control over the break between pages.
I write in the hope that you have already witnessed a situation like this and then manage to shed some light on me.

**Comment by MatthewHerbst** [comment]
So, it sounds like you just have more data than can fit on the page, and the browser has to break? Have you tried changing the format/font-size/line-size during printing to see if you can fit more information on the page? There's no way to completely stop page breaks if the information gets too long, the printer knows how long the physical piece of paper is that you will be printing to (or the PDF equivalent). You could increase the page size if needed, though you would need to know ahead of time what that should be

**Comment by AyaIsmeal** [comment]
![332](https://github.com/gregnb/react-to-print/assets/119849186/afbd74a4-d620-4ad3-b179-08e55ef997d0)
how to prevent case of happened ? divide row in two page !!!!!!!!!!!!
@MatthewHerbst

**Comment by MatthewHerbst** [comment]
@AyaIsmeal wrap the row container with a CSS class that has a [page-break](https://github.com/gregnb/react-to-print#page-breaks) property specified

**Comment by FahadWebDev** [comment]
> @AyaIsmeal wrap the row container with a CSS class that has a [page-break](https://github.com/gregnb/react-to-print#page-breaks) property specified

Hey @MatthewHerbst , I'm having the same issue which @AyaIsmeal shared. Can you please share any codepen with your solution? It will be really helpful.

**Comment by MatthewHerbst** [comment]
I don't have anything that I remember. If you could make your own showing the problem I'm happy to take a look

**Comment by FahadWebDev** [comment]
> I don't have anything that I remember. If you could make your own showing the problem I'm happy to take a look

Thanks for the quick response, we can use the @ChristopherHauschild example.
Here: https://codesandbox.io/s/empty-river-rgob2?file=/src/example/toPrint.css
I want to avoid these cutting between pages where I want to print my all content as single page.
I applied your solution which you shared but got no success.

<img width="534" alt="Screenshot_1" src="https://github.com/MatthewHerbst/react-to-print/assets/60930720/2835e78a-c47b-4c48-aca6-318d9f07adcb">

**Comment by MatthewHerbst** [comment]
Here is the above fixed: https://codesandbox.io/p/sandbox/to-print-forked-6vvc8f?file=%2Fsrc%2Fexample%2Findex.js%3A21%2C45

Instead of `page-break-after: avoid;` I added `break-inside: avoid;`

**Comment by FahadWebDev** [comment]
> break-inside: avoid;

Not able to check the sandbox :(
Is there any permission issues?

![image](https://github.com/MatthewHerbst/react-to-print/assets/60930720/4db73bd7-5c13-4674-bc2c-861e199fc075)

**Comment by MatthewHerbst** [comment]
Try now please: https://codesandbox.io/p/sandbox/to-print-forked-q9zhl3

**Comment by FahadWebDev** [comment]
> Try now please: https://codesandbox.io/p/sandbox/to-print-forked-q9zhl3

Thanks for sharing, but still it is showing the cut/gap between pages/sheet :(

![image](https://github.com/MatthewHerbst/react-to-print/assets/60930720/27cca707-4196-423e-aa76-9a86e7873118)

**Comment by MatthewHerbst** [comment]
You're printing _pages_, there is always a cut between the sheets. The fix I have above stops the content from being split incorrectly.

**Comment by FahadWebDev** [comment]
> You're printing _pages_, there is always a cut between the sheets. The fix I have above stops the content from being split incorrectly.

Ohh my bad, I didn’t understand the @AyaIsmeal's issue completely. Thanks for the assistance.

my concern was the gap/cut between sheets. I want to print it on single sheet. I have used the react-pdf/renderer(I believe you definitely know it), in this they have the prop called wrap={false} on Page which does the same work which I want.

**Comment by MatthewHerbst** [comment]
Ah. We don't have any such feature built in since we don't focus specifically on PDFs. My guess though is that what they are doing is setting the CSS page size to something custom

**Comment by FahadWebDev** [comment]
> Ah. We don't have any such feature built in since we don't focus specifically on PDFs. My guess though is that what they are doing is setting the CSS page size to something custom

Okay, no worries. Thanks for the support. I really appreciate that.
