### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findDOMNode' of undefined     at t.handlePrint (index.js?3a62:2)     at t.handleClick

### ISSUE THREAD

**Issue by pradeepippaguntaspv** [MatthewHerbst/react-to-print#334]
Uncaught TypeError: Cannot read property 'findDOMNode' of undefined
    at t.handlePrint (index.js?3a62:2)
    at t.handleClick

Getting error when I am trying to use in functional component that is wrapped with one higher-order component and redux.

I can able to print the current ref.

but getting an error "TypeError: undefined is not an object (evaluating 'i.findDOMNode')"

<img width="818" alt="Screenshot 2020-12-22 at 2 47 41 PM" src="https://user-images.githubusercontent.com/22342573/102871692-ba6c2500-4464-11eb-9f7e-4915789ba9cf.png">

**Comment by MatthewHerbst** [comment]
Hello. Could you please share an example (or ideally a working codesandbox) of your code?

**Comment by MatthewHerbst** [comment]
We import `findDOMNode` from `react-dom` (which is listed as a `peerDependency`). Only reason I can think that this error would show up is if your `react-dom` import has an issue.
