### ISSUE TITLE
Can not image tag <img onError={} />

### ISSUE THREAD

**Issue by tikthanawat** [MatthewHerbst/react-to-print#339]
The problem arises in the **chome browser**.

<img src = {imgSrc} **onError = {handleErrorImage}** alt = "product-img" />

prop onError cannot display images in response to print
** Note it works normally in html web page 1st image.
But does not display the image when printing the 2nd image.

![1](https://user-images.githubusercontent.com/67634370/105029075-729ce580-5a84-11eb-8852-f61375b4b29b.jpg)
image1
![2](https://user-images.githubusercontent.com/67634370/105029092-7892c680-5a84-11eb-8d64-13509a3c86b0.jpg)
image2

**Comment by MatthewHerbst** [comment]
Hello. Any chance you could make a codesandbox showing the issue? It's hard to debug otherwise. Thank you
