### ISSUE TITLE
Print not working in IE11 (

### ISSUE THREAD

**Issue by Carrasqueira-Creator** [MatthewHerbst/react-to-print#341]
Hi, first of all, thank you for this amazing library!
I was using it for IE11 and i'm currently having an issue related with the print functionality.
I'm using the hook useReactToPrint and i get the following error when the hook resolves:

"Object doesn't support property or method 'append'".

From looking at the library code, this method is being called from the body of an iframe, so i'm not being able to add a polyfill to fix this. 
There are multiple calls to "appendChild" from the iframe body, and one for the "append", and by updating it to "appendChild", this issue gets solved since the iframe body recognizes the "appendChild" method.
There was a reason to have the "append" method called that i'm not aware of?

Thank you!

**Comment by MatthewHerbst** [comment]
Hello, thanks for reporting this. Not sure why `append` was used instead of `appendChild`. I'll test out converting it to `appendChild` and will make that change if everything works. In the meantime, you should be able to polyfill `append` in IE 9+: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append#polyfill

**Comment by Carrasqueira-Creator** [comment]
Hi @MatthewHerbst. Thank you for your quick reply!
Yes, i've tried that polyfill, but unfortunately, the iframe element is different from an html element as described here: 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement
The polyfill doesn't work because the append method was used from the body of the contentWindow/contentDocument, and both of them are read only properties. Passing the HTMLIframe element to the polyfill would only add the method "append" to the HTMLIframe interface, not to the contentWindow/contentDocument property.
I couldn't find a good solution for this issue intead of chaging the method append to appendChild.

**Comment by Carrasqueira-Creator** [comment]
Hi @MatthewHerbst.
Do you have any updates on this issue?

**Comment by MatthewHerbst** [comment]
@Carrasqueira-Creator I've been doing extensive testing locally to ensure everything will work with `appendChild`. `append` and `appendChild` have slightly different behaviors and I want to ensure that changing to `appendChild` will not be a breaking change for any users. I think React saves us a bit here and it won't be a problem, but I want to be 100% sure. I'll have an update/release out later today assuming I don't find any issues

**Comment by MatthewHerbst** [comment]
Published as v2.12.3, please let me know if you run into any additional issues, and thank you for reporting this!

**Comment by Carrasqueira-Creator** [comment]
@MatthewHerbst it is working correctly in IE11 so far, many thanks for your hard work!
