### ISSUE TITLE
documentTitle not working in safari

### ISSUE THREAD

**Issue by WoodenPC** [MatthewHerbst/react-to-print#346]
"react-to-print": "2.9.0"
documentTitle not working in safari
if i call window.print from console in browser, document title is visible in print mode

**Comment by WoodenPC** [comment]
as i workaround i use custom print callback and change frame.contentWindow.document.title property, and its working in both safari and chrome

**Comment by MatthewHerbst** [comment]
Hello. This issue is being tracked in #321 thank you
