### ISSUE TITLE
Can not print new content after changing its values.

### ISSUE THREAD

**Issue by yoshifumi4423** [MatthewHerbst/react-to-print#348]
Hello.
Thank you for developing great package!
I recently started to use this, and I got stuck with problem about title.
Could you help me to find solution.

**Expected result**
Component can print  `<ChartToPrint />` with updated `reportHeader` props.

**Current result**
After passing new props, component can not print `<ChartToPrint />` with updated `reportHeader` props but old `reportHeader` props.

**Sample**
```ts
  const componentRef = React.useRef(null);
  const onBeforeGetContentResolve = React.useRef(Promise.resolve);

  const [loading, setLoading] = React.useState(false);
  const [text, setText] = React.useState("text");

  const handleAfterPrint = React.useCallback(() => {
    console.log("`onAfterPrint` called");
  }, []);

  const handleBeforePrint = React.useCallback(() => {
    console.log("`onBeforePrint` called");
  }, []);

  const handleOnBeforeGetContent = React.useCallback(() => {
    setLoading(true);
    setText("Loading new text...");

    return new Promise((resolve: any) => {
      onBeforeGetContentResolve.current = resolve;

      setTimeout(() => {
        setLoading(false);
        setText("New, Updated Text!");
        resolve();
      }, 2000);
    });
  }, [setLoading, setText]);

  const reactToPrintTrigger = React.useCallback(() => {
    return (<Button
      className="print-report-button ltr-spn-def"
      type="primary"
      loading={loading}
      icon={<img src="/icons/print.png" />}
      disabled={disablePrint}
      size="large">Print</Button>
    )
  }, [useState(loading)]);

  return (
    <div>
      <ReactToPrint
        content={() => componentRef.current}
        documentTitle="TestPrint"
        onAfterPrint={handleAfterPrint}
        onBeforeGetContent={handleOnBeforeGetContent}
        onBeforePrint={handleBeforePrint}
        removeAfterPrint
        trigger={reactToPrintTrigger}
      />
      <div className="printer-dom">
          <ChartToPrint
            ref={componentRef}
            reportHeader={reportHeader} />
      </div>
    </div>
  );
```

Thank you.

**Comment by MatthewHerbst** [comment]
Hi @yoshifumi4423 could you share please how `ChartToPrint` works, or ideally make a working codesandbox with an example showing the problem? Thank you.

One thing I did notice, the dependency array for `reactToPrintTrigger` callback seems wrong. I think it should be `[disablePrint , loading]`, not `[useState(loading)]`

**Comment by yoshifumi4423** [comment]
@MatthewHerbst 
Thank you for your advise.
I solved this problem.
This was caused by my code, not `react-to-print`.

I checked below things.
1. I fixed `useCallback` as you mentioned.
2. I fixed `<ChartToPrint />`. In this component, re-render process didn't work. After fixing re-render process, it prints updated `reportHeader` props.
