### ISSUE TITLE
Images fetched  are not showing in function components

### ISSUE THREAD

**Issue by clevermatem** [MatthewHerbst/react-to-print#349]
Hello sir, 
thank you for this awesome library.
My issue is: I am trying to print a function component that contains 3  images 1 is local and shown correctly, 2 fetched from my s3 aws, they don't appear when I try to print them: 
this is my toPrintComponent : 

```
import React from "react";
import reportLogo from "../../../assets/report/reportlogo.png";
import {
  Box,
  Card,
  Container,
  Grid,
  makeStyles,
  Typography
} from "@material-ui/core";
export const FMRPage01 = React.forwardRef((props, ref) => {
  const classes = useStyles();

 return (
    <Container className={classes.root} ref={ref}>
      {/* THIS IMAGE IS SHOWING CORRECTLY*/}
      <img
        className={classes.vipLogo}
        src={reportLogo}
         alt="logo"
        loading='lazy'
      />

      {/* THESE 2  IMAGES ARE NOTTTT SHOWING CORRECTLY*/}

    <Grid container>
        <Grid xs={12} sm={6}  item>
          <Card className={classes.cardImg}>
            <img
              className={classes.img}
              src={props.fullInfo.book_cover}
              alt="book_cover"
              loading='lazy'            />
          </Card>
        </Grid>
        <Grid xs={12} sm={6}  item>
          <Card className={classes.cardImg}>
            <img
              className={classes.img}
              src={props.fullInfo.first_page}
              alt="first_page"
              loading='lazy'            />
          </Card>
        </Grid>
      </Grid>
    </Grid>

    </Container>
  );
});
```

and this is the component containing the CAT button: 

```
export default function Report({ fullInfo }) {

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  });
  return (
   <Button onClick={handlePrint}>Print this out!</Button>

      <FMRPage01
        fullInfo={fullInfo}
        profileData={profileData}
        ref={componentRef}
      />
 
  );
}
```

What is causing the issue? and is there a solution? 
Cordially,

**Comment by MatthewHerbst** [comment]
Hi there, thanks for using the library and for writing in. Any chance you could share a codesandbox showing the issue, or just give the me the urls of the images so I can test them? We should be waiting for all images to load before printing

**Comment by clevermatem** [comment]
Hello sir, 
thank you for your response, 
this is a sandbox showing the issue, 
https://codesandbox.io/s/strange-leavitt-772fr?file=/src/FMRPage01.js

if you don't scroll to the image and click print the images won't be fetched  the first time, but they are fetched when you click close and print again, 
everything is fixed by removing lazy loading, but I prefer keeping it because the report I want to print is large and contains a lot of photos,

**Comment by MatthewHerbst** [comment]
> fixed by removing lazy loading

We can't print what's not on the page 😄 

Take a look at the `onBeforeGetContent` prop. You should be able to use that to perform a full render of the page before printing occurs.

**Comment by clevermatem** [comment]
Ah ok my bad, 
Closing the issue 😅
