### ISSUE TITLE
Question: Changing the style of the Document

### ISSUE THREAD

**Issue by nonoumasy** [MatthewHerbst/react-to-print#352]
I have a React app which has pages like this: 
<img width="629" alt="Screen Shot 2021-03-25 at 2 09 01 AM" src="https://user-images.githubusercontent.com/6312676/112447965-22096900-8d0f-11eb-890a-28ab180db889.png">

I would like to keep some of the elements on the page, leave some out and restyle it. 
What would be the best way to achieve this with this library?
Would I need to create a different version of the page?

The screenshot would be the style I am going for.
![A4 - 4](https://user-images.githubusercontent.com/6312676/112447790-eec6da00-8d0e-11eb-8d0e-f1192487bcda.png)

The site is here: https://www.history-maps.com/story/t4jxOvc2j2WSqtLEk66z

**Comment by MatthewHerbst** [comment]
Hi @nonoumasy you have two options. The first is to just create a second version of the page in React, and then use `onBeforeGetContent` to render that component for printing. The second option would be to use CSS to achieve what you want, using a mix of `@media print {}` and `display` styles. Inside of the `@media print {}` query you would modify the CSS as needed to hide things you don't want to show, show things that are normally hidden, and change any other styles you need to change. I hope that helps. Please let me know if I can provide any further assistance, and thanks for using the library!

**Comment by nonoumasy** [comment]
@MatthewHerbst Thanks for replying.
I tried the second option and got it to almost to a point where its good enough. However, I've reached my limits as far as print css styling. I can't seem to get rid of the page breaks . I've tried every combination I can think of in @media print. Also, I am using MUI styles and I was able to hide some components. I just can't seem to get rid of the blank spaces.

Here is a pdf sample:
[History Maps.pdf](https://github.com/gregnb/react-to-print/files/6213687/History.Maps.pdf)

**Comment by MatthewHerbst** [comment]
Does [this section from the README](https://github.com/gregnb/react-to-print#page-breaks) help at all? It's hard for me to help debug without seeing the code unfortunately, though I do see the page breaks in the PDF

**Comment by nonoumasy** [comment]
@MatthewHerbst thanks again for replying. I used the code from the README however I still get those darn page breaks.  :)
The following is what I added to my index.css. 


```
/* pdf styling */
@media print {
  * {
    box-shadow: none !important;
    text-shadow: none !important;
    background: transparent !important;
    color: #000 !important;
    -webkit-print-color-adjust: exact;
  }

  p {
    orphans: 3;
    widows: 3;
  }
}

@page {
  size: auto;
  margin: 3cm;
}

```

**Comment by MatthewHerbst** [comment]
Hi @nonoumasy sorry for the delayed response. Any chance you can make a minimal reproduction on codesandbox or something where I can play with the code? Extremely difficult to help debug otherwise. It might also be good to cross-post this question to StackOverflow since it's almost certainly CSS related
