### ISSUE TITLE
Print multi pages with header and footer

### ISSUE THREAD

**Issue by hussenIbrahim** [MatthewHerbst/react-to-print#353]
I am trying to print multi pages with header and footer  , I found this [example ](https://plnkr.co/edit/lWk6Yd?preview)  it works fine until change the header height to 450px , the first page is fine , but the content  of  next pages is covered by the header

**Comment by MatthewHerbst** [comment]
Hi @hussenIbrahim could you share an example of your code, possibly as a codesandbox? It's very hard to help debug otherwise, thanks

**Comment by hussenIbrahim** [comment]
> Hi @hussenIbrahim could you share an example of your code, possibly as a codesandbox? It's very hard to help debug otherwise, thanks

https://codesandbox.io/s/immutable-morning-gy81p

**Comment by MatthewHerbst** [comment]
Apologies this never got responded to. If you still need help with this please let me know

**Comment by phaxz10** [comment]
anyone solved this?

**Comment by Claire-bk** [comment]
.page {
  page-break-after: page;
}

**Comment by Claire-bk** [comment]
> anyone solved this?

```css
.page {
  page-break-after: page;
}
```
