### ISSUE TITLE
[Chrome] [Adobe Acrobat] Garbage values printed for the pdf encoded on Chrome

### ISSUE THREAD

**Issue by harsha-jay** [MatthewHerbst/react-to-print#354]
This is a pdf saved using print option on Chrome. It has garbage values only when viewed on Acrobat reader. However Firefox generated pdfs do not seem to have this issue.

![image](https://user-images.githubusercontent.com/54434451/114046641-a3800000-98a6-11eb-85e6-5384a5b56bcf.png)

**Comment by MatthewHerbst** [comment]
Hi there. This is almost certainly a font/browser specific issue. Can you share the code you are using to generate the PDF so I can take a closer look? A working codesandbox or similar would be greatly appreciated

**Comment by harsha-jay** [comment]
Hi Matthew, You are correct. I did more testing and extracted a pdf from a normal page and the issue is in that as well. The font is heebo. I have to look into it.

Closing the tickets. Thanks!
