### ISSUE TITLE
Icon fonts are not rendering the icons

### ISSUE THREAD

**Issue by suthanbala** [MatthewHerbst/react-to-print#36]
I have a component rendering icons using fonts. When the print on that component is triggered, it doesn't load the fonts, all the other styles are there, but not the icons

**Comment by gregnb** [comment]
Could you put up a small example repo to look at? I would love to solve this for everyone. Thank you

**Comment by gregnb** [comment]
@suthanbala ?

**Comment by suthanbala** [comment]
@gregnb Sorry been occupied with something urgent. I will prepare a repo or a fiddle as soon as I can.

**Comment by suthanbala** [comment]
Actually I was using the older version. Updated to the latest version, it seems to be working good. Thanks
