### ISSUE TITLE
No text when printing

### ISSUE THREAD

**Issue by Azarians** [MatthewHerbst/react-to-print#360]
sometimes there is no text when I printing my calendar.
[issue.pdf](https://github.com/gregnb/react-to-print/files/6305095/issue.pdf)

**Comment by MatthewHerbst** [comment]
Hello. Could you post a code sample please, or ideally a working codesandbox so I can see the problem?

**Comment by Azarians** [comment]
you can see live demo at https://boomteamcalendar.wixsite.com/for-test
in some cases window.print() works better than react-to-print ( I mean window.print() prints styles better )

**Comment by MatthewHerbst** [comment]
This is what I see when I go to print the calendar (I'm on Chrome 89)
![Screen Shot 2021-04-14 at 11 15 39 AM](https://user-images.githubusercontent.com/1287375/114735194-f0cef800-9d12-11eb-82a0-91791aa8105c.png)
