### ISSUE TITLE
Can not print RTL table columns

### ISSUE THREAD

**Issue by yousefshakoury** [MatthewHerbst/react-to-print#361]
![prob](https://user-images.githubusercontent.com/13915152/115621979-81f23000-a30c-11eb-9bae-87b1c2de6d94.png)
I can not print RTL table columns !!! (the columns orders is changed in print)

**Comment by MatthewHerbst** [comment]
Hi there. Can you please share a working code example of your code that you used to make the page RTL? Thanks
