### ISSUE TITLE
My browsers don't allow the iframe to be printed

### ISSUE THREAD

**Issue by GeorgePasquali** [MatthewHerbst/react-to-print#364]
Hello, I have no idea if this is the place, but I have no idea how to resolve this issue.

 I created a working example with the using the useReactToPrint hook and in a local environment everything works as expected.
 Once I deployed the application though, I get the following error inside my browser console:
 ```
 Ignored call to 'print()'. The document is sandboxed, and the 'allow-modals' keyword is not set
 ```
 This is the error message from chrome, but Firefox and Edge both throw a similar error.
 
I did some digging regarding the cause of this issue and I found out that a possible solution would be to add a sandbox attribute to the printed iframe component. So not knowing how to do that I tried the following

```javascript
const handlePrint = useReactToPrint({
    content: () => ref.current,
    print: async (target: HTMLIFrameElement) => {
      target.setAttribute('sandbox', 'allow-modals allow-forms allow-popups');
      if (target.contentWindow.print) {
        target.contentWindow.print();
      }
    },
  });
```
again, this solution works on a local environment, but after I deploy this it doesn't work anymore.
Does anyone know if this is an issue with the version of the library i'm using or whether i'm doing something wrong setting it up?

**Comment by MatthewHerbst** [comment]
Hi there. That's very interesting. It makes me wonder if your entire web app is possibly being run inside an iframe when deployed?

Any chance you could share the DOM structure of your page?

Also, so I can mimic your environment, what version of Chrome are you using?

**Comment by GeorgePasquali** [comment]
Sure, Here is a screen of my DOM tree:
![image](https://user-images.githubusercontent.com/23388713/117023939-3b380900-ad02-11eb-8153-b6b238c6531b.png)

I have tested this with Firefox(v 88.0) and Chrome (90.0.4430.93 (Official Build) (64-bit))

And I am relatively sure there are no other iframes in my app. I am using a pretty standard next.js setup.

**Comment by GeorgePasquali** [comment]
Okay, I feel a little dumb, but I found what caused the issue.
I noticed that my nginx was serving the page with a security header, which looked like this:
![image](https://user-images.githubusercontent.com/23388713/117031671-7db11400-ad09-11eb-8ef7-51fba8cbb950.png)

I added the allow-modals property to the content-security-policy security header and now it all works:
![image](https://user-images.githubusercontent.com/23388713/117032095-e39d9b80-ad09-11eb-8714-b08b23023f3e.png)

Thanks for the quick response, feel free to close/remove this and sorry for wasting your time.

**Comment by MatthewHerbst** [comment]
Glad you were able to figure it out! Always good to have documented errors so when the next person comes looking they will hopefully find this. 😄
