### ISSUE TITLE
Can I export more than 1 page ?

### ISSUE THREAD

**Issue by jcsouz10** [MatthewHerbst/react-to-print#365]
Hi guys..

I liked the library but I need to export more than 1 page.

For example:

I have two components in different places and they are not on the same page.

Is there any way to do that?

**Comment by MatthewHerbst** [comment]
Hello. So when you print you want both components to show up in the print, or you want to have a separate print for each of them?

**Comment by jcsouz10** [comment]
> Hello. So when you print you want both components to show up in the print, or you want to have a separate print for each of them?

Hiii, I want both components at the same print.

**Comment by MatthewHerbst** [comment]
So, you have two equally good options. The first is that you could simply hide everything else using

```css
@media print {
  .dontPrintMe {
    display: none;
  }
}
```

Another alternative is that, during the print, you could modify the JSX of the page:

```js
<ReactToPrint
  onAfterPrint={() => this.setState({ printing: false })}
  onBeforeGetContent={() => {
    return new Promise((resolve, reject) => {
      // Modify the page here, for example, by setting state:
      this.setState({ printing: true }, resolve);
    });
  }}
  ...
/>
```

**Comment by jcsouz10** [comment]
> ```css
> @media print {
>   .dontPrintMe {
>     display: none;
>   }
> }
> ```

NICE, thank so much... I did the opposite. I put my component as `none` and when I go to print, I put it as `flex` ahahha, but worked as expected... <3

**Comment by MatthewHerbst** [comment]
Glad you got it working! Please let me know if you run into any other issues
