### ISSUE TITLE
Controlling window properties (fullscreen, toolbar etc.)

### ISSUE THREAD

**Issue by codesignist** [MatthewHerbst/react-to-print#37]
Can we control all of the window parameters? I think this will be useful.
Actually I only need fullscreen property but controlling the other properties could be good.

https://github.com/gregnb/react-to-print/blob/f03aa02caf9a871b9cbf90e9a3c5d1a09fa4f144/src/index.js#L59

I think we could make an object property **(windowParams)** and override it.

```JavaScript
class Example extends React.Component {
  render() {
    return (
      <div>
        <ReactToPrint
          windowParams={{
            fullscreen: 'yes',
          }}
          trigger={() => <a href="#">Print this out!</a>}
          content={() => this.componentRef}
        />
        <ComponentToPrint ref={el => (this.componentRef = el)} />
      </div>
    );
  }
}
```
And we could convert this object to string.
**index.js**
```JavaScript
const windowParameters = {
  status: 'no',
  toolbar: 'no',
  scrollbar: 'yes',
  ...windowParams
}
//Need a good stringify algorithm or npm project
let printWindow = window.open("", "Print", windowParameters.stringifyProperly(), "false");
```

What do you think?

**Comment by gregnb** [comment]
@codesignist It sounds reasonable but I am hoping to get away from the older implementation done via a window popup and rely on the iframe one i created in the beta release. A lot of people have cross origin issues I would love to resolve with that

**Comment by codesignist** [comment]
What about only controlling fullscreen property?
Because I need it so much.
