### ISSUE TITLE
(Pagebreak/Paginated style issues) 分页样式问题

### ISSUE THREAD

**Issue by longgegege** [MatthewHerbst/react-to-print#370]
```jsx
return (
    <section style={{ display: 'flex', flex: 'auto' }} ref={componentRef}>
        <Button
            onClick={() => {
                handlePrint()
            }}
            className={styles.m_r_bt_s}
        >
            打印
        </Button>
        <div id="page1" style={{ pageBreakAfter: "always" }}>
            第一页打印内容
        </div>
        <div id="page2">
            第一页打印内容
        </div>
    </section>
);
```
1，在react项目中使用react-to-print组件，在样式中使用了`style={{ pageBreakAfter: "always" }}`但是没有分页效果？请问如何解决

**Comment by Migueacalle98** [comment]
Translation:
**Paginated style issues**
Using the react-to-print component in a react project, using `style={{ pageBreakAfter: "always" }}`, but no paging effect? May I ask how to solve it

**Comment by MatthewHerbst** [comment]
Apologies for the massively delayed response to this. There is a pagebreak section in the README. Please let me know if that helps. Otherwise, please show more code, specifically how you call react-to-print
