### ISSUE TITLE
window print events not fired when using react to print

### ISSUE THREAD

**Issue by psevery** [MatthewHerbst/react-to-print#371]
Hi All,

I am printing out an analytics page with react to print, and over all it is working very well. The only issue I am having is that the window beforeprint event is not being fired. When I instead just call window.print, it is fired. 

I understand that I could potentially use onBeforeGetContent, but the element I would like to modify (resize in JS) is deeply nested underneath my print content element. 

Thanks so much!

**Comment by MatthewHerbst** [comment]
Hi there. Do you mind sharing a little bit of code that shows this off please, maybe in a codesandbox? Also, what browser are you using?

**Comment by psevery** [comment]
I have tried both on firefox, and chrome. While I get familiar with code sandbox I will give an overall look of the structure of the elements in case that is helpful, thanks so much for the fast reply!

analytics.js
```
...
const printRef = useRef();
const handlePrint = useReactToPrint({
    content: () => printRef.current,
  });

const print = () => {
  handlePrint();
};

return (
<Grid container className={classes.grid} ref={printRef} >
 <Grid item>
   <IconButton onClick={print} color="primary" className={classes.printButton}>
     <Print fontSize="large"></Print>
   </IconButton>
 </Grid>
 ... many visualizations elements on cards, which luckily can be sized with css
 <Grid item>
   <Paper className={classes.paper}>
     <PressureMetrics />
   </Paper>
 </Grid>
</Grid>
)
```

PressureMetrics.js (uplot requires sizing in js)
```
...
  window.addEventListener('beforeprint', (e)=>{ 
    console.log('before print event!'); //this does take place when using window.print in analytics.js but not when using handlePrint()
    if (myChart && plotContainer?.current?.offsetWidth) {
      myChart.setSize({
        width: 800,
        height: plotContainer.current.offsetWidth / plotContainer.current.offsetHeight * 800
      });
    }
  });

   window.addEventListener('resize', ()=>{ // this window event works correctly
    if (myChart && plotContainer?.current?.offsetWidth) {
      myChart.setSize({
        width: plotContainer.current.offsetWidth,
        height: plotContainer.current.offsetHeight-85
      });
    }
  });

   return (
    <div tag='my root' ref={plotContainer} className={classes.container}>
      <div className={classes.plot} ref={plotRef} tag='myref' />
    </div>
  );
```

**Comment by psevery** [comment]
Code sandbox: 
https://codesandbox.io/s/interesting-sound-gr0jl

**Comment by MatthewHerbst** [comment]
Ah, I see. `ReactToPrint` creates a hidden iframe to do its printing off of, so any window events would need to be attached to that hidden iframe since no print events are actually occurring against the main window. I suggest defining a custom `print` prop to do what you want, since in that function you can get access to the underlying iframe:

```tsx
  const handlePrint = useReactToPrint({
    content: () => printRef.current,
    print: (iframe) => {
      return new Promise((resolve) => {
        iframe.contentWindow.addEventListener("beforeprint", (e) => {
          console.log("before print");
          setBeforePrint("yes");
        });

        iframe.contentWindow.print();
        resolve();
      });
    },
  });
```

**Comment by psevery** [comment]
Awesome, it seems like the tools are there for me, just need to put them together, ill close.

**Comment by MatthewHerbst** [comment]
Please let me know if you run into any other issues. Thanks for using the package!
