### ISSUE TITLE
Print Content Not Adjusting

### ISSUE THREAD

**Issue by evspice** [MatthewHerbst/react-to-print#372]
I am using this library to take printouts but not able to adjust the content in the table format as per the page selected. The content is getting shrunk instead of adjusting to the page's actual size, which I'm selecting at the time of print preview. I have tried multiple solutions from web but still not helpful

**Comment by MatthewHerbst** [comment]
Hello. Could you please provide ideally a working codesandbox showing the issue?

**Comment by BrenoVelasco** [comment]
I am facing the same issue. Maybe it's something simple but I'm clueless:

<img width="1632" alt="Screen Shot 2021-06-09 at 16 24 47" src="https://user-images.githubusercontent.com/21113340/121416779-92ec1480-c93f-11eb-8441-fe34f2474a95.png">
<img width="2066" alt="Screen Shot 2021-06-09 at 16 25 12" src="https://user-images.githubusercontent.com/21113340/121416792-97183200-c93f-11eb-9937-d98658f6db18.png">
<img width="435" alt="Screen Shot 2021-06-09 at 16 26 23" src="https://user-images.githubusercontent.com/21113340/121416796-97b0c880-c93f-11eb-8476-b50f244a5fa4.png">
<img width="474" alt="Screen Shot 2021-06-09 at 16 26 40" src="https://user-images.githubusercontent.com/21113340/121416801-98495f00-c93f-11eb-9e4a-0339882f11ac.png">

**Comment by MatthewHerbst** [comment]
@BrenoVelasco it clearly looks above to me that the printer viewport is smaller than the page, causing the styles to automatically shrink as if printing on a smaller device. Could you share a working code sample by chance? What style framework do you use? What does `setPrintMode` do?
