### ISSUE TITLE
Problem to understand the doc: landscape printing

### ISSUE THREAD

**Issue by rdhox** [MatthewHerbst/react-to-print#373]
I want to force landscape printing, and I see in your documentation that you have a way explained: 

```
In the component that is passed in as the content ref, add the following:

@media print {
  @page { size: landscape; }
}
```

And I don't understand what you mean... Here what I try to do, which do not work: 

```javascript
  const handlePrint = useReactToPrint({
    content: () => weeklyPrintRef.current,
    pageStyle: `@media print {
      @page { size: landscape; }
    }`
  });
```

thanks!

**Comment by MatthewHerbst** [comment]
Hmm. What browser are you on? Can you try `orientation: landscape;` please?

**Comment by MatthewHerbst** [comment]
Hi @rdhox are you still having issues here?

**Comment by rdhox** [comment]
@MatthewHerbst Seems to not really work. But I think it's more a problem depending of browsers. If the way I done it with the hook is the right way, it is what I wanted to know 👍

**Comment by MatthewHerbst** [comment]
Yes, you have done it correct. And yes, different browsers will do the CSS differently, especially for printing 😢 Please let me know if you have anymore questions
