### ISSUE TITLE
useReactToPrint wont trigger print because of empty src property on img tag

### ISSUE THREAD

**Issue by pabloiea1995** [MatthewHerbst/react-to-print#378]
When handlePrint function (returned by useReactToPrint) is called over a component with an img tag that has an empty string value, the function will no execute and the print dialog will not show, displaying this WARNING message on console:

"react-to-print" encountered an <img> tag with an empty "src" attribute. It will not attempt to pre-load it. The <img> is:

Is this the expected behavior?

Shouldn't this be an error message so that it causes the print function not to work?

Thanks

**Comment by MatthewHerbst** [comment]
This is an expected warning message: https://github.com/gregnb/react-to-print#why-does-react-to-print-skip-link-relstylesheet-href-tags

`img` tags with an empty `src` are not valid HTML. 

Having these should not prevent printing, I'll look into that. But you really shouldn't have any in your DOM.

**Comment by MatthewHerbst** [comment]
This is fixed in the just published v2.12.6. Thanks for using the library and thanks for reporting the bug!
