### ISSUE TITLE
Styles missing in print dialog

### ISSUE THREAD

**Issue by lohiaumang** [MatthewHerbst/react-to-print#382]
Hi, 

I have a component that looks like this - 

![Screenshot 2021-06-05 at 7 50 49 PM](https://user-images.githubusercontent.com/22180193/120894731-97f74e00-c637-11eb-99d8-4a2ca6b06374.png)

But when I print this, I get this in the print dialog - 

![Screenshot 2021-06-05 at 7 51 30 PM](https://user-images.githubusercontent.com/22180193/120894748-a5acd380-c637-11eb-9830-b293ca9c6567.png)

I am using bootstrap grid with react (which uses flexbox). I am using the library like this -

```
const deliveryOrderTableRef =
    useRef() as React.MutableRefObject<HTMLDivElement>;
const printPage = useReactToPrint({
    content: () => deliveryOrderTableRef.current,
    copyStyles: true,
});
```

`<div className="delivery-order-table" ref={ref}>`

**Comment by MatthewHerbst** [comment]
Hello. Could you please make a working codesandbox or similar so I can see the issue and try to debug? I've seen similar issues before and normally what's happening is that bootstrap is thinking the printer is a small viewport and so sizes everything down to `sm` which often throws off styles from what people expect

**Comment by lohiaumang** [comment]
Hi Matthew, I created a project that shows my problem here - https://stackblitz.com/edit/react-f7gtpf?file=src/App.js. Press the `Open in New Window` button to see it on a full browser screen. Let me know if you have any problems viewing it. Thanks for the prompt reply.

**Comment by lohiaumang** [comment]
Hi @MatthewHerbst, any insights into how I can solve this problem will be very helpful. Thank you

**Comment by MatthewHerbst** [comment]
@lohiaumang apologies for not getting back to you. Were you able to solve this?

**Comment by lohiaumang** [comment]
Hi @MatthewHerbst, figured I should make sure that the right styles are being applied at the `xs` screen size. I had the layout designed for the `sm` screen size and above. Just changing `sm` to `xs` solved the issue. Your reply from earlier was quite helpful, thanks 😄 

> Hello. Could you please make a working codesandbox or similar so I can see the issue and try to debug? I've seen similar issues before and normally what's happening is that bootstrap is thinking the printer is a small viewport and so sizes everything down to `sm` which often throws off styles from what people expect
