### ISSUE TITLE
Paper height not working when use POS printers

### ISSUE THREAD

**Issue by MassoudSharifi** [MatthewHerbst/react-to-print#383]
I want to print all of the data on one page with no page break.
when I want to increase the height of the page. margin of that page increasing instead of height
but when using pdf it works correctly

```jsx
class Example extends React.Component {
  render() {
    const pageStyle = `  @page {
      size: 80mm 3276mm;
    }
   `;
    return (
      <div>
        <ReactToPrint
          trigger={() => <button>Print this out!</button>}
          content={() => this.componentRef}
          pageStyle={pageStyle}
        />
        <ComponentToPrint ref={(el) => (this.componentRef = el)} />
      </div>
    );
  }
}
```

**Comment by MassoudSharifi** [comment]
<img width="549" alt="Capture" src="https://user-images.githubusercontent.com/43839019/120919795-ae051d00-c6d0-11eb-9171-cd9095fb77c3.PNG">
<img width="546" alt="Captureddd" src="https://user-images.githubusercontent.com/43839019/120919804-b78e8500-c6d0-11eb-8d2e-9e291c8ad3c0.PNG">

**Comment by MassoudSharifi** [comment]
![Uploading Screenshot 2021-06-06 141046.png…]()

**Comment by MatthewHerbst** [comment]
Hmm. Maybe your printer has a maximum page height?

**Comment by MassoudSharifi** [comment]
@MatthewHerbst
Thanks you are right
