### ISSUE TITLE
Unable to print a long component

### ISSUE THREAD

**Issue by joelethan** [MatthewHerbst/react-to-print#385]
Hi guys...

I like the library a lot however I need to print a long component that goes beyond 1 page.
When I try to print, I only get content that fits on one page then the rest isn't printed.

What do I do to have the rest of the content go to the next pages i.e (page 2, 3 .... )

Thank you in advance 😊 cc. @MatthewHerbst

**Comment by MatthewHerbst** [comment]
Hello. Glad you enjoy the library! Could you please share some code (or ideally, a working codesandbox) that shows the problem? Thank you

**Comment by joelethan** [comment]
It is Okay, I found what my issue was. I had `overflow: hidden;` on my root CSS. My bad. Thank you for your support.
