### ISSUE TITLE
Quality issue on thermal printers

### ISSUE THREAD

**Issue by Exonalex** [MatthewHerbst/react-to-print#392]
when try to print on thermal printer, the text is not defined, and i know is based on antialiasing and other setting that i can't override also by doing -webkit-print-color-adjust: exact; or -webkit-font-smoothing: none; 

For qr code i fixed by convert it into svg.

any solution? or future update?

Thanks

**Comment by MatthewHerbst** [comment]
Hello. I don't have a thermal printer so I can't do any testing here. Is this specific to Firefox? Also, if you could share the full code you use it would be helpful.
