### ISSUE TITLE
Mapped Component - Only shows last mapping

### ISSUE THREAD

**Issue by kagedevelopment** [MatthewHerbst/react-to-print#395]
I have a component that renders multiple times based on the number of entries. When I added the code for react-to-print, it displays the button on all rendered components to print, but when I click print it only displays the last render of the component, not the render where the button resides.

```jsx
cards = () => {
  const final = [];
  for (var i = 0; i < this.state.truckNumber; i++) {
    final.push(
      <Card
        body
        inverse
        style
        style={{
          width: "400px",
          "max-width": "400px",
          borderColor: "#333",
          backgroundColor: "#333",
          "margin-left": "5px",
          "margin-left": "5px",
        }}
      >
        <CardBody>
          <CardTitle tag="h5">
            Truck Build {i + 1}
          </CardTitle>
          <CardText></CardText>
          <ReactToPrint content={() => this.componentRef}>
            <PrintContextConsumer>
              {({ handlePrint }) => (
                <button onClick={handlePrint}>Print this out!</button>
              )}
            </PrintContextConsumer>
          </ReactToPrint>
          <Canvas
            ref={el => (this.componentRef = el)}
            positionalData={this.state.positionalData.filter(truck => truck.truckNumber == i)}
          />
          <Button className="button">Button</Button>
        </CardBody>
      </Card>
    );
```

**Comment by MatthewHerbst** [comment]
Hi, thanks for reporting this. I am able to verify the issue. Looking into why it is happening now

**Comment by MatthewHerbst** [comment]
I found the issue. With every iteration of the loop you are overriding the reference of `this.componentRef`. Make sure to give each element a unique ref:

```jsx
<ReactToPrint content={() => this[`canvasref:${i}`]}>
  <PrintContextConsumer>
    {({ handlePrint }) => (
      <button onClick={handlePrint}>Print this out!</button>
    )}
  </PrintContextConsumer>
</ReactToPrint>
<Canvas
  ref={el => (this[`canvasref:${i}`] = el)}
  positionalData={this.state.positionalData.filter(truck => truck.truckNumber == i)}
/>
```

**Comment by kagedevelopment** [comment]
I changed my code as follows and it is still only showing the last iteration. Did I do something wrong here?

```
     <ReactToPrint content={() => this[`canvasref:${i}`]}>
        <PrintContextConsumer>
            {({ handlePrint }) => (
              <button onClick={handlePrint}>Print this out!</button>
            )}
          </PrintContextConsumer>
        </ReactToPrint>
        <Canvas ref={el => (this[`canvasref:${i}`] = el)}
          positionalData={this.state.positionalData.filter(truck => truck.truckNumber == i)}
        ></Canvas>
```

**Comment by MatthewHerbst** [comment]
Can you show the full code please? Ideally a codesandbox would be best for help debugging

**Comment by kagedevelopment** [comment]
I added you to the repository. The code is on the master branch. Please note that this does not include the backend. The backend is only accessible from our network, so you wont be able to use it.

**Comment by MatthewHerbst** [comment]
@kagedevelopment apologies for the delayed response, I've had to spend the last few weeks focusing on work. I hope to have time this weekend to work on these issues. Could you please re-send the invitation link for the repo? Thank you

**Comment by katherine95** [comment]
@kagedevelopment [kagedevelopment](https://github.com/kagedevelopment) did you manage to get a fix?

I figured, if using functional components, define `componentRef` within the loop
