### ISSUE TITLE
[How to question] Printing hidden component

### ISSUE THREAD

**Issue by barvhaim** [MatthewHerbst/react-to-print#396]
I am trying to achieve the following use-case with React:
I have state `isPrintableAreaShowing` which is false at the beginning, I want to, by button click, render the component <PrintableArea /> (make is visible instead of null) and call print using `react-to-print`, however I have some difficulties.

I tried to use `useReactToPrint` function hook and call it after setIsShow(true);
like 
```
<Button onClick={() => {
          setIsShow(true);
          printHandler();
      }} >Print</Button>
```
however, only on 2nd click and on the button will work, is the lib support that use-case?

**Comment by barvhaim** [comment]
eventually I called the hook in useEffect and afterPrint set the isShowing to false, it did the trick, can close.

**Comment by MatthewHerbst** [comment]
Apologies for never responding here. Glad you were able to find a solution that works for you!
