### ISSUE TITLE
"SecurityError" on Firefox

### ISSUE THREAD

**Issue by MoffNotFound** [MatthewHerbst/react-to-print#398]
When I use the official example [https://codesandbox.io/s/rzdhd](https://codesandbox.io/s/rzdhd) with Firefox, I get the following error message:

"SecurityError - CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet".

The same problem occurs in my own app but not with every click..

![Clipboard02](https://user-images.githubusercontent.com/4356094/125700209-0dc50295-db5a-47aa-bbaf-e96381174ac7.jpg)

 What could be the reason for this? Many thanx ...

Windows 10, Firefox 91.0b2 (64-Bit)

**Comment by MatthewHerbst** [comment]
Hello. I see no such error using Firefox 90 with no extensions. What version of Firefox are you using, and what extensions do you have installed?

https://user-images.githubusercontent.com/1287375/125700746-0f383ead-f8f4-46d8-ae0f-2d9463492476.mov

**Comment by MoffNotFound** [comment]
Thank you very much for the quick answer. In fact, the cause is probably an extension (in my case I identified the "NoFllow" extension). But there are probably more. After deactivating the extension, the problem no longer occurs. Many thanks...
