### ISSUE TITLE
Printing failed because the `contentWindow` of the print iframe did not load

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [MatthewHerbst/react-to-print#399]
Hi support team,

I am build electron desktop app with react, I am trying to print data from database using **async function** called `onhadleClick()`, I am trying to call this function whenever the printer is available. And then update the `useState` called data and send by props to `ComponentToPrint` ,

### 1 My need and problems I got
**My need:** Is to print without show the printing dialog (**Printing silent**).
**problem:** After click the button it doesn't print.
**error:** After clicking many other times it make an error, ''Printing failed because the `contentWindow` of the print iframe did not load'' 
     
![Sans titre](https://user-images.githubusercontent.com/74948380/126085057-a047673e-2ced-4b7c-aa32-2871bd449899.png)

### 2 some of my code
![code](https://user-images.githubusercontent.com/74948380/126086049-ab8cf3c9-f948-4ba3-8a28-14fa6d1439ed.png)

**Comment by MatthewHerbst** [comment]
Hello, sorry for the delayed response. Can you please show the code for both `onhandleClick` and `ComponentToPrint` please? Thank you

**Comment by MatthewHerbst** [comment]
Working Electron example with how to print using `react-to-print` is now available! https://stackoverflow.com/questions/68751490/electron-print-iframe-given-reference-to-it
