### ISSUE TITLE
Not working on Edge.

### ISSUE THREAD

**Issue by pbpraveen1988** [MatthewHerbst/react-to-print#4]
Hello @gregnb ,

Really I like the library and its working fine on chrome but not working on Microsoft Edge and also in safari new window is getting open but not initializing the print.

Can you please look into that.

Thanks

**Comment by gregnb** [comment]
Sure I'll look into it.  Which version are you running ?

**Comment by pbpraveen1988** [comment]
@gregnb right now i am using the version  1.0.6 of your library.

**Comment by gregnb** [comment]
@pbpraveen1988 Ok, you are right it is not working properly in EDGE.  I'll look into it shortly. Thank you

**Comment by pbpraveen1988** [comment]
@gregnb  any update on Edge issue ?

**Comment by gregnb** [comment]
@pbpraveen1988 Sorry for the delay. So I fixed Safari but I'm still working on EDGE but I'm pretty busy at the moment. I will try to look into it tonight. Once I fix edge I'll release both fixes in 1.0.7

**Comment by pbpraveen1988** [comment]
okay thanks @gregnb

**Comment by pbpraveen1988** [comment]
@gregnb  can you first release the Safari issue , so i can move , I am stuck actually ?

**Comment by gregnb** [comment]
@pbpraveen1988 Just published 1.0.7 try that for Safari

**Comment by pbpraveen1988** [comment]
okay thanks @gregnb

**Comment by gregnb** [comment]
This should be resolved with the latest version
