### ISSUE TITLE
Print specific styles are not being taken into effect

### ISSUE THREAD

**Issue by suthanbala** [MatthewHerbst/react-to-print#40]
When I wrap the styles by the `@media print{}` those styles are not taking effect.

**Comment by gregnb** [comment]
Can you share an example repo?

**Comment by suthanbala** [comment]
Once again, it seems to be working when I try to bring it up on the codesandbox. Btw great library mate 👍

**Comment by gregnb** [comment]
Awesome man glad it's working for you
