### ISSUE TITLE
page breaks are not happening properly, due to this loss of data in styled components

### ISSUE THREAD

**Issue by venu-3** [MatthewHerbst/react-to-print#400]
@MatthewHerbst Can you Please look into this Issue, Please Provide any suggetions

![image](https://user-images.githubusercontent.com/57657470/127746234-da26754c-23ce-4e8f-a3a4-398f02ffddaf.png)

**Comment by MatthewHerbst** [comment]
Hello. Could you please provide a working codesandbox or other similar environment? I can't debug a picture

**Comment by missill** [comment]
Hello,

I have the same problem, did you resolve it @venu-3 ?

**Comment by sbimochan** [comment]
facing same issue.

**Comment by missill** [comment]
This seems to be a css media print issue with margin and break on page.
I tried so many things. but i can't fix the problem :(

**Comment by sbimochan** [comment]
Same here. I tried making block elements. Updating package. Using all page breaks in parent and child elements.

**Comment by sbimochan** [comment]
I think in my case it was not working properly because it was a modal.

**Comment by missill** [comment]
I'm in a modal too but i try out of modal and no results.
I resolved my case to build a classic html table and no more antd table, and wrap my table with a div.

**Comment by MrBlenny** [comment]
I was having having an issue where `page-breaks` were not being respected and data was being cutoff. Changing the `content` el to `display: block` (instead of a flex-col) resolved this for me.
