### ISSUE TITLE
Typescript > Functional component > Example

### ISSUE THREAD

**Issue by michaelpeterlee** [MatthewHerbst/react-to-print#401]
React: 16.14.0

Typescript is not happy, below. Can someone please provide an example implementation. 

![image](https://user-images.githubusercontent.com/19398181/127813646-b1659a23-b442-40fb-ae15-bc1e93339307.png)

![image](https://user-images.githubusercontent.com/19398181/127813694-01402855-3ae5-49e4-80ca-861f20252c7d.png)

**Comment by MatthewHerbst** [comment]
Hello. Can you show your code without the error boxes? Specifically, how did you define the generic that `useContext`/`createContext` takes?

**Comment by michaelpeterlee** [comment]
```tsx
const MyView: React.FC<IMyView> = (props) => {
  const componentRef = React.useRef();
  return React.useMemo(() => {
    <>
      <ReactToPrint trigger={() => (<div>PRINT</div>)} content={() => componentRef.current} />
      <div>Print this</div>
    </>
  });
}
```

**Comment by MatthewHerbst** [comment]
`const componentRef = React.useRef(null);` should fix the error I believe. This will make the value of `componentRef.current` `null` until it makes its way to `ReactToPrint`.

**Comment by michaelpeterlee** [comment]
Thanks @MatthewHerbst, it compiles now however a subsequent error fires when printing:

`There is nothing to print because the "content" prop returned "null". Please ensure "content" is renderable before allowing "react-to-print" to be called.`

**Comment by MatthewHerbst** [comment]
That's a correct error. You never assign the ref to anything. You need to do: `<div ref={componentRef}>Print this</div>`

**Comment by michaelpeterlee** [comment]
That is it @MatthewHerbst, thanks for the support and please remember to update the docs.

**Comment by MatthewHerbst** [comment]
@michaelpeterlee PRs are welcome 😄

**Comment by dglitxh** [comment]
If the component to be printed is wrapped in a div, the ref should be placed inside the div and not the component itself.
This worked for me.
