### ISSUE TITLE
How to use this to print out a Redux component?

### ISSUE THREAD

**Issue by DevinParentice** [MatthewHerbst/react-to-print#404]
All of my components are class components, yet when I hit the print button I get the error:

For "react-to-print" to work only Class based components can be printed.

The problem is the component I want to print is using Redux, so it is like:

```
export Class ExampleComponent extends React.Component {
        ... ... ...
}
```

```
function mapStateToProps(state) {
       return {
              ... ... ...
       }
}
```

```
export default compose (
    withRouter,
    connect(mapStatetoProps)
)(ExampleComponent);
```

I am guessing this is the issue? That it is no longer being considered a class component? Is there any way to fix this?

**Comment by MatthewHerbst** [comment]
Hello. Hard to tell from the limited code example, but yes, that could be the problem. The solution is to create a parent class component around the reduxed-component. This thread might help: https://github.com/gregnb/react-to-print/issues/280

**Comment by DevinParentice** [comment]
Solved, very simple solution, thank you.

For any future people:

Just create another class component as a wrapper:

```
export class WrapperComponent extends React.Component {
    render() {
        return (
           <DesiredComponentToPrint />
        )
    }
}
```
