### ISSUE TITLE
Open print preview in ElectronJS app

### ISSUE THREAD

**Issue by KimTrongNguyen** [MatthewHerbst/react-to-print#405]
Hello, currently I'm developing a desktop app with React and Electron to print barcode on A4 paper, when I press Print button on the browser, the print preview work perferectly. But in the Electron app it just show me a dialog to choose print options, then if I press print it will let me save the pdf file. How can I show the print preview like in the browser in my Electron app?
Thank you so much!

**Comment by MatthewHerbst** [comment]
Hello. The print preview is displayed by the browser in response to the `window.print` event. I don't know what the Electron equivalent, if any is. There is a `print` prop that you can use (and that was added specifically for Electron support) that allows you to define your own print action. So for example:

```tsx
const handleElectronPrint = async (target: HTMLIFrameElement) => {
  // `target` is the iframe with all the content to print
  // print target using electron:
    // https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback
    // https://www.geeksforgeeks.org/printing-in-electronjs/
};

<ReactToPrint
  ...
  print={handleElectronPrint}
/>
```
Does that help? I don't have any Electron experience myself unfortunately. If you have a good solution for this I would welcome a PR to add it to the README

**Comment by KimTrongNguyen** [comment]
@MatthewHerbst After a few research, I figure out that print preview is possible in Electron but it was not bundled in Electron, which mean I have to do it myself and I don't think I have enough time and able to do it :((( I think I need to find other approach to work around. Thank you!

**Comment by MatthewHerbst** [comment]
Maybe someone on SO will know: https://stackoverflow.com/questions/68751490/electron-print-iframe-given-reference-to-it

**Comment by MatthewHerbst** [comment]
The SO post was answered with a working example! I will be adding this to the README as well so people can find it in the future
