### ISSUE TITLE
The latest version 2.0.0-alpha-2 is not working with IE.

### ISSUE THREAD

**Issue by anudeep1426** [MatthewHerbst/react-to-print#41]
Hello @gregnb ,

Its working great in chrome, firefox, Edge.
When I try to print using IE browser its giving me error as below.

![image](https://user-images.githubusercontent.com/16793358/44866700-965cf800-ac4b-11e8-8e63-601d9d55c7db.png)

please take a look.

thanks,

**Comment by gregnb** [comment]
Which version of IE and can you provide a code sandbox of your sample

**Comment by gregnb** [comment]
@anudeep1426 Care to share an example? Again, I probably should put in the README this library isn't intended to support IE11

**Comment by anudeep1426** [comment]
@gregnb , Yeah, I'm using the IE 11 version. but the lower version of library(1.0.21) is working fine with IE 11.

**Comment by gregnb** [comment]
Try the latest version. Just merged a PR that might help

**Comment by anudeep1426** [comment]
Hey that works great!! Thanks.

**Comment by anudeep1426** [comment]
As it is working fine with IE11. I'm closing this issue. Thanks
