### ISSUE TITLE
Blank sheet error react to print

### ISSUE THREAD

**Issue by lizarragadev** [MatthewHerbst/react-to-print#410]
Hi everyone, I have a problem that has already been with me for two days. I'm using pure functional components, I found the following example, but when I press the button, I only get a blank sheet in the print preview, I tried to do it with classes, but it doesn't give me either, I don't know if I'm doing something wrong , all this in React JS, my files have a .jsx extension, I'm not sure what the problem is, I've already looked for too many solutions and I can't find what I'm doing wrong, thanks.

I'm using: "react": "^ 16.8.6", "react-to-print": "^ 2.13.0"

```javascript
import React, { useRef } from "react";
import ReactToPrint from "react-to-print";

const ComponentToPrint = React.forwardRef((props, ref) => (
      <table ref={ref}>
        <thead>
          <th>column 1</th>
          <th>column 2</th>
          <th>column 3</th>
        </thead>
        <tbody>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
        </tbody>
      </table>
));

const Example = () => {
    const componentRef = useRef();
    return (
      <div>
        <ReactToPrint
          trigger={() => <a href="#">Print this out!</a>}
          content={() => componentRef.current}
        />
        <ComponentToPrint ref={componentRef} />
      </div>
    );
}

export default Example;
```

**Comment by lizarragadev** [comment]
This is the view when I press print...

<img width="996" alt="Captura de Pantalla 2021-08-24 a la(s) 18 17 24" src="https://user-images.githubusercontent.com/1924390/130697478-61f9e6f5-c24b-47b9-910d-364f459a3435.png">

**Comment by philhaynes337** [comment]
I am currently getting the same issue with my project. Found anything yet?

**Comment by lizarragadev** [comment]
Hi @philhaynes337  I still couldn't find a solution. Clicking on the button opens the print window with the sheet and everything but everything blank, I tried with a lot of content in the table, static data just to test, but also, the strange thing is that several pages are put, since it detects that it is a lot of content but still everything in white.
I think there is a problem in:

```javascript
const componentRef = useRef ();
```

since in another example using a Calendar in full screen, the view was not complete, and I noticed that I didn't grab the value of useRef, but when somehow something in the view was modified or there was a small status update, with some button or something, it was just updated and everything was displayed normal.
Hopefully someone can give us a hand with the problem.

**Comment by MatthewHerbst** [comment]
Hello. I've run into problems using `useRef` and `forwardRef` before as well, though in theory it should work. Are you able to convert `ComponentToPrint` to a class component by chance to see if it works that way? Then you would know if it was an issue with `forwardRef` or not

**Comment by lizarragadev** [comment]
Hi @MatthewHerbst here is a fragment of code in class, I also tried it and it doesn't work, maybe you will have more luck and tell us how.

```javascript
const Example = () => {
  const componentRef = useRef();
  return (
    <div>
      <ReactToPrint
        trigger={() => <button>Print this out!</button>}
        content={() => componentRef.current}
      />
      <ComponentToPrint ref={componentRef} />
    </div>
  );
};
```

**Comment by lizarragadev** [comment]
Hi @MatthewHerbst , here is a fragment of code in class, I also tried it and it doesn't work, maybe you will have more luck and tell us how.

```javascript
class ComponentToPrint extends React.PureComponent {
  render() {
    return (
      <table>
        <thead>
          <th>column 1</th>
          <th>column 2</th>
          <th>column 3</th>
        </thead>
        <tbody>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
        </tbody>
      </table>
    );
  }
}
```

**Comment by philhaynes337** [comment]
I believe the problem lies within the PDFDownloadlink function / component
it self. That would be within the node package itself. Ill dig deeper into
this when this long weekend is over.

**Comment by jncoates** [comment]
Hi @philhaynes337 and @MatthewHerbst, I am experiencing the same issue were you able to find a solution?

**Comment by babin93** [comment]
Same issue here, The only way I can see something in the print preview is by setting `copyStyles={false}` which gives an ugly rendering of my content.

Edit:

I had an import of a specifc css file in my js file. By removing that import it started working properly.

**Comment by MatthewHerbst** [comment]
@babin93 could you explain that import a bit more please? Might help others here

**Comment by babin93** [comment]
Alright, the styling issue was actually related to this problem: https://github.com/gregnb/react-to-print/issues/11#issuecomment-902726347 (mostly a lack of understanding on my side)

For the blank page:

I had this import in my file
`import 'react-toastify/dist/ReactToastify.css';` (not sure why this was there)

By removing it, there was no longer a STYLE tags in my page's HEAD so everything started working properly even with `copyStyles={true}`. 

Before removing this import, I was only able to seem something when I would set copyStyles={false}.

Not sure this will help a lot...

**Comment by MatthewHerbst** [comment]
Ok, thanks for the explanation @babin93! I'll see about adding something to the README regarding https://github.com/gregnb/react-to-print/issues/11#issuecomment-902726347

**Comment by gaisuke** [comment]
i'm still experiencing this issue, is anyone had an update to this? my code looks exactly like @lizarragadev . Thanks in advance.


Update 2 hours after i commented this : 
turns out mine is already showed, but because of my component is white text, it shows a blank preview which is actually there is text on it with white color. so i add copyStyles={false} prop to negate the css

**Comment by MatthewHerbst** [comment]
I added a note about this issue to the [Common Pitfalls section](https://github.com/gregnb/react-to-print/blob/master/README.md#common-pitfalls) of the README, hopefully that helps others in the future. Thanks all

**Comment by fosteman** [comment]
Having the same issue. 

Exactly the same setup as of @lizarragadev, created #455

**Comment by dennemark** [comment]
Custom-font might not be loaded correctly. Using `font-display: swap` in `@font-face` might solve this: https://github.com/gregnb/react-to-print/issues/281#issuecomment-1098039528
At least it worked for me.
