### ISSUE TITLE
How do I set a default background to every report page?

### ISSUE THREAD

**Issue by hobbitjeditransgender** [MatthewHerbst/react-to-print#411]
I've already tried setting the main component backgroundImage, but it only worked for the first page.

I'm trying to figure out if pageStyle property is the way, but, until now, could not find a way to do it:

```
const handlePrint = useReactToPrint({
        content: () => reportElement.current,
        pageStyle: `
        @page {
            background-image: url(${reportBackground})
        }`,
    });
```

**Comment by MatthewHerbst** [comment]
Hello. I think what you want to do is to use your existing styles to ensure that the component class of the printed image has the background. For example, something like:

```jsx
<div ref={reportElement} style={{ backgroundImage: 'url(${reportBackground})' }}>
  {/* some content here */}
</div>
const handlePrint = useReactToPrint({
  content: () => reportElement.current,
});
```

If you could provide a codesandbox of your code I would be happy to help you debug

**Comment by MatthewHerbst** [comment]
Hello. I think what you want to do is to use your existing styles to ensure that the component class of the printed image has the background. For example, something like:

```jsx
<div ref={reportElement.current} style={{ backgroundImage: 'url(${reportBackground})' }}>
  {/* some content here */}
</div>
const handlePrint = useReactToPrint({
  content: () => reportElement.current,
});
```

If you could provide a codesandbox of your code I would be happy to help you debug
