### ISSUE TITLE
Styling is not printed

### ISSUE THREAD

**Issue by jaballogian** [MatthewHerbst/react-to-print#413]
Hello,

I am creating a react app to print some QR codes and the corresponding texts together.

When I clicked the export button, the QR codes and the texts are shown in the preview but the styles (like the background color and the flex display) didn't apply in the preview (as you can see in the screenshot below).
When I downloaded the file as PDF then I opened it, the styles also didn't apply.

I have tried to add ```copyStyles={true}``` to the ```<ReactToPrint/>``` component but it didn't work.
I don' think it's necessary because from the documentation, the default value of ```copyStyles``` is true. 

### Screenshot in browser

![image](https://user-images.githubusercontent.com/24468466/132624112-7ef82d18-1b54-4215-b064-fb6da53ac25f.png)

Browser: Google Chrome 93
OS: Windows 10 Home Single build 19042

### Preview before printing

![image](https://user-images.githubusercontent.com/24468466/132624410-135420f1-3d77-43b4-bfd8-6fe3ac5d3807.png)

As you can see, I have checked the background graphics option there.

### Code

<details>
  <summary>App.js</summary>

```javascript
import React, { useState, useEffect, useRef } from 'react'

// PDF PRINT
import ReactToPrint from 'react-to-print'

// QR CODE
import QRCode from 'qrcode'

// STYLES
import './App.scss'

function App() {
  const [ imageSourceList, setImageSource ] = useState(null)

  const firstSectionRef = useRef()
  const secondSectionRef = useRef()
  const thirdSectionRef = useRef()
  const forthSectionRef = useRef()
  const fifthSectionRef = useRef()

  const textList = [
    // FIRST SECTION
    '351756051523999-085123456789',
    // SECOND SECTION
    'Hello world 1', 'Hello world 2',
    // THIRD SECTION
    'Hello world 3', 'Hello world 4',
    'Hello world 5', 'Hello world 6',
  ]

  const generateQR = async (text, index) => {
    try {
      const url = await QRCode.toDataURL(text)
      console.log(`index: ${index}, url: ${url}`)
      return url
    } catch (err) {
      console.log(`index: ${index}, error: ${err}`)
      return err
    }
  }

  const generateImageList = async (list) => {
    let output = []
    for(let i = 0; i < list.length; i++) {
      const item = list[i]
      const url = await generateQR(item, i)
      output.push(url)
    }
    setImageSource(output)
  }

  useEffect(() => {
    generateImageList(textList)
  }, [])

  return (
    <div className='root'>

      {/* FIRST SECTION */}
      <div
        className='section'
        ref={firstSectionRef}
      >
        {imageSourceList && <img src={imageSourceList[0]} alt=''/>}
        <p>{`Text: "${textList[0]}"`}</p>
      </div>

      {/* EXPORT BUTTON */}
      <ReactToPrint
        trigger={() =>
          <div className='export-button'>
            Export
          </div>
        }
        content={() => firstSectionRef.current}
      />

      {/* SECOND SECTION */}
      <div 
        className='section flex'
        ref={secondSectionRef}
      >
        {/* FIRST ITEM */}
        {imageSourceList && imageSourceList.map((item, index) => {
          if(index === 1 || index === 2) {
            return(
              <div key={index}>
                <img src={item} alt=''/>
                <p>{`Text: "${textList[index]}"`}</p>
              </div>
            )
          }
        })}
      </div>

      {/* EXPORT BUTTON */}
      <ReactToPrint
        trigger={() =>
          <div className='export-button'>
            Export
          </div>
        }
        content={() => secondSectionRef.current}
      />

      {/* THIRD SECTION */}
      <div 
        className='section flex'
        ref={thirdSectionRef}
      >
        {imageSourceList && imageSourceList.map((item, index) => {
          if(index > 2) {
            return(
              <div key={index}>
                <img src={item} alt=''/>
                <p>{`Text: "${textList[index]}"`}</p>
              </div>
            )
          }
        })}
      </div>

      {/* EXPORT BUTTON */}
      <ReactToPrint
        trigger={() =>
          <div className='export-button'>
            Export
          </div>
        }
        content={() => thirdSectionRef.current}
      />

      {/* FORTH SECTION */}
      <div 
        className='section flex'
        ref={forthSectionRef}
      >
        {imageSourceList && imageSourceList.map((item, index) => {
          if(index >= 0 && index <= 3) {
            return(
              <div key={index}>
                <img src={item} alt=''/>
                <p>{`Text: "${textList[index]}"`}</p>
              </div>
            )
          }
        })}
      </div>
      <div className='section flex'>
        {imageSourceList && imageSourceList.map((item, index) => {
          if(index >= 4 && index <= 6) {
            return(
              <div key={index}>
                <img src={item} alt=''/>
                <p>{`Text: "${textList[index]}"`}</p>
              </div>
            )
          }
        })}
      </div>

      {/* EXPORT BUTTON */}
      <ReactToPrint
        trigger={() =>
          <div className='export-button'>
            Export
          </div>
        }
        content={() => forthSectionRef.current}
      />

      {/* FIFTH SECTION */}
      <div
        className='section'
        ref={fifthSectionRef}
      >
        {imageSourceList && 
        <img 
          src={imageSourceList[0]} 
          alt=''
          className='small'
        />
        }
        <p>{`Text: "${textList[0]}"`}</p>
      </div>

      {/* EXPORT BUTTON */}
      <ReactToPrint
        trigger={() =>
          <div className='export-button'>
            Export
          </div>
        }
        content={() => fifthSectionRef.current}
      />
    </div>
  )
}

export default App;
```

</details>

<details>
  <summary>App.scss</summary>

```scss
.root {

  .section {
    padding: 20px;
    background-color: lavender;
  }
  
  .flex {
    display: flex;
    justify-content: space-between;
  }
  
  .small {
    height: 1cm;
    width: 1cm;
  }

  .export-button {
    width: fit-content;
    background-color: gainsboro;
    padding: 10px 20px;
    border-radius: 10px;
    cursor: pointer;
    margin: 20px;
  }
}
```

</details>

<details>
  <summary>package.json</summary>

```json
{
  "name": "test-react-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "apexcharts": "^3.26.1",
    "node-sass": "^4.14.1",
    "qrcode": "^1.4.4",
    "react": "^17.0.2",
    "react-apexcharts": "^1.3.9",
    "react-datepicker": "^3.8.0",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "react-to-print": "^2.13.0",
    "web-vitals": "^1.0.1"
  },
  "engines": {
    "node": "12.19.0",
    "npm": "6.14.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

</details>

Here is the codesandbox https://codesandbox.io/s/test-qrcode-pdf-print-7jbfd

**Comment by MatthewHerbst** [comment]
Hello. Your SCSS targeting the `section` class requires the `root` ID to exist. However, when printing, the `div` with the `root` ID will not exist since the "root" element will be the `div`s referenced by the various `ReactToPrint` components. Move the `section` SCSS outside of the `.root` and it works.

**Comment by jaballogian** [comment]
> Hello. Your SCSS targeting the `section` class requires the `root` ID to exist. However, when printing, the `div` with the `root` ID will not exist since the "root" element will be the `div`s referenced by the various `ReactToPrint` components. Move the `section` SCSS outside of the `.root` and it works.

You're right.

But what if (another case) I need to keep the ```root``` style? For example, adding a background color to the root.
I've tried to change the ```root``` name into another name like ```parent-element``` but still didn't work. (I've updated the codesandbox for this).

### Edit:

I change the ```root``` selector name into ```parent-element``` and moved all the selectors in App.scss outside the ```parent-element```.
Everything was working fine.

Then I have a question. By moving all the selectors outside the parent selector, does this mean that ```react-to-print``` library doesn't support yet for nested styling in ```sass```?

It's a great and helpful library btw.

**Comment by MatthewHerbst** [comment]
It's not an issue of nested styling or SASS, it wouldn't work if you were using plain CSS either. We don't have a way of knowing which classes above the child are being used, or what each of them might do, so there's no concept of trying to apply the parent classes to the child. What you can do is put additional styles on the child inside an `@media print {}` directive so that when printing those are used:

```scss
.root {
  background-color: orange;

  .section {
    width: 10px;
  }
}

@media print {
  .section {
    background-color: orange;
  }
}
```

**Comment by jaballogian** [comment]
> It's not an issue of nested styling or SASS, it wouldn't work if you were using plain CSS either. We don't have a way of knowing which classes above the child are being used, or what each of them might do, so there's no concept of trying to apply the parent classes to the child. What you can do is put additional styles on the child inside an `@media print {}` directive so that when printing those are used:
> 
> ```css-scss
> .root {
>   background-color: orange;
> 
>   .section {
>     width: 10px;
>   }
> }
> 
> @media print {
>   .section {
>     background-color: orange;
>   }
> }
> ```

Okay thank you for the explanation 👍🏻
