### ISSUE TITLE
Chrome: Background not working in print

### ISSUE THREAD

**Issue by pnyennhi** [MatthewHerbst/react-to-print#416]
I'm trying print preview (pdf) with my component but the background style seems not to be working, even with inline CSS.
I tried to use ``` @media print{} ``` but it didn't work. 

Here is my component:
![Screenshot from 2021-09-22 11-39-04](https://user-images.githubusercontent.com/43275742/134284724-9a097100-043b-437a-ac9e-8f3cd8913b02.png)

And this is print preview (I want to download pdf file):
![Screenshot from 2021-09-22 11-39-22](https://user-images.githubusercontent.com/43275742/134284754-e38636dc-9319-4142-b128-7cffd8eec834.png)

What solution should I apply for my use case?

I hope to be answered soon. Thank you.

**Comment by MatthewHerbst** [comment]
Hello. Could you please provide a codesandbox or similar demo? It's not really possible to offer help without seeing your code

**Comment by pnyennhi** [comment]
I have a question. Does this package work fine with node v8?
I'm using node v8 and ```react 16.14```, ```react-dom: 16.14``` on my local and it does not work.

I created a demo: [https://react-et5qvf.stackblitz.io](https://stackblitz.com/edit/react-et5qvf?file=src/App.js) and it seems to be working fine on this environment.

I can't point out why it doesn't work for me.

**Comment by MatthewHerbst** [comment]
The version of Node you're using shouldn't matter if you're using the production build (`import ReactToPrint from 'react-to-print'`). If you're trying to build the package locally (`npm run build`) then you need Node >12 [as mentioned in the README](https://cnycentral.com/news/local/independent-pharmacies-can-vaccinate-hundreds-a-week-but-dont-have-easy-access-to-doses). 

I can't determine what Node version your example uses, but it also uses React 17. I moved it to 16.14 and don't see any issues. Can you reproduce as an example on Stackblitz the package not working with Node 8?

**Comment by pnyennhi** [comment]
It seems like there is an issue with my current project. I tried to create another react app and it worked fine.
However, it' weird that just background-color does not work, other CSS styles works perfectly...

**Comment by pnyennhi** [comment]
I found the issue. It was my fault. I'd set `@media print { background: transparent }` before.

I'm sorry for my annoyance. I'll close this issue.
Thank you so much for your quick response.
