### ISSUE TITLE
React-to-Print with Functional Components 

### ISSUE THREAD

**Issue by tommy-banana** [MatthewHerbst/react-to-print#417]
Hi has there been any progress on using React-toPrint with functional components?  I am still getting the error ComponenttoPrint can only be a class based.

**Comment by MatthewHerbst** [comment]
This can be done already using `React.forwardRef` to wrap the functional component. See the example in this PR I've been working on: https://github.com/gregnb/react-to-print/pull/418 (specifically, look a the bottom of the modified `examples/ComponentToPrint/index.tsx` file in that PR). I will add to the docs in that PR as well.

**Comment by tommy-banana** [comment]
Thanks Matthew. I am not a total React expert.... Do you mean this:

```
export const FunctionalComponentToPrint = React.forwardRef<ComponentToPrint | null, Props>((props, ref) => { 
  return <ComponentToPrint ref={ref} text={props.text} />;
});
```

To me that looks like it is being used in a Class based component. Do you mean i should use that wrapper in the export of a functional based component?

**Comment by MatthewHerbst** [comment]
@tommy-banana yes, you need to use that wrapped, but it can wrap anything inside. That's a good point to make clear, I'll fix that as well, thanks. You should be able to do:

```tsx
export const FunctionalComponentToPrint = React.forwardRef<ComponentToPrint | null, Props>((props, ref) => { 
  return <div ref={ref}><p>My Component Content Here</p></div>;
});
```

You'll notice that the `React.forwardRef` call is simply wrapping a functional component definition.

Note that you cannot pass a ref directly to a functional component: https://reactjs.org/docs/refs-and-the-dom.html#accessing-refs

So for example, you cannot do this:

```tsx
export const FunctionalComponentToPrint = React.forwardRef<ComponentToPrint | null, Props>((props, ref) => {
  // Functional components cannot take refs, unless wrapped with React.forwardRef
  return <MyCustomFunctionalComponent ref={ref} />;
});
```
