### ISSUE TITLE
Page break does not look good

### ISSUE THREAD

**Issue by kstulgys** [MatthewHerbst/react-to-print#420]
I have table component in react. The page break doesn't make sense. What can I do? The length of UI/list is not know beforehand. I want to make it dynamic.
Example:
![image](https://user-images.githubusercontent.com/25918214/137494371-33088db5-ee23-4bf1-aeff-53241c874db3.png)

**Comment by MatthewHerbst** [comment]
Hello. Could you please post ideally a working codesandbox of your code? Also, the README has some good tips about page breaks that might be helpful for you: https://github.com/gregnb/react-to-print/blob/master/README.md#page-breaks

**Comment by kstulgys** [comment]
Hi there, it's working! I just refactored my code to use `ForwardRef`:
![image](https://user-images.githubusercontent.com/25918214/137583686-13c58d13-2e11-46a0-9d57-814f98cdeb11.png)
This look way better although I wish I can control the padding/margin (top in this case) of the next page:
![image](https://user-images.githubusercontent.com/25918214/137583718-8fa5c005-06e7-400d-a2a6-4fe75bc5fb4b.png)

**Comment by MatthewHerbst** [comment]
Hello. I can't help debug from an image though, I need to see the full code

**Comment by darshakeyan** [comment]
@MatthewHerbst  I am facing the similar issue but i am still could not able to replicate after going through similar issues solution of page break.
Basically I am want form in PDF Format but some of the form field does not look good.
![image](https://user-images.githubusercontent.com/61287039/151817067-14473f1b-da5a-4b4b-b7ef-4485184790a7.png)

can you please tell how to display field dynamically if it has long form

**Comment by MatthewHerbst** [comment]
@darshak369 hello. As mentioned above, without seeing code it's impossible for me to help debug anything.
