### ISSUE TITLE
Ant Design Form Label doesn't get horizontal

### ISSUE THREAD

**Issue by ardaorkin** [MatthewHerbst/react-to-print#423]
Hi. First of all, thank you for this great library.
I have a problem.
I am using [antdesign form](https://ant.design/components/form/). Even though I set the form layout as horizontal and it is rendering into the DOM as what it is, when I try to get PDF, it turns to vertical.
I couldn't overcome this issue.
Can you please help me?
Thanks.

**Comment by MatthewHerbst** [comment]
Hello. Could you share the code you are using please? My guess is that antd doesn't include the horizontal styling in their `@media print` directive. You may need to add one of your own to control styling during the print. Happy to help figure this out

**Comment by ardaorkin** [comment]
Hello. Sorry for my late.
Well, I slightly changed the code. I used [addonBefore and addonAfter](https://ant.design/components/input/#API) properties of the Input component. And when these properties weren't enough, I used div elements with a "position: absolute" style property; because the PDF is gonna static, anyway; so I thought that setting "position: absolute" would be a good go around the issue.

Thank you for your response, anyway.

**Comment by MatthewHerbst** [comment]
Hello. Could you please share your code? Thank you

**Comment by ardaorkin** [comment]
Here is an example of how I go around the issue:
```javascript
import React from "react";
import { Form, Input } from "antd";

const PDFTemplate = React.forwardRef((props, ref) => {
  return (
    <div ref={ref}>
      <Form
        style={{ fontSize: 8, margin: "0 auto" }}
        layout="horizontal"
        labelCol={{ span: 8 }}
        wrapperCol={{ span: 16 }}
      >
        <Form.Item name="first_name">
          <Input
            addonBefore={
              <div
                style={{
                  marginLeft: 0,
                  padding: 5,
                  border: "1px solid",
                  boxShadow: "2px 3px",
                }}
              >
                First Name
              </div>
            }
          />
        </Form.Item>
        <Form.Item name="last_name">
          <Input
            addonBefore={
              <div
                style={{
                  marginLeft: 0,
                  padding: 5,
                  border: "1px solid",
                  boxShadow: "2px 3px",
                }}
              >
                Last Name
              </div>
            }
          />
        </Form.Item>
      </Form>
    </div>
  );
});

export default PDFTemplate;
```

**Comment by MatthewHerbst** [comment]
Does that work for you, or do you still need help? My guess is antd is changing the styles using a built-in `@media print` query, but those can usually be overridden

**Comment by ardaorkin** [comment]
The code I shared with you worked for me. I didn't use `@media print` query
