### ISSUE TITLE
After build i have a problem for style not working some time. 

### ISSUE THREAD

**Issue by Desmond98-droid** [MatthewHerbst/react-to-print#425]
Simple print
this print at localhost

<img width="381" alt="Screen Shot 2564-11-02 at 10 16 27" src="https://user-images.githubusercontent.com/30744764/139782188-2ef34863-08eb-4ac5-a25f-09fb2fe9501c.png">
 
 after build
 
<img width="267" alt="Screen Shot 2564-11-02 at 10 17 54" src="https://user-images.githubusercontent.com/30744764/139782174-a03107d4-4f54-46ac-8026-121afdffcae2.png">

**Comment by MatthewHerbst** [comment]
Hello. It sounds like your build process is changing some of your styles. Could you share your code please?

**Comment by Desmond98-droid** [comment]
@MatthewHerbst this is map scalbar use ol.css (openlayer lib). After build when click print some time correct and some time not correct.

**Comment by MatthewHerbst** [comment]
Without seeing code I'm not able to help
