### ISSUE TITLE
Printed document differs from preview

### ISSUE THREAD

**Issue by MattFanto** [MatthewHerbst/react-to-print#427]
Hi folks,

I'm using react-to-print lib to print several document with different template, one of the template is quite "fancy" after a lot of trouble with the style and everything I managed to get a decent preview on Chrome, unfortunately when I effectively try to print the printed document becomes awful.
Do you know what may be causing this issue?

react-to-print: 2.14.0

P.S. do you use any kind of virtual printer to test your lib?

![image](https://user-images.githubusercontent.com/17476233/140560800-cd32930a-c493-42aa-aa66-c4d87cbe3258.png)
![image](https://user-images.githubusercontent.com/17476233/140561184-5534a7b2-981d-4fda-bcf7-ed71dfe55d7e.png)

**Comment by MatthewHerbst** [comment]
Hi there. Thanks for reporting your issue. That doesn't look great! I'm not sure it's a problem with the library though, we only get as far as the preview. Sending the preview to the printer is the job of the browser/operating system and we don't have any control over that unfortunately. 

Can you let me know your printer make/model/setting please? Also what operating system are you on?

I don't have a virtual printer to test with, though that's actually a really good idea, will look into seeing if there is something like that. I usually just test using my at-home crappy Brother brand printer.

**Comment by MattFanto** [comment]
Hi @MatthewHerbst thanks for your prompt reply and this fantastic library.
The OS my colleague is using is Windows10 [WorkCentre](https://colour-laser-printers.co.uk/printer/WC7830/WorkCentre%207830.php) 

I just made a new test and it seems it's related to the font (Ubuntu) not being available, when I sent a version with Aria it worked.
But to be honest I can't tell because I don't have the printer available here (sending mail to my colleague)

Re: virtual printer I found some solutions on Linux if you are interested https://askubuntu.com/questions/1051602/virtual-printer

**Comment by MatthewHerbst** [comment]
Thanks for the links, I'll check them out. You should be able to add the font to your website so that people who don't have it can download it, then it might solve that problem.
