### ISSUE TITLE
How to trigger an event if success in printing using useReactToPrint in react-to-print

### ISSUE THREAD

**Issue by JasonCabral131** [MatthewHerbst/react-to-print#431]
```jsx
const handlePrint = useReactToPrint({
  content: () => componentRef.current,
});
```

can someone help me thanks

**Comment by MatthewHerbst** [comment]
Hi @JasonCabral131 as I mentioned in my other [comment](https://github.com/gregnb/react-to-print/issues/96#issuecomment-969170050) you can fire events in the `onAfterPrint` callback that `react-to-print` takes, but we have no way of knowing if the user actually printed or if they closed the print dialog without printing. This is unfortunately a browser limitation and not something we can fix 😢

**Comment by JasonCabral131** [comment]
!
