### ISSUE TITLE
How to directly upload the pdf file immediately after generating the pdf file?

### ISSUE THREAD

**Issue by krushna-cruxbyte** [MatthewHerbst/react-to-print#449]
I want to upload the pdf file through api, once its generated. User may save or cancel pdf window but the pdf file has to uploaded.
I am using react functional component.

**Comment by MatthewHerbst** [comment]
Hello. This library does not generate PDFs, so I think you'll need to find a different tool to do that. This library just opens the browser's native print dialog. If the browser has an option to download as a PDF it is using some other tool to make that happen.

**Comment by krushna-cruxbyte** [comment]
Ok thanks for your response. I will be very thankful if you could suggest a tool that will help me to style, generate and upload pdf of a react component . I am using material ui for my project.

**Comment by krushna-cruxbyte** [comment]
> Hello. This library does not generate PDFs, so I think you'll need to find a different tool to do that. This library just opens the browser's native print dialog. If the browser has an option to download as a PDF it is using some other tool to make that happen.

Ok thanks for your response. I will be very thankful if you could suggest a tool that will help me to style, generate and upload pdf of a react component . I am using material ui for my project.

**Comment by MatthewHerbst** [comment]
I believe this package can do what you need: https://www.npmjs.com/package/@react-pdf/renderer
