### ISSUE TITLE
pageStyle - size not works?

### ISSUE THREAD

**Issue by hoangdoan267** [MatthewHerbst/react-to-print#45]
I add pageStyle prop to my PrintComponent but it doesn't work with specific size like "A4 portrait" or "A4 landscape".

```
class Example extends React.Component {
  render() {
    return (
      <div>
        <ReactToPrint
          trigger={() => <a href="#">Print this out!</a>}
          content={() => this.componentRef}
        />
        <PrintComponent
          ref={el => (this.componentRef = el)}
          pageStyle="@page { size: A4 portrait;}"
        />
      </div>
    );
  }
}

export default Example;
```

**Comment by lidaof** [comment]
I have this issue too, any solutions? Can I specify a much big width?

**Comment by ghost** [comment]
Some problem here, `width `and `height `doesn't work, even with an `!important`

**Comment by gregnb** [comment]
Anyone else having issues?

**Comment by loverdeveloper** [comment]
@gregnb 
is this fix?

**Comment by NguyenTheSon** [comment]
same issues

**Comment by akafaneh** [comment]
Same issue here, any update or work around for now?

**Comment by cathysandstrom** [comment]
The component has a prop called pageStyle which allows you to override the default window print styling that is used by react-to-print. I'm not 100% sure on how this is used at the moment, but setting it to an empty string will remove the resizing done by the component. 
Hope this helps!
```
<ReactToPrint
          trigger={() => <a href="#">Print this out!</a>}
          content={() => this.componentRef}
          pageStyle={""}
/>
```

**Comment by ghost** [comment]
@lidaof @Khyzz @NguyenTheSon 
I got these question, you can use html tag not class name. Such as

```
:global {
    .patchPrintStyle {
        section {
            display: block !important;
        }
        article {
            height: 100% !important;
        }
        * {
            border: 0 none !important;
        }
    }
}
```
