### ISSUE TITLE
Print PDF multi page component 

### ISSUE THREAD

**Issue by duyanh4788** [MatthewHerbst/react-to-print#452]
Dear

I have 3 component hook and printing same time but only one component printing 

Please help me

**Comment by MatthewHerbst** [comment]
Make sure each component/hook has its own `ref` otherwise all the hooks will print the same thing

**Comment by duyanh4788** [comment]
Dear .

I have 3 component printing PDF , but only 1 component printRef printing .

![image](https://user-images.githubusercontent.com/75610658/147815360-ef06c86e-cc0c-4b92-add4-274a78cfd65d.png)
![image](https://user-images.githubusercontent.com/75610658/147815386-ba988aec-eccc-4c3f-a8e7-09c5f60a984f.png)
![image](https://user-images.githubusercontent.com/75610658/147815405-0d8c7ca0-f0fd-4b3d-8274-d463a9362ff3.png)

**Comment by MatthewHerbst** [comment]
Hello. I really need these to be in codesandbox please, it is not possible for me to help debug when only seeing images with small amounts of code.

**Comment by duyanh4788** [comment]
Dear .

This my code is code sanbox : 

https://codesandbox.io/s/react-to-print-forked-quuh3?file=/index.js

**Comment by MatthewHerbst** [comment]
> https://codesandbox.io/s/react-to-print-forked-quuh3?file=/index.js

```jsx
<div style={{ display: "none" }}>
  <ComponentA ref={printRef} info={text} />
  <ComponentB ref={printRef} info={text} />
</div>
```
As I mentioned above, each component needs its own ref, and you would presumably want a different print button for each:
```jsx
<div style={{ display: "none" }}>
  <ComponentA ref={printRef1} info={text} />
  <ComponentB ref={printRef2} info={text} />
</div>
```
Or, if you do actually want to print both of them, just move the `ref` to a parent component:
```jsx
<div style={{ display: "none" }}>
  <div ref={printRef}>
    <ComponentA info={text} />
    <ComponentB info={text} />
  </div>
</div>
```

**Comment by duyanh4788** [comment]
Dear .

Your can heple me print success component A and continue print component B .

Thanks You

**Comment by duyanh4788** [comment]
Dear .

Your can cup 2 component on 2 page ?

**Comment by MatthewHerbst** [comment]
To print each component on its own page use the CSS [`page-break-after`](https://www.w3schools.com/cssref/pr_print_pageba.asp) styles to force a page break after the first component:

```jsx
<div style={{ display: "none" }}>
  <div ref={printRef}>
    <ComponentA info={text} />
    <div style={{ pageBreakAfter: 'always' }} />
    <ComponentB info={text} />
  </div>
</div>
```

**Comment by duyanh4788** [comment]
Dear .

I do success , thanks your so much
