### ISSUE TITLE
Is there anyway to download to pdf instead of printing?

### ISSUE THREAD

**Issue by JackMcBride98** [MatthewHerbst/react-to-print#454]
I like the way the component is converted to pdf, but I think I have used the wrong library for the job.

**Comment by JackMcBride98** [comment]
I've done some more reading and I see I could use the print method, but I am unsure what to do when it says function must return a promise. What should the promise do? Are there any examples of using this function to immediately download the generated content?

**Comment by MatthewHerbst** [comment]
Hello, and thanks for checking out the library. To be very clear, `react-to-print` does not generate PDFs. We simply generate an iframe and then tell the browser to print it. How the browser does that is completely up to each browser, there is no standard. The PDF that you can download from most browser print previews is actually generated by the browser, not by us.

Now, to get to your question, you certainly could overwrite the print and use another library to generate the PDF, and then download it. That would look something like this:

```tsx
const handlePrint = (iframe: HTMLIframeElement) => {
  // You could certainly make this method `async` and use `await` within if the code you call inside this
  // function also uses Promises. Since most browser code is synchronous normally you have to write
  // the Promise like this and then manually call `resolve` once everything is done 
  return new Promise((resolve, reject) => {
    try {
      const pdf = SomeCoolPDFLibrary.generateFromNode(iframe);
      download(pdf); // Presumably a function you have defined somewhere
      resolve();
    } catch (error) {
      reject(error);
    }
  });
};

<ReactToPrint
  ...
  print={handlePrint}
/>
```

**Comment by JackMcBride98** [comment]
Hi Matthew,
Thank you very much for the response. I have spoken to my design team and they are happy with the current implementation we have (using react-to-print), which opens the print menu with the option to save as pdf. This library is a pleasure to use. Converting react components to pdf is not the easiest thing to do. Thanks again :)

**Comment by MatthewHerbst** [comment]
Please don't hesitate to let us know if you have any other questions or issues. Thanks!
