### ISSUE TITLE
Custom header and footer from <div>

### ISSUE THREAD

**Issue by marco910** [MatthewHerbst/react-to-print#457]
Is there a way to add a `<div>` on every page as custom header and footer?

**Comment by MatthewHerbst** [comment]
Hello. We don't specify header/body/footer content, we just take whatever is within you React component. What you could do is modify your React component during printing. This gets a little annoying with functional components because there is no callback in set state the way there is with class components using `this.setState(newState, callback)`:

```jsx
import React, { useEffect, useRef } from 'react';
import { useReactToPrint } from 'react-to-print';

import { ComponentToPrint } from './ComponentToPrint';

const Example = () => {
  const componentRef = useRef();

  const [printing, setPrinting] = useState(false);
  const onBeforeGetContentResolve = useRef(null);

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    onAfterPrint: () => {
      setPrinting(false);
    },
    onBeforeGetContent: () => {
      return new Promise((resolve) => {
        setPrinting(true);
        onBeforeGetContentResolve = resolve;
      });
    },
  });

  useEffect(() => {
    if (printing && onBeforeGetContentResolve.current) {
      onBeforeGetContentResolve.current(); // Resolves the Promise in `onBeforeGetContent`
    }
  }, [printing, onBeforeGetContentResolve]);

  // If you do this a lot you could create a component with props such as
  // <PrintTemplate content={<ComponentToPrint />}> and the
  // PrintTemplate would just always include the PrintHeader and PrintFooter
  return (
    <div>
      <div ref={componentRef}>
        {printing && <PrintHeader />}
        <ComponentToPrint />
        {printing && <PrintFooter />}
      </div>
      <button onClick={handlePrint}>Print this out!</button>
    </div>
  );
};
```

Hope that helps, please let me know if you run into other issues.

**Comment by marco910** [comment]
@MatthewHerbst Thank you so much for that!
I only had to change the `useRef` for `onBeforeGetContentResolve` to a `useState` but now it's working. 

But I noticed that this is not working with multiple pages. Is there a way to get it working?

**Comment by MatthewHerbst** [comment]
Glad you got the first step going. As noted above, `react-to-print` has no knowledge of the number of pages the content will take to print, that is determined by the browser. If you know the size of your components you can the [CSS `page-break-after` property](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after) to force each set onto a new page:

```jsx
const content = myContent.map((content, i) => {
  if (!printing) {
    return <ContentComponent content={content} key={i} />;
  }

  return (
    <div key={i} style={{ pageBreakAfter: 'always' }}>
      <PrintHeader />
      <ContentComponent content={content} />
      <PrintFooter />
    </div>
  );
});

return (
  <div>
    <div ref={componentRef}>
      {content}
    </div>
    <button onClick={handlePrint}>Print this out!</button>
  </div>
);
```

**Comment by phanquanDHTB** [comment]
> Glad you got the first step going. As noted above, `react-to-print` has no knowledge of the number of pages the content will take to print, that is determined by the browser. If you know the size of your components you can the [CSS `page-break-after` property](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after) to force each set onto a new page:
> 
> ```js
> const content = myContent.map((content, i) => {
>   if (!printing) {
>     return <ContentComponent content={content} key={i} />;
>   }
> 
>   return (
>     <div key={i} style={{ pageBreakAfter: 'always' }}>
>       <PrintHeader />
>       <ContentComponent content={content} />
>       <PrintFooter />
>     </div>
>   );
> });
> 
> return (
>   <div>
>     <div ref={componentRef}>
>       {content}
>     </div>
>     <button onClick={handlePrint}>Print this out!</button>
>   </div>
> );
> ```

i need render antd table with header multiple page, can u help me?

**Comment by bishoymelek** [comment]
Hello,
I don't get the example mentioned, I want to add a footer in each page, but sometimes it gets in the middle of the page, especially if the user changed the page size for example. Do I have to define specific `height` or `size` for the @page or something? I want to enforce it to be letter size. I tried but it's gets weird.

**Comment by MatthewHerbst** [comment]
Hi @bishoymelek. There are many ways to do thing like this. If you could provide an example of your code that would be helpful.
