### ISSUE TITLE
Print button only works the first time

### ISSUE THREAD

**Issue by daiichie** [MatthewHerbst/react-to-print#463]
I'm having an issue where all is good the first time I press print, and then if I close the print dialog (either by save or cancel) and press the print button again, the dialog does not open a second time. 

I can post code, but this happens even on the very basic ComponentToPrint example in readme. Could this perhaps be an issue with my browser? 

Thanks for any assistance!

**Comment by MatthewHerbst** [comment]
Hello. What browser/browser version are you using?

**Comment by daiichie** [comment]
I'm using Chrome! (Version 97.0.4692.99 (Official Build) (64-bit))

**Comment by MatthewHerbst** [comment]
I'm able to print the official example (https://codesandbox.io/s/rzdhd) multiple times on MacOS Chrome 97.0.4692.99 (Official Build) (x86_64) without issue. Have you tried turning off all of your extensions?
