### ISSUE TITLE
When calling the print function is generating unnecessary pages

### ISSUE THREAD

**Issue by caioorg** [MatthewHerbst/react-to-print#464]
Hey guys, how are you?

I'm experiencing a problem in my project when I try to call the useReactToPrint hook it opens the save option but I'm rendering unnecessary pages.

I'll put below print of the function call and what is being referenced to save.

1 - here is the reference I create
```jsx
  const summaryRef = useRef<HTMLDivElement>(null)
```

2 - hook configuration and call
```jsx
 const onHandlePrintPage = useReactToPrint({
    content: () => summaryRef.current,
    onBeforePrint: () => setDisabled(true),
    onAfterPrint: () => setDisabled(false),
    documentTitle: 'admissao',
    removeAfterPrint: true
  })
```

3 - Call to action hook useReactToPrint
```jsx
<ButtonIcon onClick={() => onHandlePrintPage()} leadingIcon={<Printer />} />
```

4 - HTML reference to be downloaded
```jsx
<div ref={summaryRef}>
  {summary?.visit.visits && summary.visit.visits.length > 0 && (
    <Box width='100%'>
      <TabContainer position='left'>
        {summary.visit.visits?.map((_, index) => {
          return (
            <Tab
              active={activeVisit === `visit-${index + 1}`}
              key={index}
              sx={tab}
              handleClick={(e: string) => setActiveVisit(e)}
              style={{ width: `calc(100% / ${summary.visit.visits.length})` }}
              label={`Visita ${index + 1}`}
              tabName={`visit-${index + 1}`}
            />
          )
        })}
      </TabContainer>
      <TabPanesContainer activeTab={activeVisit}>
        {summary.visit.visits?.map((item, index) => {
          return (
            <TabPane key={index} tabName={`visit-${index + 1}`}>
              <Spacing size='sm' />
              <Pack direction='row'>
                <Box width='40%'>
                  <Body>N° do pedido: {item.order}</Body>
                  <Body>FAP: -</Body>
                </Box>
                <Box width='60%'>
                  <Action>Horário da coleta: {moment(item.visitDate).format('DD/MM - HH:mm')}</Action>
                </Box>
              </Pack>

              <Spacing size='xxs' />
              <Pack direction='column'>
                <ExamsList data={item.exams} />
              </Pack>
            </TabPane>
          )
        })}
      </TabPanesContainer>
    </Box>
  )}
</div>
```

5 - rendering on the front

<img width="818" alt="Captura de Tela 2022-02-10 às 17 54 31" src="https://user-images.githubusercontent.com/29618154/153494982-a5ddd553-1829-494c-8d7d-80f4f8ba5fd7.png">

6 - bug generated when trying to do action

<img width="1001" alt="Captura de Tela 2022-02-10 às 17 54 42" src="https://user-images.githubusercontent.com/29618154/153495006-c33a6f7d-69f6-4e28-b67a-48de00b68e64.png">

**Note**: _This bug also occurs natively using window.print() I believe the package uses this under the hood to generate the pdf._

**Additional Information**:
- Chrome: _version 97.0.4692.99_
- React: _17.0.2_
- React To Print: _2.14.4_

**Comment by MatthewHerbst** [comment]
Hi, thanks for writing in

> **Note**: _This bug also occurs natively using window.print() I believe the package uses this under the hood to generate the pdf_

That's correct. Under the hood we build a completely new window in an `iframe` with just the content you want to print, and then we call `window.print` on that iframe.

One thing I should note is that `react-to-print` does not generate a PDF. That's something your browser does for you, and each browser might do it a bit differently.

> bug generated when trying to do action

Are you able to see any errors in your developer console?

**Comment by Andrparsons** [comment]
Hi,

I don't know if this is helpful, but I have also come across this bug. It is only happening in chrome and seems to be triggered by adding a bodyClass. Removing the class allows printing as normal if you can live without styling it.

**Comment by MatthewHerbst** [comment]
@Andrparsons any chance you could share a codesandbox replicating the problem?
