### ISSUE TITLE
fonts not loading on chrome only

### ISSUE THREAD

**Issue by sailordotcom** [MatthewHerbst/react-to-print#465]
The fonts work on safari and firefox but does not seem to work on chrome. 

I don't have the time to reproduce you a code pen sorry.

**Comment by MatthewHerbst** [comment]
Hello, thanks for the report. Could you at least please show me a code snippet of how you are using fonts? I have a custom font loaded in the [official Codesandbox example](https://codesandbox.io/s/rzdhd), and it loads on Chrome on my machine without issue
