### ISSUE TITLE
Not working in Chrome 99 when inside of `iframe`

### ISSUE THREAD

**Issue by xch1029** [MatthewHerbst/react-to-print#470]
version    99.0.4844.51

**Comment by MatthewHerbst** [comment]
Hello, thanks for the report. I can confirm that the codesandbox version is not working on Chrome 99, but locally on Chrome 99 it works without issue. Could you please provide more details on where and how you are using the package?

**Comment by YaoHuangMark** [comment]
Yes, I have encountered it, print the blank。The same browser version

**Comment by MatthewHerbst** [comment]
Yes, but can you please show me the code you are using to put it on your website?

**Comment by YaoHuangMark** [comment]
React：16.12.0
react-to-print：2.14.4
Chrome：99.0.4844.51

**Comment by MatthewHerbst** [comment]
The versions are helpful, thank you. Can you please show the actual code you are using? 代码示例或示例

**Comment by YaoHuangMark** [comment]
@MatthewHerbst 
```javascript
// Parent Component
const componentRef = useRef(null)
const handlePrint = useReactToPrint({
  content: () => componentRef.current
})
const setPrintInfo = async() => {
  try {
    const res = await operatorPrintOrder({})
    setListInfo(res)
    handlePrint?.()
  } catch (error) {}
}

return (
  <>
     <DetailPrint ref={componentRef}  />
    <button onClick={() => setPrintInfo()}></button>
  </>
)
//  DetailPrint   Component
const DetailPrint = React.forwardRef((props, ref) => {
  return (
    <div ref={ref}>
      <h1>anything....</h1>
    </div>
  )
})

```
My page is in iframe. But, If are not in my iframe, everything is normal.

**Comment by xch1029** [comment]
me too. I use useReactToPrint api and my page is in an iframe

**Comment by MatthewHerbst** [comment]
@YaoHuangMark thank you, that is very helpful

@xch1029 thank you

Codesandbox also runs the code in an `iframe` and it is not working there.
It seems clear to me that the `iframe` is likely the issue. I will investigate, hopefully can fix very soon

**Comment by MatthewHerbst** [comment]
Bug report filed with Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1303840

**Comment by MatthewHerbst** [comment]
The Chrome team has confirmed that this is a Bug-regression in Chrome. Waiting to see estimates on when they think it might get fixed

**Comment by YaoHuangMark** [comment]
> The Chrome team has confirmed that this is a Bug-regression in Chrome. Waiting to see estimates on when they think it might get fixed

@MatthewHerbst  very happy to hear this news and thank you very much.

**Comment by YaoHuangMark** [comment]
@MatthewHerbst 
I am thinking, is there an alternative, or say that we can only wait for chromium to solve this bug?

**Comment by MatthewHerbst** [comment]
> I am thinking, is there an alternative, or say that we can only wait for chromium to solve this bug?

Unfortunately I am note aware of a way for us to fix this since it is a problem with Chromium itself. If you are able to remove the `iframe` then as we know it should work.

The Chromium team has given the bug priority 2, so I think it should get fixed very soon I hope 🙏

**Comment by YaoHuangMark** [comment]
> > I am thinking, is there an alternative, or say that we can only wait for chromium to solve this bug?
> 
> Unfortunately I am note aware of a way for us to fix this since it is a problem with Chromium itself. If you are able to remove the `iframe` then as we know it should work.
> 
> The Chromium team has given the bug priority 2, so I think it should get fixed very soon I hope 🙏

Yes, I know remove `iframe` can be used normally, but I can't get it now, so I am very troubled.

**Comment by MatthewHerbst** [comment]
The Chrome team has created a fix and merged it. It should be available in Chrome Canary builds starting tomorrow. They usually issue patch releases every 2-3 weeks so hopefully the fix should be released in the main version very soon.

**Comment by YaoHuangMark** [comment]
> The Chrome team has created a fix and merged it. It should be available in Chrome Canary builds starting tomorrow. They usually issue patch releases every 2-3 weeks so hopefully the fix should be released in the main version very soon.

I greatly hope that they will go online tomorrow 🙈

**Comment by YaoHuangMark** [comment]
I have solved it in a special way, which is to let the newly created iframe display in the screen. 🤣🤣🤣

**Comment by xch1029** [comment]
> 

not work for me

**Comment by xch1029** [comment]
> I have solved it in a special way, which is to let the newly created iframe display in the screen. 🤣🤣🤣

not work for me

**Comment by YaoHuangMark** [comment]
> > I have solved it in a special way, which is to let the newly created iframe display in the screen. 🤣🤣🤣
> 
> not work for me

React-to-print creates a iframe and set to not display within the screen, you must display it within the screen, just set it as `position = fixed` and `z-index = -1`.

You either clone the source code down to modify it, or use `patch-package`.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/20807958/158044370-a51046e8-e16e-4059-858c-0520e9fd7111.png">

**Comment by jiaoguanwen** [comment]
same problem, BUT I found when browser URL is SAME with iframe src, it will be fine. MAYBE it is chrome's new security law.

**Comment by MatthewHerbst** [comment]
@jiaoguanwen [the bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1303840) has been identified and fixed by the Chrome team. The fix will ship in Chrome 100.

**Comment by say1921** [comment]
I have encountered it, print the blank. The same browser version

**Comment by MatthewHerbst** [comment]
I was just able to upgrade my Chrome to version 100 and I can confirm it works. Thanks all!
