### ISSUE TITLE
i new chrome browser iframe and svg d3 charts print is not working and crashing the website

### ISSUE THREAD

**Issue by mohamedikram-qapita** [MatthewHerbst/react-to-print#471]
custom hook 
```jsx
import { useRef, useState } from 'react';
import { useReactToPrint, IReactToPrintProps } from 'react-to-print';

export const usePrint = (
  config: IReactToPrintProps = { content: () => null },
): [boolean, any, (() => void) | undefined] => {
  const [isPrinting, setIsPrinting] = useState<boolean>(false);

  const componentRef: any = useRef();

  const handlePrint = useReactToPrint({
    ...config,
    content: () => componentRef?.current,
    onBeforeGetContent: () => setIsPrinting(true),
    onBeforePrint: () => setIsPrinting(false),
  });

  return [isPrinting, componentRef, handlePrint];
};
```

in the component im calling as
```jsx
const [isPrinting, componentRef, handlePrint] = usePrint({
    content: () => null,
  });

  const handlePrinter = () => {
    if (handlePrint) {
      handlePrint();
    }
  };
```

output i have attached image
![Screenshot from 2022-03-14 13-26-48](https://user-images.githubusercontent.com/95607047/158328714-19c6fab1-ba9c-4604-92a3-7f795211ba7c.png)

**Comment by MatthewHerbst** [comment]
What errors are you getting? Also, calling the state methods in the callbacks will not work as expected. The state methods are asynchronous, and printing might happen before your state effects and/or re-renders happen.

**Comment by mohamedikram-qapita** [comment]
@MatthewHerbst  i have made changes after going through examples still page is crashing.kindly check the video i have attached
```jsx
const componentRef = React.useRef(null);
const reactToPrintContent = React.useCallback(() => {
  return componentRef.current;
}, [componentRef.current]);

const reactToPrintTrigger = React.useCallback(() => {
  return <button>Print using a Functional Component</button>;
}, []);

return (
  <ReactToPrint
    content={reactToPrintContent}
    documentTitle="AwesomeFileName"
    removeAfterPrint
    trigger={reactToPrintTrigger}
  />
  <CustomComponent ref={componentRef} />
)
```

https://user-images.githubusercontent.com/95607047/158347944-4d823637-c459-40de-a2dc-d6cb43abfda8.mp4

**Comment by MatthewHerbst** [comment]
Hello. Are you getting any errors in the developer console?

**Comment by mohamedikram-qapita** [comment]
no im not getting any error in developer console

https://user-images.githubusercontent.com/95607047/158520328-86228e25-5183-42fa-9c4e-96f1c5f64950.mp4

**Comment by MatthewHerbst** [comment]
Hmm, very strange. Any chance you could make a Codesandbox example of the error so I can debug?

**Comment by mohamedikram-qapita** [comment]
yeah sure i will try to add that things in code sand box

**Comment by MatthewHerbst** [comment]
Hello. Did you solve your problems?
