### ISSUE TITLE
Any Working Example? 

### ISSUE THREAD

**Issue by nassif7** [MatthewHerbst/react-to-print#473]
I have been trying with the sandbox examples but unfortunately it did not work, also tried locally and the same it is not working. 

``` 
"react": "^17"
"react-to-print": "^2.14.4"
"typescript": "^4.4.4"
```

**Comment by MatthewHerbst** [comment]
What browser are you using? The Codesandbox example doesn't work on Chrome 99 due to #470, but that will be fixed in Chrome 100.
