### ISSUE TITLE
How to force set page size as B4

### ISSUE THREAD

**Issue by MuttakinHasib** [MatthewHerbst/react-to-print#477]
I want to set default page size as B4 when its popup for print

**Comment by MatthewHerbst** [comment]
Use the CSS [`size`](https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size) property with a [`media`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) query

```css
@media print {
  size: B4;
}
```
