### ISSUE TITLE
Styled not showing in dark mode

### ISSUE THREAD

**Issue by waptik** [MatthewHerbst/react-to-print#478]
Hi. I came across this library yesterday after trying various libs without result.
I am using this lib along with [nextjs](https://nextjs.org) and [chakra-ui](https://chakra-ui.com) and they work great. But one issue I am facing is that when I enable dark mode, the styles don't show up in both the preview and downloaded pdf file.
My app itself uses dark mode and it's one of its core features.
Is there a way around it?

Here's a live reproduction of my use case: https://codesandbox.io/s/quizzical-browser-jcvyjb

**Comment by MatthewHerbst** [comment]
Hey, looking into it. My guess is chakra-ui, like many component libraries, does some weird things with print styles. Will let you know what I find, but I probably can't dive into it until this weekend

**Comment by waptik** [comment]
Oh ok, no problem. No hurry with that. I'll just have to delay the printing
feature for now(not a major one)

**Comment by singhkunal2050** [comment]
Same for me with tailwind and create-react-app v18

**Comment by MatthewHerbst** [comment]
I'm no longer able to reproduce this issue: printing from the original example when in dark mode correctly creates a print preview with dark mode, and when saving to PDF via chrome, the saved PDF has the correct dark mode theme. Please let me know if this is still an issue and happy to re-open and look into it further

**Comment by amarstb** [comment]
Facing the same issue while using material UI components

**Comment by MatthewHerbst** [comment]
> Facing the same issue while using material UI components

Could you please provide reproduction steps, or ideally a working demo? At minimum I would expect to know what dependency versions you are using. Thanks!
