### ISSUE TITLE
Can't print table on Google Chrome

### ISSUE THREAD

**Issue by UKRx** [MatthewHerbst/react-to-print#48]
when i click button to print data in data in tbody can't display on print mode but show in non-print mode

Google Chrome
Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by MatthewHerbst** [comment]
@UKRx did you get it to work? If not, can you post an MVP example of the code to reproduce the problem please?

**Comment by MatthewHerbst** [comment]
@UKRx any update on this please?
