### ISSUE TITLE
Issues on Chrome

### ISSUE THREAD

**Issue by gabycperezdias** [MatthewHerbst/react-to-print#482]
If my content has more than 1 page (either due to content itself of page-break) Chrome only prints the first page (don't even show more pages available). Any idea what this could/how to fix?

**Comment by MatthewHerbst** [comment]
Hello. Could you please share an example such as on Codesandbox? Thanks!

**Comment by gabycperezdias** [comment]
Hi, I am so sorry, I went to try and create an example on CodePen but everything was working so I started to dig deeper, and I have a `body > overflow: hidden` on my code, and since `copyStyles` is true by default the body on the iframe was also overflow hidden. 

To fix this I could either set copyStyles to false (but that broke the design of the printing page) or set `pageStyle` and overwrite the body to be overflow unset. Now everything seems to be working :) Sorry about that...

**Comment by MatthewHerbst** [comment]
No problem, glad you got it working!
