### ISSUE TITLE
Can you download PDF without the print preview? 

### ISSUE THREAD

**Issue by rkushkuley** [MatthewHerbst/react-to-print#483]
I saw this was brought up a few years ago? Is it still not possible?

or is possible to force settings ex. portrait, save as pdf, default scale, etc?

**Comment by MatthewHerbst** [comment]
Unfortunately there is no standard API to interact with the browser's print preview pane, so at this time that is not possible. If you want to download directly as a PDF without printing you'll need to find a PDF generation library, generate the PDF on the user's client or on your server, and then download the file that way. I hope this will be possible in the browser in the future, but it's not today 😢
