### ISSUE TITLE
`<style>` tags being treated as empty `<link>` tags

### ISSUE THREAD

**Issue by brucethomaswayne6** [MatthewHerbst/react-to-print#485]
Prompt this question as I print: 
![image](https://user-images.githubusercontent.com/52198079/162566986-dcea54ff-f5f7-4ae4-bfcf-2d1da7b822ad.png)
Not displayed correctly:
![image](https://user-images.githubusercontent.com/52198079/162567033-b760c3cc-c02e-4ad2-b7d7-409eb9348fec.png)

codesandbox: https://codesandbox.io/s/damp-sky-xexium?file=/src/ComponentToPrint.tsx

**Comment by MatthewHerbst** [comment]
It seems we are being too strict in our checking of `<style>` tags. Currently we check to see if the `tagName === 'STYLE'` but it seems it can also be lower-case `'style'` sometimes. I'll make the check more resilient and have a fix shortly.

**Comment by MatthewHerbst** [comment]
Ok, v2.14.6 fixes the warnings, but it still does not print the selection. Will keep looking

**Comment by MatthewHerbst** [comment]
It's strange, because in the [official example codesandbox](https://codesandbox.io/s/rzdhd) radio buttons print without problem, so it makes me think the issue is something with `survey-react`, not sure yet though

**Comment by brucethomaswayne6** [comment]
> It's strange, because in the [official example codesandbox](https://codesandbox.io/s/rzdhd) radio buttons print without problem, so it makes me think the issue is something with `survey-react`, not sure yet though

 `survey-react`   radio is a SVG img.  and When selected, modify SVG fill color.

**Comment by MatthewHerbst** [comment]
Yeah, not sure why that isn't being picked up, we already have a test for making sure we do SVGs properly and there is no problem there. Will look into it tonight

**Comment by brucethomaswayne6** [comment]
> Yeah, not sure why that isn't being picked up, we already have a test for making sure we do SVGs properly and there is no problem there. Will look into it tonight

ok, thinks.
