### ISSUE TITLE
Printing additional components between selected component ref

### ISSUE THREAD

**Issue by lucaswong98** [MatthewHerbst/react-to-print#488]
Hi, I have a component that I want to print, but I would like to add it in between other components, such as the <Header /> & <Footer /> components without rendering other parts of the page, how would I achieve that? Because the content props are only accepting ref

**Comment by MatthewHerbst** [comment]
Hello. Do you mind sharing a code example please? I think I'll better understand what you're asking that way. My guess is that you should be using the `onBeforeGetContent` callback to change the content of the print

**Comment by cardechr** [comment]
Don't mean to hijack OP question, but roughly same question. Currently we have micro frontends all using SPAs. Is there anyway to get an element from one of the micro frontends I.E. Logo Image by id, class, etc. And render it only for the component I'm trying to print?

**Comment by MatthewHerbst** [comment]
@cardechr no problem, though I would ask similar to the above that you please share a code sample of what exactly you are trying to do, thanks!

**Comment by lucaswong98** [comment]
After looking at the closed issues, I found a similar issue that has the same question as mine.

https://github.com/gregnb/react-to-print/issues/457

I've followed the code in here and managed to render the header and footer component tgt with the components referenced.

**Comment by MatthewHerbst** [comment]
@lucaswong98 great to hear! If possible, could you please share the finished code so people in the future know how to put it all together? Thanks

**Comment by cardechr** [comment]
Funny enough, I ended up doing that similar to [#457](https://github.com/gregnb/react-to-print/issues/457) and it's working. Thanks
