### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'value')     at HTMLIFrameElement.f.onload (index.js:2:1)

### ISSUE THREAD

**Issue by 3egg** [MatthewHerbst/react-to-print#493]
```js
const [activeKey, setActiveKey] = useState<any>(['basic']);
const [triggerPrint, setTriggerPrint] = useState<boolean>(false);
const expandPanels = (open = false) => {
      if (open) {
        const keys = data.map(a => a.key);
        allSectionKeys.push('basic');
        setActiveKey(keys);
        setTriggerPrint(open);
      } else {
        setActiveKey(['basic'])
        setTriggerPrint(open);
      }
    }
}

useEffect(() => {
  if (triggerPrint) {
    handlePrint();
  }
}, [triggerPrint])

const handlePrint = useReactToPrint({
  content: () => componentRef.current,
  onAfterPrint: () => expandPanels(false)
});

return(
    <Button
    onClick={() => expandPanels(true)}
    />
)

```

There is a expandable panel in the page, when click print btn, we will expand all panels.
No idea why this cannot work, anyone can help?

**Comment by MatthewHerbst** [comment]
Hello. Can you provide the full example please? For example, where is `componentRef` defined? A working codesandbox replicating the problem would be ideal please

**Comment by 3egg** [comment]
https://codesandbox.io/s/musing-cannon-i77sqr?file=/src/demo.js
Hi @MatthewHerbst  u can find the example from the above link.
No this uncaught TypeError now, but the print is a little bit later than the latest UI. But if setTimeOut then is Fine.
```js
setTimeout(() => {
handlePrint();
}, 100)
```

**Comment by MatthewHerbst** [comment]
On my computer I don't see any noticeable delay, but it could just be a rendering speed issue. Glad you have something that works for you. Are there still any issues I can help with?

**Comment by 3egg** [comment]
Well, it seems to my computer/code issue. sorry to bother you, YOU ARE THE BEST!

Thanks!

**Comment by MatthewHerbst** [comment]
Heh, not the best, but always trying to be better! Not a bother at all, please feel free to ask any other questions and report any other suspected issues. Really appreciate the codesandbox!
