### ISSUE TITLE
Destroying style of html page

### ISSUE THREAD

**Issue by taliha-arif** [MatthewHerbst/react-to-print#497]
I have HTML code returned from 3rd party service, now wants to print returned HTML code. Everything is working fine except a few of the text is hidden behind lines. Lines are crossing the text.

**Comment by taliha-arif** [comment]
This is how I am using react-to-print on button click:
`const componentRef = useRef()
	const handlePrint = useReactToPrint({
		content: () => componentRef.current,
	})`
	
And this is how I am passing HTML code to print:
`<div
							ref={componentRef}
							dangerouslySetInnerHTML={{ __html: labelData }}
						></div>`

**Comment by MatthewHerbst** [comment]
Hello, thanks for posting. Can you share what `labelData` looks like?

**Comment by taliha-arif** [comment]
> Hello, thanks for posting. Can you share what `labelData` looks like?

<div style='position: relative; margin-top: 25px; height: 800px;page-break-after: always;margin:0;padding:0;'><table style="font-family:arial;">
    <tr>
        <td width="0px">&nbsp;</td>
        <td valign="top" width="626px">
            <div style="position:absolute;">
                
    
        <span style='left:356px;top:34px;position:absolute;'><img
                src='data:image/gif;base64,R0lGODlhFABgAIAAAAAAAP///yH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxMzIgNzkuMTU5Mjg0LCAyMDE2LzA0LzE5LTEzOjEzOjQwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdFJlZj0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlUmVmIyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxNS41IChNYWNpbnRvc2gpIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjdCMTBDNjZGQTdGMjExRTY4RDhBQTcyRTI5Q0M2N0JFIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjdCMTBDNjcwQTdGMjExRTY4RDhBQTcyRTI5Q0M2N0JFIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6N0IxMEM2NkRBN0YyMTFFNjhEOEFBNzJFMjlDQzY3QkUiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6N0IxMEM2NkVBN0YyMTFFNjhEOEFBNzJFMjlDQzY3QkUiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4B//79/Pv6+fj39vX08/Lx8O/u7ezr6uno5+bl5OPi4eDf3t3c29rZ2NfW1dTT0tHQz87NzMvKycjHxsXEw8LBwL++vby7urm4t7a1tLOysbCvrq2sq6qpqKempaSjoqGgn56dnJuamZiXlpWUk5KRkI+OjYyLiomIh4aFhIOCgYB/fn18e3p5eHd2dXRzcnFwb25tbGtqaWhnZmVkY2JhYF9eXVxbWllYV1ZVVFNSUVBPTk1MS0pJSEdGRURDQkFAPz49PDs6OTg3NjU0MzIxMC8uLSwrKikoJyYlJCMiISAfHh0cGxoZGBcWFRQTEhEQDw4NDAsKCQgHBgUEAwIBAAAh+QQAAAAAACwAAAAAFABgAAACuoyPqcsLD5qKssFqMbra0L5x4HhAH3aOIplWK0qWb6yZYNvNufqodGD77RimoKSFSyBlS6WnNNlAn5NVsScEXpMOZpE4/STFVKAF60FntVdm1Gkuy6lkKXxrnx91rPb6X4WEF0cIo2fkBqcHNmU4p4NIyPVWmKb21LTY1ajFKBcB+pYSOqkUeVFqF1qDGfIFtYoS+cO1lQoY6KO5WenSi2t62ygsyUMMPISszEZ8zHkzqzzI2ndctxxQAAA7'/></span>
    

<span style='left:100px;top:0;position:absolute;font-size:12px;'><b>Responsible Delivery - CO<sub>2</sub> Neutral</b></span>
<span style='left:196px;top:88px;position:absolute;font-size:8px;'>Sender</span>
<span style='left:196px;top:96px;position:absolute;font-size:8px;'>DPD GROUP LTD</span>
<span style='left:196px;top:105px;position:absolute;font-size:8px;'>ROEBUCK LANE</span>
<span style='left:196px;top:114px;position:absolute;font-size:8px;'>SMETHWICK</span>
<span style='left:196px;top:123px;position:absolute;font-size:8px;'>BIRMINGHAM</span>
<span style='left:196px;top:132px;position:absolute;font-size:8px;'></span>
<span style='left:196px;top:141px;position:absolute;font-size:8px;'>B66 1BY</span>
<span style='left:242px;top:145px;position:absolute;font-size:8px;'>Phone:0121 500 2500</span>
<span style='left:250px;top:88px;position:absolute;font-size:8px;'>Account:3015872</span>

    <span style='left:4px;top:19px;position:absolute;font-size:12px;'>TR</span>
<span style='left:4px;top:30px;position:absolute;font-size:12px;'>HEADINGTON</span>
<span style='left:4px;top:41px;position:absolute;font-size:12px;'></span>
<span style='left:4px;top:52px;position:absolute;font-size:12px;'>OXFORD</span>
<span style='left:4px;top:63px;position:absolute;font-size:12px;'></span>
<span style='left:4px;top:74px;position:absolute;font-size:12px;'>OX1 4BH</span>
<span style='left:90px;top:74px;position:absolute;font-size:12px;'>United Kingdom</span>
<span style='left:220px;top:68px;position:absolute;font-size:18px;'></span>
<span style='left:4px;top:88px;position:absolute;font-size:8px;'>Contact</span>
<span style='left:4px;top:120px;position:absolute;font-size:8px;'>Consignment</span>
<span style='left:4px;top:128px;position:absolute;font-size:8px;'>Ref</span>
<span style='left:4px;top:104px;position:absolute;font-size:8px;'>Info</span>

    <span style='left:60px;top:104px;font-size:8px;position:absolute;'></span>
    <span style='left:60px;top:112px;font-size:8px;position:absolute;'></span>

<span style='left:60px;top:88px;position:absolute;font-size:8px;'>TR</span>
<span style='left:60px;top:120px;position:absolute;font-size:8px;'>6882973993</span>
<span style='left:60px;top:128px;position:absolute;font-size:8px;'></span>
<span style='left:60px;top:136px;position:absolute;font-size:8px;'></span>
<span style='left:60px;top:144px;position:absolute;font-size:8px;'></span>

<span style='left:284px;top:18px;position:absolute;font-size:8px;'>Packages</span>
<span style='left:276px;top:48px;position:absolute;font-size:8px;'>Total Weight</span>
<span style='left:274px;top:26px;position:absolute;font-size:16px;'>1 of 1</span>
<span style='left:274px;top:56px;position:absolute;font-size:16px;'>1 kg</span>

                <span style='left:6px;top:180px;position:absolute;font-size:8px;'>Track</span>
<span style='left:350px;top:180px;position:absolute;font-size:8px;'>Service</span>
<span style='left:5px;top:158px;position:absolute;font-size:22px;'>1597</span>
<span style='left:62px;top:160px;position:absolute;font-size:16px;'>6882 9739 93P</span>
<span style='left:5px;width:370px;top:250px;position:absolute;font-size:10px;text-align:center;'>      25/05/22 16:36 Web 4.6.5-api      </span>
<span style='left:19px;top:265px;border-top-style:solid;border-width:thin;position:absolute;'><img width='348px' height='95px' src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAegAAAAOCAMAAADT5H8VAAADAFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALI7fhAAABAHRSTlP//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKmfXxgAAGslJREFUeNoBvhpB5QABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBAQABAQEBAAABAQAAAAABAQAAAAAAAAAAAQEAAAAAAAABAQAAAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEBAQAAAAABAQAAAAAAAAEBAQEBAQAAAQEBAQAAAQEBAQEBAAAAAAAAAQEAAAEBAQEAAAEBAAAAAAEBAQEBAQAAAAABAQEBAAABAQEBAAAAAAEBAAAAAAEBAQEBAQAAAQEAAAAAAAABAQAAAQEBAQAAAAAAAAEBAQEAAAAAAAABAQAAAQEAAAAAAAABAQAAAQEBAQEBAAABAQEBAQEBAQAAAQEAAAEBAQEBAQAAAAABAQEBAAAAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQAAAAAAAAAAAQEAAAAAAQEBAQAAAQEAAAAAAQEAAAAAAQEBAQEBAQEAAAEBAQEBAQEBAAABAQAAAQEAAAAAAAABAQEBAAABAQAAAAAAAAEBAAAAAAAAAQEAAAEBAAAAAAAAAQEBAQEBAQEAAAEBAAAAAAEBAAABAQEBAQEBAQAAAAABAQEBAQEAAAAAAQEBAQAAAQEAAAAAAQEBAQEBAAAAAAEBAAAAAAEBAQEAAAEBAAAAAAAAAQEBAQAAAQEBAQEBAAABAQEBAAAAAAAAAQEBAQEBAAABAQAAAQEBARqxDZHS2CzNAAAAAElFTkSuQmCC'/></span>
<span style='left:85px;top:363px;position:absolute;font-size:12px;'>0OX1 4BH1 5976 8829 7399 3812 826H</span>
<span style='right:5px;top:158px;width:250px;text-align:right;position:absolute;font-size:20px;'>       NEXTDAY PCL</span>
<span style='left:130px;top:230px;position:absolute;font-size:14px;'>   812-GB - OX1 4BH   </span>
<span style='left:10px;top:190px;position:absolute;font-size:18px;'></span>
<span style='left:10px;top:225px;position:absolute;font-size:30px;'></span>
<span style='right:10px;top:225px;position:absolute;font-size:30px;'>0029</span>
<span style='left:3px;top:183px;width:380px;font-size:46px;position:absolute;text-align:center;'>GB-OX1 4BH</span>

                <table style='display:inline-block;border:3px solid black;padding:0;border-spacing:0;border-collapse:collapse;' height='385' width='385px'>
    <tr>
        <td>
            <table style='padding:0;border-spacing:0;border-collapse:collapse;' width='100%'>
                <tr>
                    <td style='font-size:1px;border-bottom:1px solid black;' colspan='4'>
                        <div style='height:10px'>&nbsp;</div>
                    </td>
                </tr>
                <tr>
                    <td colspan='2' style='text-align:left;border-bottom:1px solid black;vertical-align:top;'>
                        <div style='height:69px'>&nbsp;</div>
                    </td>
                    <td style='border-bottom:1px solid black;border-left:1px solid black;'>&nbsp;</td>
                    <td style='border-bottom:3px solid black;border-left:1px solid black;' rowspan='2'>&nbsp;</td>
                </tr>
                <tr>
                    <td style='border-bottom:3px solid black;'>
                        <div style='height:66px'>&nbsp;</div>
                    </td>
                    <td style='border-bottom:3px solid black;border-left:1px solid black;' colspan='2'>&nbsp;</td>
                </tr>
                <tr>
                    <td style='text-align:left;vertical-align:top;' colspan='4'>
                        <div style='height:226px'>&nbsp;</div>
                    </td>
                </tr>
                <tr>
                    <td style='font-size:1px;' width='195px'>&nbsp;</td>
                    <td style='font-size:1px;' width='70px'>
                        <div style='height:1px'>&nbsp;</div>
                    </td>
                    <td style='font-size:1px;' width='80px'>&nbsp;</td>
                    <td style='font-size:1px;' width='40px'>&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

            </div>
        </td>
    </tr>
</table></div>
