### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by gorilla076** [MatthewHerbst/react-to-print#498]
Please update to React version 18. Currently react-to-print is using ^17.0.2.

**Comment by MatthewHerbst** [comment]
Hello. We already offer React 18 support. In our [`package.json`](https://github.com/gregnb/react-to-print/blob/87f67dcdc02b3d699c16fc241fde5c08e550b81e/package.json#L35-L38):

```json
  "peerDependencies": {
    "react": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0"
  },
```

The React ^17.0.2 version you see in the `devDependencies` is only if you want to run the `react-to-print` local examples.
