### ISSUE TITLE
Version 2.14.4 and up changes print output

### ISSUE THREAD

**Issue by Tian94** [MatthewHerbst/react-to-print#499]
Hello there,

We are experiencing an issue where version **2.14.4** and upwards changes our print outputs, previous versions seem to be working as expected.

**2.14.3** and below
<img width="341" alt="image" src="https://user-images.githubusercontent.com/64617278/173504360-03e8e001-d029-4195-a8e5-ef1a2b78e7da.png">

**^2.14.4**
<img width="352" alt="image" src="https://user-images.githubusercontent.com/64617278/173504110-16528a0e-5856-4192-b5bc-70df85a1e0fb.png">

Do you have any ideas on what changes in **2.14.4** have caused this or if it can be fixed in future versions?

Thanks in advance.

**Comment by MatthewHerbst** [comment]
In 2.14.4 we properly [set a `DOCTYPE` on the window](https://github.com/gregnb/react-to-print/blob/master/CHANGELOG.md#2144-january-24th-2022), which tells the browser to not use [quirks mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode). Apologies if this is causing upgrade pains, happy to help where I can

**Comment by Tian94** [comment]
Thanks for looking into this @MatthewHerbst , I'm wondering if you've come across a way to export the output to somewhere other than the print window as that's difficult to inspect? This way I could view differences between versions and work out exactly what's being altered.

**Comment by MatthewHerbst** [comment]
@Tian94 you could pass the `print` prop and then just console log it. That will override the default browser print method and allow you to see the `iframe` that has all the content being printed. If I had to guess the content of the DOM being printing is not changing. Rather, the way the browser interprets your content has changed slightly.

```tsx
const handlePrint = useReactToPrint({
  ...,
  print: (iframe: HTMLIFrameElement) => {
    console.log(iframe);
    return Promise.resolve();
  },
});
```
