### ISSUE TITLE
Only runs window.print if img tag is present

### ISSUE THREAD

**Issue by TheRohitSharma** [MatthewHerbst/react-to-print#5]
The browser's print dialog does not seem to trigger unless an img tag is present. It can even be an img tag with no actual image (e.g. <img src="" />) From the code, I can see that it assumes the content contains an image and then waits for the image(s) to load before firing window.print.

I can try my hand at a PR if needed.

**Comment by gregnb** [comment]
Ah boy, you know this is sloppy work on my part. I tried to solve another ticket related to images and missed this. Fixing it right now. Thank you

**Comment by TheRohitSharma** [comment]
No problem! Thanks for making this.

**Comment by gregnb** [comment]
No problem. Thanks for the feedback and bug report!

Just published 1.0.8 please try that
