### ISSUE TITLE
Text splitting

### ISSUE THREAD

**Issue by MatthewHerbst** [MatthewHerbst/react-to-print#500]
@[zakarehman270](https://github.com/zakarehman270)

I asked you to please create a new issue, not add more comments in the other (unrelated) issue.

> I have a problem React-to-print half text remain upper page and half remain lower page when print large content ??? please help
[ZULQARNAIN ALI ABID444.pdf](https://github.com/gregnb/react-to-print/files/8896394/ZULQARNAIN.ALI.ABID444.pdf)
>
> ![image](https://user-images.githubusercontent.com/104195807/173502243-fc3c28dd-7596-4171-9a95-810b104900f8.png)
>
> This is my code  
>
```jsx
  <ReactToPrint
    pageStyle="@page { size: auto; margin: 18mm; } }"
    content={reactToPrintContent}
    documentTitle={ResumeName}
    onAfterPrint={handleAfterPrint}
    onBeforeGetContent={handleOnBeforeGetContent}
    onBeforePrint={handleBeforePrint}
    removeAfterPrint
    trigger={reactToPrintTrigger}
  />
```
>
> My issue is that when I print some large text then some text remain upper page and some text remain lower page

**Comment by MatthewHerbst** [comment]
This appears to just be a styles/CSS issue. It would be helpful if you could make a working [codesandbox](https://codesandbox.io/) or similar that reproduces the issue, then I could help debug

**Comment by jaballogian** [comment]
I also faced this issue @zakarehman270

After searching, some answers from Stackoverflow didn't work in my case but then I modified this answer https://stackoverflow.com/a/55400513/8339172 and it worked in my case.

We could apply it to all elements on our app by adding this code to our general CSS file (for example `index.css` or `App.css`):
```css
* {
    page-break-inside: avoid;
}
```

Here is the result before implementing the code above (**the text "Delivery Note: ..." is split**):
![image](https://user-images.githubusercontent.com/24468466/182026193-422ff7b3-d6b0-49ef-ba6d-f1214e01046b.png)

Here is the result after implementing the code above (**no text is split**):
![image](https://user-images.githubusercontent.com/24468466/182026139-49197d4d-da21-42ae-b4db-7f3609782710.png)

I hope this answer could help and close the issue

**Comment by MatthewHerbst** [comment]
Thanks @jaballogian!
