### ISSUE TITLE
How to directly get binary or blob file of pdf so that I can send it to server and save it?

### ISSUE THREAD

**Issue by gunpreetsingh007** [MatthewHerbst/react-to-print#501]
I created a open URL on my react app which gets triggered by cron. I want to find a way to get the binary file of pdf just like form element , so that I can call a POST request and save the pdf file. Can someone help me on this?

**Comment by MatthewHerbst** [comment]
Hello. We don't actually generate a PDF. We just generate an `iframe` and then call `window.print` on it. The browser itself (Chrome, Firefox, Safari, etc) then decides how to handle it, and they have all built-in PDF functionality.

If you would like to generate a PDF from the front-end I suggest a library such as [`@react-pdf/renderer`](https://github.com/diegomura/react-pdf)

Please let me know if I can help in any other way.
