### ISSUE TITLE
Print pdf file from object URL

### ISSUE THREAD

**Issue by SutnuiBorshik** [MatthewHerbst/react-to-print#502]
Is it possible to print a pdf file by it's object URL?

I needed to print multiple pdf files at once. So I merged them into one via 3rd party lib. And created it's object URL by running
```javascript
URL.createObjectURL(new Blob([buffer], { type: "application/pdf" }));
```
Can it be printed by using this library?

**Comment by MatthewHerbst** [comment]
Hello. This library is specifically for printing parts of the web page (DOM). If the PDF is rendered within the DOM you want to print that should be printed. If you just want to create PDFs on the client you should instead use a library such as [`@react-pdf/renderer`](https://github.com/diegomura/react-pdf)

Please let me know if I can help in any other way.
