### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by ManavJoshi111** [MatthewHerbst/react-to-print#503]
Hello...
I am using react-to-print to print one of the functional components in my react project. The component is being printed perfectly but the links with <a></a> tags are not working in the pdf.

can you please help me with this?

**Comment by MatthewHerbst** [comment]
Hello. We don't generate the PDF, that's done by the browser, but happy to help check ensure we are generating the links correctly. Could you please share a working demo, maybe a CodeSandbox? That way I can help debug. Thanks!

**Comment by ManavJoshi111** [comment]
This is the sample CodeSandbox you have asked for...
https://codesandbox.io/s/inspiring-allen-po2h1u?file=/src/index.js
It has a link to google and works fine when we render the component but it doesn't work in PDF
Please help me ASAP

**Comment by MatthewHerbst** [comment]
The link works fine on my Windows machine when using Chrome (version 102.0.5005.115). What browser are you using?

**Comment by ManavJoshi111** [comment]
I'm not talking about the browser thing...
Please download the pdf and then try to use the link, it won't work
That's the issue I'm facing

**Comment by MatthewHerbst** [comment]
> Please download the pdf and then try to use the link, it won't work

I did. It worked fine for me.

What browser are you using?
What program are you using to open the PDF?

**Comment by ManavJoshi111** [comment]
I'm using google chrome version : 103.0.5060.66 (Official Build) (64-bit) (cohort: 103_Win_53) 
I'm using Adobe Acrobat Reader XI to open the pdf

**Comment by MatthewHerbst** [comment]
I think it must be a problem with Acrobat Reader XI. I've tested that it works for me using MacOS Preview, using Safari, using Chrome on Windows and MacOS.

Have you tried opening it with another program?

**Comment by ManavJoshi111** [comment]
I have tried on Google Chrome as well. It's not working

Could you please share the pdf which you've downloaded

**Comment by MatthewHerbst** [comment]
https://user-images.githubusercontent.com/1287375/176512981-4aab20c0-986e-4ea1-b3bb-120a08db872b.mov

**Comment by ManavJoshi111** [comment]
Thanks Man...
Actually It works on my mobile phone as well but I don't why it's not working on my laptop


I've tried opening my pdf using google chrome as well

**Comment by MatthewHerbst** [comment]
Might be some settings somewhere? Not sure honestly 😢 Please let me know if you figure it out!

**Comment by ManavJoshi111** [comment]
Got it man ... 💯
Actually, the print dialogue box has an option called destination in which I had to select save as pdf but the default one was Microsoft Print to pdf, that was the reason why it was not working


Btw, Thanks a lot for your support, seriously 👍

**Comment by MatthewHerbst** [comment]
Glad you got it working!
