### ISSUE TITLE
Printing page doesn't render on first opening, but second opening works

### ISSUE THREAD

**Issue by erkanisuf** [MatthewHerbst/react-to-print#504]
When i first time click the button to open the printing window, the text fields are not displayed at all, even tho it displays image base items. But when i close the printing window and reopen it again everything is fine.

Versions:
 "react-to-print": "^2.14.7",
 "react": "^17.0.2",
 "react-dom": "^17.0.2",

```
  <ReactToPrint
                        pageStyle={`@page {
                     margin: 18mm 5mm 18mm 5mm;
                     size: landscape;
                    }`}
                        trigger={() => <Button variant="outline-primary" className="px-3 mx-2"><i
                            className="fa-solid fa-print"></i> <span
                            className="d-none d-lg-inline">{l("buttons.print")}</span>
                        </Button>}
                        content={() => componentRef.current}
                    />

   <div style={{display:'none'}}>
<MyComponent  ref={componentRef}/>
</div>
```
Components are functional based.

**On first opening:**

![Screenshot 2022-06-23 at 10 28 39](https://user-images.githubusercontent.com/63913743/175241700-b7941e81-3c06-4c43-bf69-a6726b18c23d.png)

**Second Opening works fine:**

![Screenshot 2022-06-23 at 10 28 55](https://user-images.githubusercontent.com/63913743/175241756-2269923a-2f12-4a8a-a937-3232875afb9c.png)

**Comment by MatthewHerbst** [comment]
Hello. Thanks for sharing your issue. Would it be possible for you to make a CodeSandbox or similar that can reproduce the problem, or share a link with me to a website experiencing the problem? Would love to be able to debug to take a closer look at this. Thanks!

**Comment by dennemark** [comment]
Custom-font might not be loaded correctly. Using `font-display: swap` in `@font-face` might solve this: https://github.com/gregnb/react-to-print/issues/281#issuecomment-1098039528
At least it worked for me.
