### ISSUE TITLE
How to change icon size in printing without reflecting it in react component?

### ISSUE THREAD

**Issue by haresh6x** [MatthewHerbst/react-to-print#505]
Suppose I have icon component which accepts ```size``` prop. How do I change it only for the printing?

```jsx
// initial size
const [size, setSize] = useState(10)
```

```jsx
  const onBeforeGetContent = () => {
    setSize(200);
    return Promise.resolve();
  };

  const onBeforePrint = () => {
    setSize(100);
    return Promise.resolve();
  };

  const onAfterPrint = () => {
    setSize(100);
    return Promise.resolve();
  };
```

**Comment by MatthewHerbst** [comment]
You can use [CSS Media Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) to only apply styles during print:

```css
/* https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_types */
@media print {
  /* styles here will only be applied during printing */
}
```

Please let me know if I can help in any other way!

**Comment by haresh6x** [comment]
> You can use [CSS Media Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) to only apply styles during print:
> 
> ```css
> /* https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_types */
> @media print {
>   /* styles here will only be applied during printing */
> }
> ```
> 
> Please let me know if I can help in any other way!

Thanks for the fast reply. But as you can see I have a state variable ```size```. Its not from the CSS. Any idea how do I achieve that?

**Comment by MatthewHerbst** [comment]
Apologies, I for sure answered this right before going to bed late and misread I think what you're looking for.

Before giving the answer I think you want, I should note that somewhere in your component stack the `size` prop is changing CSS, so the answer I gave above certainly should work.

However, if your goal is to just change the value of the `size` prop during printing, that can be done with `onAfterPrint`, but it's a little convoluted.

```jsx
const promiseRef = useRef(null);
const [size, setSize] = useState(10);

useEffect(() => {
  // Check both that there is a promise to resolve AND that the state has actually changed
  if (promiseRef.current && size === 100) {
    // Resolve the promise, causing react-to-print to continue
    promiseRef.current();
  }
}, [promiseRef.current, size]);

const onBeforeGetContent = () => {
  return new Promise((resolve) => {
    // This is async: we don't know when React will actually make the state change
    setSize(100);
    promiseRef = resolve;
  });
};

const onAfterPrint = () => {
  setSize(10);
};
```
