### ISSUE TITLE
Bug - No CSS applied while printing using electron

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [MatthewHerbst/react-to-print#508]
I'm trying to print with electron using the following example:
https://github.com/gregnb/react-to-print/issues/270#issuecomment-1003447151

**Bug:**
Print is working fine, but without CSS.

**Sample Code:**
```ts
 const win = new BrowserWindow({ show: false }); // set show to true for preview
  win.loadURL(args.url);

  win.webContents.on('did-finish-load', () => {
    win.webContents.print(
      { printBackground: true },
      (success, failureReason) => {
        console.log('Print Initiated in Main...');
        if (!success) console.log('[print][failed]', failureReason);
      }
    );
  });
  ```

**Expected:**
CSS must be applied on print.

**Workaround:**
For now I'm using electron PDF to print function which works fine, but it's not proper solution.
```ts
  let win: any = new BrowserWindow({ show: false });

  win.loadURL(args.url);

  win.webContents.once('did-finish-load', () => {
    win.webContents
      .printToPDF({ printBackground: true })
      .then((data: any) => {
        const buf = Buffer.from(data).toString('base64');
        const url = `data:application/pdf;base64,${buf}`;

        // @ts-ignore
        win.webContents.on('ready-to-show', () => {
          if (process.env.NODE_ENV === 'development') win.show();
          win.webContents.print(
            { printBackground: true },
            (success, failureReason) => {
              console.log('Print Initiated in Main...');
              if (!success) console.log('[print][failed]', failureReason);
            }
          );
        });

        // @ts-ignore
        win.webContents.on('closed', () => {
          win = null;
        });

        return win.loadURL(url);
      })
      .catch((error) => {
        console.log(error);
      });
  });
  ```
  
 **Additional Info:**
  I can see all the CSS in inspect element (but not applied) - see attached screenshot for reference.
  
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/15345707/179804421-7303814e-cb03-4a42-b3bd-8d94bc24ba01.png">

**Comment by ahmedmukhtar1133** [comment]
**Client side sample code:**
```ts
  print: (target: any) => {
      return new Promise((resolve, reject) => {
        console.log('[Print] Forwarding request to the main process...');
        // convert the iframe into data url
        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
        const data = target.contentWindow.document.documentElement.outerHTML;

        const blob = new Blob([data], { type: 'text/html' });
        const url = URL.createObjectURL(blob);

        backend.print({ url }).then(resolve).catch(reject);
      });
    },
```

**Comment by MatthewHerbst** [comment]
Hello. Unfortunately I'm not an Electron expert so I really don't know much about what would cause it to not use the CSS. `react-to-print` simply provides the data to Electron, but we cannot control what it does with it.

I noticed in the linked example the author talks about putting some CSS in an `@page` directive, have you tried that? If you could share your full code in a codesandbox or github link that might be helpful as well. Thanks!

**Comment by ahmedmukhtar1133** [comment]
Yes, I've already put the CSS in @page directive but it's not working. I'll try to provide you github repo with minimal code.

**Comment by tokochi** [comment]
i had the same bug, and i did avoid it using styled components in my React App, CSS modules didn't work either
