### ISSUE TITLE
onAfterPrint not firing at all

### ISSUE THREAD

**Issue by croberembt** [MatthewHerbst/react-to-print#509]
onAfterPrint={() => console.log("PRINTING COMPLETE")} - this is just simply not firing at all for me. Seemingly having the same issue with onBeforePrint. Otherwise the library is working fine for me. Does it appear I am doing something wrong?

**Comment by MatthewHerbst** [comment]
Hello. Could you share your full code please, and what browser/device you are running into this issue on? As you can see in the [official demo](https://codesandbox.io/s/rzdhd) (see the console output on that page) `onBeforePrint` and `onAfterPrint` are working as expected

**Comment by croberembt** [comment]
I appreciate your super fast reply! I killed node modules and reinstalled and this resolved the issue. onAfterPrint is now working. Thanks again!
