### ISSUE TITLE
[ useReactToPrint] How to use documentTitle when use the hook [useReactToPrint]?

### ISSUE THREAD

**Issue by momolly1024** [MatthewHerbst/react-to-print#512]
Hi,
How can i use the documentTitle  api when i use the hooks useReactToPrint to print?

```jsx
const handlePrint = useReactToPrint({
        content: () => ref.current,
    })

```

```jsx=
<button onClick={handlePrint}>
    print 
</button>
```

 
Where should i add  [ documentTitle ] ?

**Comment by MatthewHerbst** [comment]
Hello. You can use the `onBeforeGetContent ` and `onAfterPrint` callbacks to change the title during print and then set it back to whatever you need after printing has completed. Note that this will not work if your code is running in an `iframe`. Please let me know if you run into issues with those, thanks!

**Comment by momolly1024** [comment]
Hi @MatthewHerbst,   
Thanks for replying. It's work now :) 
Have a nice day !

**Comment by MatthewHerbst** [comment]
Awesome! Please let us know if you run into any more issues 😀
