### ISSUE TITLE
Is there any way to print dynamic header and footer for multiple pages?

### ISSUE THREAD

**Issue by Saral33** [MatthewHerbst/react-to-print#514]
I am using an approach like this for the custom header and footer [https://plnkr.co/edit/lWk6Yd](https://plnkr.co/edit/lWk6Yd) . Works good if the header and is footer are static but if I am using the map function to print from array , it only use last element from array.

**Comment by MatthewHerbst** [comment]
Hello. Could you show an example of what you are trying to do please? Not sure exactly what your question is
