### ISSUE TITLE
When the font is bold in Song typeface when printing, the printing effect is not bold

### ISSUE THREAD

**Issue by longgegege** [MatthewHerbst/react-to-print#515]
When the font is bold in Song typeface when printing, the printing effect is not bold
 <div ref={headerRef} style={{
                display: "flex",
                justifyContent: "center",
                flexDirection: "column",
                padding: "70px 80px 0",
                fontFamily: "SimSun",
                fontWeight: 900,
            }} >加粗</div>

**Comment by MatthewHerbst** [comment]
Hello. Can you please provide the code to reproduce? Ideally using codesandbox?

**Comment by longgegege** [comment]
```tsx
import "./styles.css";
import React, { useRef } from "react";
import useReactToPrint from "react-to-print";

export default function App() {
  const headerRef = useRef();
  const handlePrint = useReactToPrint({
    content: () => headerRef.current
  });
  
  return (
    <div className="App">
      <butto onClick={handlePrint}>打印</butto>
      <div ref={headerRef}>
        <span
          style={{
            display: "flex",
            justifyContent: "center",
            marginTop: "10px",
            fontFamily: "SimSun",
            fontWeight: "bold"
          }}
        >
          动力设备轮开计划表
        </span>
      </div>
    </div>
  );
}
```

**Comment by MatthewHerbst** [comment]
Thank you. Which browser are you using? I do not see a problem on Chrome. Is there any other code you have that could be changing styles? What is inside of `styles.css`?
