### ISSUE TITLE
Using react-to-print with Puppeteer

### ISSUE THREAD

**Issue by pabloiea1995** [MatthewHerbst/react-to-print#516]
Hello!

I have been trying to replicate the printing method we use in our frontend with react-to-print on the server using puppeteer, but the problem is that Puppeteer (as far as I know) only allows to simulate cntrl + P command on browser. Eventhougth I simulate the react-to-print button, it opens the printing dialog, and puppeteer can't then save the file, because it can't interact with the dialog. 

Deeping a bit on the library code, I realized that its creates an iframe then then prints. A possible solution would be to execute the printing logi (creating the I frame) and the stopping the execcution so the printing dialog does not even open. Would this be possible? If it was, I coul then use the created  and persisted Iframe to print its content (or at least try it)

Thank you!

**Comment by MatthewHerbst** [comment]
Hello. Interesting use case 😄 You should be able to accomplish this by passing a custom `print` prop to `react-to-print`:

```tsx
const handlePrint = useReactToPrint({
  print: () => {
    return new Promise((resolve, reject) => {
      // I believe you want to no-op here, so just:
      resolve();
    });
  },
});
```

This functionality was originally added to support printing in Electron (since it doesn't use `window.print`). Please let me know if that works for you!

**Comment by pabloiea1995** [comment]
It actually worked 🤙🏻

Thanks Matthew!

Awesome library
