### ISSUE TITLE
How to make page break efficient in components?

### ISSUE THREAD

**Issue by nappalm** [MatthewHerbst/react-to-print#518]
![image](https://user-images.githubusercontent.com/35016608/184784465-55030c85-41a5-4e69-a3b0-6ed19ff3b7e2.png)

I have a problem, I am using chakra-ui, my main problem is in all the line breaks. My components are cut (deformity) is there a trick to improve this? 🤔🤔🤔🤔

**Comment by MatthewHerbst** [comment]
Hello. You'll want to play around with the [`break-after`](https://developer.mozilla.org/en-US/docs/Web/CSS/break-after) CSS property. This is an updated property for the old `page-break-before` and `page-break-after` properties. We have a [section in the README](https://github.com/gregnb/react-to-print#page-breaks) explaining page breaks. Please let me know if you need additional help, thanks!

**Comment by y-maslouskaya** [comment]
Hello, I have the same issue and I can't figure it out. I've added page-break and styles from the Readme:: 

<img width="457" alt="Screen Shot 2022-08-16 at 9 45 24 PM" src="https://user-images.githubusercontent.com/59900627/185023265-696c18c3-1a3a-4855-8aa4-a90eaefba9b0.png">

<img width="402" alt="Screen Shot 2022-08-16 at 9 44 47 PM" src="https://user-images.githubusercontent.com/59900627/185023195-81d67a66-c0da-464b-a20d-5e50ce85b94d.png">

and it didn't change anything. Then I've changed page-break-before: auto; to page-break-before: always;. It splitted my content but in a weird way.
<img width="658" alt="Screen Shot 2022-08-16 at 9 41 08 PM" src="https://user-images.githubusercontent.com/59900627/185022951-a852c8ef-bb1b-4aa8-a3dc-bc56e88d1a89.png">

 Is there any way to get rid of the blank space? I would appreciate any help. Thank you

**Comment by MatthewHerbst** [comment]
Hi @y-maslouskaya. Could you share your code, ideally a minimal reproducible example, in a codesandbox or similar so I can help debug? Thanks

**Comment by y-maslouskaya** [comment]
Hi @MatthewHerbst , thank you for such a quick response. Here is my example: 
https://codesandbox.io/s/print-issue-ksn4ks?file=/src/components
index.css has print styles. And under components/Card/Card.js you can find my page-break

**Comment by nappalm** [comment]
@MatthewHerbst I have the same problem as @y-maslouskaya in his codesandbox

**Comment by MatthewHerbst** [comment]
I know it's a few months later, but I've solved this. You need to add the `page-break-inside: avoid;` CSS rule: https://codesandbox.io/s/print-issue-forked-9f7xne I will add something about this to the README
