### ISSUE TITLE
Could React be moved to a peerDependency, allowing "official" React 15 support?

### ISSUE THREAD

**Issue by MatthewHerbst** [MatthewHerbst/react-to-print#52]
The package currently lists `"react": "^16.2.0"` in it's `dependencies`. Could this be relaxed to a `peerDependency`?

Further, as far as I can tell, there is nothing special about [React `16.2.0`](https://github.com/facebook/react/blob/master/CHANGELOG.md#1620-november-28-2017) that this library uses. It does not use `<Fragment>` and it does not care about the `setState` callback.

Actually, as far as I can tell, this library doesn't even need React 16 at all, and should work fine with earlier versions of React, at least React 15. Do you know of any reason why React 16 would be required?

If not, would a PR removing the dependency on React and adding

```json
"peerDependencies": {
  "react": "^15.0.0 || ^16.0.0"
}
```

be alright? This would mean users of other React versions would not need to ship an entirely different version of React to their users just for this package to work.

**Comment by gregnb** [comment]
Sure, seems fair. Feel free to send in a PR
