### ISSUE TITLE
page break not working in echart

### ISSUE THREAD

**Issue by RImpression** [MatthewHerbst/react-to-print#522]
In the same page, Page break is useful for table and text, but not for EChart, as shown in the figure below for print preview。Is there any solution to this problem?

![image](https://user-images.githubusercontent.com/15820088/186823519-501ccb81-8c17-4fe8-a895-52b59c8689bf.png)
![image](https://user-images.githubusercontent.com/15820088/186823553-b14e9260-0f14-4239-b02d-903621af0f78.png)

**Comment by MatthewHerbst** [comment]
Hello. You should put the page break on the `div` that wraps each chart

**Comment by RImpression** [comment]
您的邮件已收到！谢谢！

**Comment by RImpression** [comment]
您的邮件已收到！谢谢！

**Comment by MukeshPothala** [comment]
> Hello. You should put the page break on the `div` that wraps each chart

but it still not working

**Comment by RImpression** [comment]
您的邮件已收到！谢谢！

**Comment by MatthewHerbst** [comment]
Hi @MukeshPothala. Please open a new issue if you are having issues, thank you
