### ISSUE TITLE
Forcing Print Preview Properties

### ISSUE THREAD

**Issue by rkushkuley** [MatthewHerbst/react-to-print#523]
Is there anyway to force the Scale to be Default in the print preview?

**Comment by MatthewHerbst** [comment]
Hello. Do you mean to select one of the options in the preview by default? If so, unfortunately that is not possible. The HTML/JS spec simply implements `window.print` with no options passed to it, so once we call that we lose control and the browser takes over, and each browser does things a little differently of course

**Comment by rkushkuley** [comment]
UPDATE: I was able to figure it out for chrome by placing this in my div component

`<style type="text/css" media="print">{"@page {size: portrait; margin: 0 0 0 0}"}</style>`

It updates the page to force to potrait getting rid of the advanced setting option so by default scale is 100

Unfortunately it is not working for Edge

**Comment by MatthewHerbst** [comment]
Yeah, unfortunately there is no shared spec for how browsers should print thing. This might be a good question to ask StackOverflow, maybe someone knows if there is an Edge equivalent for that

**Comment by rkushkuley** [comment]
Yeh its interesting. 

This works in Chrome:
```
 <style type="text/css" media="print">{"@page {size: portrait; margin: 0 0 0 0}"}</style>
  <style type="text/css" media="print">{"@media print {body {zoom: 50%;}}"}</style>
```


But just this , does not work:
`<style type="text/css" media="print">{"@media print {body {zoom: 50%;}}"}</style>
`
