### ISSUE TITLE
how to scale component to fit page

### ISSUE THREAD

**Issue by Jadentr44** [MatthewHerbst/react-to-print#524]
I'm having an issue where I want my component to take up the entire page, but when i see the preview, the elements are squished and not taking up the full print page

**Comment by MatthewHerbst** [comment]
Hi there. This sounds like a CSS issue with your print styles. Would you mind making a codesandbox or similar to show your issue? Happy to help debug if you can do that

**Comment by Jadentr44** [comment]
yeah it ended up being a css issue, I was using another package that allowed elements to be draggable, and it would do so by adjusting the divs pixels, not making it scalable
