### ISSUE TITLE
i need help for try to print a repeated component twice. But in the interface it comes out only once.

### ISSUE THREAD

**Issue by CesarGMEFA** [MatthewHerbst/react-to-print#525]
I need help to be able to print two times a component that appears only once in the interface.

![image](https://user-images.githubusercontent.com/83330595/189511048-08cfd721-739b-48f5-80a5-9370b7732deb.png)

As I show below in the image, when I click on it I do not get the print option, but I get the second copy of the component in the interface
![image](https://user-images.githubusercontent.com/83330595/189511104-20a3409e-7caa-459e-b650-278e6fff34ad.png)

**Comment by CesarGMEFA** [comment]
how add a labels?

**Comment by MatthewHerbst** [comment]
Hello. Can you please show all of the code for the component so I can help debug? And please copy/paste the code, do not use an image. Another option would be to make a Codesandbox. Thank you

**Comment by CesarGMEFA** [comment]
I tried to put the code here but it shows up wrong.

the code... ⬇
[component code in notion](https://knowing-guavaberry-4bb.notion.site/Code-to-print-two-components-but-that-appears-once-in-the-interface-bf2f08720d304a898afba9f31a9f5b1a)

**Comment by MatthewHerbst** [comment]
It seems correct. To verify, if you remove the condition on `printing` and just have the component twice on the page, does that work?

**Comment by CesarGMEFA** [comment]
It does not work for me.
⬇ I want this ⬇
![image](https://user-images.githubusercontent.com/83330595/189816944-a56b8a75-a315-4bfa-b861-6dd34c1652c4.png)

⬇ But I have this ⬇
![image](https://user-images.githubusercontent.com/83330595/189816671-e2e5cd7b-3c67-46ae-99e1-f49967e74c86.png)

**Comment by MatthewHerbst** [comment]
Yes, I understand what you want. I'm trying to determine where the issue is.

If the components don't both show up without the `printing` condition it is likely an issue in your code/with your styles. If the components do both show up then it is more likely an issue with `react-to-print`. Does that make sense?

**Try this**
```jsx
<div ref={componentRef} >
    <ComponentToPrint
        data={data}
        services={services}
        created={created}
        pieces={pieces}
        total={total}
    />
    <ComponentToPrint
        data={data}
        services={services}
        created={created}
        pieces={pieces}
        total={total}
      />
</div>
```

Does it work like that?

**Comment by CesarGMEFA** [comment]
yes it is work to print. But I can see both components on the web and I don't want that, I only want to see one.

**Comment by MatthewHerbst** [comment]
Yep, I understand, just wanted to make sure the problem was where we think it is. Would it be possible for you to create a codesandbox with your example? The code in Notion isn't fully complete so it's hard for me to truly replicate what you have

**Comment by CesarGMEFA** [comment]
ok here
https://codesandbox.io/s/help-to-good-printing-b38mol?file=/src/App.js

**Comment by nomanjavaid821** [comment]
> yes it is work to print. But I can see both components on the web and I don't want that, I only want to see one.

You Can apply "display: none" css property on one of two component. by doing this only one component will be displayed on screen and both on print

**Comment by CesarGMEFA** [comment]
ok great, that directly did not solve my problem. Pero me dio ideas para probar hasta que se me ocurrió esta posible solución. Look.
https://codesandbox.io/s/help-to-good-printing-b38mol?file=/src/App.js

What do you think about it?

**Comment by nomanjavaid821** [comment]
> ok great, that directly did not solve my problem. Pero me dio ideas para probar hasta que se me ocurrió esta posible solución. Look. https://codesandbox.io/s/help-to-good-printing-b38mol?file=/src/App.js
> 
> What do you think about it?

Not a good method but its a trick you can wrap both component in a parent div with display property set to none and below this parent div you can add component again
![code](https://user-images.githubusercontent.com/102572459/190870069-ea8ddf57-211b-420a-82fe-f545d0b479ed.png)

**Comment by CesarGMEFA** [comment]
Yes, you're right, I like it. thanks.
