### ISSUE TITLE
Firefox: Not able to download css file under HTTPS by CSP 

### ISSUE THREAD

**Issue by charlscross** [MatthewHerbst/react-to-print#527]
Hello, we are using version 2.5.0, and from at least 3 months ago, when using Firefox (104.0.2) on HTTPS under a load balancer, the css styles are not able to load because Firefox CSP blocks it (only on Firefox). This only happens in one of our apps on stage - production servers, I tried to reproduce locally the issue creating a Webpack HTTPS server but the error still appears. The CSS files are linked to the index.html of the Application, so it's hosted on the same host than the react-to-print code, so it's hard to understand why happens.

So not sure if updating to latest version can solve this problem due to changes in your package, and testing this update is gonna be hard cause need to deploy on stage servers just to have the HTTPS balancer in front, wanted to ask if this is a know issue, or maybe a resolved issue on latest versions, or maybe you can provide me info about the reason of this problem.

Ts in advance

**Comment by MatthewHerbst** [comment]
Hello. In version `2.13.0` we added the ability to pass a `nonce` prop which should allow you to use CSP properly. Upgrading to the latest version and using the `nonce` may very well solve your issue.

**Comment by charlscross** [comment]
Hello! Txs for fast reply, gonna check, but a doubt cames into my mind: if the react-to-print code is hosted on server domain, and the css files are in server domain as well, should be any reason for CORS declaration? Txs in advance!

**Comment by MatthewHerbst** [comment]
CSP and CORS are not the same thing. Which are you having issues with?

**Comment by charlscross** [comment]
Hello, txs and sorry did mixed both things. Firefox browser says "Blocked by CSP". But from my little understanding in the CSP we declare scripts that are outside server domain. 
So in this case, the css file which Firefox is blocking (when react-to-print is trying to copy) is not in an external domain link, but exists in the same domain, and even was downloaded previously cause it's included in index root file, so, if the react-to-print code it's in our js bundle which is as well on the same domain, cannot figure why should be whitelisted.

so if we have
<link re="stylesheet" href="/some-path-to-some-script-in-same-server-than-index-file">
Than later react-to-print tries to  recreate for the printing view

Which value should be needed to be listed in the nonce property?

Txs in advance again!!!!

**Comment by MatthewHerbst** [comment]
That highly depends on what your CSP policy looks like. I should note that I am far from a CSP expert. Depending on your CSP policy, you may need to specify `nonce` if you only allow certain content to be loaded. As an example: https://content-security-policy.com/nonce/ Though your policy might also allow all content from your domain, in which case, from my understanding, a `nonce` shouldn't be needed.
