### ISSUE TITLE
pageStyle problem maybe?

### ISSUE THREAD

**Issue by nyteghost** [MatthewHerbst/react-to-print#528]
I am trying to make it so the printer prints out the page in 4 x 6 using 

const pageStyle = `
@page{
    width: 4;
    height: 6;
    margin: 5;
    padding: 0;
    text-align: center;
}
`;

but this does not seem to work. 

Also the lines have spaces in between them 

![image](https://user-images.githubusercontent.com/12069785/190252466-f358c479-656a-4d51-8a6b-48e223cf2161.png)

Can anyone tell me what I am doing wrong here?

**Comment by MatthewHerbst** [comment]
Hello. Have you tried using the [`size`](https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size) CSS property?

**Comment by nyteghost** [comment]
Yeah, I am an idiot. I figured out I was using size incorrectly. For some
reason it would not read it from the css file, so I used `pageStyle= ***@***.***{
size 4in 6in;` and it started working.

**Comment by MatthewHerbst** [comment]
Glad you got it working!
