### ISSUE TITLE
chrome zoom level screwing up grid system

### ISSUE THREAD

**Issue by anujshah108** [MatthewHerbst/react-to-print#529]
Hi I am using the library and its really great. I noticed an issue where if the zoom for chrome is under 100% is screwed up my grid layout of a component in react. Is there any way to mitigate this? Can I force the component to render at 100% zoom when printing or is there anything to keep in mind? 

Thanks!

**Comment by MatthewHerbst** [comment]
Hello. Interesting issue. Would you mind sharing some of the code you're using and/or what grid library you're using? This sounds like it's actually an issue with the grid itself, but maybe there are some easy hacks we can do to make it work while printing.

**Comment by anujshah108** [comment]
Hey! Thanks fo reply. I got it working by passing down an indicator prop for the print component and then making the grid layout be large in that case at any point:

` columns={printPage ? 12 : { xs: 4, sm: 10, md: 12 }}`

This fixed the issue.

Thanks!

**Comment by MatthewHerbst** [comment]
Glad you got it working!
