### ISSUE TITLE
Printing data from an API

### ISSUE THREAD

**Issue by ag288** [MatthewHerbst/react-to-print#531]
The issue I have encountered is as follows : 
The info to be printed is received as a response from a REST API. Thus the component to be printed is initially empty. In the API callback, I tried calling the `handlePrint` function , however the component that is printed is still empty, i.e., the data doesnt update. What is a way to print such dynamic data using this package?
My code is as below:
```jsx
export const ListComponent = () => {
    const [printItem, setPrintItem] = useState()
    const componentRef = useRef()
    const handlePrint = useReactToPrint({
        content : () => componentRef.current
    });

    useEffect(() => {
        
    }, [printItem])

    function callApi() {
        callApi().then((res) => {
            setPrintItem(JSON.parse(res.data).result)
            handlePrint()
        });
    }

    return (
        <>
            <Button colorScheme={"blue"} onClick={callApi}>Book</Button>
            <div style={{ display: "none" }}>
                <ComponentToPrint ref={componentRef} item={printItem} />
            </div>
        </> 
    );
}
```

However `printItem` is undefined at the point when the handlePrint function is called

**Comment by MatthewHerbst** [comment]
Hello. State changes in React are asynchronous. You need to wait for the state change to complete before printing:

```jsx
useEffect(() => {
    if (printItem) {
        handlePrint();
    }
}, [printItem])

function callApi() {
    callApi().then((res) => {
        setPrintItem(JSON.parse(res.data).result)
    });
}
```

**Comment by ag288** [comment]
Thank you so much for your quick response. It worked perfectly!! I had tried something similar to this, but it hadn't worked. I don't know what you did differently, but it worked! Thank you :)
