### ISSUE TITLE
Override or disable browser tool bar print trigger

### ISSUE THREAD

**Issue by kmaheshgit** [MatthewHerbst/react-to-print#532]
I am using react to print for printing my component , however when the user clicks on print button in browser's tool bar its printing the entire page instead of the component which I wanted to render. Is there any way to avoid the same ?

**Comment by MatthewHerbst** [comment]
Hello. `react-to-print` can't override the browser functionality unfortunately. If you find your users using the browser's print often the best option would be to make sure your entire page looks good when printing using `@media print` CSS queries
