### ISSUE TITLE
how to add style RTL to ReactToPrint?

### ISSUE THREAD

**Issue by Rasool65** [MatthewHerbst/react-to-print#533]
by default is LTR but my content is RTL 
how to add direction style?
```
 <ReactToPrint
         //   pageStyle={'direction:rtl'}
            trigger={() => (
              <a className="btn btn-m mt-4 mb-4 btn-full bg-red-dark rounded-sm text-uppercase font-900 m-3">download</a>
            )}
            content={() => componentRef.current}
          />
```

**Comment by Shaker-Hamdi** [comment]
@Rasool65  Did you find a solution to the RTL issue? I'm having the same issue.

**Comment by Shaker-Hamdi** [comment]
OK, in case anyone came across this issue, I fixed it by passing a `bodyClass` property to the object passed to the `useReactToPrint` hook in case the user switched to "RTL", and I just added `direction: rtl;` to that classname in my CSS, that's it.

**Comment by MatthewHerbst** [comment]
Thanks for letting us know @Shaker-Hamdi! That should be very helpful for others in the future

**Comment by Rasool65** [comment]
> @Rasool65 Did you find a solution to the RTL issue? I'm having the same issue.

i use the content with ref and put the inline style  to solved my problem.
button :
```jsx
<ReactToPrint
    trigger={() => <button className="print-btn"> چاپ رسید</button>}
    content={() => factorRef.current}
/>
```

content :
```jsx
<div ref={factorRef} style={{ direction: 'rtl' }}>
    ...
</div>
```

**Comment by Shaker-Hamdi** [comment]
@Rasool65 Nice. My approach works on mutli-directional websites, it works on "LTR" by default, and if the user switches to "RTL", then the classname is sent to the body of the print, and I just change the direction of that classname.

**Comment by MatthewHerbst** [comment]
Happy to accept a PR that adds a RTL section in the [README's Helpful Style Tips](https://github.com/gregnb/react-to-print#helpful-style-tips) 😄
