### ISSUE TITLE
Hidden element from component

### ISSUE THREAD

**Issue by AlexRousseau92** [MatthewHerbst/react-to-print#534]
Hello i'um using react-to-print and i would like to know if its possible to hidden the last part of my table 
Every line is a component and the function to print is on the parent div

![image](https://user-images.githubusercontent.com/68659555/194821109-89b2e6bd-5bde-428f-877a-924c3927aff3.png)

![image](https://user-images.githubusercontent.com/68659555/194821023-4b1b6cd1-5ac1-4088-a07a-0fc545a82e5b.png)

![image](https://user-images.githubusercontent.com/68659555/194820037-85ec5ea2-4db8-42cd-8afc-e9fd4bf0375c.png)

I've tried to hidden the part with a hook 
![image](https://user-images.githubusercontent.com/68659555/194824769-62b89053-9496-45ae-ac4c-401b5f0c16a6.png)
At the first click the part is always display but at the second click the part is hidden
Thank for help

**Comment by MatthewHerbst** [comment]
Hello. The simplest way to hide content during print is to use the `@media print {}` directive. For example:

```css
@media print {
  .classIWantToHide {
    display: none;
  }
}
```

You can use JavaScript as well, but remember that setting state in React is asynchronous, so you would need a `useEffect` hook to watch for the updated state before starting to print. `react-to-print` supports this using the `onBeforeGetContent` prop, though using the CSS way is much simpler if that's an option for you

**Comment by AlexRousseau92** [comment]
Hello,

I had succeeded with the hooks but it's more easy with @media print ! 
thank you :)
