### ISSUE TITLE
Any way to access the pdf blob data from ReactToPrint?

### ISSUE THREAD

**Issue by isaac-cameron** [MatthewHerbst/react-to-print#539]
Hi,

Is there any way that I could get access the blob for the pdf that is rendered in the download dialog?

**Comment by MatthewHerbst** [comment]
Hello. Unfortunately there is not 😢 There is no standard printing API for browsers, so once the print preview window opens we lose all ability to interact with it sadly. I'm hoping this will change in the future but that's probably years away.

Is there something specific you are looking to do? I might be able to point you in the right direction based on what's possible todday

**Comment by stevecastaneda** [comment]
> I might be able to point you in the right direction based on what's possible todday

Do you know of a package to download a PDF client-side, of a rendered webpage, without having to use headless chrome?

RTP works great for me, but I'd love to avoid the extra step of having to show users how to print to PDF after seeing the print dialog popup.

**Comment by MatthewHerbst** [comment]
[`jsPDF`](https://www.npmjs.com/package/jspdf) is a popular project for creating PDFs in JS. You might want to ask them if there is a way to just take an entire DOM node/element and print it, I know there are some libraries on npm that do this but AFAIK they are all old/unmaintained/deprecated
