### ISSUE TITLE
have you tried print multiple pages?

### ISSUE THREAD

**Issue by zzq0324** [MatthewHerbst/react-to-print#54]
@gregnb have you tried print multiple pages? I have print one page with more than one page, but it only print first page. Can you tell me what should I do? Thank you!

**Comment by shawnco** [comment]
Complete shot in the dark here but try adding this CSS somewhere:

`@media print {
    html, body {
        height: initial !important;
        overflow: initial !important;
}}`

**Comment by eric-burel** [comment]
Hi, I've managed to print multiple pages but the cut is disgraceful, there is no bottom padding. I've played with `page-break-inside`, it does not work as expected (it tries to avoid the page break but cut the paragraph in 2).

**Comment by MatthewHerbst** [comment]
Is this a bug or is there functionality that needs to be added?

**Comment by balzee** [comment]
I face the same issue too, I have a long table and can only print 1 page at a time and when i scroll and try again there is an akward cut .

**Comment by MatthewHerbst** [comment]
Hi all. Could anyone please share a codepen or fiddle with an example so that I can play around with it and try and work on a fix? Thanks

**Comment by zzq0324** [comment]
@MatthewHerbst 
I use [rc-print](https://github.com/hanzhangyu/rc-print) instead, code just like this：
`<Print title="" insertHead={false} otherStyle="@page { size: auto;  margin: 0mm; } @media print { body { -webkit-print-color-adjust: exact; } }"><div></div></Print>`

I hope it can help you.

**Comment by hrafaelveloso** [comment]
When the Component I want to print only takes 1 page, everything works great.
I'm using Material-UI and I have tables that use material-table and this works great when the result is a single page file. 
However, when it goes to multiple pages I can't:
. Break where I want (using css page-break-before) ;
. Bottom margin is inexistent, even with padding and margin-bottom... 


I really need that functionality, and I lost at least 2 days trying to figure it out without success...

**Comment by MatthewHerbst** [comment]
@hrafaelveloso PRs are welcome if you have any ideas on how best to do this! I haven't had too much time to look at this issue over the other issues in the codebase

**Comment by Zuzze** [comment]
I also struggled with styling/margins on multiple pages and found a workaround with viewport units:
```
<div className="container" style={{margin: "0", padding: "0"}}>
   <div style={{height: "90vh", padding: 5vh}}>
      page 1 content
   </div>
   <div style={{height: "90vh", padding: 5vh}}>
       page 2 content
    </div>
</div>
```

**Comment by kaydeniz** [comment]
> When the Component I want to print only takes 1 page, everything works great.
> I'm using Material-UI and I have tables that use material-table and this works great when the result is a single page file.
> However, when it goes to multiple pages I can't:
> . Break where I want (using css page-break-before) ;
> . Bottom margin is inexistent, even with padding and margin-bottom...
> 
> I really need that functionality, and I lost at least 2 days trying to figure it out without success...

Hi, did you find any solution for print of multiple pages. I'm using Material-UI template and i have long tables to print. I'm having problems at the top of page 2.

**Comment by hrafaelveloso** [comment]
> Hi, did you find any solution for print of multiple pages. I'm using Material-UI template and i have long tables to print. I'm having problems at the top of page 2.

Unfornately I can't figure out what the problem was, and I was forced to choose pdfmake...

**Comment by kaydeniz** [comment]
> > Hi, did you find any solution for print of multiple pages. I'm using Material-UI template and i have long tables to print. I'm having problems at the top of page 2.
> 
> Unfornately I can't figure out what the problem was, and I was forced to choose pdfmake...

@hrafaelveloso thank you.

**Comment by jesobreira** [comment]
Mixed @shawnco's and @zzq0324's solutions and it worked well for me:

```css
@media print {
  html, body {
    height: initial !important;
    overflow: initial !important;
    -webkit-print-color-adjust: exact;
  }
}

@page {
  size: auto;
  margin: 20mm;
}

```

**Comment by MatthewHerbst** [comment]
Going to close this as a CSS issue. Thanks everyone for the solutions, and please feel free to continue talking about it here.

**Comment by hbrannan** [comment]
After playing for a while, the solution that worked for me was to treat `page-break` (`-inside`, etc.) more granularly than I had been. 

I had been under the impression that my dynamically rendering react components' split would happen automatically as long as I didn't have overflow or display set incompatibly with print mode, but that wasn't what I observed. 

Instead, my breaks appeared only once I both: added a `.page-break` class to the dynamically-rendering components that I envisioned could auto-break, and then applied the following styles:

```
@media all {
  .page-break {
     display: none;
  }
}

@media print {
  .page-break {
      display: block;
      page-break-before: auto;
    }
}
```

**Comment by MatthewHerbst** [comment]
If anyone would like to add to the README FAQ with a generic solution to this I would be happy to accept that PR!

**Comment by AchmadWahyu** [comment]
> After playing for a while, the solution that worked for me was to treat `page-break` (`-inside`, etc.) more granularly than I had been.
> 
> I had been under the impression that my dynamically rendering react components' split would happen automatically as long as I didn't have overflow or display set incompatibly with print mode, but that wasn't what I observed.
> 
> Instead, my breaks appeared only once I both: added a `.page-break` class to the dynamically-rendering components that I envisioned could auto-break, and then applied the following styles:
> 
> ```
> @media all {
>   .page-break {
>      display: none;
>   }
> }
> 
> @media print {
>   .page-break {
>       display: block;
>       page-break-before: auto;
>     }
> }
> ```

Hi @hbrannan , may i ask you a fiddle or codepen by the example of this multiple printing page for me to play around, please?

**Comment by fizzvr** [comment]
The FAQ is clear [Page Breaks](https://github.com/gregnb/react-to-print#page-breaks) 🍻

**Comment by louidorjp** [comment]
> I also struggled with styling/margins on multiple pages and found a workaround with viewport units:
> 
> ```
> <div className="container" style={{margin: "0", padding: "0"}}>
>    <div style={{height: "90vh", padding: 5vh}}>
>       page 1 content
>    </div>
>    <div style={{height: "90vh", padding: 5vh}}>
>        page 2 content
>     </div>
> </div>
> ```

it's work for me
![Screenshot from 2021-03-24 11-43-47](https://user-images.githubusercontent.com/56307966/112339844-699fde80-8c96-11eb-98c5-8a8e95184b63.png)

**Comment by harishkoninti** [comment]
CSS property page-break-inside worked for me 
`@media print {
 div.qandA{ 
    page-break-inside: avoid;
}
}`  
Here my div className is "qandA" and  wrap all elements in one div which you want to show on one page

**Comment by Tevvek** [comment]
> 

I am also using MUI and having the same issue with the tables, how did you manage to fix it? Thanks!

**Comment by Tevvek** [comment]
@kaydeniz Hi! Just stumbled upon this thread and decided to share my workaround. So my guess is that you were using the right structure for a table i.e. `<TableHead />` but what happens is that the default behaviour of the html tag for the table head is repeating itself when printing in a new page and that somehow messes with the rest of the styles.
So I removed the table head and added the head row inside the body twitching the styles so it looks like the actual head. For now this is the best workaround I found until I figure out what in MUI is messing with the printing.

**Comment by pranavubarhande** [comment]
This worked for me. Use this for the div which is scrolling

```css
@media only print {
   #idOfYourDiv {
     width: auto;
     height: auto;
     overflow: visible;
   }
}
```

**Comment by saipraveenp** [comment]
can any one help me to print one page 

im generating to print a label but im getting 8 pages  page 1 is filled with data and remaining 7 pages are getting empty
![screenshott](https://github.com/user-attachments/assets/9d9fc7e1-448a-49f5-98cd-883609b6c6c5)
