### ISSUE TITLE
Content of a `@uiw/react-textarea-code-editor` component not printing

### ISSUE THREAD

**Issue by Utilitycoder** [MatthewHerbst/react-to-print#540]
I am trying to print the value pasted in a content area as it appears but have been unable to do so. The print dialogue returns an empty page when the textarea has a value but prints the placeholder correctly if there's no value present.

**Comment by MatthewHerbst** [comment]
Hello. Could you please share the code you are using?

**Comment by Utilitycoder** [comment]
Here is the app component 

```javascript
import React, { useRef, useEffect } from 'react';
import { useReactToPrint } from 'react-to-print';
import '@wcj/dark-mode';
import './App.css';
import TextArea from './components/TextArea';


function App() {
  const componentRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    copyStyles: true,
  });

  // useEffect(() => {
  //   console.log(componentRef.current.innerHTML)
  // }, [handlePrint])
  


  return (
    <div className='App'>
      <dark-mode dark='Dark' light='Light' style={{ position: 'fixed', top: 9, left: 10}}>
      </dark-mode>
      <TextArea ref={componentRef} />
      <button className='Button-print' onClick={handlePrint}>Print this out!</button>
  </div>
  );
}

export default App;
```
and here is the textarea component

```javascript
import React, { useState } from 'react';
import CodeEditor from '@uiw/react-textarea-code-editor';

import './style.css'

const TextArea = React.forwardRef((props, ref) => {
    const [code, setCode] = useState("")
    
    return (
        <CodeEditor
            value={code} 
            language="sol"
            onChange={(e) => setCode(e.target.value)}
            padding={20}
            className="textarea"
            placeholder='Paste Your Solidity Code Here'
            minHeight={120}
            ref={ref}
        />
    )
});

export default TextArea
```

**Comment by MatthewHerbst** [comment]
Hmm, I'll need to dive into this more. It may be something inside of `CodeEditor`. I can confirm that `textarea` (what `CodeEditor` renders) works fine: https://codesandbox.io/s/react-to-print-forked-trig0v?file=/examples/ComponentToPrint/index.js:4866-4876

**Comment by Utilitycoder** [comment]
Thanks for taking the time to respond to this. I think I'd do something similar to what you did in the sandbox and wrap the CodeEditor component in a div. I will then print the div.

**Comment by MatthewHerbst** [comment]
Did you find a solution for this?

**Comment by Utilitycoder** [comment]
No, I haven't. In the meantime, I have reverted to printing the whole page. It is a basic app for printing out highlighted solidity codes.

**Comment by MatthewHerbst** [comment]
I've taken another look at this. If you look closely, the `CodeEditor` does actually have the content during the print, but it does not have the correct styles, so instead of being white the code is dark, almost blending in with the background. I've tracked this down to an issue with the "auto" styles they are applying. If you look at their official CodeSandbox example app [here](https://mcebp.csb.app/) you will notice that printing that page the "auto" styles have the same problem. It seems if you are able to manually force the styles that should solve the problem, I think

**Comment by MatthewHerbst** [comment]
I opened a [issue](https://github.com/uiwjs/react-textarea-code-editor/issues/134) with `react-textarea-code-editor` to look into solving this
