### ISSUE TITLE
Blank pages appear when printing

### ISSUE THREAD

**Issue by Loveapleace** [MatthewHerbst/react-to-print#541]
When I print a table, the first page of the table can be fully displayed, the second page will appear blank。

**Comment by MatthewHerbst** [comment]
Hello. Could you please share a code example of your problem? I should note that if you table is using virtualized rendering, `react-to-print` will not be able to print virtualized columns: we can only print what is in the DOM

**Comment by Loveapleace** [comment]
```tsx
const printRef = useRef() as React.MutableRefObject<HTMLDivElement>
  const openPrint = useReactToPrint({
    content:            () => printRef.current,
    onAfterPrint:       () => loading.destroy()
  }) as () => {}
```

`content` is the content of my table. Its content can be fully displayed on one page, but the second blank page will appear。
![image](https://user-images.githubusercontent.com/96719332/198535090-93e40b12-9931-4a04-8e9a-7daf4dab8664.png)

**Comment by MatthewHerbst** [comment]
Is there any chance you could make a reproducible example on a website such as Codesandbox, or something similar? The code you've shared is not enough for me to understand how your code works

**Comment by MatthewHerbst** [comment]
@Loveapleace were you able to find a solution? If not, could you please share your code? Thanks!

**Comment by Aliendre** [comment]
I solved this issue removing '`<br />`' tag from jsx
