### ISSUE TITLE
Media Queries not working with Print

### ISSUE THREAD

**Issue by TomAndrewRocks** [MatthewHerbst/react-to-print#542]
Tryin' to change the result of my print with media queries (styled-components/inline-style) and still not working

**Comment by MatthewHerbst** [comment]
Hello. Could you please share your code so we can take a look? Thanks

**Comment by PraveenVerma17** [comment]
i can say the same, print is not working with media query.  In my case i am using mui media query breakpoints to update the layout.

**Comment by MatthewHerbst** [comment]
@PraveenVerma17 could you please share a [CodeSandbox](https://codesandbox.io/s/rzdhd) showing the issue?
