### ISSUE TITLE
deal with refs withing loops

### ISSUE THREAD

**Issue by Hamza-Wakrim** [MatthewHerbst/react-to-print#544]
there are any ways to deal with refs withing loops when i want to print

![image](https://user-images.githubusercontent.com/57459253/199483637-d7084dad-4d43-46a9-beeb-e9fdfcf1a66a.png)

i have this code and is inside loop and i have list of element and i want to make ref deal withing loop

**Comment by MatthewHerbst** [comment]
Hello. I'm not sure I understand what your problem is. Could you post more of your code (copy/paste, not an image), and give a better explanation of what you want to happen versus what actually happens? Thanks!

**Comment by Hamza-Wakrim** [comment]
i found solution about this problem thank yo
