### ISSUE TITLE
Electron: `documentTitle` not working

### ISSUE THREAD

**Issue by Flaviano-Rodrigues** [MatthewHerbst/react-to-print#547]
```jsx
<div>
  <ReactToPrint
    documentTitle='Recibo2.pdf'
    onBeforeGetContent={async () => setHideToPrint(true)}
    onAfterPrint={() => setHideToPrint(false)}
    trigger={() => <FaPrint />}
    content={() => ref.current} />
</div>
```

**Comment by MatthewHerbst** [comment]
Hello. When I run the examples locally I can verify that the `documentTitle` is working correctly in Chrome. Could you please add more detail/explain what the issue is for you?

Also, what browser are you using, what type of printing are you trying to do, and could you please show more of your code?

Thanks

**Comment by Flaviano-Rodrigues** [comment]
Hi, I'm using electron and I'm using the default way to use that lib

**Comment by MatthewHerbst** [comment]
Unfortunately I don't know much about Electron printing, and while we do our best, we don't officially support Electron. If you know how to set the title in Electron I would be happy to make sure our code does that, though to the best of my knowledge Electron tries to just use Chromium as much as possible.

I've posted to SO to see if anyone there knows how to do it: https://stackoverflow.com/questions/74338908/how-to-provide-electron-with-the-a-title-during-printing

Related: https://github.com/electron/electron/issues/23380

**Comment by Flaviano-Rodrigues** [comment]
No problem, If I can do the document get the title I will return in this  issue. By the way, ty so much for the attention!
