### ISSUE TITLE
Scale on print

### ISSUE THREAD

**Issue by brognilucas** [MatthewHerbst/react-to-print#55]
Hello @gregnb ! 
Can I pass a scale to resize my print ? 

Something like this 
```

     <ReactToPrint
                trigger={() => (
                  <Menu.Item
                    icon='print'
                    name='Imprimir'
                    active={false}
                    onClick={() => { }}
                    scale={0.6}
                  />
                )}
                content={() => this._print}
                pageStyle=''
              />
```

**Comment by joshkoo** [comment]
@brognilucas You can pass the styles you want to your print content and shape it however you like. 
What reactToPrint does is, it goes over every css in html and copy all of them to your print window.

```
import React from 'react';
//Just a normal component with styling
import printContent from './PrintContent';
import ReactToPrint from "react-to-print";

class ContentfulPrint extends React.Component {
  constructor(props) {
    super(props);
    // create a ref to store component reference
    this.printContent = React.createRef();
  }

  render() {
    const {
      triggerComponent, onAfterPrint
    } = this.props;

    return (
      <div>
        <ReactToPrint
          trigger={() => (
            triggerComponent
          )}
          content={() => this.printContent}
          onAfterPrint={onAfterPrint}
        />
        <div style={{ display: 'none' }}>
          <PrintContent
            ref={(el) => { this.printContent = el; }}
          />
        </div>

      </div>
    );
  }
}

export default ContentfulPrint;
```
Hope it helps!

**Comment by brognilucas** [comment]
@joshkoo I do it. But the result is not the same if I pass the style on css or on a Print page. 

If I pass scale 0.6 on bodyClass I got these result.
![captura de tela 2018-10-16 as 08 49 39](https://user-images.githubusercontent.com/20867062/47014398-8aa49280-d120-11e8-865c-7be0c59775e9.png)

And if I pass the scale on print configuration the result is another one. 
![captura de tela 2018-10-16 as 08 51 55](https://user-images.githubusercontent.com/20867062/47014528-d820ff80-d120-11e8-88d1-9caed9f4676b.png)

If isn't possible add this feature on reactToPrint ok, I'll try solve this problem on my code, using the scale with other form.

**Comment by joshkoo** [comment]
It is possible to add this feature but giving option to everyone to style page as they like is a better option and it is already there.

Just try to create a wrapper for your print content and style it however you like with css
