### ISSUE TITLE
Google Font

### ISSUE THREAD

**Issue by rkushkuley** [MatthewHerbst/react-to-print#552]
Anyone have a example of how they are using a google font? Correct font only shows up if i have the font downloaded on my machine , but not on other machines that do not. The raw html has the right font but once the print window opens its defaults to the systems font. 

My index file is exporting the font.
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

**Comment by MatthewHerbst** [comment]
Hello. Could you please show your code, ideally in a [Codesandbox](https://codesandbox.io/s/rzdhd)? That will help debug your issue. Thanks!
