### ISSUE TITLE
border 1px solid sometimes does not work

### ISSUE THREAD

**Issue by tyometarou** [MatthewHerbst/react-to-print#559]
border="1px solid" sometimes  does not work

in pdf preview it can work

but in first preview it cant work
1page it can work and 2page it cant work placeA but 3page it cant work placeB

**Comment by MatthewHerbst** [comment]
Hello, thanks for making the issue. Could you please make a [Codesandbox](https://codesandbox.io/s/rzdhd) showing the problem so that I can easily debug it? Also, what browser/version are you using? Thanks!

**Comment by tyometarou** [comment]
sorry,this situaiton happened in my business
so i cant share this code correctly
this situation happend in Chaka Ui and apply theme

**Comment by MatthewHerbst** [comment]
Hello. I don't need you to share your business code, just to create a similar example on Codesandbox. I have never used Chaka UI before

**Comment by MatthewHerbst** [comment]
If you're able to share some code to replicate this issue I'm happy to help with it, but closing for now

**Comment by alekseykurylev** [comment]
@MatthewHerbst, the problem is in the css variable, where an underscore is used in the name, for example "--_divider-color". Try to use the mantine library https://v7.mantine.dev/

**Comment by MatthewHerbst** [comment]
> @MatthewHerbst, the problem is in the css variable, where an underscore is used in the name, for example "--_divider-color". Try to use the mantine library https://v7.mantine.dev/

Hi! Could you please create a new issue for this? It's not something I'm familiar with. A [codesandbox](https://codesandbox.io/s/rzdhd) showing it failing with -react-to-print` would be super helpful
