### ISSUE TITLE
align time and date format at bottom

### ISSUE THREAD

**Issue by umeshgAmpcome** [MatthewHerbst/react-to-print#560]

**Comment by MatthewHerbst** [comment]
Hello. Could you please provide a more detailed question/issue? What exact problem are you having, and what have you tried that isn't currently working?

**Comment by umeshgAmpcome** [comment]
ya i need adjust time and date  and page number 
at bottom from top and also i want to remove title and url also in the page

**Comment by umeshgAmpcome** [comment]
@MatthewHerbst  
 i need to adjust time and date and page number at bottom from top
 and  i also  want to remove title and url also in the page
could please tell what should do

**Comment by MatthewHerbst** [comment]
Hello. Could you please share the code you are using? The default styles that `react-to-print` applied should be removing the browser's header/footer, so they should only appear if you have passed custom styles. In terms of changing that content, it's not possible unfortunately, the browser controls what goes there. The best we can do is hide it

**Comment by umeshgAmpcome** [comment]
but how can we apply custom style for footer the date and time
can you please give some e.g of putting date and time at bottom like give some code of it

**Comment by umeshgAmpcome** [comment]
Hi @MatthewHerbst
but how can we apply custom style for footer the date and time
can you please give some e.g of putting date and time at bottom like give some code of it

**Comment by MatthewHerbst** [comment]
Date and time in JavaScript can be accessed with the [Date API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). Many people use libraries such as [moment.js](https://momentjs.com/) to make working with dates and times simpler.

If you want to include a date/time, or any content, at the bottom of your page, just make it show in the JSX while you are printing. You can use CSS to make sure it is at the bottom.

You cannot apply custom styling to the date/time the browser puts into the print automatically. Instead, hide that (what `react-to-print` does by default) and then add your own.

Again, if you could provide a code example I am happy to help, but I cannot write your code for you. If you make some code on [Codesandbox](https://codesandbox.io/s/rzdhd) I can easily help you.
