### ISSUE TITLE
[Bug] Print content on Desktop is correct with defined ref, but on mobile or tablet is incorrect?

### ISSUE THREAD

**Issue by thanhchuongbmd** [MatthewHerbst/react-to-print#562]
I set ref to QuotePrint component to print, but on tablet or mobile then it's print all current page current, check image below!  

<img width="518" alt="Screen Shot 2022-11-23 at 00 43 58" src="https://user-images.githubusercontent.com/67777599/203384535-b7e2d0a2-ac1d-4338-bfd1-856f7694f2f2.png">

**Correct**
<img width="518" alt="Screen Shot 2022-11-23 at 00 47 22" src="https://user-images.githubusercontent.com/67777599/203385301-a886d626-b5d5-4212-99f9-bad0f9243bb9.png">

**Incorrect: Mobile, table**
![photo_2022-11-23 00 50 03](https://user-images.githubusercontent.com/67777599/203385944-614dd6d7-0f8f-4e0e-9a46-c4c7420c6569.jpeg)

**Comment by MatthewHerbst** [comment]
Hello. Yes, this is a bug we are tracking here: https://github.com/gregnb/react-to-print/issues/187

Hope to have a fix soon 🙏
