### ISSUE TITLE
Document title prop not working

### ISSUE THREAD

**Issue by TomAndrewRocks** [MatthewHerbst/react-to-print#563]
Hi folks!

I'm having trouble getting any sort of title into my print using react-to-print. I've tried to use look for a solution (reading documentation and DOM manipulation) but none of that seems to work. Can you give me a hint of how I'm supposed to get over it?

**Comment by MatthewHerbst** [comment]
Hello. If you run the examples locally via `npm start` (won't work in Codesandbox unfortunately) you'll see that when the page first loads the title is ""ReactToPrint Examples" but when you click print, and you select to save as a PDF, the file name is "AwesomeFileName". As you can see in the example, that can be set by passing the `documentTitle` prop. https://github.com/gregnb/react-to-print/blob/f8180b511bf9408cb2dda12a07130242925991b6/examples/FunctionalComponent/index.tsx#L63

If that's not working for you, could you please share the code you are using, and which browser/version you are on? Thanks!

**Comment by TomAndrewRocks** [comment]
you're right! it worked out!
there's some way to force this option of ''save as a PDF" as default? 
Down below it's my code:

```jsx
import { useReactToPrint } from 'react-to-print';

const componentRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: "HEY",
  });

 <Print ref={componentRef}>
          <Charts
            id={id}
            isComparing={false}
          />
 </Print>
```

**Comment by MatthewHerbst** [comment]
> there's some way to force this option of ''save as a PDF" as default?

There is not unfortunately 😢 There is no "Print API" that browsers expose, so once we call `window.print` to open the print preview box, we lose all control.
