### ISSUE TITLE
I have some error styles by firefox.

### ISSUE THREAD

**Issue by leo95123** [MatthewHerbst/react-to-print#568]
When use it by edge or chrome, the styles were normal,like this:
![pic-edge](https://user-images.githubusercontent.com/28439527/208812002-a7443b4e-b8c2-4259-afba-d2528792c668.jpg)
But in firefox,QRcode and last words show failed, like this:
![pic-firefox](https://user-images.githubusercontent.com/28439527/208812163-4913f9a9-7a2d-4a11-92d7-357530be35a6.jpg)

**Comment by MatthewHerbst** [comment]
Hello. In "More settings" drop down, can you please ensure you have "Print backgrounds" option selected in the extra print options?

If that does not work, can you please share your code?
