### ISSUE TITLE
issue in firefox

### ISSUE THREAD

**Issue by tampham512** [MatthewHerbst/react-to-print#569]
![image](https://user-images.githubusercontent.com/104890135/209096223-bbbfc107-1639-45ad-ba4f-2e219b3fd8e7.png)

**Comment by MatthewHerbst** [comment]
Hello. Could you please share your code? Not possible to help with just a screenshot.

**Comment by tampham512** [comment]
![image](https://user-images.githubusercontent.com/104890135/209299330-a08b2d63-b7cb-474f-b048-1902c80df4a2.png)
![image](https://user-images.githubusercontent.com/104890135/209299466-4cf7323b-6899-4def-b8e1-d153eaead002.png)

there is my code, please support

**Comment by tampham512** [comment]
> Hello. Could you please share your code? Not possible to help with just a screenshot.
![image](https://user-images.githubusercontent.com/104890135/209302878-c2a92b29-3992-43c8-ba2e-6177b5fdd2d8.png)

![image](https://user-images.githubusercontent.com/104890135/209302872-8d13f508-4d5b-4555-8b17-4f0131386348.png)
there is my code, please support

**Comment by MatthewHerbst** [comment]
The little you shared looks fine, but I need to see a working example please. Ideally make a [CodeSandbox](https://codesandbox.io/s/rzdhd)

**Comment by tampham512** [comment]
yeah, this code work right in chrome, but I have issue blank title and time in the header document with firefox.

**Comment by MatthewHerbst** [comment]
I'm happy to help if you can provide a working code example please showing the problem

**Comment by tampham512** [comment]
![image](https://user-images.githubusercontent.com/104890135/209529018-86970b0f-1a9d-4274-8fcc-b7040a18bf65.png)
please support show url not show blank:about

**Comment by tampham512** [comment]
in firefox

**Comment by MatthewHerbst** [comment]
@tampham512 we don't put those words on the page, that is your code. I can only help if you share your code.
