### ISSUE TITLE
Can we get a 2.0.0-beta-5?

### ISSUE THREAD

**Issue by Batistleman** [MatthewHerbst/react-to-print#57]
Seems like some 'bodyClass' fixes were made on the v2-iframe branch. :-)

**Comment by gregnb** [comment]
the only thing added since the last release to master has been moving the packages down to react 15

**Comment by Batistleman** [comment]
I meant this one: https://github.com/gregnb/react-to-print/commit/0fa79c94470097ce3de6ef51e1b555a7fd974b5b

Is it already merged to master?

**Comment by gregnb** [comment]
Yep https://github.com/gregnb/react-to-print/blob/master/src/index.js
