### ISSUE TITLE
Whole page prints on mobile browsers

### ISSUE THREAD

**Issue by pvalcamartins** [MatthewHerbst/react-to-print#570]
https://codesandbox.io/s/rzdhd

I'm tryng to print a single component through a mobile browser and it doesn't work for me. On the mobile the page rendered to print is the whole page with all elements and components. On desktop all works fine, but on mobile it looks like that the useRef lost the reference and print all page.

I tested on chrome and opera (mobile).

Does anyone have faced this issue? Thank you in advance

![17 28 25](https://user-images.githubusercontent.com/38440265/209220636-21d42b7d-b39f-4555-8bc7-cde25f9a611a.jpeg)

**Comment by ericmartins0203** [comment]
i had the same issue

**Comment by MatthewHerbst** [comment]
Hello. Going to close this in favor of https://github.com/gregnb/react-to-print/issues/187 which is the same issue. Unfortunately I'm not aware of a fix yet, but I do plan on looking into this more soon. If you have any ideas on a possible fix, PRs are always welcome!
