### ISSUE TITLE
`onBeforeGetContent` is works before any changes.

### ISSUE THREAD

**Issue by ozgurSULUM** [MatthewHerbst/react-to-print#572]
`onBeforeGetContent` works before any updates so my state changes in it does not show in print.

For example

```ts
const [isPrinting, setIsPrinting] = useState(false);
const printRef = useRef(null);

const handlePrint = useReactToPrint({
  content: () => printRef.current,
  onBeforeGetContent: () => {
    setIsPrinting(true);
  },
  onAfterPrint: () => {
    setIsPrinting(false);
  }
});

return <ComponentToPrint ref={printRef} />
```

In the above code I get stale version of ComponentToPrint (isPrinting = false). Am I doing something wrong or is this is an issue? I am updating MUI Grid xs breakpoints with isPrinting state inside of ComponentToPrint component. Because it is printing with xs breakpoint.

Like below
`<Grid item xs={isPrinting ? 6 : 12}> `

I like to know if there is a workaround.

Actually I have found a workaround but I think above code should work too, I did set isPrinting true when the user clicked print button and it worked.

**Comment by MatthewHerbst** [comment]
Hello. So, the issue here is that setting state is asynchronous, meaning that the state update isn't happening until after the print starts. To fix this, you need to return a `Promise` to `onBeforeGetContent` that resolves when the state update completes. The pattern for doing this with functional component is ugly, but it's the only way unfortunately since they removed the set state on complete callback (the second parameter of `this.setState` in class components):

```tsx
const [isPrinting, setIsPrinting] = useState(false);
const printRef = useRef(null);

// We store the resolve Promise being used in `onBeforeGetContent` here
const promiseResolveRef = useRef(null);

// We watch for the state to change here, and for the Promise resolve to be available
useEffect(() => {
  if (isPrinting && promiseResolveRef.current) {
    // Resolves the Promise, letting `react-to-print` know that the DOM updates are completed
    promiseResolveRef.current();
  }
}, [isPrinting]);

const handlePrint = useReactToPrint({
  content: () => printRef.current,
  onBeforeGetContent: () => {
    return new Promise((resolve) => {
      promiseResolveRef.current = resolve;

      setIsPrinting(true);
    });
  },
  onAfterPrint: () => {
    // Reset the Promise resolve so we can print again
    promiseResolveRef.current = null;

    setIsPrinting(false);
  }
});
``` 

Let me know if you run into any trouble with that!

**Comment by ozgurSULUM** [comment]
Thank you, I tried your approach and it worked nicely.
