### ISSUE TITLE
When I want to print, two pages are printed instead of one page

### ISSUE THREAD

**Issue by YahyaProg** [MatthewHerbst/react-to-print#575]
hi,
i have a problem
When I want to print, two pages are printed instead of one page
A page containing the desired content
and a blank page

**Comment by YahyaProg** [comment]
![image](https://user-images.githubusercontent.com/109727350/210347122-4aa73319-85d3-4baf-97a7-49d8e8c88bae.png)

**Comment by MatthewHerbst** [comment]
Hello. This is likely due to the styles of your component. Do you have any margin or padding at the bottom you can remove?

**Comment by YahyaProg** [comment]
no..i don't have any margin or padding...
I even removed the extra elements and put only a short text...I still had the same problem

![image](https://user-images.githubusercontent.com/109727350/210489931-8aa97125-f197-4767-a9e5-c6adc96a6712.png)

**Comment by MatthewHerbst** [comment]
Could you replicate your code in a [CodeSandbox](https://codesandbox.io/s/rzdhd) please so I could see a working example? It's not really possible to debug from photos

**Comment by YahyaProg** [comment]
this project has thousands line Css code that I can't show you all of them...
Is there any code where we can command only one page to be printed?
And delete the second page?

**Comment by MatthewHerbst** [comment]
The library doesn't work like that. We load all of the styles and the HTML for the component you give the ref to, put it into an `iframe`, and then we print that `iframe`. So whatever is in the `iframe` will get printed.

Is there any way you can scope the CodeSandbox down to just replicate your problem? I doubt the component being printed actually has that much CSS affecting it, especially considering it appears to almost be a blank page.
