### ISSUE TITLE
I get a blank page the first time I print

### ISSUE THREAD

**Issue by AntonPiniaz** [MatthewHerbst/react-to-print#577]
The first time I load a page or use incognito, I get a blank pdf and an extra second page to print (there should be one). I use the useReactToPrint hook to grab the component for printing. There are no errors or warnings in the console.  After the second attempt to print, I get the correct result.

![Screenshot_20230106_112148](https://user-images.githubusercontent.com/42865860/210972734-88135bce-d662-4c34-b79a-9ed7699033f9.png)

**Comment by MatthewHerbst** [comment]
Hello. Are you changing state when you start the print? My best guess is that you aren't waiting for the state change to complete. Could you please share your `useReactToPrint` code?

**Comment by AntonPiniaz** [comment]
Hi! Here is the component with `useReactToPrint` :

```tsx
const LabelsModal = ({ modalOpen, toggleModal, labels }) => {
  const { t } = useTranslation();
  const componentRef = useRef(null);
  const [labelsData, setLabelsData] = useState([]);

  useEffect(() => {
    const labelsDataMods = labels.map(({ data: { id }, data, updated_at }) => ({
      id,
      qty: 1,
      labelInfo: data,
      checked: true,
      updated_at,
    }));

    setLabelsData(labelsDataMods);
  }, [labels]);

  const handleLabelsData = (id, qty, checked) => {
    const copyLabels = [...labelsData];

    if (!copyLabels.length) {
      return;
    }

    copyLabels.map(item => {
      if (item.id === id) {
        item.qty = qty;
        item.checked = checked;
      }
    });

    setLabelsData(copyLabels);
  };

  const reactToPrintContent = useCallback(() => {
    return componentRef.current;
  }, [componentRef.current]);

  const handlePrint = useReactToPrint({
    content: reactToPrintContent,
    pageStyle: pageStyle,
    documentTitle: 'Label',
  });

  return (
    <Modal isOpen={modalOpen} toggle={toggleModal} className="modal-dialog-centered">
      <ModalHeader toggle={toggleModal}>
        <b>{t('Print label')}</b>
      </ModalHeader>
      <ModalBody>
        {labels.map(label => (
          <Fragment key={label.id}>
            <LabelToPrint label={label} handleLabelsData={handleLabelsData} />
            <hr />
          </Fragment>
        ))}
        <div style={{ display: 'none' }}>
          <LabelPrintCards
            patientName={patientName}
            patientNameArabian={patientNameArabian}
            updatedAt={updatedAt}
            labels={labelsData}
            pharmacistName={pharmacistName}
            phoneNumber={phone}
            orderNumber={orderNumber}
            ref={componentRef}
          />
        </div>
      </ModalBody>
      <ModalFooter>
        <Button color="primary" onClick={handlePrint}>
          {t('Print')}
        </Button>
      </ModalFooter>
    </Modal>
  );
};
```

**Comment by MatthewHerbst** [comment]
I see two possible issues:

First, without running it (at work right now), I think the issue may be the `useCallback` around `componentRef.current`. Recall that when ref values update, the component does NOT re-render, which means the when your component first renders the ref value is `null`, and even when it changes, that doesn't cause the component to re-render, meaning the `useCallback` never updates, meaning we're getting a `null` value passed into `content`.

Second, while it shouldn't be impacting the print, the `display: 'none'` style around the component to print might be getting in the way somehow. Can you try commenting that out to see if the print works with it gone? If that ends up being the issue it would point to an issue with `react-to-print`

**Comment by AntonPiniaz** [comment]
Thanks for the reply, I need time to test these options.

**Comment by MatthewHerbst** [comment]
Hi @AntonPiniaz, just following up, did you get something working here?

**Comment by devlopersabbir** [comment]
### **I have also faced this issue it's not a big issue**
if we are thinking deeply about what's happening here then we can understand very easily but we are not thinking deeply 😄

> Anyway let's jump to the solution

our all of the elements or components that we want to apply page break
```jsx
<!-- our all components as JSX/TSX -->
<React.Fragment >
<Container ref={componentRef as any}>
 <PageOne />
 <PageTwo />
</Container>
</React.Fragment >

<!-- our all components as HTML -->
<div className="container" ref={componentRef as any}>
 <div className="page-break">page one</div>
 <div className="page-break">page two</div>
</div>
```

> **Now let's create a style file called style.css OR index.css (whatever you want) and add this code**

```css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

@media print {
  @page {
    size: A4;
    margin: 20px;
  }
  .page-break {
    page-break-before: always !important;
  }
}
```

### This code is enough to solve this issue `100%`

> `Not required, I just mentioned here my **printHandler**`
```jsx
const componentRef = useRef();
const handlePrint = useReactToPrint({
  content: () => componentRef.current as any,
  documentTitle: "Astrology",
  removeAfterPrint: true,
  onBeforeGetContent: () => setLoading(true),
  onAfterPrint: () => {
    setLoading(false);
    toast.success("PDF save successfully🚀");
  },
});
```
`**### Enjoy 😍**`
