### ISSUE TITLE
Print in chrome not working with react-to-print [FIXED]

### ISSUE THREAD

**Issue by YoussefZidan** [MatthewHerbst/react-to-print#579]
I'm trying to only display a component in print and hide it on the screen, but this is giving me problems in **Chrome** however it works perfectly in **Firefox**.

The code is shown below *(I'm using tailwindcss)*. 

```jsx
import { forwardRef } from "react";

const ComponentToPrint = forwardRef(({ data }, ref) => (
  <div ref={ref} className="hidden print:block">
     {data}
  </div>
));

export default ComponentToPrint;

```

By putting the div `absolute` in **screen** with `top-100000px` and making it `block` in **print**, I was able to resolve this problem in the end. 

```jsx
import { forwardRef } from "react";

const ComponentToPrint = forwardRef(({ data }, ref) => (
  <div ref={ref} className="absolute left-0 top-[-100000%] print:top-0">
     {data}
  </div>
));

export default ComponentToPrint;

```

**Comment by MatthewHerbst** [comment]
I'm not familiar with the particulars of Tailwind, but you should be able to trivially use `display: none` to make this happen:

```css
.myComponent {
  display: none;

  @media print {
    display: block;
  }
}
```

Glad you found a solution that works for you!

**Comment by YoussefZidan** [comment]
> I'm not familiar with the particulars of Tailwind, but you should be able to trivially use `display: none` to make this happen:
> 
> ```css
> .myComponent {
>   display: none;
> 
>   @media print {
>     display: block;
>   }
> }
> ```
> 
> Glad you found a solution that works for you!


this is what exactly `hidden print:block` does in tailwind but somehow it didn't work in chrome

**Comment by MatthewHerbst** [comment]
Hmm, interesting. It may be worth asking about this on the Tailwind discussions page, it's possible there is a bug somewhere: https://github.com/tailwindlabs/tailwindcss/discussions?discussions_q=print
