### ISSUE TITLE
I have problem with my size div elements

### ISSUE THREAD

**Issue by abrorxon-karimxonov** [MatthewHerbst/react-to-print#580]
hi how are you?
can you help me? 
https://codesandbox.io/s/great-northcutt-77yrhp?file=/src/styles.css
how to show view it doesn't matter
how can i do it firstdiv one page seconddiv second page
please bro help me if you know answer

**Comment by MatthewHerbst** [comment]
Hello. Your example does not work because you are missing imported files.

If you want to control page-breaks, [the README](https://github.com/gregnb/react-to-print#page-breaks) has good examples on how to do it. For example:

```css
.page-break {
  break-after: always;
}
```

**Comment by abrorxon-karimxonov** [comment]
Thanks for writing in. Any chance you can make a https://codesandbox.io/s/great-northcutt-77yrhp?file=/src/styles.css replicating the issue?

**Comment by abrorxon-karimxonov** [comment]
this solution it doesn't work 
```css
.page-break {
  break-after: always;
}
```

**Comment by MatthewHerbst** [comment]
Your height is `150vh` (150% size of the viewport), of course it will go across multiple pages. https://codesandbox.io/s/zealous-cherry-1sbhmj?file=/src/styles.css

**Comment by abrorxon-karimxonov** [comment]
Thank you bro it works

**Comment by abrorxon-karimxonov** [comment]
Thank you so much it works
