### ISSUE TITLE
Blank page when printing

### ISSUE THREAD

**Issue by mahendharrv** [MatthewHerbst/react-to-print#581]
Hi, I am getting a blank page when printing react-table (v7.3.2) data, able to print headers but table data is not printing. The print function is working is my local machine but it is not working in other PCs. We tried changing copyStyles={false}, it worked initially but not working now. Can anyone please help me where to look at

**Comment by MatthewHerbst** [comment]
Hello. Could you please share some code, or ideally a working [Codesandbox](https://codesandbox.io/s/rzdhd) showing the problem? Thanks
