### ISSUE TITLE
Add blank space in between content 

### ISSUE THREAD

**Issue by SauravPatel3042** [MatthewHerbst/react-to-print#583]
Hello Team,
  I am using this package for a year, I work very well but in the last few days, it add blank space in between page content. I face this issue in safari, not in other browsers, so can you please give a response to solve this issue?

**Comment by MatthewHerbst** [comment]
Heh, if only there was a team. Just me 😄 

Have you updated your `react-to-print` version recently? We haven't released a new one in about a month.
Could you please share a [Codesandbox](https://codesandbox.io/s/rzdhd) showing the problem? Thanks!
