### ISSUE TITLE
Direct Download PDF

### ISSUE THREAD

**Issue by ladvabhautik7** [MatthewHerbst/react-to-print#591]
I am using react-to-print for download pdf but I am facing issue while I click on download pdf it's showing print instead of download how can I directly download pdf without showing print option.

Thanks

**Comment by MatthewHerbst** [comment]
Hello. This is unfortunately not easily possible. You would need to use the `print` prop to pass a custom print function, and in that function pass the contents of the iframe into whatever client-side PDF library you have.
