### ISSUE TITLE
Component is not being printed properly while using bootstrap with React

### ISSUE THREAD

**Issue by ManavJoshi111** [MatthewHerbst/react-to-print#592]
Hey there...
I am trying to print the following React component but in the PDF file the bootstrap col classes are not being printed next to each other. 

I am attaching both the images, one which is I want to print and another which is being actually printed.
<img width="459" alt="Resume_Org" src="https://user-images.githubusercontent.com/73978411/221423220-f81c7952-199f-4786-be12-54f1bc6a4db4.png">
<img width="447" alt="Resume_Org_Printed" src="https://user-images.githubusercontent.com/73978411/221423267-c4299761-cfe0-477d-99f1-3712d018a9ab.png">

I hope this will give you the idea of what I am trying to say. If you want I will share the code as well but I want this to be done really soon

**Comment by MatthewHerbst** [comment]
Hello. It looks like bootstrap is printing using a smaller viewport. Are you using the grid system to do the layout? Does this part of the README help? https://github.com/gregnb/react-to-print#styles-incorrect-in-print-dialog-when-using-grid-system
