### ISSUE TITLE
How to remove header and footer

### ISSUE THREAD

**Issue by gutisalex** [MatthewHerbst/react-to-print#593]
Hey, is there an option how to remove the header and footer via code?

![Bildschirmfoto 2023-02-28 um 08 29 43](https://user-images.githubusercontent.com/52527652/221784099-0515b016-ae19-402d-9642-96f9341af1e1.png)

![Bildschirmfoto 2023-02-28 um 08 30 01](https://user-images.githubusercontent.com/52527652/221784103-fcc88479-5516-4b30-9fd0-6ef8166dd26c.png)

**Comment by MatthewHerbst** [comment]
Hello. This shouldn't be showing be default. Are you passing in custom styles? If you could share your code it would be helpful. We hide this by default with this: https://github.com/gregnb/react-to-print/blob/8f88a81304fe070b7e850cc6f0014391803d1810/src/index.tsx#L31-L35

**Comment by gutisalex** [comment]
I am using useReactToPrint for this:

```ts
import { useReactToPrint } from 'react-to-print';
```

```ts
  const componentRef = useRef();
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  });
``` 

```html
<Styled.Content ref={componentRef}>
  <RichText htmlString={description} />
</Styled.Content>
```

Using Chrome!

**Comment by MatthewHerbst** [comment]
Hmm, without knowing what your `Styled.Content` and `RichText` components do, I wouldn't expect any issues there. Could you make a [Codesandbox](https://codesandbox.io/s/rzdhd) replicating the problem so I can help debug?

**Comment by gutisalex** [comment]
I created a sandbox and its working there as intended. I used a normal paragraph with some lorem ipsum. Then I used the same paragraph in my project but I got the header and footer again! Weird! Is it possible to overwrite those settings somewhere else? Some next settings, or so?

**Comment by MatthewHerbst** [comment]
Could you share the one where it's not working? I wonder if there is something special about it that we haven't seen that case before. As long as you're not setting the `pageStyle` prop it should be working

**Comment by gutisalex** [comment]
It will be difficult because its a huge project with contentful implementation and so on... but I try to reproduce the issue somehow...

**Comment by MatthewHerbst** [comment]
Yeah, just a minimum reproducible example would be ideal, definitely don't need your entire project!
