### ISSUE TITLE
Adding custom attributes to html tag 

### ISSUE THREAD

**Issue by NaqibAli** [MatthewHerbst/react-to-print#594]
Hi,  my css is using some html attributes like `dir="ltr"`   how it possible to add in [react-to-print](https://github.com/gregnb/react-to-print)

**Comment by MatthewHerbst** [comment]
Hello. Could you be more specific please? What about your CSS is not working? A reproducible code example on [Codesandbox](https://codesandbox.io/s/rzdhd) would be appreciated

**Comment by NaqibAli** [comment]
i am using styles like this 

```
[dir] .table:not(.table-dark):not(.table-light) thead:not(.table-dark) th, [dir] .table:not(.table-dark):not(.table-light) tfoot:not(.table-dark) th {
    background-color: #f3f2f7;
}
```
