### ISSUE TITLE
I am going to print an QR code may I know how can I set it to the center and bigger for printing?

### ISSUE THREAD

**Issue by MarcusCody** [MatthewHerbst/react-to-print#596]
`const pageStyle = "@page { size: A4 } @media print {html, body {height: 99%}}";`

![image](https://user-images.githubusercontent.com/104601262/223919626-775dc856-79d2-4319-b74b-9e975b02a2c0.png)

![image](https://user-images.githubusercontent.com/104601262/223919478-c70d7d93-3992-4c4f-a52a-a3031dca0bd5.png)

Is there a CSS attribute that can make the QR code to the center and bigger?

**Comment by MatthewHerbst** [comment]
Hello. Not to be unhelpful, but there are many ways to center a div using CSS. [MDN has a doc section on it](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Center_an_element). For specific CSS styling questions, StackOverflow is probably the best place to look for/ask about that. If you're running into a specific issue with `react-to-print` please let me know.
