### ISSUE TITLE
How to solve "Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.     at f.onload" error?

### ISSUE THREAD

**Issue by Khairul38** [MatthewHerbst/react-to-print#598]
![image](https://user-images.githubusercontent.com/86685877/224052464-9cba9110-e572-4422-b07f-df832ed1903a.png)

**Comment by MatthewHerbst** [comment]
Hello. As the error states, you have `img` tags on your page that do not have `src` properties set. This is not valid HTML. `react-to-print` will ignore those images and continue printing without them. You can either add a `src` property to the image, or remove them, or do nothing

**Comment by Khairul38** [comment]
![image](https://user-images.githubusercontent.com/86685877/224113921-e7827364-b35f-451a-8fcb-8ea7c63be06e.png)
![image](https://user-images.githubusercontent.com/86685877/224114640-4ab07d84-56af-4a99-ada6-150363b27d8c.png)

When I chose an image I set the src as createobjectURL. but when I click the print button entire component breaking. which kind of src react to print accept?

**Comment by MatthewHerbst** [comment]
Have you tried logging the output of `URL.createobjectURL(file)`? My guess is that it's returning an empty string. If you expand the error message you should be able to see the `img` node and what the attributes are on it. Could you share a picture of the expanded `img` and/or make a Codesandbox replicating the issue?

**Comment by Khairul38** [comment]
![image](https://user-images.githubusercontent.com/86685877/224146943-7564277e-d5e1-488b-95d4-273032e7981b.png)

**Comment by Khairul38** [comment]
There is no issue with the src or empty string, the image state not empty. i check this with console.log

**Comment by MatthewHerbst** [comment]
The logic that checks for this error is very simple:

https://github.com/gregnb/react-to-print/blob/8f88a81304fe070b7e850cc6f0014391803d1810/src/index.tsx#L362-L365

Are you able to reproduce the issue on [Codesandbox](https://codesandbox.io/s/rzdhd)? It's very difficult to debug from screenshots

**Comment by Khairul38** [comment]
![image](https://user-images.githubusercontent.com/86685877/224262784-f28ec819-63db-480e-b788-7492799d60e8.png)
I fixed this^ issue.
![image](https://user-images.githubusercontent.com/86685877/224263491-ab49a68f-d89c-4bab-88f6-3441cf326cb5.png)
![image](https://user-images.githubusercontent.com/86685877/224263966-4cd59ae1-58d9-4f3d-88f7-72a5db696722.png)
Now I need help to solve this^ issue. When I select any profile pic and then click on the download resume button then the error happens

Here is the link [Codesanbox url](https://codesandbox.io/p/github/Khairul38/resume-builder/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf29gefu000x356mhsihp68w%2522%253A%257B%2522key%2522%253A%2522clf29gefu000x356mhsihp68w%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clf29gv7500b9356mvhe54qs8%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F1%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clf29gthi006z356mteyes47h%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf29gefu000x356mhsihp68w%2522%252C%2522spacesOrder%2522%253A%255B%2522clf29gefu000x356mhsihp68w%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

There is 2 issue:
1. When I select the profile pic this^ error happens.
![image](https://user-images.githubusercontent.com/86685877/224265620-84b81c66-92c8-4c20-9287-4836fa1cb750.png)
2. ^window.print() method pdf page size and handlePrint() method pdf page size/print result not same. You can check both methods for the difference. I need window.print() method pdf page size on handlePrint() method

**Comment by MatthewHerbst** [comment]
The DOM error looks like an issue with your code, `react-to-print` doesn't change any values.

Regarding the page size, we have a section about this on the README, does it work for you? https://github.com/gregnb/react-to-print#set-the-page-size

**Comment by Khairul38** [comment]
![image](https://user-images.githubusercontent.com/86685877/224289950-cde70b42-711c-4e61-b24a-317096a7ecfb.png)
![image](https://user-images.githubusercontent.com/86685877/224288838-2d480abd-ba34-4722-90ec-26137fe15840.png)
If i give src like this^ there is no error

![image](https://user-images.githubusercontent.com/86685877/224289382-ca2815a9-77cd-4c95-b7cf-ab1f7cf80c5e.png)
when I give src like^ createobjectURL() then the error happen
![image](https://user-images.githubusercontent.com/86685877/224290513-55dd0407-0771-428d-aaf8-46402e0cbb23.png)

And this error happens only on handlePrint() method, if I use window.print() method there is no error.

**Comment by Khairul38** [comment]
You can check it on [Codesanbox](https://codesandbox.io/p/github/Khairul38/resume-builder/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf29gefu000x356mhsihp68w%2522%253A%257B%2522key%2522%253A%2522clf29gefu000x356mhsihp68w%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clf29gv7500b9356mvhe54qs8%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F1%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clf29gthi006z356mteyes47h%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf29gefu000x356mhsihp68w%2522%252C%2522spacesOrder%2522%253A%255B%2522clf29gefu000x356mhsihp68w%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

**Comment by Khairul38** [comment]
@MatthewHerbst 
Which type of src value does react-to-print allow?

**Comment by Khairul38** [comment]
Is there any solution to this issue?

**Comment by MatthewHerbst** [comment]
Hey, apologies. `react-to-print` doesn't check the type of the `src` value, just that it exists. However, the browser will force it to be a string. There is some issue with the input element as you can see in that last error, which causes the styles to break when uploading a picture (printing works fine before uploading the picture). I will try and find the issue, but I think it's not an issue directly with `react-to-print`

**Comment by Khairul38** [comment]
Please check the [Codesanbox](https://codesandbox.io/p/github/Khairul38/resume-builder/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf29gefu000x356mhsihp68w%2522%253A%257B%2522key%2522%253A%2522clf29gefu000x356mhsihp68w%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clf29gv7500b9356mvhe54qs8%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F1%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clf29gthi006z356mteyes47h%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf29gefu000x356mhsihp68w%2522%252C%2522spacesOrder%2522%253A%255B%2522clf29gefu000x356mhsihp68w%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

**Comment by MatthewHerbst** [comment]
Going to close this. Please feel free to re-open if this is still an issue, but it is extremely likely that it is an issue with the HTML on your page, not with `react-to-print`

**Comment by FredericEspiau** [comment]
I had this issue today and @MatthewHerbst is right, it was an issue in my code. I had a `<input type="file" />` with no `value` property on it. The issue was solved once I replaced my node with `<input type="file" value="" />`

**Comment by arlenkevich** [comment]
> I had this issue today and @MatthewHerbst is right, it was an issue in my code. I had a `<input type="file" />` with no `value` property on it. The issue was solved once I replaced my node with `<input type="file" value="" />`

Thank you buddy! Really very, very helpful!
