### ISSUE TITLE
Can't Load all print settings

### ISSUE THREAD

**Issue by SaravananAnbu** [MatthewHerbst/react-to-print#60]
`<div>
                                                    <div className="text-center">
                                                        <ReactToPrint
                                                            copystyles={true}
                                                            trigger={() => <a href="#">Print this out!</a>}
                                                            content={() => this.componentRef}
                                                            pageStyles="@page { size: landscape; }"
                                                        />
                                                    </div>
                                                        <PrintPage ref={el => (this.componentRef = el)}  />
                                                </div>`
![print](https://user-images.githubusercontent.com/38387413/47630851-25fa2680-db69-11e8-9dd5-c2c03d4a89dd.PNG)

**Comment by MatthewHerbst** [comment]
Can you be more specific about what your issue is please? Also, did you try clicking the "Background graphics" option in that dialog to see if that fixed your problem?

**Comment by MatthewHerbst** [comment]
@SaravananAnbu any update on this please?
