### ISSUE TITLE
 The color of the image changes when I try to print it.

### ISSUE THREAD

**Issue by kusu0830** [MatthewHerbst/react-to-print#600]
As the title suggests, the color of the image changes when I try to print it.

When I do a print preview, the colors are already unintended.

I intend to print the image, so I export it in CMYK.

Is there a setting I can do to print the image with the original color tones?

**Comment by MatthewHerbst** [comment]
Hello. Do you have "Background graphics" setting selected in the print preview? `react-to-print` does not change any colors, so this sounds like either a browser issue, or you have code that changes CSS styles during printing

**Comment by kusu0830** [comment]
Thank you for your response.
I don't think it is the library's fault either, but I was wondering if there is a way around this.

I have -webkit-print-color-adjust: exact; set and the image is always ready to be printed.

However, I am having trouble because the colors appear more bluish than expected.

The images are prepared in CMYK because they are intended to be printed.

**Comment by kusu0830** [comment]
I'm sorry.

There was a setting in the printer settings to turn off color matching. In my environment it gave me the desired color, but it is difficult to see if the user will do it.

If there is a setting that prevents the extra help, I am looking for a response again.

**Comment by MatthewHerbst** [comment]
Unfortunately we have zero control over the print dialog and the settings in there 😢 There is no web standard for printing, so each browser has their own implementation. The best we can do is call `window.print()` and hope the browser chooses good defaults. I'm hopeful in the future they will add a more standard API, so we could do something like `window.print(printSettings)`. 

Your best bet for now would be to show the user a tooltip or message near the print button telling them what they need to do if this is important. Note that what worked for your browser/printer might not be the same settings available for another user's browser/printer
