### ISSUE TITLE
How do I change the font size when changing the layout from portrait to landscape?

### ISSUE THREAD

**Issue by TaeHyun-Kim2** [MatthewHerbst/react-to-print#601]
Changing the layout from portrait to landscape and printing reduces the font size. How do I keep or grow without shrinking?

**Comment by MatthewHerbst** [comment]
Hello. You can control CSS in printing (which includes fonts) by using an `@media print` directive:

```css
@media print {
  font-size: 500px;
}
```

**Comment by TaeHyun-Kim2** [comment]
Hi I tried the following, but only size: landscape is applied and font-size is not applied. What should I do?

It is the same even if delete`@page {\ size: landscape; font-size: 700px\}\` and leave only font-size
```
{isLandscape && (
                <>
                    <style type="text/css" media="print">
                        {"\
                        @page {\ size: landscape; font-size: 700px\}\
                        "}
                    </style>
                    <style type="text/css" media="print">{"\
                        @page {\ font-size: 500px\}\
                    "}</style>
                </>
            )}
```

**Comment by MatthewHerbst** [comment]
What happens if you use a class instead of trying to dynamically load the CSS? Also, where are these tags relative to the component being printed. If you could make a [Codesandbox](https://codesandbox.io/s/rzdhd) showing your problem it would be much simpler to help

**Comment by TaeHyun-Kim2** [comment]
https://codesandbox.io/embed/suspicious-shadow-g0xl58?fontsize=14&hidenavigation=1&theme=dark

I attached the codesandbox
I want to give different font-size for horizontal and vertical

Just in case, I also added it to the styles.css file

**Comment by MatthewHerbst** [comment]
Please see the correct way of doing the CSS here: https://codesandbox.io/s/wonderful-elion-ou34bz?file=/src/styles.css

**Comment by TaeHyun-Kim2** [comment]
thank you i solved it

**Comment by MatthewHerbst** [comment]
Great! Please let me know if you run into other issues 😄
