### ISSUE TITLE
Printing multiple documents

### ISSUE THREAD

**Issue by torepettersen** [MatthewHerbst/react-to-print#602]
Hi, thanks for creating this nice library :smiley: 

I am just curious if it is possible to print multiple pdfs from a single button click?

E.g. I have one component for creating an invoices. And depending on the input is renders the different invoices I want to print. Is there a way where I can click a single button to save all the invoices at once? If possible I don't even want to see the print screen, just one click and all the invoice would directly start to print the invoice to the default download folder.

**Comment by MatthewHerbst** [comment]
Hello, and thanks for using the library!

Unfortunately, as mentioned in the [README](https://github.com/gregnb/react-to-print#can-react-to-print-be-used-to-download-a-pdf-without-using-the-print-preview-window), we aren't able to download a PDF directly. You can however use `react-to-print` to help facilitate creating a PDF locally and then downloading it. There is an issue linked in README that has many examples of how others have done this. Please let me know if you aren't able to find a solution.

**Comment by torepettersen** [comment]
Thanks, that was very helpful :smiley: 

I was at least able to use the `print` function to generate a single pdf using `js-html2pdf` as others suggested in the issue linked in the README. Then I hope I should be able to do that for more than once as well.
