### ISSUE TITLE
Is it possible to get a selectable/copiable text in the generated PDF ?

### ISSUE THREAD

**Issue by Bartaf83** [MatthewHerbst/react-to-print#605]
It seems you're generating a canvas and printing it.
I can't copy text from the generated PDF as a consequence.
And the content doesn't split properly per page, some elements are cut in their middle [https://i.imgur.com/3RNlgeB.png](https://i.imgur.com/3RNlgeB.png)

**Comment by MatthewHerbst** [comment]
Hello. That is not correct, we do not generate a canvas. We grab the part of the DOM that you want printed (as indicated by the ref returned in the `content` prop), and then we copy that DOM, along with all global styles, into an `iframe`. We than call `window.print` on the iframe, and everything after that, including any PDF generation, is done by the browser, not by us.

There is a section on the README that gives tips on how to properly do page breaks, as well as many issues dedicated to the topic. If you want to make a Codesandbox or similar showing your code we may be able to point you in the right direction.
