### ISSUE TITLE
When exporting with redux and refreshing browse, content disappears.  

### ISSUE THREAD

**Issue by chris2kus31** [MatthewHerbst/react-to-print#606]
When connecting redux, it looses it connects when refreshing browser. 

 connect(mapStateToProps, mapDispatchToProps).  Before refreshing screen, everything prints correctly, however, when you refresh your browse, all the content disappears and only the styles show on print preview.  

My component is a class component and is exported as below

`export default withStyles(s)(connect(mapStateToProps, mapDispatchToProps, null, { forwardRef: true })(ComponentToPrint))`

**Comment by MatthewHerbst** [comment]
Hello. Would it be possible for you to please make a [Codesandbox](https://codesandbox.io/s/rzdhd) replicating your issue? It's very difficult to offer support otherwise

**Comment by chris2kus31** [comment]
@MatthewHerbst ok, I will try but as in general, `react-to-print` works when exported with `mapStateToProps` and `mapDispatchToProps` ?

**Comment by MatthewHerbst** [comment]
I'm not a Redux expert so I can't speak too much about it, but `react-to-print` should work with any React code, regardless of what state management solution you use. I'm not sure if it's related, but we do have a paragraph about Redux in the [README](https://github.com/gregnb/react-to-print#common-pitfalls):

> The `connect` method from `react-redux` returns a functional component that cannot be assigned a reference to be used within the `content` props' callback in `react-to-print`. To use a component wrapped in `connect` within `content` create an intermediate class component that simply renders your component wrapped in `connect`. See https://github.com/gregnb/react-to-print/issues/280 for more.
