### ISSUE TITLE
can I get page number ?

### ISSUE THREAD

**Issue by shiv-raj45** [MatthewHerbst/react-to-print#607]
For each page can I get the page number at the bottom of each page?

**Comment by MatthewHerbst** [comment]
Hello. If you pass a custom value for the `pageStyle` you can show them. Specifically, we set `@page { margin: 0; }` which hides the page numbers: https://github.com/gregnb/react-to-print/blob/8f88a81304fe070b7e850cc6f0014391803d1810/src/index.tsx#L32-L35

**Comment by shubhamS-vs** [comment]
@shiv-raj45 Did it worked?

**Comment by aleksa-codes** [comment]
I have tried increasing the margin, but still can't see the page number.

**Comment by MatthewHerbst** [comment]
@aleksa-codes if you are able to share a Codesandbox or similar showing the issue I can take a look to try and help
