### ISSUE TITLE
Can I specify print preview settings?

### ISSUE THREAD

**Issue by TaeHyun-Kim2** [MatthewHerbst/react-to-print#609]
hi first of all thank you for making such a nice library

my customer wants two button one button is print and another button is download pdf

so i want to specify preview target when i click the button  print or save pdf

but i don't know how, can you tell me what to do?

**Comment by MatthewHerbst** [comment]
Hello. Unfortunately there is no ability to specify the print target in the print preview window. If you must have both of these buttons I would suggest having the PDF button download the content directly as a PDF and skip the print preview completely. If you search this repo's issues for PDF printing there are many questions/answer about how to do this. We also have a section on the [README ](https://github.com/gregnb/react-to-print#can-react-to-print-be-used-to-download-a-pdf-without-using-the-print-preview-window)about it (probably need to expand that, it doesn't give much info right now, sorry!)

**Comment by TaeHyun-Kim2** [comment]
Thank you for quick response
I already found out through READ.ME and issue, but I left a question in case I missed something.
I guess I'll have to find another way. Thank you.

**Comment by MatthewHerbst** [comment]
Sorry there isn't a better solution 😢 hopefully one day there will be a standard Print API for browsers! If you find a good solution for you please feel free to post it here for others to see in the future, thanks!
