### ISSUE TITLE
Print with title attribute.

### ISSUE THREAD

**Issue by KesavarajaRK** [MatthewHerbst/react-to-print#610]
Thanks for the awesome package.
I have a situation that people will add title attribute to few texts and when I print only the text content is getting in pdf. Any option to display the content of title attribute on hover / as a comment in PDF?. I need your guidance.

**Comment by MatthewHerbst** [comment]
Hello. If you know the nodes to look at you could change the content of the print yourself by using the `onBeforeGetContent` callback prop. Would that work for you?

**Comment by KesavarajaRK** [comment]
Let me try that and come back to you.

**Comment by KesavarajaRK** [comment]
Thanks. I got the content and title to be displayed in table and made it to print. Thank you so much.
