### ISSUE TITLE
In Microsoft office word addin print button doesn't open the print dialog on MAC

### ISSUE THREAD

**Issue by sajaadkhan7** [MatthewHerbst/react-to-print#613]
In Microsoft office word addin print button doesn't open the print dialog on MAC.
it is working fine in windows for the same. There is no console error and even the content is rendered.

**Comment by MatthewHerbst** [comment]
Hello. I'm not sure I understand. You are using this library in a addin to Microsoft Office online?

**Comment by sajaadkhan7** [comment]
Actually I am using this library inside officejs addin to Microsoft word on MAC desktop version. I have checked that the component to print is being rendered in the dom but clicking on print trigger button does not open the print dialog. Clicking on button just does nothing even no error in the console.
same code works for windows.

**Comment by sajaadkhan7** [comment]
![Uploading image.jpg…]()

**Comment by sajaadkhan7** [comment]
Even here I tried one of the examples given in this git repo.

**Comment by sajaadkhan7** [comment]
![IMG_4027](https://github.com/gregnb/react-to-print/assets/37328086/4a06576c-aa6b-4be2-9764-5b4f354f37d3)
![IMG_4026](https://github.com/gregnb/react-to-print/assets/37328086/cb4c0e67-4dac-4789-a4d0-4234b370bcc6)

**Comment by sajaadkhan7** [comment]
Looks like window.print() method doesn't work in the addin.

**Comment by MatthewHerbst** [comment]
It's very interesting, you're the first person I've ever heard of try to use the library like this. We do rely on `window.print` existing, so if that doesn't work in the addin then the library won't very well unfortunately. Please let me know if you find a solution, this is very interesting

**Comment by MatthewHerbst** [comment]
Going to close this for now, but again, please let me know if you find a solution here, it's a fascinating use-case
