### ISSUE TITLE
It looses styles when I hosted the website (hosted on firebase)

### ISSUE THREAD

**Issue by ali1998-wq** [MatthewHerbst/react-to-print#614]

**Comment by MatthewHerbst** [comment]
Hello. Could you please provide more details? It's not possible to debug or help you otherwise

**Comment by ali1998-wq** [comment]
The problem got solved when I used inline styling instead of using scss file

**Comment by MatthewHerbst** [comment]
Glad you got it working!

**Comment by ali1998-wq** [comment]
![image](https://github.com/gregnb/react-to-print/assets/69641688/6469fc59-3cf2-4158-8608-1f5a775f75d6)
![image](https://github.com/gregnb/react-to-print/assets/69641688/729b3af5-6f18-4fcc-8577-3e47cec0ff61)
I have attached two images of the barcode.One is the Image of the barcode on the website and other is the print preview of the barcode.It is not printing the barcode exactly.which is causing problems in scanning the barcode
