### ISSUE TITLE
Intermittent failures to print text

### ISSUE THREAD

**Issue by ghost** [MatthewHerbst/react-to-print#615]
I'm observing an issue that occurs intermittently. Text is not printed. Attached is a screenshot. Under which conditions does this type of issue occur? Perhaps my configuration is incorrect.

Invocation:

```jsx
<ReactToPrint
  documentTitle="Portfolio Analytics"
  content={() => this.componentRef}
  removeAfterPrint
  copyStyles
  trigger={() => (
    <div className="pdf-button">
      <div className="pdf-trigger">
        <PictureAsPdfOutlined />
        <div className="text">PDF Download</div>
        </div>
      </div>
    )}
  />
```

I have tried removing the 'removeAfterPrint' property to no avail.

I notice that, when the print dialog is open, the font changes on the page beneath the dialog. There must be some change to the DOM while printing. This could also be an issue with Chrome.

![Untitled](https://github.com/gregnb/react-to-print/assets/23711791/5943b218-10b8-4466-88e2-114457b82779)

**Comment by MatthewHerbst** [comment]
Hello. Would it be possible for you to make a [codesandbox](https://codesandbox.io/s/rzdhd) or similar replicating the problem? Hard to debug without being able to see it, your props look fine. During printing we create a hidden `iframe` and call `window.print` on that `iframe`, but otherwise your DOM shouldn't change unless you are using styles that change the DOM based on `@media print`

**Comment by ghost** [comment]
@MatthewHerbst Hmm, I likely can't reproduce my issue in a sandbox due to the size of the application.
I will, however, look into print media queries.
The application shouldn't be implementing any media queries that change or remove fonts.

**Comment by MatthewHerbst** [comment]
If the app is publicly hosted somewhere I can also look at it there. Just need a minimum reproducible example

**Comment by ghost** [comment]
The app is private I'm afraid, belongs to a company website. I'll come up with a way to reproduce the issue on a public platform ...

**Comment by ghost** [comment]
@MatthewHerbst looks like main window is being modified during the print operation. Observe the 'title' tag. It changes from 'BondNav | Portfolio Analytics' ( the name of the page), to 'Portfolio Analytics' (the name specified in the ReactToPrint invocation).

Before print:
![image](https://github.com/gregnb/react-to-print/assets/23711791/fd239cb5-57da-49bf-b3b8-63a4a99c08bd)

After print:
![image](https://github.com/gregnb/react-to-print/assets/23711791/0854d0b5-15ab-4885-b70f-2c06c0c5769c)

Any ideas as to how this could be happening? It seems significant to me because the library aims to modify the iframe window, but in this case is modifying the main window. Do you suspect that my issue is related?

**Comment by MatthewHerbst** [comment]
Ah, that is a good catch, and I should have been clearer when I commented, but that is expected. We do need to change the parent document's title temporarily since for some reason some browsers (namely, Chrome) don't seem to take the title off the `iframe` 😢 

https://github.com/gregnb/react-to-print/blob/8f88a81304fe070b7e850cc6f0014391803d1810/src/index.tsx#L119-L138

That code is super simple though, I don't see how it could causing your content not to display

**Comment by ghost** [comment]
@MatthewHerbst Thanks for your reply and for explaining the changes to the main window. This makes sense. I have since discovered that the fonts are not done loading when the print dialog window opens, in fact the fonts stay in 'pending' state while the dialog is open. This seems like it must have something to do with my issue. I discovered this while toggling the 'Disable Cache' checkbox in Chrome's Developer Tools window. This occurs when entering window.print() into the console. It's not related to react-print ... gotta be my application's architecture. Thanks for your time Matthew!

![image](https://github.com/gregnb/react-to-print/assets/23711791/be21a417-f247-47f2-9a41-1032681ccdc5)

**Comment by MatthewHerbst** [comment]
Ah yes, font loading during printing has been a very difficult issue for us to deal with. I tried a while back adding the `font` prop to `reacct-to-print` which attempts to load custom fonts before the print but it doesn't always work, have been looking for a better general solution here, but to your point, the browsers also just need to behave better

**Comment by ghost** [comment]
Thanks again Matthew

**Comment by MatthewHerbst** [comment]
Going to close this for now, but if you do find a solution please let me know, would love to learn how to help people solve these!

**Comment by ghost** [comment]
@MatthewHerbst Looks like my issue was occurring due to duplicate font-face definitions. We have a theme library which defines font-faces, an internal utility library which imports the theme lib, and an application which imports both the theme lib and the util lib.

When I removed the font-face imports from the util lib the issue was resolved...
Removing the duplicate font-face imports also fixed the issue with standard window.print() invocations.

thanks for your attention into the matter Matthew. Hope this helps others.

**Comment by MatthewHerbst** [comment]
Thanks for reporting back! Good to know that can be an issue
