### ISSUE TITLE
In iterative code like table rows it is passing all records to ComponentToPrint component even I passing current element as a props. How to fix this?

### ISSUE THREAD

**Issue by shraoned** [MatthewHerbst/react-to-print#617]

**Comment by MatthewHerbst** [comment]
Hello. Could you please show an example of your issue? Thanks

**Comment by shraoned** [comment]
![image](https://github.com/gregnb/react-to-print/assets/34828836/c02cb52d-86eb-4ef9-87d2-160c8ff4710d)

I'm doing this in the table but not getting perfect output.

```jsx
<ReactToPrint
    trigger={() => <img src="assets/images/print.png" alt="" className="w-25" />}
    content={() => componentRef.current}
/>
<div style={{ display: "none" }}><Print ref={componentRef} data={item} /></div>
```

**Comment by MatthewHerbst** [comment]
Can you show what you are getting versus what you expect to be getting? It's very difficult to help without seeing more of the code
