### ISSUE TITLE
 The border between pages is not perfect

### ISSUE THREAD

**Issue by mhanifmuhsin** [MatthewHerbst/react-to-print#624]
I have a problem with the table border not being perfect if the page is more than 1, here is a picture of the print preview results :

<img width="1135" alt="Screenshot 2023-06-09 at 16 11 05" src="https://github.com/gregnb/react-to-print/assets/68141840/3687dd05-1e15-4437-9bd8-d3ef39c96e1e">

is there any solution to solve this problem ? thank's

**Comment by MatthewHerbst** [comment]
Hello. You'll need to experiment with adding page breaks. We have a [README section](https://github.com/gregnb/react-to-print#page-breaks) on this topic, please let me know if that helps you. If not, I can try to help if you make a [Codesandbox](https://codesandbox.io/s/rzdhd) or similar showing the problem

**Comment by mhanifmuhsin** [comment]
Here is a sample [code](https://codesandbox.io/p/sandbox/clever-star-zj3wy9)

**Comment by MatthewHerbst** [comment]
Hello, just had time to look at this now, apologies, though hope you've figured something out. I have tried playing around with it, but page breaks inside of a table are hard, even without printing. This is probably a good question for StackOverflow if you need additional help. Please let us know, thanks!
