### ISSUE TITLE
Want to ask, when printing there is a zoom, how to display suitable for the printable area  

### ISSUE THREAD

**Issue by Julycc41** [MatthewHerbst/react-to-print#625]
![7251686569393_ pic](https://github.com/gregnb/react-to-print/assets/80231740/dfcf5c97-457c-4d18-bf00-fe4709405d2f)
![7261686569394_ pic](https://github.com/gregnb/react-to-print/assets/80231740/3d6556c8-8829-4b02-b77c-c327d4c09bb9)

**Comment by MatthewHerbst** [comment]
Hello. Apologies for the delayed response, I had to translate the text in the images.

Unfortunately there is no way to control this 😢 Once we call `window.print` the browser is in control, and we have very little ability to change what it decides.

You may be able to simulate the same by changing the CSS scale: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale

Please let me know what you discover. Apologies we cannot be of more help. Thank you!
