### ISSUE TITLE
How to dynamically change text without showing in UI

### ISSUE THREAD

**Issue by genesispvtltd** [MatthewHerbst/react-to-print#626]
Hi Sir,

I have used this react to print component in one of our projects and would like to disscuss how
can we show a dynamic text in the printing and not showing it for human eye in UI. I managed
to do this by using onBeforeGetContent and onAfterPrint but the user can see the dynamic text
apearing and dissapearing for one second in the UI and print looks good. My problem is how can I make it to work without
showing it to human eye in UI? can you please show me a code sample? or is this possible using
this package? Please help.
cc: @MatthewHerbst  @devuxer @cmckni3 

Regards,
Shameera

**Comment by MatthewHerbst** [comment]
Hello. We have a section about this on the [README](https://github.com/gregnb/react-to-print#how-do-you-make-componenttoprint-show-only-while-printing):

```jsx
<div style={{ display: "none" }}><ComponentToPrint ref={componentRef} /></div>
```

Please let me know if you run into any issues with this, thanks.

**Comment by adnanmirani1990** [comment]
Use Template Element  :
<template ><ComponentToPrint ref={componentRef} /></template >

**Comment by adnanmirani1990** [comment]
Use Template Tag :
<template ><ComponentToPrint ref={componentRef} /></template >

**Comment by adnanmirani1990** [comment]
Use Template  :
<template ><ComponentToPrint ref={componentRef} /></template >

**Comment by adnanmirani1990** [comment]
Use Template Tag :
<template ><ComponentToPrint ref={componentRef} /></template >
