### ISSUE TITLE
useReactToPrint -> print : styles are added as <link> instead of <styles> in production build

### ISSUE THREAD

**Issue by sumindersingh** [MatthewHerbst/react-to-print#627]
in below code, dev build has all the styles added as <styles> but in production builds it add styles as link. for example : <link href="/static/css/main.04fa777a.css" rel="stylesheet">.  if this HTML is send to API for PDF generation at backend then it wouldn't generate appropriate styles. Dev build works perfectly though. Any suggestions for prod builds ?  

```tsx
const handleSubmit = useReactToPrint({
  onPrintError: (error) => console.log(error),
  content: () => componentRef.current,
  removeAfterPrint: true,
  copyStyles: true,
  print: async (printIframe) => {    
    const document = printIframe.contentDocument;
    if (document) {
      const html = document.getElementsByTagName('html')[0];
    }
  },
});
```

**Comment by MatthewHerbst** [comment]
Hello. This sounds like an issue with your build system, not with `react-to-print`. The version of `react-to-print` that you are consuming doesn't change between your dev and prod builds.

In the off chance this is a `react-to-print` problem though, could you share a reproducible example? A [Codesandbox](https://codesandbox.io/s/rzdhd) would be ideal. We use [`element.tagName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) to set the correct tag ([here](https://github.com/gregnb/react-to-print/blob/de4c04b5472ccf00e3fdcd8f333fb4faf066e0b2/src/index.tsx#L442C59-L442C82) for styles, [here](https://github.com/gregnb/react-to-print/blob/de4c04b5472ccf00e3fdcd8f333fb4faf066e0b2/src/index.tsx#L484) for links). I tested `<style>` and `<link>` tags and they both give the expected result.

**Comment by sumindersingh** [comment]
hello Matt, thanks for your quick response. Attached first image shows a html produced in dev environment (npm start) and second image shows html from prod build (npm run build). In the prod version a <link> is added with relative path of the css. It would work fine if we generate PDF in the UI but sending this html as a param to api (to generate pdf at the backend) will not work. I will try to share some live example. 

![image](https://github.com/gregnb/react-to-print/assets/35346600/4104618c-228b-40a9-986a-58261c12f231)
![image](https://github.com/gregnb/react-to-print/assets/35346600/c52b8551-dfc6-4c05-8bcb-9f3ae5b3a64d)

**Comment by MatthewHerbst** [comment]
I assume the above is the HTML `react-to-print` is giving your `print` function. What does the HTML of the page look like before you print?

**Comment by sumindersingh** [comment]
yeah, correct the HTML <head> looks very different in Dev vs Prod builds. Generating PDF from the HTML using print function would work locally since css path and contents are available at this moment. I don't consider this to be an issue with react-to-print package and needs to find a way to extract the css in some variable and send it to the API.
