### ISSUE TITLE
Cors

### ISSUE THREAD

**Issue by matheusbento** [MatthewHerbst/react-to-print#628]
Hi Guys.

I'm loading an image dynamically in the front end from a variable, in the front end looks good, but when I click to save the PDF the same image is not showing on the pdf. I can see on the console the Cors error.

How can I solve this?

OBS: I don't have access to the backend code.

usage example:

```tsx
 const generateDoc = useReactToPrint({
    content: () => componentRef.current,
    pageStyle,
    // pageStyle: stylePrint
    print: async (printIframe: HTMLIFrameElement) => {
      const document = printIframe.contentDocument;
      if (document && deal?.ID) {
        const proposal = document.getElementById('proposal');

        var opt = {
          margin: [20, 20, 22, 20], //top, left, buttom, right
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: {
            scale: 2,
            bottom: 20,
          },
          pagebreak: { avoid: ['tr', 'span', 'p', 'td'], mode: 'css', before: '#nextpage1' },
          // pagebreak: { mode: 'css' },
          jsPDF: {
            unit: 'mm',
            orientation: 'portrait',
          },
        };

        await html2pdf()
          .from(proposal)
          .set(opt)
          .toPdf()
          .toCanvas()
          .save();
      }
    },
  });
```

**Comment by MatthewHerbst** [comment]
Hello. It's hard to know exactly what the error is since you haven't posted it, but if it's just a normal CORS error, you won't be able to fix it unless you have access to the server your page is being served from. If you can't get access you need to find a way to host the content on the  same origin
