### ISSUE TITLE
I am not able to sticky footer at the end of last page only. Is there any method to do it?

### ISSUE THREAD

**Issue by ArslanKhan99** [MatthewHerbst/react-to-print#634]
I am not able to sticky footer at the end of last page only. Is there any method to do it?

**Comment by MatthewHerbst** [comment]
Hello. You should be able to use the `onBeforeGetContent` prop to modify the React components during printing. When printing is happening you'll want to hide the footer from the page and then just include it as fixed bottom at the end. Does that make sense?

**Comment by ArslanKhan99** [comment]
Yes Thanks I will do it and inform here if its work. Thank you
