### ISSUE TITLE
Namespace 'React' has no exported member 'JSX'.

### ISSUE THREAD

**Issue by andrewerrico** [MatthewHerbst/react-to-print#636]
Running into this error with typescript project. Is this a typo? Should it be `JSXElement` ?

```
../../node_modules/react-to-print/lib/index.d.ts:51:21 - error TS2694: Namespace 'React' has no exported member 'JSX'.

51     render(): React.JSX.Element | null;
                       ~~~

Found 1 error.
```

**Comment by MatthewHerbst** [comment]
Are you looking for `React.ReactElement`?

**Comment by MatthewHerbst** [comment]
Though if you're trying to type a `render` function, I think what you really want is `React.ReactNode`.

Though really, you shouldn't ever need to type the `render` function. If you really want to, just type the component (`const MyComponent: React.FC` for functional component, `class MyComponent extends React.Component` for class components)

**Comment by andrewerrico** [comment]
No sorry, let me clarify I'm not using `render`. I'm using the `useReactToPrint` hook and everything works great locally, but when I go to run `tsc` it throws that error. Is there a minimum typescript version needed? Our project is still on v4

Edit:

I have a functional component like this based on the docs
```
export const Calendar = React.forwardRef<
  HTMLDivElement,
  React.PropsWithRef<CalendarProps>
>((props: CalendarProps, ref: React.Ref<HTMLDivElement>)) => {
    return (
      <div ref={ref}>
        ...
      </div>
  }
)
```

**Comment by MatthewHerbst** [comment]
Can you show your `react-to-print` usage please?

**Comment by andrewerrico** [comment]
Yes here's a trimmed down version of how I'm implementing it

```tsx
import React, { useRef } from 'react'
import { Calendar as YearCalendarForPrint } from './calendar'
import { useReactToPrint } from 'react-to-print'

export const Calendar: React.FC<CalendarProps> = (props: CalendarProps) => {
  const yearCalRef = useRef(null)

  const handlePrint = useReactToPrint({
    content: () => yearCalRef.current,
  })

  const handleOnClickPrint = () => {
    if (props.mode === 'year') {
      handlePrint()
    } else {
      window.print()
    }
  }

  return (
    <div>
      <button onClick={handleOnClickPrint} title='Print'>
        Print
      </button>
      <div style={{ display: 'none' }}>
        <YearCalendarForPrint
          events={props.events}
          ref={yearCalRef}
        />
      </div>
    </div>
  )
}
```

**Comment by andrewerrico** [comment]
So I tried a new project and a code sandbox matching all dependency versions and it compiles just fine. I can get around it by setting `skipLibCheck` in my tsconfig but just can't figure out why I have to do that

**Comment by MatthewHerbst** [comment]
Really not sure honestly. That type is coming directly from React; might be a good question to ask on StackOverflow?

**Comment by cmdoptesc** [comment]
Just an FYI, for anyone coming across this TypeScript issue, you need to update your `@types/react`. For folks still on React 17, @types/react [17.0.71](https://www.npmjs.com/package/@types/react/v/17.0.71) will fix this.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64464
