### ISSUE TITLE
DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

### ISSUE THREAD

**Issue by NeluQi** [MatthewHerbst/react-to-print#638]
DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

i use Ionic

Ionic use ShadowRoot

pls fix

**Comment by MatthewHerbst** [comment]
Hello. Can you provide more details please, include code samples and/or a working Codesandbox? I am not familiar with Ionic.

**Comment by NeluQi** [comment]
Right now I have no opportunity to give a ready-made example.

Try to run any demo https://ionicframework.com/ and try to print the block with any few components


The problem is most likely in the use
https://ionicframework.com/docs/theming/css-shadow-parts



Below is a very similar example on vue3
npm i
npm run serve
[bug-ionic-modal-master.zip](https://github.com/siaikin/vue-to-print/files/12483792/bug-ionic-modal-master.zip)

**Comment by siaikin** [comment]
I found a similar issue in html2canvas and a solution in this [issue](https://github.com/niklasvh/html2canvas/issues/2058) and [pull request](https://github.com/niklasvh/html2canvas/pull/2785). 

We need to copy the entire `Shadow DOM`, including its internal DOM elements and all styles, to the print document. In other words, we need to convert the `Shadow DOM` to a regular DOM.

> By the way, this is an issue from `vue-to-print`.

**Comment by MatthewHerbst** [comment]
The more I look at this the more I question what we should do here. The only way I've found to copy all of the shadow DOMs is to walk the entire DOM tree, check each node to see if it has a shadow tree, and clone it if there is one. I would really like to avoid having to iterate through the entire DOM tree. Curious to know your thinking on this @siaikin

**Comment by siaikin** [comment]
Unfortunately, it seems like iterating is the only option. The related issue https://github.com/whatwg/dom/issues/665 has not made any progress.

I implemented this functionality in https://github.com/siaikin/vue-to-print/pull/5, which required me to almost rewrite the code that clones specific elements (because it needs to clone the DOM through iteration instead of querySelector).
> print example: https://vue-to-print.netlify.app/guide/basic-usage.html#print-web-components

I think this is a significant change that needs to be approached with caution. Perhaps you can implement it in a new library https://github.com/gregnb/react-to-print/issues/635#issuecomment-1682706037.

**Comment by indraeng** [comment]
i am facing the same problem ,but i have noticed that this error is occuring in chrome but the same code is working in microsoft edge and firefox properly

**Comment by siaikin** [comment]
> i am facing the same problem ,but i have noticed that this error is occuring in chrome but the same code is working in microsoft edge and firefox properly

No idea. Can you provide an online code example?

**Comment by stavan-vc** [comment]
I guess you can use this [sandbox](https://codesandbox.io/p/sandbox/react-to-print-shoelace-w6hfgf?file=%2Fsrc%2FApp.js%3A24%2C15). It is also using ShadowDOM.

**Comment by MatthewHerbst** [comment]
`v3.0.0` has just been published which among other things includes a new `copyShadowRoots` option if you'd like to explicitly include Shadow DOM content in your print
