### ISSUE TITLE
Print dialogue only open once in safari on Mac

### ISSUE THREAD

**Issue by kapssoni** [MatthewHerbst/react-to-print#64]
Please help with following issue.

On safari, first time print dialogue opens up and everything works fine.
When trying to print again, A dialogue coming up asking to print or not(That is safari may be)
But after i click on "Print" then print dialogue is not showing up.

I also tried the same thing on the example provided in repo. same thing.

Please guide if you faced such issue or help fixing it.

**Comment by MatthewHerbst** [comment]
I was able to print twice using the demo app in Safari v12, MacOS 10.14 (Mojave).

Can you please me more specific about how to reproduce your issue, or even upload a video if possible?

Also, what version of Safari are you on?

**Comment by MatthewHerbst** [comment]
@kapsonic any updates on this by chance please?

**Comment by kapssoni** [comment]
To make this work I had to make few changes the way iframe is appended to the body and removed.

There us confirmation on safari to print and by the time user confirm to print the iframe is removed from dom. That is why this was happening. I changed and it worked.

**Comment by MatthewHerbst** [comment]
@kapsonic Great that you got it working! Could you please show us what you changed so that we can help others with this issue in the future?
