### ISSUE TITLE
table is not wrapped on the page. It was wrapped when printing

### ISSUE THREAD

**Issue by vaynevayne** [MatthewHerbst/react-to-print#642]
The page effect is not consistent with the print style, is there a way to solve this?

<img width="1253" alt="image" src="https://github.com/gregnb/react-to-print/assets/124666577/b4a12cef-81a8-4a90-baf5-82f5b185329d">

**Comment by MatthewHerbst** [comment]
Hello. This is likely a CSS issue where the page size of the print is smaller than the viewport of your browser. Are you able to share a reproducible code example?

**Comment by vaynevayne** [comment]
How to change the size of the print container?

**Comment by MatthewHerbst** [comment]
> How to change the size of the print container?

Make sure the page size is correct, and make sure the styles being applied during print are correct.  This will different for every website based on the technologies they use and the styles they have
