### ISSUE TITLE
No printing of the contents of the scroll container

### ISSUE THREAD

**Issue by vaynevayne** [MatthewHerbst/react-to-print#650]
https://stackblitz.com/edit/react-ks2bwr?file=index.css

This doesn't seem to be working.
```jsx
@media print {
  .ant-table-content {
    overflow: visible !important;
    height: fit-content;
  }
}
```

**Comment by MatthewHerbst** [comment]
Hello, thanks for the link!

I'm not sure I'm seeing the problem though, the vertical content seems to print fine? The horizontal content isn't making it onto the page but that's much more complicated to deal with, you need the table to become responsive.

What is the exact issue?


https://github.com/gregnb/react-to-print/assets/1287375/10b4dfbe-8592-4395-a7d4-a4d4af54f65d

**Comment by vaynevayne** [comment]
Yes, the horizontal scrolling content is not printed, how to deal with it?

**Comment by vaynevayne** [comment]
It's strange, in my project, I didn't add that css, but also can print the scrolling content, why is it?

<img width="1263" alt="image" src="https://github.com/gregnb/react-to-print/assets/124666577/cbd6f0cb-b2a9-4d16-96a1-1f5f92d35369">
<img width="1276" alt="image" src="https://github.com/gregnb/react-to-print/assets/124666577/3ac774ef-56ee-48e2-a36a-45538b3117cf">

**Comment by vaynevayne** [comment]
https://stackblitz.com/edit/react-ks2bwr?file=demo.tsx

customPrint can't resolve this
<img width="733" alt="image" src="https://github.com/gregnb/react-to-print/assets/124666577/6d183e2e-0e57-4851-acb1-e80b6e2a988c">

**Comment by siaikin** [comment]
hi @vaynevayne, Regarding this issue, first we need to clarify that printing paper requires sufficient width and height to accommodate the elements you need to print. When the height is insufficient, more pages are generally generated. However, when the width is insufficient, only the printed content is truncated.

From the above, you need to set a larger paper size or reduce the width of the printed content.

* For the first point: set a larger paper size through @page { size: WIDTH HEIGHT }, https://github.com/gregnb/react-to-print#set-the-page-size
  *  @page { size: 800mm 800mm } 
    ![image](https://github.com/gregnb/react-to-print/assets/24749324/1312e895-322c-4125-b7f2-98bb7f6b3ff5)

* For the second point: I see that you have set the width of the columns, please reduce it.

**Comment by vaynevayne** [comment]
thanks,
