### ISSUE TITLE
No import for @types/react-to-print

### ISSUE THREAD

**Issue by ac185426** [MatthewHerbst/react-to-print#651]
This package is created in typescript but we cannot actually import types to use during development

**Comment by MatthewHerbst** [comment]
Hello. This project is natively written in TypeScript, and ships with an `index.d.ts` file. You should be able to get any types you need directly from the project. Most project written in TypeScript, including this one, do not ship a `@types/<project>` package.

For example:
```ts
import type { IReactToPrintProps } from "react-to-print";
```
