### ISSUE TITLE
Duplicating the page when using @react-to-print

### ISSUE THREAD

**Issue by Alluri-Sahiti** [MatthewHerbst/react-to-print#653]
```
const handlePrint = useReactToPrint({
		content: () => PrintRef.current,
	  });
```
I hope you can help me with this issue

**Comment by MatthewHerbst** [comment]
Hello. Can you please explain what your issue is? Some code (ideally a working, reprodceable example on Codesandbox or Stackblitz, etc) would be helpful,

**Comment by Alluri-Sahiti** [comment]
The webpage i'm trying to print is duplicating in one more tab in the browser and the page where i'm clicking on print button  getting this error in console 
```
(5) ['"react-to-print" was unable to load a resource but will continue attempting to print the page', 'Failed to load', link#app-style, 'Error:', undefined]
0
: 
"\"react-to-print\" was unable to load a resource but will continue attempting to print the page"
1
: 
"Failed to load"
2
: 
link#app-style
3
: 
"Error:"
4
: 
undefined
length
: 
5
[[Prototype]]
: 
Array(0)
```

**Comment by Alluri-Sahiti** [comment]
The problem got resolved i was using anchor tag with target="_blank" attribute

**Comment by MatthewHerbst** [comment]
Thanks for letting us know!
