### ISSUE TITLE
Different print styles using beforeprint event listener vs. button using same ReactToPrint function

### ISSUE THREAD

**Issue by tryding** [MatthewHerbst/react-to-print#655]
I'm seeing different content/styling on the print preview between a button using the useReactToPrint function and an event listener that uses the same function. Below screenshot is what our print view should look like, this view comes up when you right click -> hit print or hit CTRL+P.

![ctrl p print](https://github.com/gregnb/react-to-print/assets/3631865/fd4a5788-c3f6-4def-9169-52fcc7b8527c)

There is a button that you can click to open the print dialog as well, but it seems like it's not pulling the print media queries, see next screenshot

![print button](https://github.com/gregnb/react-to-print/assets/3631865/db6bbcd4-eaa3-451f-ad73-0cebcf32ef47)

The reactToPrint function is created and attached to the event handler in the container component. That function is also passed down to a child component that contains the print button itself. I can see that the reactToPrint function is getting called regardless of how you get the print dialog to open. Here's the useReactToPrint function as well, let me know if there's anything else I can add to help. Sandbox might be difficult to set up but I can try if that's what I need to do. Any help figuring out why this is happening is appreciated, thanks!

```jsx
  const handlePrint = useReactToPrint({
    content: () => printRef.current,
    pageStyle: ``,
    onBeforeGetContent: async () => {
      setPerformanceQuarterly(true);
      viewResult();
      const screenerData = resultData?.screenerData;
      const overallDisclosures = [];
      let xidList = '';

      screenerData?.forEach((item, index) => {
        xidList = xidList.concat(`${item.TCWSODIssue}|`);
        if (item.TCFundType === FUND_TYPES.variableAnnuityCref) {
          const hasCrefDisclosures = overallDisclosures.some(disclosure => disclosure.header === 'CREF Expenses');
          if (hasCrefDisclosures) return;
          overallDisclosures.push({
            header: 'CREF Expenses',
            subText: 'The following expense information applies to all CREF Variable Annuities',
            content: expenseDisclosures.crefVAExpenseNote
          })
        }
      });
      
      const service = await internalApiClient(yyy, channel)
      const disclosureBulkResult = await getProfileFootnotesBulk({ xidList, client: service });
      
      setPrintDisclosures(disclosureBulkResult);
      setPrintOverallDisclosures(overallDisclosures);

      return new Promise(async resolve => {
        printPromiseResolveRef.current = resolve;
        setIsPrinting(true);
      });
    },
    onAfterPrint: () => {
      // Reset the Promise resolve so we can print again
      printPromiseResolveRef.current = null;
      setIsPrinting(false);
    }
  });
```

**Comment by MatthewHerbst** [comment]
Hi, apologies for the delayed response, I was traveling and did not have access to a computer. Are you still having an issue here? My naive guess is that your styles are included somewhere above the ref being passed to react-to-print and so the styles just aren't included in the react-to-print iframe, but it's really hard to know without seeing more of your code

**Comment by alamenai** [comment]
I guess it's the same issue as [#664 ](https://github.com/gregnb/react-to-print/issues/664)
