### ISSUE TITLE
sometimes some images (Next.js Image) not load in print preview

### ISSUE THREAD

**Issue by mengxi-ream** [MatthewHerbst/react-to-print#656]
Hi, I got some images (school icons which are images) in my like this:
![CleanShot 2023-10-05 at 16 40 09@2x](https://github.com/gregnb/react-to-print/assets/38809606/d663a2f1-2ff1-46f4-83b7-d5ad1e1ff61c)
But sometimes, when I click "Download Resume" button to open the pdf preview window, some images may not be loaded, for example, the following school icons are missing:
![image](https://github.com/gregnb/react-to-print/assets/38809606/e2ba1091-073b-4118-b884-370fb65b933e)
I tried to use the following code to wait for loading? but the issue still happens
```tsx
    // wait animation or image loading for a while before printing?
    onBeforePrint: () => {
      return new Promise<void>((resolve) => {
        setTimeout(() => {
          resolve();
        }, 500);
      });
    },
```

My code is here https://github.com/Crayon-ShinChan/react-resume-starter, You can download it, and `npm i` & `npm run dev` to start. The relevant files are in folder `app/(main)/resume`

This issue occurs approximately once every 20~30 ”Download Resume" button clicks.

**Comment by siaikin** [comment]
Removing `loading="lazy"` from the `img` tag can solve the problem. The root cause is that the `iframe` element created for printing content is hidden (off-screen), and `loading="lazy"` will defer loading of invisible images, causing the images to not be rendered during print preview.

> The load event fires when the eagerly-loaded content has all been loaded; at that time, it's entirely possible (or even likely) that there may be lazily-loaded images that are within the visual viewport that haven't yet loaded.
> from: [Lazy loading](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes)

However, one thing that puzzles me is that, based on the above reasoning, all lazily-loaded images should not be rendered in print preview, but the fact is that Starbucks/Bitcoin/Tiktok always render on my computer. 🤔

**Comment by mengxi-ream** [comment]
> Removing `loading="lazy"` from the `img` tag can solve the problem. The root cause is that the `iframe` element created for printing content is hidden (off-screen), and `loading="lazy"` will defer loading of invisible images, causing the images to not be rendered during print preview.
> 
> 
> 
> > The load event fires when the eagerly-loaded content has all been loaded; at that time, it's entirely possible (or even likely) that there may be lazily-loaded images that are within the visual viewport that haven't yet loaded.
> 
> > from: [Lazy loading](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes)
> 
> 
> 
> However, one thing that puzzles me is that, based on the above reasoning, all lazily-loaded images should not be rendered in print preview, but the fact is that Starbucks/Bitcoin/Tiktok always render on my computer. 🤔

on my computer it's same. Seems the image is still loading but the images was loading one by one?

**Comment by siaikin** [comment]
Generally, `loading="eager"` is the default (which is also the reason for **removing `loading="eager"**).
> Loads the image immediately, regardless of whether or not the image is currently within the visible viewport (this is the default value). from [Lazy loading](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes)

However, in your project, [`loading="lazy"` is the default](https://nextjs.org/docs/pages/api-reference/components/image#loading), so you need to set `loading="eager"` instead of just removing `loading="lazy"`.

**Comment by mengxi-ream** [comment]
> Generally, `loading="eager"` is the default (which is also the reason for **removing `loading="eager"**).
> 
> > Loads the image immediately, regardless of whether or not the image is currently within the visible viewport (this is the default value). from [Lazy loading](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes)
> 
> However, in your project, [`loading="lazy"` is the default](https://nextjs.org/docs/pages/api-reference/components/image#loading), so you need to set `loading="eager"` instead of just removing `loading="lazy"`.

Thank you for this insight! I also check out the nextjs doc https://nextjs.org/docs/pages/api-reference/components/image#loading, they said we can also use `priority` to preload the image. So for a short summary, we can use
1. `loading="eager" for Next.js Image
2. `priority` for Next.js Image (preload image), this probably with higher performance than `loading="eager"` according to Next.js
