### ISSUE TITLE
Modifying html within iframe

### ISSUE THREAD

**Issue by skemprunner** [MatthewHerbst/react-to-print#658]
Hi,

Is there any way of adding html classes to the iframe or getting access to the document ?
I see there is a bodyClass so it would a small step to have an htmlClass prop.

Thanks.

**Comment by MatthewHerbst** [comment]
Hello. Apologies for the delayed response, I was traveling and did not have access to a computer. Could you share more about what you are trying to do please? If you pass the `print` prop you can get access to the entire iframe document, though you are then responsible for calling `window.print()` on it yourself

**Comment by skemprunner** [comment]
Hi Matthew,

Using some libraries which apply theming by applying classes on html tag. But all I need is to access the iframe to customize so was just accessing it in the onBeforePrint callback by searching for the #printWindow selector.
I'll try your suggestion also.
So considering this isn't a typical scenario, happy to continue doing this.

**Comment by MatthewHerbst** [comment]
Sounds good. Please feel free to ask any questions or post interesting code, always interesting to see non-standard use-cases

**Comment by boompttn** [comment]
For future reference, if you want to modify the body attribute inside the iframe with print function

```tsx
print: iframe => {
      return new Promise(resolve => {
        iframe.contentDocument?.body.setAttribute('id', 'iframe-body');
        iframe.contentWindow?.print();
        resolve('');
      });
    },
```
