### ISSUE TITLE
required field validation not working

### ISSUE THREAD

**Issue by gluupo** [MatthewHerbst/react-to-print#660]
we were using jsPDF and switched over to react-to-print a few days ago. we have required fields in our form that need to be filled out before printing, and the validation is not working before the print preview modal pops up. 
![image](https://github.com/gregnb/react-to-print/assets/56419984/37001939-7b9c-4727-aee3-ed111357b686)

**Comment by MatthewHerbst** [comment]
Hello. Is there a problem with `react-to-print` here? It sounds like you have a validation logic issue? Don't allow the print button to be clicked until the form is valid

**Comment by gluupo** [comment]
you're totally right, i got it to work with useReactToPrint. sorry about that!
