### ISSUE TITLE
Material UI Table can not print scroll content

### ISSUE THREAD

**Issue by RafaelCENG** [MatthewHerbst/react-to-print#661]
Hello everyone. I am trying to print my modal which has a material ui table inside it with scrolling. I tried everything for the fixes but nothing happened. I used className on my modal outside,inside my table,table container etc still nothing.

```js
  // Print
  const componentRef = useRef(null);
  const reactToPrintContent = React.useCallback(() => {
    return componentRef.current;
  }, [componentRef.current]);

  const customToPrint = useCallback((printWindow) => {
    console.log(printWindow);
    const printContent =
      printWindow.contentDocument || printWindow.contentWindow?.document;
    const printedScrollContainer =
      printContent.querySelector(".scroll-container");

    printedScrollContainer.style.overflow = "visible !important";
    printedScrollContainer.style.height = "fit-content !important";

    printWindow.contentWindow.print();

    // print must return a Promise
    return Promise.resolve();
  }, []);

  const handlePrintModal = useReactToPrint({
    content: reactToPrintContent,
    documentTitle: "Compared Session",
    print: customToPrint,
    removeAfterPrint: true,
  });

  return (
    <>

          <Modal
            open={props.showModal}
            onClose={() => props.handleCloseModal()}
            ref={componentRef}
            className="scroll-container"
            sx={{ overflow: "scroll " }}
          >
          ...
```
Im getting only the first page. (What the screen fits.) 
Thanks in Advance.

**Comment by RafaelCENG** [comment]
To clarify I'm using material ui modal --> paper --> some boxes --> table

**Comment by MatthewHerbst** [comment]
Hello. Any chance you could make a working example on Codesandbox or similar? Very hard to debug code that doesn't work without the right imports/env. Off the top of my head, I wonder if you might find it simpler to print the contents of the modal rather than the modal itself?

**Comment by RafaelCENG** [comment]
Hi, thanks for the response I will update you on Monday thanks.

**Comment by RafaelCENG** [comment]
Good morning. I moved the ref to the Paper component of the Material UI which is under Modal and it's working perfectly. One more question I gave a documentTitle string. When I save it as a file it doesn't use that name.

```
documentTitle: "Compared Sessions",
```
![image](https://github.com/gregnb/react-to-print/assets/45431116/ba627556-a777-4b0a-a112-93036c936930)

**Comment by MatthewHerbst** [comment]
Glad to know the printing is working! For the title issue, could you please let me know what browser you are using?

**Comment by RafaelCENG** [comment]
Google Chrome
Version 119.0.6045.105 (Official Build) (64-bit)

**Comment by RafaelCENG** [comment]
Im closing this issue since the first part worked.
