### ISSUE TITLE
Show All Content doesnt work for landscape and different browsers.

### ISSUE THREAD

**Issue by RafaelCENG** [MatthewHerbst/react-to-print#662]
I'm using Google Chrome. Portrait mode works perfectly with the scroll. Then on my print settings if I change to landscape shows only the first page. Also, I checked Safari and portrait mode shows only the first page too.
Im using the !importan too.

```js
    printedScrollContainer.style.overflow = "visible !important";
    printedScrollContainer.style.height = "fit-content !important";
```

**Comment by RafaelCENG** [comment]
Now it working. Weird.

**Comment by RafaelCENG** [comment]
Re-opened something weird is happening. Now it's not working again.

**Comment by siaikin** [comment]
Hello. Could you make a working example on Codesandbox or similar? The information obtained from your description is limited.
You can use this demo https://github.com/gregnb/react-to-print#demo make your example.

**Comment by RafaelCENG** [comment]
Sorry for the delay probably time difference.
[Codesandbox](https://codesandbox.io/s/hardcore-ioana-7qcx88)
I created a minimal reproduction. I  used the same code I do in my case with a fast dump material ui table.

**Comment by siaikin** [comment]
> Sorry for the delay probably time difference. [Codesandbox](https://codesandbox.io/s/hardcore-ioana-7qcx88) I created a minimal reproduction. I used the same code I do in my case with a fast dump material ui table.

i modify your example. look this https://codesandbox.io/s/wizardly-boyd-p45qr4?file=/src/App.js.

**Comment by RafaelCENG** [comment]
Thanks, I have a break now. I will reply in a bit if it's working!

**Comment by RafaelCENG** [comment]
Worked thanks. Marking the reply as an answer.
