### ISSUE TITLE
iframe is not displayed in the PDF preview

### ISSUE THREAD

**Issue by alamenai** [MatthewHerbst/react-to-print#667]
Hi @cmckni3 ,

I'm trying to print a PDF Preview component, everything is displayed well, however the `iframe` does not display it's content when I click on print:

### Component

![image](https://github.com/gregnb/react-to-print/assets/20143684/cb09b746-df90-46b0-bab2-0b8beba01f2f)

### Printing Preview

![image](https://github.com/gregnb/react-to-print/assets/20143684/7f4d95bd-2303-4d5f-8d3e-3c2c85d211c5)

If I try another HTML tag, it works well on the `iframe`.

## Code

```tsx
"use client"

import { useSelector } from "react-redux"

import { RootState } from "@/redux/store"

import { BuildingInformationCards } from "./Cards/Cards"
import { BuildingInformationTable } from "./Table/Table"

export const BuildingInformation = () => {
  const addressInfo = useSelector((state: RootState) => state.solar)
  const { city, zipCode, houseNumber, street } = addressInfo

  const src = `https://credium-viewer-map.azurewebsites.net/?street=${street}&house_number=${houseNumber}&zip_code=${zipCode}&city=${city}`

  return (
    <div className='mt-4 mb-1'>
      <p className='text-xl font-semibold'>Ihre Gebäudeinformationen</p>
      <BuildingInformationTable />
      <BuildingInformationCards />
      <iframe src={src} width='100%' height='300'></iframe>
    </div>
  )
}

```

**Comment by MatthewHerbst** [comment]
Hello. Would it be possible for you to make a codesandbox or similar that replicates the problem? It's not possible to debug this with just a little bit of code. Thank you. Also, no need to tag anyone on these, I'm the only full-time maintainer 😄

**Comment by cmckni3** [comment]
> Also, no need to tag anyone on these, I'm the only full-time maintainer 😄

Yeah not sure why I am mentioned in issues since I haven't contributed in 5 years or so 😆

**Comment by MatthewHerbst** [comment]
@cmckni3 hope all is well!

**Comment by cmckni3** [comment]
> @cmckni3 hope all is well!

Yep, all good. Busy as usual. Hope all is well!
