### ISSUE TITLE
 Issue with Link Export When Referring to the Same Page 

### ISSUE THREAD

**Issue by AleksandrKarashev** [MatthewHerbst/react-to-print#668]
version 2.14.15

I am experiencing a problem with link export functionality in version 2.14.15 when hyperlinks refer to the same page. For instance, while staying on the URL http://localhost:3000/constitution, the following hyperlinks are present:

- http://localhost:3000/constitution
- http://localhost:3000/constitution#art.5
- http://localhost:3000/constitution#art.8
- http://localhost:3000/law#art.5
- http://localhost:3000/law#art.111

The problem is that the PDF does not recognize these links when they point to the same page.
- http://localhost:3000/constitution
- http://localhost:3000/constitution#art.5
- http://localhost:3000/constitution#art.8

These links only navigate properly to other pages:
- http://localhost:3000/law#art.5
- http://localhost:3000/law#art.111

**Comment by MatthewHerbst** [comment]
Hello. If you use cmd+p/ctrl+p to print the entire page do you get the same behavior? `react-to-print` does not generate a PDF, that is done by your browser. Could you please let us know what browser and version you are using?

**Comment by AleksandrKarashev** [comment]
Hello! I tested in browsers chrome/firefox/edge, the last versions. ctrl + p also don't generate links, so this is not the issue of the library, sorry. But I suspect I know the problem: path in `href` of tag `a` must be absolute (I use relative). I will test it later, in a few hours and I will tell you result. I think so because other similar websites don't have this problem(I had should test them before to write here).

**Comment by MatthewHerbst** [comment]
We can't help with ctrl+p, but in the `react-to-print` context you could re-write the paths from relative to absolute in the `onBeforeGetContent` callback. But it would be much simpler to just use absolute paths everywhere if possible. Please let us know what you discover, always interested to learn new printing quirks/issues. Thanks!

**Comment by AleksandrKarashev** [comment]
This is a really interesting case, and there is no problem with absolute/realtive path.
I've tested it on localhost, and it might behave differently in a production environment. Consider the following example:
Let's take an example:
Suppose I'm on the URL: `http://localhost:3000/constitution`
hyperlinks: 
      `<a href={'/constitution'}>...</a>`   -> OK
      `<a href={'/constitution#art-5'}>...</a>` -> NOT OK
      `<a href="http://localhost:3000/constitution#art-5">...</a>` -> NOT OK
      `<a href="https://site.com/constitution#art-5">...</a>` -> NOT OK
      `<a href={'/anyotherurl#art-5'}>...</a>`  -> OK
      
 The problem arises with hyperlinks having an href pointing to the same URL and containing a hash. 
 (PS: chatgpt corrected my English here)
 
 I will test it later in production environment and tell you the result.

**Comment by MatthewHerbst** [comment]
Can you define what is "not ok" about the links? I tried this in Chrome with some basic html and didn't find any issues

**Comment by AleksandrKarashev** [comment]
it is not recognized as links after saving pdf-file. I will test more later and show you screenshots.

**Comment by MatthewHerbst** [comment]
Ideally we can make a minimally reproduce-able example using just some basic HTML, no React or anything else needed.

```html
<html>
  <body>
    <a href="link that works">Working Link Style A<a>
    <a href="link that works">Working Link Style B<a>
    <a href="link that does not work">Broken Link Style A<a>
    <a href="link that does not work">Broken Link Style A<a>
    <div>Div</div>
    <a id="someAnchorId">Cool content<a>
  </body>
</html>
```

**Comment by elburro1887** [comment]
In case anyone has an issue with the links, i just figured out that it didn't work if the contentRef container was a custom React component that I used (<Row> from react-bootstrap). 

Once i changed it to a regular <div>, the links started working, although they dont work on Firefox for some reason. In Firefox, the links are absolute ones and will then redirect to a browser.

**Comment by MatthewHerbst** [comment]
Hey @elburro1887. Do you mind sharing a [Codesandbox](https://codesandbox.io/s/rzdhd) example showing what happens when you use a custom React component?
