### ISSUE TITLE
Issue react-to-print style not working in production environment

### ISSUE THREAD

**Issue by rajkumars22** [MatthewHerbst/react-to-print#669]
[KDOR Assessment Connect and Comparables-Prod-env.pdf](https://github.com/gregnb/react-to-print/files/13496937/KDOR.Assessment.Connect.and.Comparables-Prod-env.pdf)  - issue in production enviroment

local environment working fine like this ..
[KDOR Assessment Connect and Comparables Test_.pdf](https://github.com/gregnb/react-to-print/files/13496980/KDOR.Assessment.Connect.and.Comparables.Test_.pdf)

```jsx
const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    copyStyles: true,
    pageStyle: `
    @page {
        /* Remove browser default header (title) and footer (url) */
        margin: 5;
    }`,
    onBeforeGetContent: () => {
      return new Promise((resolve) => {
        promiseResolveRef.current = resolve;
        setIsPrinting(true);
      });
    },
    onAfterPrint: () => {
      // Reset the Promise resolve so we can print again
      promiseResolveRef.current = null;
      setIsPrinting(false);
    }
  });
  ```

**Comment by MatthewHerbst** [comment]
Sounds like your styles in your production environment are done differently than in your dev/local environment. `react-to-print` does not run differently in the two

**Comment by rajkumars22** [comment]
Thanks, @MatthewHerbst
how to fix that issues, can you suggest the solution?

**Comment by MatthewHerbst** [comment]
I don't know anything about your project or what is different between your production and development code.

**Comment by siaikin** [comment]
@rajkumars22 Can you provide an example of a production environment? It is difficult to determine the issue based solely on your description.
