### ISSUE TITLE
direclty printing instead of downloading

### ISSUE THREAD

**Issue by mosesnagar** [MatthewHerbst/react-to-print#670]
hi, currently we're using this library to print a PDF. is there a way to skip the printing phase and just downloading it?

thanks

**Comment by MatthewHerbst** [comment]
Hello. As [mentioned on our README](https://github.com/gregnb/react-to-print#can-react-to-print-be-used-to-download-a-pdf-without-using-the-print-preview-window), `react-to-print` is not capable of generating PDFs, all we do is open the content for printing in the browser, and the browser offers you the option to print a PDF. If you visit the link in the README there is a [thread](https://github.com/gregnb/react-to-print/issues/484) with some example of how to mix `react-to-print` with other libraries to do this. Please let us know if you run into any issues.
