### ISSUE TITLE
Have problem with size when print element

### ISSUE THREAD

**Issue by gummitpro** [MatthewHerbst/react-to-print#671]
Hi guys. I have problem when I print my element
![image](https://github.com/gregnb/react-to-print/assets/82520034/6c85d53e-fa0c-4a6a-9b3e-efaf26813ff1)
It have size 1198x656
So I use ref follow document
![image](https://github.com/gregnb/react-to-print/assets/82520034/d2631a01-74e5-4627-89fd-dd7fa744305b)
![image](https://github.com/gregnb/react-to-print/assets/82520034/5f2220bc-de39-41f1-b7ac-e63aa3128774)
When I click print, it only show a part of my element like this: 
![image](https://github.com/gregnb/react-to-print/assets/82520034/6697ce80-a6b3-4675-b576-e11a549b3bcd)

How do I fix this problem?

**Comment by siaikin** [comment]
The width corresponding to A4 is 210mm (which also corresponds to 793px on my computer). However, the width of your table is 1198px, which is too large. You need to make the table width adaptive or manually adjust the width of certain columns.

But I see that you have set width: 100% on the Box component, which is not taking effect. This is confusing. Can you provide an online example (such as StackBlitz or CodeSandbox)?
