### ISSUE TITLE
Cannot Print on MS Edge Browser

### ISSUE THREAD

**Issue by InHwanPark** [MatthewHerbst/react-to-print#672]
When I print html element content on MS edge browser it never ends the download process and canceling the download process

![image](https://github.com/gregnb/react-to-print/assets/24218853/7824cac9-e588-4afb-a8f1-e574c900cd64)

it happens only on Edge browser and works fine on chrome or safari

I code is following the basic setting instruction, so I think it is about browser support 

![image](https://github.com/gregnb/react-to-print/assets/24218853/f43b4d71-aff9-4553-8a8e-cb86da674a8f)

**Comment by MatthewHerbst** [comment]
Hello. Does this only happen when you use `react-to-print`, or does it also happen if you print the whole page using ctrl+p?

**Comment by InHwanPark** [comment]
Oh! sorry for the late reply. I just checked it but it also happen on control-p command on windows edge browser.

**Comment by MatthewHerbst** [comment]
Hi, thanks for checking! That tells me that this is not a `react-to-print` issue, but rather an issue with MS Edge and/or your computer and/or your code specifically. Is it possible for you to make a Codesandbox or similar that shows the issue?
