### ISSUE TITLE
Document title with Cyrillic characters encoding problem

### ISSUE THREAD

**Issue by danikane** [MatthewHerbst/react-to-print#673]
Hi, I'm not sure this has been reported yet, but basically the title is self-explanatory.
Cyrillic characters in the document title become something else:

![image](https://github.com/gregnb/react-to-print/assets/18037666/87e3d02f-a995-42cf-b85c-a7c551e6817e)
![image](https://github.com/gregnb/react-to-print/assets/18037666/e32730d6-e3d1-48aa-a54a-c32a1415db3c)
```
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: 'Справка',
    onAfterPrint: () => console.log('Printed PDF successfully!'),
  });
```

I suspected this would be a problem for other languages/character sets, so I also tested with some Chinese characters as well so... suspicion confirmed :)

![image](https://github.com/gregnb/react-to-print/assets/18037666/b39cc956-7d91-4fb0-96b2-3325a7c6ee8d)
![image](https://github.com/gregnb/react-to-print/assets/18037666/c082441d-1070-49c0-9555-3366afff17d7)
```
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: '諺語',
    onAfterPrint: () => console.log('Printed PDF successfully!'),
  });
```

NodeJS v20.3.0
react@18.2.0
react-to-print@2.14.15
Google Chrome

Let me know if there's anything I can do to help.
Thanks!

**Comment by MatthewHerbst** [comment]
Hello. Thanks for the report. I'm not able to replicate this. I ran the test locally on:

MacOS: 13.6.1
Chrome: 119
Node: 20.10.0
React: 18.2.0
reacto-to-print: 20.14.15

Is there any other debug data you are able to provide? Are you using special fonts maybe?

![Screenshot 2023-12-11 at 12 58 28 PM](https://github.com/gregnb/react-to-print/assets/1287375/fd8d81a9-de23-4e4a-90b3-13b8d7bd82ac)

<video src="https://github.com/gregnb/react-to-print/assets/1287375/9af7e3d4-aa1c-4484-a6b0-f070fde4367c" />

**Comment by daniel-kehlibarov** [comment]
Hi, thanks for the reply!
I was thinking about supplying additional fonts as properties so I'll definitely do that. There are some project-specific fonts that are in place, if they are a likely culprit how should I proceed?
Thanks again!

**Comment by MatthewHerbst** [comment]
Can you try removing them to check if they are the issue? If they are, then what you should probably do is ensure they are not used in the printing view. That way the PDF will only use standard fonts that the computer will have. Alternatively, if you have access to all the computers the files will be viewed on, just install those additional fonts onto those computers
