### ISSUE TITLE
Printing blank page when print in safari

### ISSUE THREAD

**Issue by Chavda-Mitul** [MatthewHerbst/react-to-print#674]
when i am using this in other browser it is working fine but when using in safari it give me blank page.
my safari version is 17.2,
my os version is mac Sonoma 14.2,
when i used the react-to-print-advanced it works in safari also (it is forked form you repo)

**Comment by MatthewHerbst** [comment]
Hello. Does [this README section](https://github.com/gregnb/react-to-print?tab=readme-ov-file#getting-a-blank-page-when-printing) help you at all? If not, could you please share a Codesandbox or similar example that shows the problem?

I am able to print the [official examples](https://codesandbox.io/s/rzdhd) without issue using MacOS 13.6.1 (Ventura) with Safari 17.1. I'm not sure what `react-to-print-advanced` is, but it seems to be 5+ years old. I would not recommend using it.
