### ISSUE TITLE
Printing like the viewport is on mobile but in reality is on desktop

### ISSUE THREAD

**Issue by nosinformatica** [MatthewHerbst/react-to-print#675]
i would like to print this component that is inside a modal
![image](https://github.com/gregnb/react-to-print/assets/152480408/9776c69d-3406-448a-8ce7-4a2f4cf8b69e)
but when i print it gets out like this
![image](https://github.com/gregnb/react-to-print/assets/152480408/afdcaab9-9296-4cf8-8cf3-f94f3eff3c56)

this is the function used to print:
```jsx
<ReactToPrint
    bodyClass="print-agreement"
    content={() => ref.current}
     trigger={() => (
    <Button variant="contained" type="button" style={{ backgroundColor: 'gray', marginLeft: '2%' }} className="">
    <Download width={15} />PDF
        </Button>
    )}
    pageStyle={`@media print {@page {size: 2000x 2000px; margin: 1cm;}`}
 />
```

the component is inside a modal

```jsx
<Modal
  isOpen={open}
  toggle={handleClose}
  centered
  size="lg"
  style={{maxWidth: '1100px', width: '100%'}}
  backdropClassName={open ? 'BDModalOpen' : 'BDModalClosed'}
  modalClassName={open ? 'ModalOpen' : 'ModalClosed'}
>
    <Container fluid={true} style={{ padding: '20px' }}>
        <ReactToPrint
            bodyClass="print-agreement"
            content={() => ref.current}
            trigger={() => (
              <Button variant="contained" type="button" style={{ backgroundColor: 'gray', marginLeft: '2%' }} className="">
                <Download width={15} />PDF
              </Button>
            )}
            pageStyle={`@media print {@page {size: 2000x 2000px; margin: 1cm;}`}
          />
          <div ref={ref} ><CsvGraphs data={jsonData} /></div>
    </Container>
</Modal>
```

**Comment by MatthewHerbst** [comment]
Hello. Have you checked the styles that your component framework is using? Usually what's happening in cases like this is your framework is using smaller viewport styles when printing.

What component framework are you using?

**Comment by nosinformatica** [comment]
> Hello. Have you checked the styles that your component framework is using? Usually what's happening in cases like this is your framework is using smaller viewport styles when printing.
> 
> What component framework are you using?

Hello, thanks, i'm using reactsrap for the row and col and highcharts for the charts, i'm trying to do a codesandbox reproducing the issue and i will post the link to it as soon as i finish it

**Comment by nosinformatica** [comment]
@MatthewHerbst i just finished the sandbox reproducing the error, try to print and you will see that the cols are in mobile mode:
https://codesandbox.io/p/sandbox/wrong-viewport-react-to-print-sandbox-zs4fww?file=%2Fsrc%2FApp.js

**Comment by MatthewHerbst** [comment]
Hey, not sure why this never got followed up on, apologies. If you are still using the library and having issues, please let me know!
