### ISSUE TITLE
[BUG] [FEATURE] Can not config counter page in footer iframe

### ISSUE THREAD

**Issue by rubysky17** [MatthewHerbst/react-to-print#677]
I want to custom counter page under table in bottom right position. 
But when i find research on Google.  CSS Styling is not affect in my code.
I'm using Chrome | MacOS

Example:

![Screenshot 2023-12-20 at 16 47 17](https://github.com/gregnb/react-to-print/assets/69248909/b9b96367-1adf-4c29-bc5e-6829e2db99fb).

i'm using `counter-increment: page;
        content: "Page " counter(page);`

Always return "page 1" in footer.

**Comment by siaikin** [comment]
Currently this can't be done in Chrome(look https://bugs.chromium.org/p/chromium/issues/detail?id=774830), the page number grows automatically and there is currently no way to change it.

You may need to use other tools to do this, such as https://github.com/Kozea/WeasyPrint

**Comment by rubysky17** [comment]
Thanks for the answer of you a lot. I think it's not your bugs and i hope in the future you will add the this feature for react-to-print. Maybe it custom without default in system browser (Chrome, firefox, IE, Safari). Moreover, i will use the default header and footer on Chrome 👍🏻

**Comment by wixarm** [comment]
You can simply use a component as Footer component and define a variable as page number. In the component, add one to the variable. 

```jsx
  let pageNumber = 0;
  const FooterPDF = () => {
    pageNumber++;
    return (
      <>
        <div style={styles.footer}>
          your footer 
        </div>
      </>
    );
  };
```

And use this component in your pages : <FooterPDF />

**Comment by rubysky17** [comment]
> You can simply use a component as Footer component and define a variable as page number. In the component, add one to the variable.
> 
> ```js
>   let pageNumber = 0;
>   const FooterPDF = () => {
>     pageNumber++;
>     return (
>       <>
>         <div style={styles.footer}>
>           your footer 
>         </div>
>       </>
>     );
>   };
> ```
> 
> And use this component in your pages :

i tried your way in my code and not work. My problem is print the Iframe screen and the browser detect only 1 screen :(. I still use the default footer and header checkbox (Checkox in panel Chrome) and this is not the best way but i think my solution solved.

**Comment by wixarm** [comment]
you can define pages next to each other like this:
remember to specify the width and height dimensions for the A4 page. After clicking on the download button, ensure that the print settings are configured for A4 size, rather than Letter size.
```
page: {
    width: "210mm",
    height: "297mm",
    display: "flex",
    margin: "0 auto",
    flexDirection: "column",
    position: "relative",
  },

let pageNumber = 0;
  const FooterPDF = () => {
    pageNumber++;
    return (
      <>
        <div style={styles.footer}>
          your footer 
        </div>
      </>
    );
  };

<div ref={ref}>
<div style={styles.page}>
        <HeaderPDF />
               data page 1 
        <FooterPDF />
</div>


<div style={styles.page}>
        <HeaderPDF />
               data page 2
        <FooterPDF />
</div>
</div>
```
