### ISSUE TITLE
Page break wide content

### ISSUE THREAD

**Issue by sammyhajomar** [MatthewHerbst/react-to-print#678]
I have a table that I want to print which is both very wide and very long. Right now I am able to get the rows to all print out across multiple pages, but the columns are being truncated. The behavior I am seeking is for the column overflow to also create a new page for those same rows. The issue is the number of columns can vary so I won't know the exact width. I want to be able to support arbitrary number of columns and rows.

**Comment by MatthewHerbst** [comment]
Hello. This question might be better for StackOverflow, but my initial though is that if the size of each column is fixed then you could put a page break within the columns, does that make sense? If you could share an example of your code on Codesandbox or something that might help debug

**Comment by sammyhajomar** [comment]
This an [example of table layout](https://codesandbox.io/p/sandbox/boring-christian-4wg6tk) I have. I've hard coded the columns and rows. I'm using the <ReactToPrint> component. I'm not sure how to apply page break within columns.

```
<ReactToPrint                               
      trigger={() => {
          return (
              <button className="px-4 py-2 font-bold border border-gray-300 rounded-md shadow-sm hover:bg-gray-100">
                  <CloudArrowDownIcon className="w-6 h-6" />
              </button>)
      }}
      content={() => componentRef.current}
  />
```

In my global.css

```
@layer utilities {
    @media print {
        .print\:page-inside-avoid {
            page-break-inside: avoid;
        }
    }
}
```

**Comment by sammyhajomar** [comment]
I added this question to [StackOverflow](https://stackoverflow.com/questions/77719914/enable-printing-wide-and-long-tables-on-multiple-pages) @MatthewHerbst
