### ISSUE TITLE
Export a method to trigger print

### ISSUE THREAD

**Issue by leeseean** [MatthewHerbst/react-to-print#68]
I want to print by Api instead of click,
just like ``` target.print() ```

**Comment by MatthewHerbst** [comment]
Do you mean without using the React component at all? Right now you can do:

```javascript
render() {
  componentDidMount() {
    this.ref.handlePrint();
  }

  return (
        <ReactToPrint
          ...
          ref={ref => this.ref = ref}
        />
  );
}
```

I'd be interested in moving the print API outside of the component itself. How do you imagine setting up `target` in your example?

**Comment by leeseean** [comment]
> Do you mean without using the React component at all? Right now you can do:
> 
> ```js
> render() {
>   componentDidMount() {
>     this.ref.handlePrint();
>   }
> 
>   return (
>         <ReactToPrint
>           ...
>           ref={ref => this.ref = ref}
>         />
>   );
> }
> ```
> 
> I'd be interested in moving the print API outside of the component itself. How do you imagine setting up `target` in your example?

target is a ref or domNode

**Comment by mengbimao** [comment]
东西是好东西,但是貌似我这个项目用不了,我照着上面来做了,但是样式貌似没有打印出来,无论怎么说还是辛苦啦,点一个星,不成敬意

**Comment by mengbimao** [comment]
![image](https://user-images.githubusercontent.com/29363520/49124648-2d435a00-f2f8-11e8-8887-f3456fc1b26f.png)
![image](https://user-images.githubusercontent.com/29363520/49124668-3fbd9380-f2f8-11e8-9a21-6ec2499baec2.png)
![image](https://user-images.githubusercontent.com/29363520/49124687-54019080-f2f8-11e8-9314-e45142689e56.png)

**Comment by Eli-Black-Work** [comment]
Thanks for the info :)  It would be great if this were documented, though.

Also, any chance of making the trigger() function optional? :)

**Comment by yefriddavid** [comment]
For me works! 

this

  manualPrint() {

    this.printRef.handlePrint();

  }

render(){
        <ReactToPrint
          ref={el => (this.printRef = el)}
          trigger={() => <a href="#" id="david">Imprimir</a>}
          content={() => this.componentRef}
        />

......

**Comment by heyjaypray** [comment]
I'm currently having a similar issue.  I'm currently using material-table and would like to have a button that you click that will print the info contained passed into a component.

<img width="1395" alt="Screen Shot 2019-08-10 at 2 02 30 PM" src="https://user-images.githubusercontent.com/25106794/62825578-1ab63b80-bb7c-11e9-8e60-67e7d0be8e7f.png">

My code looks like this -

```javascript
constructor(props) {
    super(props);

    this.state = {
      orderLoaded: false,
      orderData: []
    };
    this.printRef = React.createRef();

  }
```

```javascript
onClick: (event, rowData) => {
    this.setState({ orderData: rowData })
    this.setState ({ orderLoaded: true })
    this.printRef.handlePrint();
}
```

Then i have 
```javascript
{this.state.orderLoaded ? 
  <div>
    <ReactToPrint
       ref={el => (this.printRef = el)}
       trigger={this.state.orderLoaded = true}
       content={() => this.componentRef}
     />
     <AssemblyList
       selectedOrder={this.state.orderData}
       ref={el => (this.componentRef = el)} />
   </div>
        : 
  <div />
} 
```

i'm getting an error that says 

> Uncaught TypeError: _this2.printRef.handlePrint is not a function
and
> Uncaught TypeError: e is not a function

any ideas?

**Comment by MatthewHerbst** [comment]
@heyjaypray we don't have a feature available yet where you can call that method directly. Something I've been meaning to work on. I'll also happily accept any PRs :)

**Comment by MatthewHerbst** [comment]
We have had the ability to `useReactToPrint` for some time now 😄

**Comment by Hamza-Wakrim** [comment]
did you found solution for https://github.com/gregnb/react-to-print/issues/68#issuecomment-520171309?
cause i have same problem

**Comment by Eli-Black-Work** [comment]
@Hamza-Wakrim I think you should be using the `useReactToPrint()` function 🙂
