### ISSUE TITLE
On mobile devices are not truncated accordingly ref

### ISSUE THREAD

**Issue by dimasandriano** [MatthewHerbst/react-to-print#690]
![IMG_20240220_111515~2](https://github.com/gregnb/react-to-print/assets/42687876/b682ddc5-c868-42df-b64f-22a70021d3da)
Idk but in my laptop normal, on mobile devices normal but modal also printed

**Comment by MatthewHerbst** [comment]
Hi, apologies for the delayed response. It's not clear to me exactly what the issue here is, do you mind explaining more please?
