### ISSUE TITLE
Add Border to every Page

### ISSUE THREAD

**Issue by Yashkapure06** [MatthewHerbst/react-to-print#691]
We can add styling at the front end by adding a proper border and allowing users to add the design of the borders on every page of the printed pdf.

**Comment by Yashkapure06** [comment]
@gregnb can you assign me this task? I will try to add that feature

**Comment by MatthewHerbst** [comment]
Hello. Could you please explain better what you are trying to accomplish that you cannot already do with your own page's styles?

**Comment by Yashkapure06** [comment]
@MatthewHerbst actually, when one tries to print a pdf having n number of pages, end user expects something more like does the printed pages have better look and feel or not. Adding a border feature  to it will be definitely worth.

Yes, I agree it has border feature but here the case is for n number of pages the border starts from the 1st page and doesnot completes the border for the 1st page and the left and right side border keeps on continuing till end of the page and the border bottom is added at the very last so I think adding the following feature will make this library top-notch and best choice to work with

**Comment by MatthewHerbst** [comment]
Users can already do this though? There's nothing this library needs to do to support this. Just add a border using your own CSS. Each person might want their own border styles, there's no generic way to do this. And many people might not want a border at all. This library doesn't know how many pages you are printing.
