### ISSUE TITLE
Add dynamic colors to print function

### ISSUE THREAD

**Issue by ratnabh** [MatthewHerbst/react-to-print#692]
I tried not printing my footer and what i did was

```js
const print = `
  @media print {
    footer {
      display: none;
    }
`;
```
```jsx
 const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    copyStyles: true,
    pageStyle: print,
  });
```

but what it did was it stopped printing the css colors used in my component
Isn't there a way to preserve the configs and just update the print query for footer as the default configs were printing the css color unless i had to set footer to display null and change the default print function to my custom

Moreover it also stopped printing my images which were rendering in my component

**Comment by MatthewHerbst** [comment]
Hello. Could you explain your question/problem more clearly please? It's very hard to understand what you're asking. I don't see anything in the above code that would change colors.
