### ISSUE TITLE
How Can i Print? 

### ISSUE THREAD

**Issue by loverdeveloper** [MatthewHerbst/react-to-print#70]
BAD DOCS BAD DOCS BAD DOCS BAD DOCS 
What is componentRef?

**Comment by xnart** [comment]
Check the React docs : https://reactjs.org/docs/refs-and-the-dom.html

**Comment by loverdeveloper** [comment]
How Can i Pass a function that return a div and h2 to print it?

**Comment by loverdeveloper** [comment]
is ComponentToPrint  must be an Class?

**Comment by MatthewHerbst** [comment]
@ikosar yes. The library requires the use of refs to work, and functional components do not have refs.

From the [React docs](https://reactjs.org/docs/refs-and-the-dom.html#accessing-refs):

> **You may not use the ref attribute on function components** because they don’t have instances.

If you know of a better way to write this library that without refs we'd be happy to hear it. Thanks!

**Comment by loverdeveloper** [comment]
Dear MatthewHerbst 
Many thanks to your complete answer

**Comment by AhmadiRamin** [comment]
I read the document but I still can not understand how I can define the componentRef. 
and I have another question, I'm using FabricUI Dialog component, can I print the content of the dialog?

**Comment by MatthewHerbst** [comment]
@AhmadiRamin what don't you understand? It's just any React [ref](https://reactjs.org/docs/refs-and-the-dom.html).

**Comment by AhmadiRamin** [comment]
@MatthewHerbst Thanks Matthew, I figured it out and it's working now.

**Comment by MatthewHerbst** [comment]
@ikosar are you still having problems?
