### ISSUE TITLE
How should i handle large data to print?

### ISSUE THREAD

**Issue by AlejandroSanchez90** [MatthewHerbst/react-to-print#702]
So i have this task, i have to print a long array of users data, right now when the user go to profile, they see the print all button, and in that print button i have all the logic, but it does generate a printing template per user, that is hidden so its not rendered, this is only for printing, but i dont think this is good for performance, because if the user have like 40 or 50 pages to print, it will be a super long component, is the the only way of doing it ? or does react-to-print have something to manage this properly? 

my second idea was to create like a modal, for preview of the pages to be printed, and then show another print button to cofirm, but this feels bad to me, as user should go directly to print when they click print

**Comment by MatthewHerbst** [comment]
Hey there. I'm not sure I fully understand your concern. Are you trying to avoid showing all the pages in the print preview window opened by the browser? I don't think that's possible to my knowledge, though it's generally pretty performant.

In terms of generating the content, you can pass a Promise to the `onBeforeGetContent` prop so that will cause react-to-print to wait to print until you resolve the promise, and during that time you can generate the temporary content for printing that may not display on the main page.

Does that answer your question?

**Comment by AlejandroSanchez90** [comment]
Sorry you misunderstood me
Right now we have a page where user can see all their "goals" we have a
print button next to each goal, to single print, and a print all button,
since we need a ref from a component that will be used to be printed, we
have to render the component with display hidden, when the goals page load,
but some user may have hundreds of goals, so my goal is just render the
template just after the user click prints

**Comment by MatthewHerbst** [comment]
Ah. `onBeforeGetContent` is what you want I think. It would let you only render what you want to print when the print is happening, that way you don't need to have it rendered and hidden when not printing. Does that make sense?

**Comment by AlejandroSanchez90** [comment]
Gonna try this on Monday, thanks you so much for the quick answer!

**Comment by AlejandroSanchez90** [comment]
> Ah. `onBeforeGetContent` is what you want I think. It would let you only render what you want to print when the print is happening, that way you don't need to have it rendered and hidden when not printing. Does that make sense?

how would you use this? like you still needs to pass the ref to the content property right? 

Edit: Is this how it's supposed to be used
```ts
function App() {
  const [print, setPrint] = useState(false);
  const printRef = useRef<HTMLDivElement | null>(null);
  return (
    <div>
      {print && <Template ref={printRef} />}
      <ReactToPrint
        trigger={() => <button>Print</button>}
        content={() => printRef.current}
        onBeforeGetContent={() => {
          setPrint(true);
          return Promise.resolve();
        }}
        onAfterPrint={() => {
          setPrint(false);
          return Promise.resolve();
        }}
      />
    </div>
  );
}
```

**Comment by MatthewHerbst** [comment]
That's basically right! Recall that setting state is async though, so it's a bit more complicated to know when the state has actually been set:

```tsx
function App() {
  const [print, setPrint] = useState(false);
  const onBeforeGetContentResolveRef = useRef();
  const printRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    // Wait for the state update
    if (onBeforeGetContentResolveRef.current && print === true) {
      onBeforeGetContentResolveRef.current(); // Resolve the promise
      onBeforeGetContentResolveRef.current = undefined;
    }
  }, [print])

  return (
    <div>
      {print && <Template ref={printRef} />}
      <ReactToPrint
        trigger={() => <button>Print</button>}
        content={() => printRef.current}
        onBeforeGetContent={() => {
          setPrint(true);
          return new Promise((resolve) => {
            onBeforeGetContentResolveRef.current = resolve;
          });
        }}
        onAfterPrint={() => {
          setPrint(false);
        }}
      />
    </div>
  );
}
```

In the old world you could do this with the callback function from `seState` that runs after the state is applied, but they didn't add that into the functional component/hook world unfortunately

**Comment by MatthewHerbst** [comment]
@AlejandroSanchez90 circling back here, did the above work for you?

**Comment by AlejandroSanchez90** [comment]
Hey Matthew, yup everything is good now thanks for the help!
