### ISSUE TITLE
Blank Page while printing after a certain period of time

### ISSUE THREAD

**Issue by PrabeenGautam** [MatthewHerbst/react-to-print#704]
I'm using React-to-Print in my project to allow users to print data from a modal. I've implemented a feature where users can preview the print data in the modal before printing. However, I've noticed an issue where, after printing, if the modal is left open for some time without interacting with it, and user the clicked on print button, the print modal appears empty as shown in the attached image. This behavior occurs even though the data was initially visible when the modal was opened.

Expected Behavior:
The print data should remain visible in the print modal even after some time of inactivity.

Actual Behavior:
After some time of inactivity, the print modal appears empty, as shown in the attached image.
![image](https://github.com/MatthewHerbst/react-to-print/assets/43398072/774eb2c8-2366-4347-b100-d2fae84b3038)

What it should look like
![image](https://github.com/MatthewHerbst/react-to-print/assets/43398072/2b381156-3d0e-45be-a4a1-92df5b57e4d6)

**Comment by MatthewHerbst** [comment]
Hello. Could you share a working example of your code please? It's not really possible to debug with screenshots. I'd be curious to know how your modal works though. And just so we're on the same page, you're saying the _first_ print works, but subsequent, delayed prints do not work, or even the first print does not work if delayed long enough?

**Comment by PrabeenGautam** [comment]
Since, its a company code, i can not provide the exact working example. Here is the methods i have followed
1. Use AntD modal
2. fetch data required for modal when initial print icon is clicked, it will first fetch the data, then only open a modal. The fetch data is stored in state.

Then after modal open and user can print.

If possible, i will try to create a replica and send a link

**Comment by MatthewHerbst** [comment]
A replica would be great, thank you!

**Comment by SaranyaPonnusamy** [comment]
Facing same issue

We debugged and found that the **preview popup** opened before loading the following fonts. Consequently, we were unable to view the content. Once the fonts were loaded properly, the contents appeared as expected.

open-sans-v18-600.woff2
open-sans-v18-regular.woff2
open-sans-v18-700.woff2

<img width="1081" alt="Screenshot 2024-04-15 at 1 22 07 PM" src="https://github.com/MatthewHerbst/react-to-print/assets/86963745/a7bcda78-22b0-4565-a5f4-7beb98a72ca8">

<img width="998" alt="Screenshot 2024-04-15 at 1 22 23 PM" src="https://github.com/MatthewHerbst/react-to-print/assets/86963745/8c3cc813-0251-48f0-9bf6-ea53449d06dd">

**Comment by MatthewHerbst** [comment]
@SaranyaPonnusamy could you share the method you used to ensure the fonts were loaded? Would be useful for others to see I believe. Thanks in advance!

**Comment by SaranyaPonnusamy** [comment]
We don't have any method currently.
We verified by adding a **timeout** so that fonts can be loaded before the preview is opened. 
```tsx
onBeforePrint={() => new Promise(resolve => {
  setTimeout(() => resolve(""), 1000)
})}
```

is there any other way to resolve this issue ?

**Comment by MatthewHerbst** [comment]
@SaranyaPonnusamy have you tried using the `fonts` prop? It lets you inform `react-to-print` about fonts it should ensure are loaded before trying to print

**Comment by SaranyaPonnusamy** [comment]
I tried below code. Its not working
```tsx
fonts={[{family: "Open Sans", source:""}]}
```

**Comment by MatthewHerbst** [comment]
@SaranyaPonnusamy what does the css where you apply the fonts look like, and how does it get included onto your page?
