### ISSUE TITLE
How to add style using PageStyle prop, without it overriding component’s style 

### ISSUE THREAD

**Issue by raosudheesh** [MatthewHerbst/react-to-print#705]
I’m trying to adjust the height and width of the pages before printing. I’m trying to use pageStyle, but it overrides the component style. All I want to do is adjust the page size. Could anyone help?

**Comment by MatthewHerbst** [comment]
Hello. Have you seen the [README section](https://github.com/MatthewHerbst/react-to-print?tab=readme-ov-file#set-the-page-size) about setting the page size? Please let us know i that works for you

**Comment by raosudheesh** [comment]
Hey @MatthewHerbst  that overrides the existing style of the component. I don’t want to do that

**Comment by MatthewHerbst** [comment]
> that overrides the existing style of the component. I don’t want to do that

Not sure I understand, it doesn't change any components. And you can wrap it in a media tag (as shown in the example) to make it only apply during printing

**Comment by raosudheesh** [comment]
I tied with 
```js
pageStyle : ‘@media print {
  @page {
    size: 50mm 150mm;
  }
}’
```
it did override the existing styles and applied only these

**Comment by MatthewHerbst** [comment]
Set the styles in your normal CSS, not using `pageStyle`
