### ISSUE TITLE
Kindly Update to use latest node, npm and yarn version(s)

### ISSUE THREAD

**Issue by jermsam** [MatthewHerbst/react-to-print#71]
On trying to install dependency, I get: 

> `error tav-r@1.0.0: The engine "node" is incompatible with this module. Expected version "10.11.0". Got "10.13.0"
error tav-r@1.0.0: The engine "yarn" is incompatible with this module. Expected version "1.10.1". Got "1.12.3"
error Found incompatible module`

**Comment by MatthewHerbst** [comment]
Hi @jermsam. This library does not use any [`engines`](https://docs.npmjs.com/files/package.json#engines) directives in its `package.json`, so those errors are not coming from here. Further, this library does not use Yarn. Are you sure the error you are getting is when you are installing _this_ library? If so, can you please show the install command you are running and the entire error log? Thanks!

**Comment by jermsam** [comment]
Hi @MatthewHerbst, Yes. Installing the library generates the error log highlighted above. I had to downgrade my node and yarn to the suggested to have it working. I needed to use the library ASAP so i did not wait for the issue to be resolved. Reason I downgraded, ... After downgrading it worked awesomely, however I think it would be better off being compatible with any node versions.

**Comment by MatthewHerbst** [comment]
@jermsam as far as I am aware, we are compatible with all node and npm/yarn versions. There's nothing in this library's `package.json` that I know about that could impact not working with node or npm/yarn versions. In fact, the package that your error message shows as throwing on, `tav-r`, doesn't even exist in our `package-lock.json` file, which shows everything that will get installed when you install this library.

Can you please post the entire command you run to install, plus the entire error message after it?

**Comment by jermsam** [comment]
> The entire error message was that above.  The command to install is this below: 

> `yarn add react-to-print`

**Comment by MatthewHerbst** [comment]
I just created a branch new test library and installed this package without issue.

```sh
~/Desktop/test $ yarn add react-to-print
yarn add v1.12.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
└─ react-to-print@2.0.0-alpha-4
info All dependencies
├─ js-tokens@4.0.0
├─ prop-types@15.6.2
├─ react-to-print@2.0.0-alpha-4
├─ react@16.6.3
└─ scheduler@0.11.2
✨  Done in 2.03s.
~/Desktop/test $ node --version
v10.13.0
~/Desktop/test $ yarn --version
1.12.3
```

I think there must be something else you are doing. As I previously mentioned, there is absolutely nothing in this library that would cause an `engines` failure like you described.

Can you please `rm -rf node_modules` and then try installing it? Also, please show your full command line like I have done above. Thank you.

**Comment by jermsam** [comment]
Thanks a lot. And again... am sorry. Just noticed it was my own package.json with engines directives that do not support the latest versions just as you mentioned before. I am closing this issue for that reason.

**Comment by MatthewHerbst** [comment]
@jermsam glad you were able to figure it out!
