### ISSUE TITLE
Print datatables

### ISSUE THREAD

**Issue by Shubham-Nhance** [MatthewHerbst/react-to-print#710]
I have a big data and want the height to adjust dynamically within the given space. i.e. if the row has more info the table overflows the conatiner otherwise works fine and if one row flows the rest of the pages gets affected. I am using material ui table in my project.
The max-height is set to 80vh

**Comment by MatthewHerbst** [comment]
Hello. Are you having this issue only when printing, or also when not printing? If you could share some code that would be helpful, ideally a Codesandbox with a working example of the problem please.

**Comment by Shubham-Nhance** [comment]
@MatthewHerbst Thanks for your time, I resolved the above issue.

**Comment by MatthewHerbst** [comment]
Glad you got it resolved! Do you mind sharing your solution so that if others run into the same issue in the future they can know how to solve it?

**Comment by Shubham-Nhance** [comment]
Ya sure!! So there was a css mistake where I was giving the component a fixed height to resolve it I gave it a min-height and max-height and it resolved the issue.
