### ISSUE TITLE
CSS "break-before" (replacing "page-break-before") not supported

### ISSUE THREAD

**Issue by KewDev23** [MatthewHerbst/react-to-print#712]
Hi, 

I read that "page-break-before" is now replaced by "break-before" in CSS:
https://css-tricks.com/almanac/properties/p/page-break/
_"Note: this property is in progress of being replaced by the more generic break-before property. This new property also handles column and region breaks while being syntactically compatible with page-break-before. **Thus before using page-break-before, check if you can use break-before instead.**"_

But, currently, in react-to-print, "page-break-before" works but not "break-before". Could you support it? Thank you very much in advance.

**Comment by MatthewHerbst** [comment]
Hello. `react-to-print` is agnostic of the CSS you use. We do not look at your styles at all, and there is no concept of us "supporting" a certain style or not. If it doesn't work, assuming it's being used correctly, it likely means the browser you are using doesn't support what you are trying to do. See a [Compatibility Table](https://developer.mozilla.org/en-US/docs/Web/CSS/break-before#browser_compatibility) for more.  Browsers do all sorts of weird things when printing so this may be the case even if there is normal support when not printing.

If you're still having trouble please feel free to post your code and we can try to help.

**Comment by KewDev23** [comment]
Thank you very much for your answer. You are right, I was using `break-before: always;` which is not supported for `always` value in Chrome while `page-break-before: always;` is supported since Chrome 1.0. It seems I must use  `break-before: page;` now which is working.

Sorry for thinking it was `react-to-print` the cause. I thought it when I saw my CSS code removed in the Chrome inspector for an injected code in the page by `react-to-print`:

![image](https://github.com/MatthewHerbst/react-to-print/assets/145754959/851911d3-fe84-4d24-a8cc-4ae558020b35)

**Comment by MatthewHerbst** [comment]
No problem, glad you got it figured out! Please let us know if you run into any other issues
