### ISSUE TITLE
'.brf' file :  Change the save directory. 

### ISSUE THREAD

**Issue by Shaaa-2** [MatthewHerbst/react-to-print#713]
After print operation,  a file with '.brf' extension is getting generated in a folder called 'BRF' in my home directory (I am using Ubuntu for development.  I am using  "Electron" with react). I want control over where the file is being saved , so that I can delete it after printing in any operating system.  Is there option to do this in react-to-print ? Any clue would be really helpful.

**Comment by MatthewHerbst** [comment]
Hello. I'm not familiar with any such file type or extension. It's certainly not being generated by `react-to-print`. The BRF extension seems to be related to braille programs. Do you have such a program on your computer? https://filext.com/file-extension/BRF

**Comment by Shaaa-2** [comment]
Sorry. My bad. I don't have a physical printer, so I was using 'cups' in Ubuntu. I had created a new "Virtual Braille BRF Printer"  some time back in 'cups', that is why the BRF file was getting generated.  Thanks a lot.

**Comment by MatthewHerbst** [comment]
Glad you got it figured out!
