### ISSUE TITLE
Disable option in browser window to automatically add headers and footers

### ISSUE THREAD

**Issue by Dvik** [MatthewHerbst/react-to-print#715]
Is there a way i can pass a prop to make sure the browser print window doesn't check the option "Headers and Footers" by default?

**Comment by MatthewHerbst** [comment]
Unfortunately this is not controllable from JS to my knowledge. The [`window.print`](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) API doesn't take any options, so any control we have is generally limited to what can be done with CSS. We do [add some CSS](https://github.com/MatthewHerbst/react-to-print/blob/b2b239f92ca031b661bc262c51cc69c395941029/src/consts/defaultProps.ts#L5-L8) in that generally removes these by setting the margin, so if you're passing your own CSS you should be able to replicate that.
