### ISSUE TITLE
Unable to save as pdf logically

### ISSUE THREAD

**Issue by manikanta0127** [MatthewHerbst/react-to-print#722]

**Comment by manimaduri** [comment]
i want anchor tags to be clickable after download

**Comment by MatthewHerbst** [comment]
Hello. This library does not generate PDFs so not sure how we can help with this. All we do is ask the browser to open the print preview window with your content. Your browser is what generates the PDF. You could also pass a custom `print` prop to not use `window.print` and instead use a 3rd part pdf library to generate the PDF on the client.

Happy to help where I can. I'm going to close this as it's not an issue with this library, but happy to keep discussing.
