### ISSUE TITLE
There are many line was add to page when print

### ISSUE THREAD

**Issue by Archisketch-Finn** [MatthewHerbst/react-to-print#729]
My component
![image](https://github.com/user-attachments/assets/8100bb62-df76-4ac1-919e-398df68fbae9)

Print
![image](https://github.com/user-attachments/assets/4b5db23d-cc83-4108-b928-66162e6fc00f)

**Comment by MatthewHerbst** [comment]
Hello. This is not coming from the `react-to-print` library. Instead, this is likely your styles that are changing by a media query when printing, or by being a smaller size. If you can make a working codesandbox or similar showing the problem I can try to help diagnose, but this is almost certainly a CSS issue in your code
