### ISSUE TITLE
Priniting on Ipad

### ISSUE THREAD

**Issue by simon-baehler** [MatthewHerbst/react-to-print#74]
Hi

Firstly , thanks you for this usefull tool, it works perferctly... on desktop ;( And that my issue... The printing works when I'm using my app on a desktop, but when I'm using it with Safari on an Ipad, it opens a blank printing page and with Chrome it even do nothing, and the fact is the app I did is manly for mobile users is quite annoying.

See yeaaa

**Comment by MatthewHerbst** [comment]
Are you able to see if there are any errors being reported to the console? It should be noted that Chrome on iPad/iPhone uses WebKit, not Chromium, meaning Chrome on iPad/iPhone is really just a wrapper around Safari.

**Comment by MatthewHerbst** [comment]
@simon-baehler any chance you could give us an update on this please?

**Comment by simon-baehler** [comment]
Hi, sorry of the delay, we are working on another project nowadays and are quite busy with it. No, I have no errors and no warnings.

**Comment by MatthewHerbst** [comment]
Going to close this in favor of #85
