### ISSUE TITLE
App crashes when browser's print dialog opens

### ISSUE THREAD

**Issue by king612** [MatthewHerbst/react-to-print#749]
I don't have a sandbox, but the code is very simple and follows the example in the docs very closely:

```jsx
export default function EditCoiForm({ ....}) {
  .....
  const contentRef = useRef(null);
  const reactToPrintFn = useReactToPrint({ contentRef });

  return (
.....

      {reviewOnly ? (
        <>
          <div>
            <button onClick={reactToPrintFn}>Print</button>
            <div ref={contentRef}>
              <ReviewCoiForm form={form} />
            </div>
          </div>
...
```

`ReviewCoiForm` is a functional component imported from another file.

This renders the contained tag (function) into the Print Preview dialog and prints it just fine.  But it also crashes the app in the background as soon as the print dialog comes up.  I'm guessing it triggers a page re-render, but the data passed down the tree seems to be missing.

Other details that might be relevant:

- This is a React app using plain JS only
- The code shown gets rendered in a Modal
- We use the react MUI component library
- Nothing on the component rendered is asynchronous, there are no useEffects or data fetches
- We are using the latest version:      "react-to-print": "^3.0.1",
- I get the same behavior in both Edge and Chrome

Any suggestions would be greatly appreciated.  Great work on the package.

**Comment by MatthewHerbst** [comment]
Hey @king612, thanks for reporting your issue. Could you please share the exact error message of the crash?

**Comment by king612** [comment]
Thank you for your quick response.  The error message is just about a parent component not having the data it needs to render.

Turns out my requirement involved generating and downloading a PDF document after all, so I'll close this issue.

Thanks anyway.  Good luck with the project.
