### ISSUE TITLE
Gray overlay on pdf after printing

### ISSUE THREAD

**Issue by rahulschandak** [MatthewHerbst/react-to-print#750]
I am facing an issue where there is a gray overlay after I execute this function after using onClick on a button. My app was working perfectly fine, this issue started to come from last few days!

```jsx
const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: "CoverLetter_".concat(companyName),
    onAfterPrint: () => console.log("Printed PDF successfully!"),
  });
```

**Comment by MatthewHerbst** [comment]
Hello. If you haven't upgraded `react-to-print` in the last few days I doubt it's an issue with this library. Are you able to share a reproducible example that we can look at?
