### ISSUE TITLE
using ref from inside a sibling component

### ISSUE THREAD

**Issue by steeevio** [MatthewHerbst/react-to-print#76]
I have a component containing several controls in to which I want to put the` <ReactToPrint>` button. This <Controls> component is a sibling to the actual `<ComponentToPrint>`. Is there a way to reference the component from child of a sibling?

I tried using `this.printRef = React.createRef();` and passing it as a prop the controls component and using it from there. But then I get an error "Uncaught Error: Argument appears to not be a ReactComponent. Keys: current" when I print. Is there another way I can achieve this?

**Comment by MatthewHerbst** [comment]
Hi @steeevio sorry for the delayed response. Could you post your code please so we can see exactly what you are trying to do? Thanks

**Comment by steeevio** [comment]
Hi Matt, 
This is the issue I submitted a pull request for #77 The solution I put in is working well enough for me for now. I get that it's probably not the right solution for the project though. Thanks

**Comment by MatthewHerbst** [comment]
Cool. I'm going to close this and let's keep the discussion in that PR. I'm going to try and take a good look at things this weekend :)
