### ISSUE TITLE
Unable to print in Loop

### ISSUE THREAD

**Issue by lawrence-ldn** [MatthewHerbst/react-to-print#765]
I am using a table with multiple rows, and each row has a print button. When I click the print button for a specific row, it should print the data for that particular row. However, it always prints the same data for all rows. I suspect the issue lies in handling the useRef for dynamically assigning references to each row's content. How can I correctly manage refs to ensure the proper data is printed for each row?

**Comment by MatthewHerbst** [comment]
Hello. Yeah, the content ref needs to be unique for each row. There are a few ways to solve this. One way, if you have full control over the table setup, would be to make a `Row` component, call `useReactToPrint` in each one, with its own ref, and then everything should work normally. Another way to solve this is to use the [lazy-loading feature](https://github.com/MatthewHerbst/react-to-print/blob/master/examples/LazyContent/index.tsx) of `react-to-print` (not well documented yet, apologies). Notice in the linked example how the component ref isn't set until runtime. If you're able to provide a code example of how your table is setup I can help you adopt one of the two strategies. Need to understand what controls you have though.

**Comment by lawrence-ldn** [comment]
Thank you Herbst, for sharing the reference. I will try this method  and keep you updated.

**Comment by MatthewHerbst** [comment]
Hey @lawrence-ldn did you end up solving your issue?
