### ISSUE TITLE
How to hidden content ComponentToPrint?

### ISSUE THREAD

**Issue by tnduc** [MatthewHerbst/react-to-print#83]
```
<ReactToPrint
     trigger={() => <a href="#">Print this out!</a>}
     content={() => this.componentRef}
/>
<ComponentToPrint ref={el => (this.componentRef = el)} />
```
`<ComponentToPrint ref={el => (this.componentRef = el)} />` display its content, I want to hide it, the user clicks `Print this out!` will show up on the printer page

**Comment by MatthewHerbst** [comment]
Hello. Can you please clarify exactly what you are trying to do? Not sure I understand from the above

**Comment by tnduc** [comment]
> Hello. Can you please clarify exactly what you are trying to do? Not sure I understand from the above

![screenshot from 2018-12-30 09-38-18](https://user-images.githubusercontent.com/26267956/50543931-af38e280-0c18-11e9-9c0a-88af87f2d5fb.png)
`ComponentToPrint` component not show, when click `Print this out!` start printing. Sorry about the expression

**Comment by MatthewHerbst** [comment]
So, if I understand correctly: the area labelled "Hide" isn't printing when you click it. Can you post a link to the code please?

**Comment by tnduc** [comment]
> So, if I understand correctly: the area labelled "Hide" isn't printing when you click it. Can you post a link to the code please?

Page only show `Print this out!`, When clicking on it, will print the content that I circled in red, meaning that the content in the normal red circle will not be displayed, but only displayed in the printed page, I am trying with @media print

**Comment by MatthewHerbst** [comment]
Alright - so what exactly is the problem?

**Comment by tnduc** [comment]
The content in component `ComponentToPrint` is always displayed, and I want it to be hidden, the problem is just that! You can look at your demo, and understand the problem.

**Comment by tnduc** [comment]
Perhaps your idea is to open a new tab, and print it from there, but I don't want to, I want to put the print button on a page with a lot of items, and when printing, just print the content in component `ComponentToPrint `, do you understand?

**Comment by MatthewHerbst** [comment]
> The content in component `ComponentToPrint` is always displayed, and I want it to be hidden, the problem is just that! You can look at your demo, and understand the problem.

Ah, got it. Is the issue just that the `@media print` query isn't working, or is there a problem with this component? If the issue is just with `@media print` this might be better asked on StackOverflow - you'll get a lot more people with the ability to help there. I'm not an expert with `@media` queries :(

**Comment by NAVEENND** [comment]
Hi all, I am having the same requirement of  what tranducit95 is asking ? can anyone help me ?

**Comment by NAVEENND** [comment]
@tranducit95 did you get the solution?
if yes ,can you please share with me?

Thanks,
naveen.n.d

**Comment by tnduc** [comment]
Use @media print or wrap with div and set display none 😂

**Comment by NAVEENND** [comment]
haha thank you . I tried with display but without wrap into div ,now its
working perfect.

**Comment by NAVEENND** [comment]
How to do with @media print ?

**Comment by tnduc** [comment]
You grasp the basic media query rule that is applicable.
https://www.tutorialspoint.com/css/css_printing.htm

**Comment by NAVEENND** [comment]
thank you :)

**Comment by Gaibhne** [comment]
Google has this result pretty high up for what the original poster wanted, which I believe was to have a component that is visible when printing, but not visible while looking at the page in a web browser. I find the scattered comments above very confusing, but I ended up finding the solution from the inspiration they gave. For future googlers, this is how you do it:

In your app (from the example)
```
<ReactToPrint
  trigger={() => {
    return <a href="#">Print this out!</a>;
  }}
  content={() => this.componentRef}
/>
<ComponentToPrint ref={el => (this.componentRef = el)} />
```

In your `ComponentToPrint`:
```
export class ComponentToPrint extends React.PureComponent {
  render() {
    return (
      <div className='yourClassName'>
        ...your content...
      </table>
    );
  }
}
```

And wherever you put your CSS
```
@media screen {
	.yourClassName {
		visibility: hidden;
	}
}
```

The way it works is that `@media screen` does not get applied while printing, so the component is only hidden while being rendered in the browser.

**Comment by masiafrest** [comment]
i don't know is this is useful, but is you use material ui u can import box component and wrap what u want to print, and pass props `displayPrint='block'` to show on print screen

**Comment by Suroor-Ahmmad** [comment]
Did anyone crack this?

**Comment by Suroor-Ahmmad** [comment]
> Google has this result pretty high up for what the original poster wanted, which I believe was to have a component that is visible when printing, but not visible while looking at the page in a web browser. I find the scattered comments above very confusing, but I ended up finding the solution from the inspiration they gave. For future googlers, this is how you do it:
> 
> In your app (from the example)
> 
> ```
> <ReactToPrint
>   trigger={() => {
>     return <a href="#">Print this out!</a>;
>   }}
>   content={() => this.componentRef}
> />
> <ComponentToPrint ref={el => (this.componentRef = el)} />
> ```
> 
> In your `ComponentToPrint`:
> 
> ```
> export class ComponentToPrint extends React.PureComponent {
>   render() {
>     return (
>       <div className='yourClassName'>
>         ...your content...
>       </table>
>     );
>   }
> }
> ```
> 
> And wherever you put your CSS
> 
> ```
> @media screen {
> 	.yourClassName {
> 		visibility: hidden;
> 	}
> }
> ```
> 
> The way it works is that `@media screen` does not get applied while printing, so the component is only hidden while being rendered in the browser.

This works with minor tweak, use `display: none` in the class rather than `visibility: hidden`, because `visibility` will create empty space

**Comment by david1asher** [comment]
https://github.com/gregnb/react-to-print/issues/83#issuecomment-872941426 is exactly what i needed, thank you!

**Comment by yayidg22** [comment]
`@media screen` doesn't work for me i used
```
 '@media print': {
        display: 'none'
    } 
```
and now works fine

**Comment by mahamedh** [comment]
> > Google has this result pretty high up for what the original poster wanted, which I believe was to have a component that is visible when printing, but not visible while looking at the page in a web browser. I find the scattered comments above very confusing, but I ended up finding the solution from the inspiration they gave. For future googlers, this is how you do it:
> > In your app (from the example)
> > ```
> > <ReactToPrint
> >   trigger={() => {
> >     return <a href="#">Print this out!</a>;
> >   }}
> >   content={() => this.componentRef}
> > />
> > <ComponentToPrint ref={el => (this.componentRef = el)} />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In your `ComponentToPrint`:
> > ```
> > export class ComponentToPrint extends React.PureComponent {
> >   render() {
> >     return (
> >       <div className='yourClassName'>
> >         ...your content...
> >       </table>
> >     );
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And wherever you put your CSS
> > ```
> > @media screen {
> > 	.yourClassName {
> > 		visibility: hidden;
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The way it works is that `@media screen` does not get applied while printing, so the component is only hidden while being rendered in the browser.
> 
> This works with minor tweak, use `display: none` in the class rather than `visibility: hidden`, because `visibility` will create empty space

this print empty when i have given as inline style..

**Comment by jaballogian** [comment]
> > The content in component `ComponentToPrint` is always displayed, and I want it to be hidden, the problem is just that! You can look at your demo, and understand the problem.
> 
> Ah, got it. Is the issue just that the `@media print` query isn't working, or is there a problem with this component? If the issue is just with `@media print` this might be better asked on StackOverflow - you'll get a lot more people with the ability to help there. I'm not an expert with `@media` queries :(

I know it's late but I just found out how to hide the desired components easily from this answer https://stackoverflow.com/a/39640177/8339172.

Here is the sample (I'm using MUI components):

```tsx
const handleDownloadButtonClick = useReactToPrint({
  content: () => downloadComponentRef.current.cloneNode(true),
  documentTitle: 'Detail Item',
  pageStyle: `
    ...

    @media print {
      .pagebreak {
        page-break-before: always;
      }
      // ADD THIS STYLE
      .no-print {
        display: none !important;
      }
    }
  `,
})

return (
  <CustomPaper className={`${layoutClasses.card} ${classes.root}`}>
    {/* HERE IS THE PRINTED COMPONENT */}
    <Stack ref={downloadComponentRef}>
      {/* HEADER */}
      <Stack 
        direction='row'
        justifyContent='space-between'
        spacing='8px'
        className={`${layoutClasses.cardItemTitle} ${classes.title}`}
      >
        {/* TITLE */}
        <Typography
          variant='h6'
          className='textBold'
        >
          {title} Journey
        </Typography>

        {/* DOWNLOAD BUTTON */}
        {/* THIS COMPONENT SHOULD BE HIDDEN IN THE PRINTED FILE */}
        {timelineList.length > 0 &&
        <Button
          variant='contained'
          startIcon={<IconDownload/>}
          disableElevation
          className={`${classes.downloadButton} no-print`} // ADD THE "no-print" CLASS NAME HERE
          onClick={handleDownloadButtonClick}
        >
          Download
        </Button>}
      </Stack>

      {/* TIMELINE */}
      <Timeline className={classes.timeline}>
        {timelineList.map((item, index) => (
          ...
        ))}
      </Timeline>
    </Stack>
  </CustomPaper>
)
``` 

Here is the rendered component on the browser:
![image](https://user-images.githubusercontent.com/24468466/181570353-0dc95779-ba0d-405d-b9e2-062dadc920f9.png)

and here is the result (the PDF file):
![image](https://user-images.githubusercontent.com/24468466/181570706-d64f1ab3-8717-47bf-bd71-f599b481588e.png)

The download button is not displayed on the PDF file as we want.

**Comment by ShubhamMane303** [comment]
> 

i wonder this is common problem and this npm guy's not having the proper solution

**Comment by ashishHomble** [comment]
> > Google has this result pretty high up for what the original poster wanted, which I believe was to have a component that is visible when printing, but not visible while looking at the page in a web browser. I find the scattered comments above very confusing, but I ended up finding the solution from the inspiration they gave. For future googlers, this is how you do it:
> > In your app (from the example)
> > ```
> > <ReactToPrint
> >   trigger={() => {
> >     return <a href="#">Print this out!</a>;
> >   }}
> >   content={() => this.componentRef}
> > />
> > <ComponentToPrint ref={el => (this.componentRef = el)} />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In your `ComponentToPrint`:
> > ```
> > export class ComponentToPrint extends React.PureComponent {
> >   render() {
> >     return (
> >       <div className='yourClassName'>
> >         ...your content...
> >       </table>
> >     );
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And wherever you put your CSS
> > ```
> > @media screen {
> > 	.yourClassName {
> > 		visibility: hidden;
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The way it works is that `@media screen` does not get applied while printing, so the component is only hidden while being rendered in the browser.
> 
> This works with minor tweak, use `display: none` in the class rather than `visibility: hidden`, because `visibility` will create empty space


you can also add height: 0 and width: 0, to  make sure unnecessary area is not rendered.

**Comment by lokeshdaiya** [comment]
I know this is too old post, I found one solution. we can hide component like this.
```
<ReactToPrint
  trigger={() => {
    return <a href="#">Print this out!</a>;
  }}
  content={() => this.componentRef}
/>
// css class also can be used instead inline
<div style={{ display: "none" }}>
     <ComponentToPrint ref={el => (this.componentRef = el)} />
  </div>
```
