### ISSUE TITLE
Print: Total: 2 sheets of paper

### ISSUE THREAD

**Issue by tnduc** [MatthewHerbst/react-to-print#84]
The printed page always displays 2 pages, even though there is only 1 page, I don't know the reason for me or the library
![screenshot from 2018-12-30 20-53-19](https://user-images.githubusercontent.com/26267956/50547850-2734f600-0c75-11e9-97a1-74a45b76193b.png)

- question 2
How can I call the onClick event in the ReactToPrint trigger, I want to run a function, after that function finishes printing automatically. tks

**Comment by MatthewHerbst** [comment]
We have an [`onAfterPrint`](https://github.com/gregnb/react-to-print/blob/df9baa23d13986203129df086272d45ecd7ed1d5/src/index.js#L16) callback you can use to do something after printing is finished. You're defining the trigger yourself so you should be able to put on `onClick` directly on it.

As for the two pages, are you sure your website just isn't very tall?

**Comment by zhilianbi520** [comment]
> We have an [`onAfterPrint`](https://github.com/gregnb/react-to-print/blob/df9baa23d13986203129df086272d45ecd7ed1d5/src/index.js#L16) callback you can use to do something after printing is finished. You're defining the trigger yourself so you should be able to put on `onClick` directly on it.
> 
> As for the two pages, are you sure your website just isn't very tall?

I've met the question as you too.The printed page always displays 2 pages, even though there is only 1 page。my website Only  400px high
