### ISSUE TITLE
Not working @page size A4 landscape

### ISSUE THREAD

**Issue by NguyenTheSon** [MatthewHerbst/react-to-print#86]
![image](https://user-images.githubusercontent.com/12813174/50630430-762fa380-0f73-11e9-9943-89c6fd88bb9a.png)

**Comment by MatthewHerbst** [comment]
Hi @NguyenTheSon can you please explain what's not working? What are you expecting to see above? Is there an error in the console, or is the view in the print window just not showing the entire table (it seems some columns may be cut off)?

**Comment by NguyenTheSon** [comment]
I want landscape page to display all columns

**Comment by MatthewHerbst** [comment]
Is that actually possible? A page has a fixed size, so there's a limit to how many columns can actually fit on it. Any chance you could post a live version of your code to look at?

**Comment by MohamedSafaaNasr** [comment]
@NguyenTheSon  Try in the print settings, printer properties layout change to landscape, i guess this not package issue probably.
![preview](https://user-images.githubusercontent.com/22216454/51078732-0469ff00-16c3-11e9-969a-bc37b2804ef4.PNG)

**Comment by NguyenTheSon** [comment]
Thanks for help me. Since I use the bootstrap package, I have a configuration error

**Comment by MatthewHerbst** [comment]
@NguyenTheSon does that mean you solved your issue?

**Comment by MohamedSafaaNasr** [comment]
@NguyenTheSon  if this could be any help i created a print class which consume react-to-print with print preview.

Print Class
```jsx
import React , { Component } from 'react';
import ReactToPrint from "react-to-print";

class Content extends Component{
    render(){
      let printCon = this.props.printContent;
      return(
        <div>
        {printCon}
        </div>)
    }
}

class Print extends Component {
  constructor(props){
    super(props);
    this.state = {
      content: null
    }
  }

    componentDidMount(){
        if(this.props.content){
            this.setState({content:this.props.content});
        }
    }

    render() {
          return (

              <div className="card " align="center">
                        <div className="card-header">
                        <h5 className="card-title">Print Preview</h5>
                        <ReactToPrint
                            trigger={() => <a href="#" className="btn-floating btn btn-primary">Print</a>}
                            content={() => this.componentRef}
                          />
                          </div>
                        <div className="card-body ">
                          <Content ref={el => (this.componentRef = el)} printContent={this.state.content}/>
                          
                        </div>
                      </div>
          );
      }
}
  export default Print;
```

usage:
Note: package used instead of modal reactjs-popup

Content
```js
printContent(){
   return(
   <div> {/* your content with its own style if you have too */}</div>
   );
}
```
in Render
```jsx
render(){
  let printContent= this.printContent();
  return(
    <div className="input-group col-6" align="right">
      <Popup
        trigger={
          <button className="btn-floating btn btn-secondary buttonFix">
            <span><FontAwesomeIcon icon="print" /></span> Print
          </button>
        }
        modal
        closeOnDocumentClick
      >
        <Print content ={printContent} />
     </Popup>
    </div>
)};
```

**Comment by MatthewHerbst** [comment]
@NguyenTheSon were you able to solve this, or should this issue remain open?

**Comment by NguyenTheSon** [comment]
@MatthewHerbst  Thank you. The problem has been solved

**Comment by ronyfhebrian** [comment]
so how do you resolve the issue?
