### ISSUE TITLE
Convert to TypeScript?

### ISSUE THREAD

**Issue by cmckni3** [MatthewHerbst/react-to-print#89]
As mentioned in #80, converting the project to TypeScript would make the TypeScript definition maintenance easier and automatic.

Creating this issue for discussion/blessing to convert to TypeScript.

**Comment by cmckni3** [comment]
I think this should wait until remaining PRs are closed/merged.

**Comment by MatthewHerbst** [comment]
I think the big issue here is do the maintainers know Typescript. I can say I don't have much experience with it. I'm open to learn of course, but it would slow me down a bit for a while. At the same time, the code is pretty straightforward so I can't imagine the types would be all that complicated. I can't speak for @gregnb

**Comment by cmckni3** [comment]
[dts-gen](https://github.com/Microsoft/dts-gen) seems promising. I figured out how to get it to work by using `npm link`/`yarn link`/yarn workspaces against the project and running `dts-gen -m react-to-print -o`.

I will work on getting the JSDoc types I did for #80 ported over to the codebase. `dts-gen` should pick them up for the missing types.

This should be a good middle ground 😃

**Comment by MatthewHerbst** [comment]
Awesome, looking forward to seeing it! (Though slightly concerned that `dts-gen` seems to no longer be maintained and thus on an old version of `typescript`)
