### ISSUE TITLE
How to call custom function on print button click 

### ISSUE THREAD

**Issue by manavpandya** [MatthewHerbst/react-to-print#94]
I was working on the print functionality and came to know about this package.

It's working fine to print a specific component on button click, but I want to call an external method from the component which I have developed in below sandbox

Have a look 

https://codesandbox.io/s/21r6579py

Do let me know about any solution

**Comment by MatthewHerbst** [comment]
Hello. Can you please get the codesandbox example working? It has multiple syntax errors since you have not formatted the code correctly (lots of it is commented out), and you are missing a bunch of imports.

**Comment by manavpandya** [comment]
@MatthewHerbst 

There are no errors I think, and there is a simple code which contains the normal HTML markups and trying to trigger a custom action

You can play around it and let me know about that

**Comment by MatthewHerbst** [comment]
@manavpandya when I open the link you pasted the first thing that happens is:

> Error
> A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.

**Comment by OmkarRa** [comment]
Do following change in Manav's codesandbox on line no.52. Not sure why but It will work. 
```
          //trigger={this.renderButton}
          trigger={()=><button color="primary">Print</button>}
```

**Comment by andydev404** [comment]
The renderButton should be inside the Example class component instead ComponentToPrint.

This works:

```javascript
class Example extends React.Component {
  renderButton = () => {
    return <button color="primary">Print</button>;
  }
  render() {
    return (
      <div>
        <ReactToPrint
          trigger={this.renderButton}
          content={() => this.componentRef}
        />
        <ComponentToPrint ref={el => (this.componentRef = el)} />
      </div>
    );
  }
}
```
