### ISSUE TITLE
Refs are not available for stateless components. For 'react-to-print' to work only Class based components can be printed

### ISSUE THREAD

**Issue by karanshah10** [MatthewHerbst/react-to-print#96]

**Comment by MatthewHerbst** [comment]
What part of that error message do you need help with?

**Comment by andydev404** [comment]
This's an alternative for stateless component:

```javascript
import React, { useRef } from 'react';
import ReactToPrint from 'react-to-print';

class ComponentToPrint extends React.PureComponent {
  render() {
    return (
      <table>
        <thead>
          <th>column 1</th>
          <th>column 2</th>
          <th>column 3</th>
        </thead>
        <tbody>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
        </tbody>
      </table>
    );
  }
}

const Example = () => {
  const componentRef = useRef();
  return (
    <div>
      <ReactToPrint
        trigger={() => <button>Print this out!</button>}
        content={() => componentRef.current}
      />
      <ComponentToPrint ref={componentRef} />
    </div>
  );
};
export default Example;

```

**Comment by MatthewHerbst** [comment]
@andydev404 hooks 💯

**Comment by MarkNewcomb1** [comment]
Something worth noting: the component you want to print will still need to be a class component. If Example _AND_ ComponentToPrint are both non-class-based, it won't work. I had trouble with this this morning, where in my example, Example was a functional, stateless component and ComponentToPrint was also a functional, stateless component. I kept getting this `Refs are not available for stateless components` error when clicking on my print link. Taking this error message quite literally, I tried converting my ComponentToPrint to a stateful component using `useState` while still keeping it a functional component. 

Turned out that wasn't good enough. It's not necessarily that it's a stateless component. It's that it's not a _class based component_. 

Interestingly, in my wrestling with this, I tried `<h1 ref={componentRef}>HELLO?</h1>` and that worked - even though a simple h1 tag is certainly not a class based component.

**Comment by MatthewHerbst** [comment]
Thanks for the information @MarkNewcomb1 we may need to update our error messages in the hooks world, since previously a functional component had no effective way of maintaining state.

**Comment by jianghuaw** [comment]
Add my thanks to @MarkNewcomb1. The above information is useful. I met the same problem to print non-class-based component and I finally got it to work by putting the component as the child of `<div ref={componentRef} />`.

**Comment by dmajumder4292** [comment]
If one wants to just have functional components, they can refer to the below example:

```jsx
import React, { useRef } from "react";
import ReactToPrint from "react-to-print";

const ComponentToPrint = React.forwardRef((props, ref) => (
      <table ref={ref}>
        <thead>
          <th>column 1</th>
          <th>column 2</th>
          <th>column 3</th>
        </thead>
        <tbody>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
          <tr>
            <td>data 1</td>
            <td>data 2</td>
            <td>data 3</td>
          </tr>
        </tbody>
      </table>
));

const Example = () => {
    const componentRef = useRef();
    return (
      <div>
        <ReactToPrint
          trigger={() => <a href="#">Print this out!</a>}
          content={() => componentRef.current}
        />
        <ComponentToPrint ref={componentRef} />
      </div>
    );
}

export default Example;
```

**Comment by Farnis** [comment]
I got the correct answer with the following solution and bypassed this error 

```jsx
import React, { useRef } from "react";
import ReactToPrint from "react-to-print";

export default function PrinterWrapper({ children }) {
    const linkToPrint = () => {
        return (
            <button>Click To PrintOF Body</button>
        )
    }
    const componentRef = useRef();
    return (
        <>
            <ReactToPrint trigger={linkToPrint} content={() => componentRef.current} />
            <div ref={componentRef}>
                {children}
            </div>
        </>
    );
}
```

**Comment by opinyinRob** [comment]
I followed the examples given and still get the error message. Could it be because the wrapped component has some stateless components in it?

**Comment by JasonCabral131** [comment]
can someone help me how to trigger an event if success printing or not  using useReactToPrint
Thanks in advance

**Comment by MatthewHerbst** [comment]
> can someone help me how to trigger an event if success printing or not using useReactToPrint Thanks in advance

@JasonCabral131 As called out [in the README](https://github.com/gregnb/react-to-print#why-does-onafterprint-fire-even-if-the-user-cancels-printing), unfortunately the `onAfterPrint` event is fired when the user closes the print dialog regardless of what action (print, cancel) they have taken. This is a browser limitation and not something `react-to-print` can solve. I am in the very slow process of making a WC3 Print API proposal, but that will likely take years before becoming a reality 😢

**Comment by ahmad-ahmadnejad** [comment]
I Fix This Issue with This Approach :
move ref attribute from my Component to a div . And it was well resolved .
![Screenshot (1355)](https://user-images.githubusercontent.com/75561736/232308242-b95d0137-52ed-452e-9f16-21b280d36e65.png)
